import { existsSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

const adminNestedRoutesWithDedicatedLoading = [
  '3d-assets/list',
  'agentcreator/personas',
  'agentcreator/runs',
  'agentcreator/teaching',
  'agentcreator/teaching/agents',
  'agentcreator/teaching/chat',
  'agentcreator/teaching/collections',
  'auth/dashboard',
  'auth/login-activity',
  'auth/permissions',
  'auth/settings',
  'auth/user-pages',
  'auth/users',
  'kangur/[...slug]',
  'kangur/appearance',
  'kangur/builder',
  'kangur/content-manager',
  'kangur/documentation',
  'kangur/lessons-manager',
  'kangur/observability',
  'kangur/settings',
  'kangur/social',
  'kangur/tests-manager',
  'cms/builder',
  'cms/pages',
  'cms/slugs',
  'cms/themes',
  'cms/zones',
  'ai-paths/dead-letter',
  'ai-paths/jobs',
  'ai-paths/queue',
  'ai-paths/trigger-buttons',
  'ai-paths/validation',
  'case-resolver/capture',
  'case-resolver/cases',
  'case-resolver/categories',
  'case-resolver/identifiers',
  'case-resolver/preferences',
  'case-resolver/settings',
  'case-resolver/tags',
  'chatbot/context',
  'chatbot/memory',
  'chatbot/sessions',
  'filemaker/campaigns',
  'filemaker/emails',
  'filemaker/events',
  'filemaker/list',
  'filemaker/mail',
  'filemaker/organizations',
  'filemaker/persons',
  'image-studio/settings',
  'image-studio/ui-presets',
  'image-studio/validation-patterns',
  'integrations/add',
  'integrations/aggregators',
  'integrations/aggregators/base-com',
  'integrations/imports',
  'integrations/marketplaces',
  'integrations/marketplaces/allegro',
  'integrations/marketplaces/category-mapper',
  'integrations/tradera',
  'notes/notebooks',
  'notes/settings',
  'notes/tags',
  'notes/themes',
  'prompt-exploder/projects',
  'prompt-exploder/settings',
  'products/import',
  'products/orders-import',
  'products/preferences',
  'products/producers',
  'products/settings',
  'settings/ai',
  'settings/brain',
  'settings/database',
  'settings/folder-trees',
  'settings/menu',
  'settings/notifications',
  'settings/playwright',
  'settings/recovery',
  'settings/storage',
  'settings/sync',
  'settings/text-editors',
  'settings/typography',
  'system/analytics',
  'system/logs',
  'system/upload-events',
  'validator/lists',
] as const;

const adminRootDirectory = path.join(process.cwd(), 'src/app/(admin)/admin');

describe('admin nested loading route inventory', () => {
  it.each(adminNestedRoutesWithDedicatedLoading)(
    'ensures the %s admin subsection has a dedicated loading route',
    (routeSegment) => {
      expect(existsSync(path.join(adminRootDirectory, routeSegment, 'loading.tsx'))).toBe(true);
    }
  );
});
