// @vitest-environment jsdom

import React from 'react';
import { fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  useSystemLogsStateMock: vi.fn(),
  useSystemLogsActionsMock: vi.fn(),
}));

vi.mock('@/features/observability/context/SystemLogsContext', () => ({
  useSystemLogsState: mocks.useSystemLogsStateMock,
  useSystemLogsActions: mocks.useSystemLogsActionsMock,
}));

import { LogTriagePresets } from './SystemLogs.Presets';

describe('LogTriagePresets', () => {
  const handleFilterChangeMock = vi.fn();
  const handleResetFiltersMock = vi.fn();

  afterEach(() => {
    vi.useRealTimers();
  });

  beforeEach(() => {
    mocks.useSystemLogsStateMock.mockReset().mockReturnValue({
      level: 'all',
      query: '',
      source: '',
      service: '',
      method: '',
      statusCode: '',
      minDurationMs: '',
      requestId: '',
      traceId: '',
      correlationId: '',
      userId: '',
      fingerprint: '',
      category: '',
      fromDate: '',
      toDate: '',
    });
    handleFilterChangeMock.mockReset();
    handleResetFiltersMock.mockReset();
    mocks.useSystemLogsActionsMock.mockReset().mockReturnValue({
      handleFilterChange: handleFilterChangeMock,
      handleResetFilters: handleResetFiltersMock,
    });
  });

  it('renders triage preset buttons with wrapping text and taller height', () => {
    render(<LogTriagePresets />);

    const button = screen.getByText('System Alerts').closest('button');
    expect(button).not.toBeNull();
    expect(button).toHaveClass('min-h-[5.75rem]');
    expect(button).toHaveClass('whitespace-normal');
    expect(button).toHaveClass('items-start');

    const label = screen.getByText('System Alerts');
    expect(label).toHaveClass('whitespace-normal');
    expect(label).toHaveClass('break-words');

    const description = screen.getByText(
      'Alert events generated by the observability worker in the last 24 hours.'
    );
    expect(description).toHaveClass('whitespace-normal');
    expect(description).toHaveClass('break-words');
  });

  it('applies the selected preset filters with resolved date values', () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-03-19T12:00:00.000Z'));

    render(<LogTriagePresets />);

    fireEvent.click(screen.getByText('Recent Errors').closest('button') as HTMLButtonElement);

    expect(handleFilterChangeMock.mock.calls).toEqual(
      expect.arrayContaining([
        ['level', 'error'],
        ['query', ''],
        ['source', ''],
        ['fromDate', '2026-03-18'],
        ['toDate', '2026-03-19'],
      ])
    );
  });

  it('shows an active preset state and clears it through the shared reset action', () => {
    vi.useFakeTimers();
    vi.setSystemTime(new Date('2026-03-19T12:00:00.000Z'));
    mocks.useSystemLogsStateMock.mockReturnValue({
      level: 'error',
      query: '',
      source: '',
      service: '',
      method: '',
      statusCode: '',
      minDurationMs: '',
      requestId: '',
      traceId: '',
      correlationId: '',
      userId: '',
      fingerprint: '',
      category: '',
      fromDate: '2026-03-18',
      toDate: '2026-03-19',
    });

    render(<LogTriagePresets />);

    expect(screen.getByRole('button', { name: 'Clear preset' })).toBeInTheDocument();
    expect(screen.getByText('Active')).toBeInTheDocument();

    fireEvent.click(screen.getByRole('button', { name: 'Clear preset' }));

    expect(handleResetFiltersMock).toHaveBeenCalledTimes(1);
  });
});
