import type { KangurGameDefinition, KangurGameVariant } from '@/shared/contracts/kangur-games';

const createVariant = (
  input: Omit<KangurGameVariant, 'sortOrder' | 'status'> &
    Partial<Pick<KangurGameVariant, 'sortOrder' | 'status'>>
): KangurGameVariant => ({
  sortOrder: 0,
  status: 'active',
  ...input,
});

const KANGUR_DEFAULT_GAMES: readonly KangurGameDefinition[] = [
  {
    id: 'clock_training',
    engineId: 'clock-dial-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['clock'],
    activityIds: ['clock-training'],
    legacyScreenIds: ['clock_quiz'],
    label: 'Clock training',
    title: 'Clock Training',
    description:
      'Shared clock engine for analogue reading drills in lessons, the games library, and fullscreen practice.',
    emoji: '🕐',
    mechanic: 'clock_training',
    interactionMode: 'mixed',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['time', 'clock', 'analogue'],
    variants: [
      createVariant({
        id: 'clock_training.lesson-inline',
        label: 'Lesson inline',
        title: 'Clock training in lessons',
        description: 'Embeds the shared clock engine inside modular lesson documents.',
        surface: 'lesson_inline',
        legacyActivityId: 'clock-training',
      }),
      createVariant({
        id: 'clock_training.library-preview',
        label: 'Library preview',
        title: 'Clock training preview',
        description: 'Shows the shared clock engine as a reusable catalog entry.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'clock_training.game-screen',
        label: 'Game screen',
        title: 'Clock training fullscreen',
        description: 'Launches the shared clock engine from the standalone game runtime.',
        surface: 'game_screen',
        legacyScreenId: 'clock_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 100,
  },
  {
    id: 'calendar_interactive',
    engineId: 'calendar-grid-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['calendar'],
    activityIds: ['calendar-interactive'],
    legacyScreenIds: ['calendar_quiz'],
    label: 'Calendar interactive',
    title: 'Calendar Interactive',
    description:
      'Interactive calendar engine for dates, weekdays, and time shifts reused across lesson and game surfaces.',
    emoji: '📅',
    mechanic: 'calendar_interactive',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['calendar', 'dates', 'time'],
    variants: [
      createVariant({
        id: 'calendar_interactive.lesson-inline',
        label: 'Lesson inline',
        title: 'Calendar practice in lessons',
        description: 'Embeds the shared calendar engine inside lesson activity blocks.',
        surface: 'lesson_inline',
        legacyActivityId: 'calendar-interactive',
      }),
      createVariant({
        id: 'calendar_interactive.library-preview',
        label: 'Library preview',
        title: 'Calendar preview',
        description: 'Catalog preview of the reusable calendar engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'calendar_interactive.game-screen',
        label: 'Game screen',
        title: 'Calendar fullscreen practice',
        description: 'Standalone game runtime entry backed by the shared calendar engine.',
        surface: 'game_screen',
        legacyScreenId: 'calendar_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 200,
  },
  {
    id: 'adding_ball',
    engineId: 'quantity-drag-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['adding'],
    activityIds: ['adding-ball'],
    legacyScreenIds: [],
    label: 'Adding ball',
    title: 'Adding Ball',
    description:
      'Drag-and-drop quantity engine for early addition practice. Intended as a shared lesson and library asset before fullscreen rollout.',
    emoji: '➕',
    mechanic: 'drag_drop',
    interactionMode: 'drag',
    surfaces: ['lesson', 'library'],
    tags: ['addition', 'drag', 'quantity'],
    variants: [
      createVariant({
        id: 'adding_ball.lesson-inline',
        label: 'Lesson inline',
        title: 'Adding ball in lessons',
        description: 'Current lesson activity backed by the shared quantity-drag engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'adding-ball',
      }),
      createVariant({
        id: 'adding_ball.library-preview',
        label: 'Library preview',
        title: 'Adding ball preview',
        description: 'Preview variant used by the shared games library.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
    ],
    status: 'active',
    sortOrder: 300,
  },
  {
    id: 'adding_synthesis',
    engineId: 'rhythm-answer-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['adding'],
    activityIds: ['adding-synthesis'],
    legacyScreenIds: [],
    label: 'Adding synthesis',
    title: 'Adding Synthesis',
    description:
      'Rhythm-based answer engine for addition fluency. Shared catalog entry for future standalone practice modes.',
    emoji: '🎵',
    mechanic: 'rhythm',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library'],
    tags: ['addition', 'rhythm', 'fluency'],
    variants: [
      createVariant({
        id: 'adding_synthesis.lesson-inline',
        label: 'Lesson inline',
        title: 'Adding synthesis in lessons',
        description: 'Current lesson activity variant powered by the rhythm-answer engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'adding-synthesis',
      }),
      createVariant({
        id: 'adding_synthesis.library-preview',
        label: 'Library preview',
        title: 'Adding synthesis preview',
        description: 'Library preview of the shared rhythm engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
    ],
    status: 'active',
    sortOrder: 400,
  },
  {
    id: 'subtracting_garden',
    engineId: 'quantity-drag-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['subtracting'],
    activityIds: ['subtracting-game'],
    legacyScreenIds: [],
    label: 'Subtracting garden',
    title: 'Subtracting Garden',
    description:
      'Shared quantity-drag engine variant for subtraction, grouped with adding ball under the same mechanic family.',
    emoji: '➖',
    mechanic: 'drag_drop',
    interactionMode: 'drag',
    surfaces: ['lesson', 'library'],
    tags: ['subtraction', 'drag', 'quantity'],
    variants: [
      createVariant({
        id: 'subtracting_garden.lesson-inline',
        label: 'Lesson inline',
        title: 'Subtracting garden in lessons',
        description: 'Lesson activity variant powered by the shared quantity-drag engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'subtracting-game',
      }),
      createVariant({
        id: 'subtracting_garden.library-preview',
        label: 'Library preview',
        title: 'Subtracting garden preview',
        description: 'Library preview of the subtraction drag-and-drop variant.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
    ],
    status: 'active',
    sortOrder: 500,
  },
  {
    id: 'multiplication_array',
    engineId: 'array-builder-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['multiplication'],
    activityIds: ['multiplication-array'],
    legacyScreenIds: [],
    label: 'Multiplication array',
    title: 'Multiplication Array',
    description:
      'Array-building engine for repeated groups and visual multiplication practice, scaffolded for shared library reuse.',
    emoji: '✖️',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library'],
    tags: ['multiplication', 'arrays', 'visual'],
    variants: [
      createVariant({
        id: 'multiplication_array.lesson-inline',
        label: 'Lesson inline',
        title: 'Multiplication array in lessons',
        description: 'Lesson activity variant for the shared array-builder engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'multiplication-array',
      }),
      createVariant({
        id: 'multiplication_array.library-preview',
        label: 'Library preview',
        title: 'Multiplication array preview',
        description: 'Library preview for the shared multiplication array engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
    ],
    status: 'active',
    sortOrder: 600,
  },
  {
    id: 'multiplication_quiz',
    engineId: 'choice-quiz-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['multiplication'],
    activityIds: ['multiplication-quiz'],
    legacyScreenIds: ['multiplication_quiz'],
    label: 'Multiplication quiz',
    title: 'Multiplication Quiz',
    description:
      'Choice-based quiz engine shared between multiplication lesson activity blocks and fullscreen game practice.',
    emoji: '🧮',
    mechanic: 'multiple_choice',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['multiplication', 'quiz', 'choice'],
    variants: [
      createVariant({
        id: 'multiplication_quiz.lesson-inline',
        label: 'Lesson inline',
        title: 'Multiplication quiz in lessons',
        description: 'Lesson activity variant using the shared choice-quiz engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'multiplication-quiz',
      }),
      createVariant({
        id: 'multiplication_quiz.library-preview',
        label: 'Library preview',
        title: 'Multiplication quiz preview',
        description: 'Catalog preview for the shared multiplication quiz engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'multiplication_quiz.game-screen',
        label: 'Game screen',
        title: 'Multiplication quiz fullscreen',
        description: 'Legacy fullscreen entry wired to the same shared quiz engine.',
        surface: 'game_screen',
        legacyScreenId: 'multiplication_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 700,
  },
  {
    id: 'division_groups',
    engineId: 'choice-quiz-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['division'],
    activityIds: ['division-game'],
    legacyScreenIds: ['division_quiz'],
    label: 'Division groups',
    title: 'Division Groups',
    description:
      'Division variant of the shared choice-quiz engine, prepared for lesson embedding and standalone fullscreen practice.',
    emoji: '➗',
    mechanic: 'multiple_choice',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['division', 'quiz', 'choice'],
    variants: [
      createVariant({
        id: 'division_groups.lesson-inline',
        label: 'Lesson inline',
        title: 'Division groups in lessons',
        description: 'Lesson activity variant using the shared choice-quiz engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'division-game',
      }),
      createVariant({
        id: 'division_groups.library-preview',
        label: 'Library preview',
        title: 'Division groups preview',
        description: 'Library preview of the shared division quiz engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'division_groups.game-screen',
        label: 'Game screen',
        title: 'Division groups fullscreen',
        description: 'Legacy fullscreen entry wired to the shared division quiz engine.',
        surface: 'game_screen',
        legacyScreenId: 'division_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 800,
  },
  {
    id: 'geometry_drawing',
    engineId: 'shape-drawing-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: [
      'geometry_basics',
      'geometry_shapes',
      'geometry_symmetry',
      'geometry_perimeter',
    ],
    activityIds: ['geometry-drawing'],
    legacyScreenIds: ['geometry_quiz'],
    label: 'Geometry drawing',
    title: 'Geometry Drawing',
    description:
      'Shared drawing engine for geometry topics, reused across multiple lessons and the fullscreen geometry quiz.',
    emoji: '📐',
    mechanic: 'drawing',
    interactionMode: 'draw',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'shapes'],
    variants: [
      createVariant({
        id: 'geometry_drawing.lesson-inline',
        label: 'Lesson inline',
        title: 'Geometry drawing in lessons',
        description: 'Lesson activity variant backed by the shared drawing engine.',
        surface: 'lesson_inline',
        legacyActivityId: 'geometry-drawing',
      }),
      createVariant({
        id: 'geometry_drawing.library-preview',
        label: 'Library preview',
        title: 'Geometry drawing preview',
        description: 'Preview variant for the shared geometry drawing engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'geometry_drawing.game-screen',
        label: 'Game screen',
        title: 'Geometry drawing fullscreen',
        description: 'Fullscreen entry for the shared geometry drawing engine.',
        surface: 'game_screen',
        legacyScreenId: 'geometry_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 900,
  },
  {
    id: 'logical_patterns_workshop',
    engineId: 'pattern-sequence-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_patterns'],
    activityIds: [],
    legacyScreenIds: ['logical_patterns_quiz'],
    label: 'Logical patterns workshop',
    title: 'Logical Patterns Workshop',
    description:
      'Pattern-sequence engine shared between lesson-stage presentation and standalone logical patterns practice.',
    emoji: '🔢',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'patterns', 'sequence'],
    variants: [
      createVariant({
        id: 'logical_patterns_workshop.lesson-stage',
        label: 'Lesson stage',
        title: 'Logical patterns inside lessons',
        description: 'Lesson-stage variant intended for unified lesson flows.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_patterns_workshop.library-preview',
        label: 'Library preview',
        title: 'Logical patterns preview',
        description: 'Preview variant for the shared logical pattern engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_patterns_workshop.game-screen',
        label: 'Game screen',
        title: 'Logical patterns fullscreen',
        description: 'Fullscreen entry for the shared logical pattern engine.',
        surface: 'game_screen',
        legacyScreenId: 'logical_patterns_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1000,
  },
  {
    id: 'logical_classification_lab',
    engineId: 'classification-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_classification'],
    activityIds: [],
    legacyScreenIds: ['logical_classification_quiz'],
    label: 'Logical classification lab',
    title: 'Logical Classification Lab',
    description:
      'Shared classification engine for grouping and odd-one-out mechanics used in lesson-stage and game-screen variants.',
    emoji: '📦',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'classification', 'sorting'],
    variants: [
      createVariant({
        id: 'logical_classification_lab.lesson-stage',
        label: 'Lesson stage',
        title: 'Logical classification inside lessons',
        description: 'Lesson-stage variant for the shared classification engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_classification_lab.library-preview',
        label: 'Library preview',
        title: 'Logical classification preview',
        description: 'Library preview of the shared classification engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_classification_lab.game-screen',
        label: 'Game screen',
        title: 'Logical classification fullscreen',
        description: 'Fullscreen entry for the shared classification engine.',
        surface: 'game_screen',
        legacyScreenId: 'logical_classification_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1100,
  },
  {
    id: 'logical_analogies_relations',
    engineId: 'relation-match-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_analogies'],
    activityIds: [],
    legacyScreenIds: ['logical_analogies_quiz'],
    label: 'Logical analogies relations',
    title: 'Logical Analogies Relations',
    description:
      'Relation-matching engine shared across lesson-stage and fullscreen logical analogies practice.',
    emoji: '🔗',
    mechanic: 'logic_relation',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'analogies', 'relations'],
    variants: [
      createVariant({
        id: 'logical_analogies_relations.lesson-stage',
        label: 'Lesson stage',
        title: 'Logical analogies inside lessons',
        description: 'Lesson-stage variant for the shared relation-match engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_analogies_relations.library-preview',
        label: 'Library preview',
        title: 'Logical analogies preview',
        description: 'Catalog preview of the shared logical analogies engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_analogies_relations.game-screen',
        label: 'Game screen',
        title: 'Logical analogies fullscreen',
        description: 'Fullscreen entry for the shared logical analogies engine.',
        surface: 'game_screen',
        legacyScreenId: 'logical_analogies_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1200,
  },
  {
    id: 'english_sentence_builder',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_sentence_structure'],
    activityIds: [],
    legacyScreenIds: ['english_sentence_quiz'],
    label: 'English sentence builder',
    title: 'English Sentence Builder',
    description:
      'Sentence-building engine scaffolded as a shared asset for English lessons, previews, and fullscreen practice.',
    emoji: '🧩',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['english', 'sentence', 'grammar'],
    variants: [
      createVariant({
        id: 'english_sentence_builder.lesson-stage',
        label: 'Lesson stage',
        title: 'Sentence builder inside lessons',
        description: 'Lesson-stage variant for the shared sentence-builder engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'english_sentence_builder.library-preview',
        label: 'Library preview',
        title: 'Sentence builder preview',
        description: 'Catalog preview for the shared English sentence engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'english_sentence_builder.game-screen',
        label: 'Game screen',
        title: 'Sentence builder fullscreen',
        description: 'Fullscreen entry for the shared sentence-building engine.',
        surface: 'game_screen',
        legacyScreenId: 'english_sentence_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1300,
  },
  {
    id: 'english_parts_of_speech_sort',
    engineId: 'classification-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_parts_of_speech'],
    activityIds: [],
    legacyScreenIds: ['english_parts_of_speech_quiz'],
    label: 'English parts of speech sort',
    title: 'English Parts of Speech Sort',
    description:
      'Classification-engine reuse for English grammar, showing how one engine family can power multiple subjects.',
    emoji: '🔤',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['english', 'grammar', 'classification'],
    variants: [
      createVariant({
        id: 'english_parts_of_speech_sort.lesson-stage',
        label: 'Lesson stage',
        title: 'Parts of speech inside lessons',
        description: 'Lesson-stage variant backed by the shared classification engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'english_parts_of_speech_sort.library-preview',
        label: 'Library preview',
        title: 'Parts of speech preview',
        description: 'Catalog preview for the shared grammar classification engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'english_parts_of_speech_sort.game-screen',
        label: 'Game screen',
        title: 'Parts of speech fullscreen',
        description: 'Fullscreen entry for the shared grammar classification engine.',
        surface: 'game_screen',
        legacyScreenId: 'english_parts_of_speech_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1400,
  },
] as const;

export const createDefaultKangurGames = (): KangurGameDefinition[] =>
  KANGUR_DEFAULT_GAMES.map((game) => ({
    ...game,
    lessonComponentIds: [...game.lessonComponentIds],
    activityIds: [...game.activityIds],
    legacyScreenIds: [...game.legacyScreenIds],
    surfaces: [...game.surfaces],
    tags: [...game.tags],
    variants: game.variants.map((variant) => ({ ...variant })),
  }));
