import type { KangurLessonComponentId } from '@/features/kangur/shared/contracts/kangur';
import type { KangurLessonTemplate } from '@/features/kangur/lessons/lesson-types';

export const MATHS_LESSON_COMPONENT_ORDER = [
  'clock',
  'calendar',
  'adding',
  'subtracting',
  'multiplication',
  'division',
  'geometry_basics',
  'geometry_shapes',
  'geometry_symmetry',
  'geometry_perimeter',
  'logical_thinking',
  'logical_patterns',
  'logical_classification',
  'logical_reasoning',
  'logical_analogies',
] as const satisfies readonly KangurLessonComponentId[];

type MathsLessonComponentId = (typeof MATHS_LESSON_COMPONENT_ORDER)[number];

export const MATHS_LESSON_TEMPLATES: Record<MathsLessonComponentId, KangurLessonTemplate> = {
  clock: {
    componentId: 'clock',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Clock Lesson',
    title: 'Nauka zegara',
    description: 'Godziny, minuty i pełny czas na zegarze analogowym',
    emoji: '🕐',
    color: 'kangur-gradient-accent-indigo-reverse',
    activeBg: 'bg-indigo-500',
  },
  calendar: {
    componentId: 'calendar',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Calendar Lesson',
    title: 'Nauka kalendarza',
    description: 'Dni, miesiące, daty i pory roku',
    emoji: '📅',
    color: 'kangur-gradient-accent-emerald',
    activeBg: 'bg-green-500',
  },
  adding: {
    componentId: 'adding',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Adding Lesson',
    title: 'Dodawanie',
    description: 'Jednocyfrowe, dwucyfrowe i gra z piłkami!',
    emoji: '➕',
    color: 'kangur-gradient-accent-amber',
    activeBg: 'bg-orange-400',
  },
  subtracting: {
    componentId: 'subtracting',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Subtracting Lesson',
    title: 'Odejmowanie',
    description: 'Jednocyfrowe, dwucyfrowe i reszta',
    emoji: '➖',
    color: 'kangur-gradient-accent-rose',
    activeBg: 'bg-red-400',
  },
  multiplication: {
    componentId: 'multiplication',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Multiplication Lesson',
    title: 'Mnożenie',
    description: 'Tabliczka mnożenia i algorytmy',
    emoji: '✖️',
    color: 'kangur-gradient-accent-indigo',
    activeBg: 'bg-purple-500',
  },
  division: {
    componentId: 'division',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Division Lesson',
    title: 'Dzielenie',
    description: 'Proste dzielenie i reszta z dzielenia',
    emoji: '➗',
    color: 'kangur-gradient-accent-teal',
    activeBg: 'bg-blue-500',
  },
  geometry_basics: {
    componentId: 'geometry_basics',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Geometry Basics Lesson',
    title: 'Podstawy geometrii',
    description: 'Punkt, odcinek, bok i kąt',
    emoji: '📐',
    color: 'kangur-gradient-accent-sky',
    activeBg: 'bg-cyan-500',
  },
  geometry_shapes: {
    componentId: 'geometry_shapes',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Geometry Shapes Lesson',
    title: 'Figury geometryczne',
    description: 'Poznaj figury i narysuj je w grze',
    emoji: '🔷',
    color: 'kangur-gradient-accent-violet-reverse',
    activeBg: 'bg-fuchsia-500',
  },
  geometry_symmetry: {
    componentId: 'geometry_symmetry',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Geometry Symmetry Lesson',
    title: 'Symetria',
    description: 'Oś symetrii i odbicia lustrzane',
    emoji: '🪞',
    color: 'kangur-gradient-accent-emerald',
    activeBg: 'bg-emerald-500',
  },
  geometry_perimeter: {
    componentId: 'geometry_perimeter',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Geometry Perimeter Lesson',
    title: 'Obwód figur',
    description: 'Liczenie długości boków krok po kroku',
    emoji: '📏',
    color: 'kangur-gradient-accent-amber-reverse',
    activeBg: 'bg-amber-500',
  },
  logical_thinking: {
    componentId: 'logical_thinking',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Logical Thinking Lesson',
    title: 'Myślenie logiczne',
    description: 'Porządek, zasady i obserwacje',
    emoji: '🧠',
    color: 'kangur-gradient-accent-indigo',
    activeBg: 'bg-indigo-500',
  },
  logical_patterns: {
    componentId: 'logical_patterns',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Logical Patterns Lesson',
    title: 'Wzory',
    description: 'Powtarzalne schematy i rytmy',
    emoji: '🔁',
    color: 'kangur-gradient-accent-sky',
    activeBg: 'bg-sky-500',
  },
  logical_classification: {
    componentId: 'logical_classification',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Logical Classification Lesson',
    title: 'Klasyfikacja',
    description: 'Grupuj, sortuj i znajdź intruza',
    emoji: '📦',
    color: 'kangur-gradient-accent-teal',
    activeBg: 'bg-teal-500',
  },
  logical_reasoning: {
    componentId: 'logical_reasoning',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Logical Reasoning Lesson',
    title: 'Wnioskowanie',
    description: 'Jeśli... to... — myśl krok po kroku',
    emoji: '💡',
    color: 'kangur-gradient-accent-indigo',
    activeBg: 'bg-indigo-500',
  },
  logical_analogies: {
    componentId: 'logical_analogies',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    label: 'Logical Analogies Lesson',
    title: 'Analogie',
    description: 'Znajdź tę samą relację w nowym kontekście',
    emoji: '🔗',
    color: 'kangur-gradient-accent-rose-reverse',
    activeBg: 'bg-pink-500',
  },
};
