import type { BlockDefinition } from '@/features/cms/types/page-builder';
import {
  MODEL_ENVIRONMENT_OPTIONS,
  MODEL_LIGHTING_OPTIONS,
  SHOW_HIDE_OPTIONS,
  TOGGLE_ON_OFF_OPTIONS,
} from './media-constants';

export const MEDIA_3D_BLOCK_DEFINITIONS: Record<string, BlockDefinition> = {
  Model3D: {
    type: 'Model3D',
    label: '3D model',
    icon: 'Cube',
    defaultSettings: {
      assetId: '',
      height: 360,
      backgroundColor: '#111827',
      autoRotate: 'true',
      autoRotateSpeed: 2,
      environment: 'studio',
      lighting: 'studio',
      lightIntensity: 1,
      enableShadows: 'true',
      enableBloom: 'false',
      bloomIntensity: 0.5,
      exposure: 1,
      showGround: 'false',
      enableContactShadows: 'true',
      enableVignette: 'false',
      autoFit: 'true',
      presentationMode: 'false',
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scale: 1,
    },
    settingsSchema: [
      { key: 'assetId', label: '3D asset', type: 'asset3d' },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 360 },
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '#111827' },
      { key: 'autoRotate', label: 'Auto-rotate', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'autoRotateSpeed', label: 'Rotate speed', type: 'number', defaultValue: 2 },
      { key: 'environment', label: 'Environment', type: 'select', options: MODEL_ENVIRONMENT_OPTIONS, defaultValue: 'studio' },
      { key: 'lighting', label: 'Lighting', type: 'select', options: MODEL_LIGHTING_OPTIONS, defaultValue: 'studio' },
      { key: 'lightIntensity', label: 'Light intensity', type: 'number', defaultValue: 1 },
      { key: 'enableShadows', label: 'Shadows', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'enableBloom', label: 'Bloom', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'bloomIntensity', label: 'Bloom intensity', type: 'number', defaultValue: 0.5 },
      { key: 'exposure', label: 'Exposure', type: 'number', defaultValue: 1 },
      { key: 'showGround', label: 'Ground plane', type: 'select', options: SHOW_HIDE_OPTIONS, defaultValue: 'false' },
      { key: 'enableContactShadows', label: 'Contact shadows', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'enableVignette', label: 'Vignette', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'autoFit', label: 'Auto-fit camera', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'presentationMode', label: 'Presentation mode', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'positionX', label: 'Position X', type: 'number', defaultValue: 0 },
      { key: 'positionY', label: 'Position Y', type: 'number', defaultValue: 0 },
      { key: 'positionZ', label: 'Position Z', type: 'number', defaultValue: 0 },
      { key: 'rotationX', label: 'Rotation X (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationY', label: 'Rotation Y (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationZ', label: 'Rotation Z (deg)', type: 'number', defaultValue: 0 },
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1 },
    ],
  },
  Model3DElement: {
    type: 'Model3DElement',
    label: '3D element',
    icon: 'Cube',
    defaultSettings: {
      assetId: '',
      height: 360,
      backgroundColor: '#111827',
      autoRotate: 'true',
      autoRotateSpeed: 2,
      environment: 'studio',
      lighting: 'studio',
      lightIntensity: 1,
      enableShadows: 'true',
      enableBloom: 'false',
      bloomIntensity: 0.5,
      exposure: 1,
      showGround: 'false',
      enableContactShadows: 'true',
      enableVignette: 'false',
      autoFit: 'true',
      presentationMode: 'false',
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scale: 1,
    },
    settingsSchema: [
      { key: 'assetId', label: '3D asset', type: 'asset3d' },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 360 },
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '#111827' },
      { key: 'autoRotate', label: 'Auto-rotate', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'autoRotateSpeed', label: 'Rotate speed', type: 'number', defaultValue: 2 },
      { key: 'environment', label: 'Environment', type: 'select', options: MODEL_ENVIRONMENT_OPTIONS, defaultValue: 'studio' },
      { key: 'lighting', label: 'Lighting', type: 'select', options: MODEL_LIGHTING_OPTIONS, defaultValue: 'studio' },
      { key: 'lightIntensity', label: 'Light intensity', type: 'number', defaultValue: 1 },
      { key: 'enableShadows', label: 'Shadows', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'enableBloom', label: 'Bloom', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'bloomIntensity', label: 'Bloom intensity', type: 'number', defaultValue: 0.5 },
      { key: 'exposure', label: 'Exposure', type: 'number', defaultValue: 1 },
      { key: 'showGround', label: 'Ground plane', type: 'select', options: SHOW_HIDE_OPTIONS, defaultValue: 'false' },
      { key: 'enableContactShadows', label: 'Contact shadows', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'enableVignette', label: 'Vignette', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'autoFit', label: 'Auto-fit camera', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'true' },
      { key: 'presentationMode', label: 'Presentation mode', type: 'select', options: TOGGLE_ON_OFF_OPTIONS, defaultValue: 'false' },
      { key: 'positionX', label: 'Position X', type: 'number', defaultValue: 0 },
      { key: 'positionY', label: 'Position Y', type: 'number', defaultValue: 0 },
      { key: 'positionZ', label: 'Position Z', type: 'number', defaultValue: 0 },
      { key: 'rotationX', label: 'Rotation X (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationY', label: 'Rotation Y (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationZ', label: 'Rotation Z (deg)', type: 'number', defaultValue: 0 },
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1 },
    ],
  },
};
