'use client';

import type { BlockDefinition } from '@/features/cms/types/page-builder';
import {
  BORDER_STYLE_OPTIONS,
  CLIP_OVERFLOW_OPTIONS,
  IMAGE_ASPECT_RATIO_OPTIONS,
  IMAGE_OBJECT_FIT_OPTIONS,
  IMAGE_OBJECT_POSITION_OPTIONS,
  IMAGE_SHAPE_OPTIONS,
  OVERLAY_GRADIENT_DIRECTION_OPTIONS,
  OVERLAY_TYPE_OPTIONS,
  TRANSPARENCY_DIRECTION_OPTIONS,
  TRANSPARENCY_MODE_OPTIONS,
} from './media-constants';

export const IMAGE_BLOCK_DEFINITIONS: Record<string, BlockDefinition> = {
  ImageElement: {
    type: 'ImageElement',
    label: 'Image element',
    icon: 'ImageIcon',
    defaultSettings: {
      src: '',
      alt: '',
      width: 100,
      height: 0,
      aspectRatio: 'auto',
      objectFit: 'cover',
      objectPosition: 'center',
      opacity: 100,
      blur: 0,
      grayscale: 0,
      brightness: 100,
      contrast: 100,
      scale: 100,
      rotate: 0,
      shape: 'none',
      borderRadius: 0,
      borderWidth: 0,
      borderStyle: 'solid',
      borderColor: '#ffffff',
      clipOverflow: 'false',
      overlayType: 'none',
      overlayColor: '#000000',
      overlayOpacity: 0,
      overlayGradientFrom: '#000000',
      overlayGradientTo: '#ffffff',
      overlayGradientDirection: 'to-bottom',
      transparencyMode: 'none',
      transparencyDirection: 'bottom',
      transparencyStrength: 0,
      imageShadow: { x: 0, y: 0, blur: 0, spread: 0, color: '#00000000' },
    },
    settingsSchema: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text', defaultValue: '' },
      { key: 'width', label: 'Width (%)', type: 'range', defaultValue: 100, min: 10, max: 100 },
      { key: 'height', label: 'Fixed height (px)', type: 'range', defaultValue: 0, min: 0, max: 800 },
      { key: 'aspectRatio', label: 'Aspect ratio', type: 'select', options: IMAGE_ASPECT_RATIO_OPTIONS, defaultValue: 'auto' },
      { key: 'objectFit', label: 'Crop mode', type: 'select', options: IMAGE_OBJECT_FIT_OPTIONS, defaultValue: 'cover' },
      { key: 'objectPosition', label: 'Position', type: 'select', options: IMAGE_OBJECT_POSITION_OPTIONS, defaultValue: 'center' },
      { key: 'opacity', label: 'Opacity', type: 'range', defaultValue: 100, min: 0, max: 100 },
      { key: 'blur', label: 'Blur (px)', type: 'range', defaultValue: 0, min: 0, max: 20 },
      { key: 'grayscale', label: 'Grayscale (%)', type: 'range', defaultValue: 0, min: 0, max: 100 },
      { key: 'brightness', label: 'Brightness (%)', type: 'range', defaultValue: 100, min: 0, max: 200 },
      { key: 'contrast', label: 'Contrast (%)', type: 'range', defaultValue: 100, min: 0, max: 200 },
      { key: 'scale', label: 'Scale (%)', type: 'range', defaultValue: 100, min: 50, max: 200 },
      { key: 'rotate', label: 'Rotate (deg)', type: 'range', defaultValue: 0, min: -180, max: 180 },
      { key: 'shape', label: 'Shape', type: 'select', options: IMAGE_SHAPE_OPTIONS, defaultValue: 'none' },
      { key: 'clipOverflow', label: 'Contain image', type: 'select', options: CLIP_OVERFLOW_OPTIONS, defaultValue: 'false' },
      { key: 'borderRadius', label: 'Corner radius (px)', type: 'range', defaultValue: 0, min: 0, max: 40 },
      { key: 'borderWidth', label: 'Border width (px)', type: 'range', defaultValue: 0, min: 0, max: 12 },
      { key: 'borderStyle', label: 'Border style', type: 'select', options: BORDER_STYLE_OPTIONS, defaultValue: 'solid' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#ffffff' },
      { key: 'imageShadow', label: 'Shadow', type: 'shadow', defaultValue: { x: 0, y: 0, blur: 0, spread: 0, color: '#00000000' } },
      { key: 'overlayType', label: 'Overlay', type: 'select', options: OVERLAY_TYPE_OPTIONS, defaultValue: 'none' },
      { key: 'overlayColor', label: 'Overlay color', type: 'color', defaultValue: '#000000' },
      { key: 'overlayOpacity', label: 'Overlay opacity (%)', type: 'range', defaultValue: 0, min: 0, max: 100 },
      { key: 'overlayGradientFrom', label: 'Gradient from', type: 'color', defaultValue: '#000000' },
      { key: 'overlayGradientTo', label: 'Gradient to', type: 'color', defaultValue: '#ffffff' },
      { key: 'overlayGradientDirection', label: 'Gradient direction', type: 'select', options: OVERLAY_GRADIENT_DIRECTION_OPTIONS, defaultValue: 'to-bottom' },
      { key: 'transparencyMode', label: 'Transparency', type: 'select', options: TRANSPARENCY_MODE_OPTIONS, defaultValue: 'none' },
      { key: 'transparencyDirection', label: 'Transparency direction', type: 'select', options: TRANSPARENCY_DIRECTION_OPTIONS, defaultValue: 'bottom' },
      { key: 'transparencyStrength', label: 'Transparency strength (%)', type: 'range', defaultValue: 0, min: 0, max: 100 },
    ],
  },
  Image: {
    type: 'Image',
    label: 'Image',
    icon: 'ImageIcon',
    defaultSettings: { src: '', alt: '', width: 100, borderRadius: 0, clipOverflow: 'false' },
    settingsSchema: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text', defaultValue: '' },
      { key: 'width', label: 'Width (%)', type: 'range', defaultValue: 100, min: 10, max: 100 },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 0 },
      { key: 'clipOverflow', label: 'Contain image', type: 'select', options: CLIP_OVERFLOW_OPTIONS, defaultValue: 'false' },
    ],
  },
};
