export {
  buildKangurEmbeddedBasePath,
  getKangurInternalQueryParamKeys,
  getKangurPageSlug,
  KANGUR_EMBED_QUERY_PARAM,
  KANGUR_MAIN_PAGE_KEY,
  KANGUR_PAGE_TO_SLUG,
  readKangurUrlParam,
} from '@/features/kangur/config/routing';
export {
  Game,
  getKangurWidgetLabel,
  isKangurGameScreen,
  KangurActiveLessonPanelWidget,
  KangurAssignmentSpotlight,
  KangurFeaturePage,
  KangurGameCalendarTrainingWidget,
  KangurGameGeometryTrainingWidget,
  KangurGameHomeActionsWidget,
  KangurGameHomeHeroWidget,
  KangurGameKangurSessionWidget,
  KangurGameKangurSetupWidget,
  KangurGameNavigationWidget,
  KangurGameOperationSelectorWidget,
  KangurGameQuestionWidget,
  KangurGameResultWidget,
  KangurGameTrainingSetupWidget,
  KangurGameXpToastWidget,
  KangurLearnerProfileAssignmentsWidget,
  KangurLearnerProfileHeroWidget,
  KangurLearnerProfileLevelProgressWidget,
  KangurLearnerProfileMasteryWidget,
  KangurLearnerProfileOverviewWidget,
  KangurLearnerProfilePerformanceWidget,
  KangurLearnerProfileRecommendationsWidget,
  KangurLearnerProfileSessionsWidget,
  KangurLessonNavigationWidget,
  KangurLessonsCatalogWidget,
  KangurParentDashboardAssignmentsWidget,
  KangurParentDashboardHeroWidget,
  KangurParentDashboardLearnerManagementWidget,
  KangurParentDashboardProgressWidget,
  KangurParentDashboardScoresWidget,
  KangurParentDashboardTabsWidget,
  KangurPriorityAssignments,
  KANGUR_WIDGET_OPTIONS,
  Leaderboard,
  LearnerProfile,
  Lessons,
  ParentDashboard,
  PlayerProgressCard,
  useKangurProgressState,
} from '@/features/kangur/public';
export {
  useOptionalKangurGameRuntime,
  useOptionalKangurLearnerProfileRuntime,
  useOptionalKangurLessonsRuntime,
  useOptionalKangurParentDashboardRuntime,
  useOptionalKangurRouting,
} from '@/features/kangur/ui/context';
