import type {
  PromptExploderCaptureApplyTo,
  PromptExploderCaptureNormalize,
  PromptExploderRuleSegmentType,
  PromptValidationRule,
  PromptValidationScope,
} from '@/shared/contracts/prompt-engine';

const PROMPT_EXPLODER_SCOPE = ['prompt_exploder'] as const;

const createRegexRule = (rule: {
  id: string;
  title: string;
  description: string;
  pattern: string;
  flags?: string;
  message: string;
  sequence: number;
  sequenceGroupId: string;
  sequenceGroupLabel: string;
  promptExploderSegmentType?: PromptExploderRuleSegmentType;
  promptExploderPriority?: number;
  promptExploderConfidenceBoost?: number;
  promptExploderTreatAsHeading?: boolean;
  promptExploderCaptureTarget?: string | null;
  promptExploderCaptureGroup?: number | null;
  promptExploderCaptureApplyTo?: PromptExploderCaptureApplyTo;
  promptExploderCaptureNormalize?: PromptExploderCaptureNormalize;
  promptExploderCaptureOverwrite?: boolean;
  appliesToScopes?: PromptValidationScope[];
  launchAppliesToScopes?: PromptValidationScope[];
}): PromptValidationRule => ({
  kind: 'regex',
  id: rule.id,
  enabled: true,
  severity: 'info',
  title: rule.title,
  description: rule.description,
  pattern: rule.pattern,
  flags: rule.flags ?? 'm',
  message: rule.message,
  similar: [],
  autofix: {
    enabled: false,
    operations: [],
  },
  sequenceGroupId: rule.sequenceGroupId,
  sequenceGroupLabel: rule.sequenceGroupLabel,
  sequenceGroupDebounceMs: 0,
  sequence: rule.sequence,
  chainMode: 'continue',
  maxExecutions: 1,
  passOutputToNext: true,
  appliesToScopes: rule.appliesToScopes ?? [...PROMPT_EXPLODER_SCOPE],
  launchEnabled: false,
  launchAppliesToScopes: rule.launchAppliesToScopes ?? rule.appliesToScopes ?? [...PROMPT_EXPLODER_SCOPE],
  launchScopeBehavior: 'gate',
  launchOperator: 'contains',
  launchValue: null,
  launchFlags: null,
  promptExploderSegmentType: rule.promptExploderSegmentType ?? null,
  promptExploderPriority: rule.promptExploderPriority ?? 0,
  promptExploderConfidenceBoost: rule.promptExploderConfidenceBoost ?? 0,
  promptExploderTreatAsHeading: rule.promptExploderTreatAsHeading ?? false,
  promptExploderCaptureTarget: rule.promptExploderCaptureTarget ?? null,
  promptExploderCaptureGroup:
    typeof rule.promptExploderCaptureGroup === 'number' &&
    Number.isFinite(rule.promptExploderCaptureGroup)
      ? Math.max(0, Math.floor(rule.promptExploderCaptureGroup))
      : null,
  promptExploderCaptureApplyTo: rule.promptExploderCaptureApplyTo ?? 'segment',
  promptExploderCaptureNormalize: rule.promptExploderCaptureNormalize ?? 'trim',
  promptExploderCaptureOverwrite: rule.promptExploderCaptureOverwrite ?? false,
});

export const PROMPT_EXPLODER_PATTERN_PACK_EXTRA: PromptValidationRule[] = [
  createRegexRule({
    id: 'segment.infer.hierarchical_list.pipeline',
    title: 'Infer Hierarchical List: Pipeline',
    description: 'Recognizes process and pipeline sections.',
    pattern: '^\\s*(PIPELINE|WORKFLOW|PROCESS)\\b',
    flags: 'mi',
    message: 'Likely hierarchical list segment.',
    sequence: 150,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'hierarchical_list',
    promptExploderPriority: 18,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.qa_matrix.quality_checks',
    title: 'Infer QA Matrix',
    description: 'Recognizes QA and quality-gate matrix sections.',
    pattern: '^\\s*(FINAL\\s+QA|QUALITY\\s+GATE|QUALITY\\s+CHECKS?)\\b',
    flags: 'mi',
    message: 'Likely QA matrix segment.',
    sequence: 160,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'qa_matrix',
    promptExploderPriority: 22,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.qa_matrix.pass_fail',
    title: 'Infer QA Matrix: PASS/FAIL',
    description: 'Recognizes explicit pass/fail evaluation blocks.',
    pattern: '\\bPASS\\b[\\s\\S]{0,160}\\bFAIL\\b',
    flags: 'mi',
    message: 'PASS/FAIL matrix markers detected.',
    sequence: 170,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'qa_matrix',
    promptExploderPriority: 20,
    promptExploderConfidenceBoost: 0.12,
  }),
  createRegexRule({
    id: 'segment.infer.conditional_list.if_then',
    title: 'Infer Conditional Segment',
    description: 'Recognizes if/then/unless conditional fragments.',
    pattern: '(\\bonly if\\b|\\bif\\b[\\s\\S]{0,120}\\bthen\\b|\\bunless\\b)',
    flags: 'mi',
    message: 'Conditional segment markers detected.',
    sequence: 180,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'conditional_list',
    promptExploderPriority: 12,
    promptExploderConfidenceBoost: 0.08,
  }),
  createRegexRule({
    id: 'segment.infer.referential_list.code_title',
    title: 'Infer Referential List',
    description: 'Recognizes code-prefixed referential headings.',
    pattern: '^\\s*(P\\d+|RL\\d+|QA(?:_R)?\\d+)\\s*[—:-]',
    flags: 'i',
    message: 'Likely referential list segment.',
    sequence: 190,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'referential_list',
    promptExploderPriority: 10,
    promptExploderConfidenceBoost: 0.06,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.alpha_sections',
    title: 'Infer Sequence: Alpha Sections',
    description: 'Recognizes A) B) C) subsection sequences.',
    pattern: '^\\s*[A-Z]\\)\\s+.+$',
    flags: 'm',
    message: 'Likely alpha-sequence segment.',
    sequence: 200,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 14,
    promptExploderConfidenceBoost: 0.1,
  }),
  createRegexRule({
    id: 'segment.infer.metadata.versioned_banner',
    title: 'Infer Metadata: Versioned Banner',
    description: 'Recognizes versioned metadata banners with framing marks.',
    pattern: '^\\s*(={3,}|-{3,}).*\\bver\\.?\\s*\\d+(\\.\\d+)*.*(={3,}|-{3,})\\s*$',
    flags: 'mi',
    message: 'Likely metadata banner segment.',
    sequence: 210,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'metadata',
    promptExploderPriority: 26,
    promptExploderConfidenceBoost: 0.16,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.modules',
    title: 'Infer Sequence: Modules',
    description: 'Recognizes module-based sequences and execution module headers.',
    pattern: '(\\[MODULES\\]|\\[[A-Z_]+_MODULE\\]|^\\s*\\d+\\.\\s*\\[[A-Z_]+\\])',
    flags: 'mi',
    message: 'Likely module sequence segment.',
    sequence: 220,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 20,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.hierarchical_list.execution_template',
    title: 'Infer Hierarchical List: Execution Template',
    description: 'Recognizes execution templates and numbered run sequences.',
    pattern: '(\\[EXECUTION_TEMPLATE\\]|EXECUTION\\s+TEMPLATE)[\\s\\S]{0,240}\\b1\\.\\s+',
    flags: 'mi',
    message: 'Likely execution-template hierarchical segment.',
    sequence: 230,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'hierarchical_list',
    promptExploderPriority: 19,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.qa_matrix.validation_module',
    title: 'Infer QA Matrix: Validation Module',
    description: 'Recognizes validation/checklist modules with pass/fail style outcomes.',
    pattern: '(\\[VALIDATION_MODULE\\]|VALIDATION\\s+MODULE|FINAL\\s+QA)[\\s\\S]{0,260}(PASS|FAIL|Sanity checks)',
    flags: 'mi',
    message: 'Likely validation QA segment.',
    sequence: 240,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'qa_matrix',
    promptExploderPriority: 21,
    promptExploderConfidenceBoost: 0.13,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.data_model',
    title: 'Infer Sequence: Data Model',
    description: 'Recognizes DATA MODEL and schema-style definition sections.',
    pattern: '(\\[DATA\\s*MODEL\\]|DATA\\s*MODEL)\\b|\\bProductRecord\\b|\\bMarketplaceListingRecord\\b|\\bZeroStockMappingRecord\\b',
    flags: 'mi',
    message: 'Likely data model sequence segment.',
    sequence: 250,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 17,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.conditional_list.dry_run',
    title: 'Infer Conditional: DRY_RUN Flow',
    description: 'Recognizes DRY_RUN if/else behavior segments.',
    pattern: '(\\[DRY_RUN_BEHAVIOR\\]|DRY[_\\s]RUN)[\\s\\S]{0,260}(If\\s+\\[?DRY_RUN\\]?\\s*=\\s*true|If\\s+\\[?DRY_RUN\\]?\\s*=\\s*false)',
    flags: 'mi',
    message: 'Likely DRY_RUN conditional segment.',
    sequence: 260,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'conditional_list',
    promptExploderPriority: 18,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.logging_audit',
    title: 'Infer Sequence: Logging and Audit',
    description: 'Recognizes logging and audit governance sections.',
    pattern: '(\\[LOGGING_AND_AUDIT\\]|LOGGING\\s+AND\\s+AUDIT)\\b',
    flags: 'mi',
    message: 'Likely logging/audit sequence segment.',
    sequence: 270,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 18,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.error_handling',
    title: 'Infer Sequence: Error Handling',
    description: 'Recognizes error handling sections and retry policies.',
    pattern: '(\\[ERROR_HANDLING\\]|ERROR\\s+HANDLING)\\b[\\s\\S]{0,220}(retry|auth_error|network_error|ambiguous_match)',
    flags: 'mi',
    message: 'Likely error-handling sequence segment.',
    sequence: 280,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 19,
    promptExploderConfidenceBoost: 0.11,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.security_notes',
    title: 'Infer Sequence: Security Notes',
    description: 'Recognizes security notes and credential-handling constraints.',
    pattern: '(\\[SECURITY_NOTES\\]|SECURITY\\s+NOTES)\\b[\\s\\S]{0,220}(credentials|token|cookie|mfa|secret)',
    flags: 'mi',
    message: 'Likely security-notes sequence segment.',
    sequence: 290,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 19,
    promptExploderConfidenceBoost: 0.11,
    promptExploderTreatAsHeading: true,
  }),
];
