export const FILEMAKER_CAMPAIGN_VERSION = 1;
export const FILEMAKER_CAMPAIGN_CONTENT_GROUP_VERSION = 1;
export const FILEMAKER_CAMPAIGN_RUN_VERSION = 1;
export const FILEMAKER_CAMPAIGN_DELIVERY_VERSION = 1;
export const FILEMAKER_CAMPAIGN_DELIVERY_ATTEMPT_VERSION = 1;
export const FILEMAKER_CAMPAIGN_EVENT_VERSION = 1;
export const FILEMAKER_CAMPAIGN_SUPPRESSION_VERSION = 1;
export const FILEMAKER_EMAIL_CAMPAIGN_MAX_DELIVERY_ATTEMPTS = 3;
