services:
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-app}
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - mongodb_local:/data/db

volumes:
  mongodb_local:
