services:
  db:
    image: mongo:7
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB:-app}
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - ./mongo/local-data:/data/db

  neo4j:
    image: neo4j:5-community
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-neo4jdevpassword}
    ports:
      - '${NEO4J_BROWSER_PORT:-7474}:7474'
      - '${NEO4J_BOLT_PORT:-7687}:7687'
    volumes:
      - neo4j_local:/data

volumes:
  neo4j_local:
