import type {
  AnimationPreset,
  AnimationEasing,
  AnimationTrigger,
  StaggerFrom,
  ParallaxPreset,
  ParallaxAxis,
  ParallaxPattern,
  TextEffect,
  DragAxis,
  ObserverType,
  VelocityEffect,
  TimelineMode,
  ScrollMode,
  RevealStyle,
  GsapAnimationConfig,
} from '@/shared/contracts/gsap';

export type {
  AnimationPreset,
  AnimationEasing,
  AnimationTrigger,
  StaggerFrom,
  ParallaxPreset,
  ParallaxAxis,
  ParallaxPattern,
  TextEffect,
  DragAxis,
  ObserverType,
  VelocityEffect,
  TimelineMode,
  ScrollMode,
  RevealStyle,
  GsapAnimationConfig,
};

export {
  ANIMATION_PRESETS,
  ANIMATION_EASINGS,
  PARALLAX_PRESETS,
  PARALLAX_PATTERNS,
  TIMELINE_MODES,
  SCROLL_MODES,
  REVEAL_STYLES,
  TEXT_EFFECTS,
  DRAG_AXES,
  OBSERVER_TYPES,
  VELOCITY_EFFECTS,
  PARALLAX_DEFAULTS,
  DEFAULT_ANIMATION_CONFIG,
} from '@/shared/contracts/gsap';
