// ---------------------------------------------------------------------------
// GSAP animation configuration types
// ---------------------------------------------------------------------------

import type { 
  AnimationPresetDto,
  AnimationEasingDto,
  AnimationTriggerDto,
  StaggerFromDto,
  ParallaxPresetDto,
  ParallaxAxisDto,
  ParallaxPatternDto,
  TextEffectDto,
  DragAxisDto,
  ObserverTypeDto,
  VelocityEffectDto,
  TimelineModeDto,
  ScrollModeDto,
  RevealStyleDto,
  GsapAnimationConfigDto
} from '@/shared/contracts/gsap';

export type AnimationPreset = AnimationPresetDto;
export type AnimationEasing = AnimationEasingDto;
export type AnimationTrigger = AnimationTriggerDto;
export type StaggerFrom = StaggerFromDto;
export type ParallaxPreset = ParallaxPresetDto;
export type ParallaxAxis = ParallaxAxisDto;
export type ParallaxPattern = ParallaxPatternDto;
export type TextEffect = TextEffectDto;
export type DragAxis = DragAxisDto;
export type ObserverType = ObserverTypeDto;
export type VelocityEffect = VelocityEffectDto;
export type TimelineMode = TimelineModeDto;
export type ScrollMode = ScrollModeDto;
export type RevealStyle = RevealStyleDto;
export type GsapAnimationConfig = GsapAnimationConfigDto;

export {
  ANIMATION_PRESETS,
  ANIMATION_EASINGS,
  PARALLAX_PRESETS,
  PARALLAX_PATTERNS,
  TIMELINE_MODES,
  SCROLL_MODES,
  REVEAL_STYLES,
  TEXT_EFFECTS,
  DRAG_AXES,
  OBSERVER_TYPES,
  VELOCITY_EFFECTS,
  PARALLAX_DEFAULTS,
} from '@/shared/contracts/gsap';

export const DEFAULT_ANIMATION_CONFIG: GsapAnimationConfig = {
  preset: 'none',
  duration: 1,
  delay: 0,
  easing: 'power2.out',
  trigger: 'load',
  selector: '',
  staggerEach: 0.12,
  staggerAmount: 0,
  staggerFrom: 'start',
  parallaxPreset: 'none',
  parallaxSelector: '',
  parallaxAxis: 'y',
  parallaxOffset: 0,
  parallaxScrub: 0.6,
  parallaxStart: 'top 85%',
  parallaxEnd: 'bottom top',
  parallaxEase: 'sine.inOut',
  parallaxPattern: 'uniform',
  parallaxReverse: false,
  parallaxChildStep: 16,
  parallaxLayerStrength: 0.35,
  parallaxLayerScaleStep: 0.015,
  parallaxRandomSeed: 7,
  parallaxScaleFrom: 1,
  parallaxScaleTo: 1,
  parallaxRotateFrom: 0,
  parallaxRotateTo: 0,
  parallaxOpacityFrom: 1,
  parallaxOpacityTo: 1,
  parallaxBlurFrom: 0,
  parallaxBlurTo: 0,
  motionPathEnabled: false,
  motionPathPath: '',
  motionPathAlign: true,
  motionPathAutoRotate: true,
  motionPathRotateOffset: 0,
  motionPathStart: 0,
  motionPathEnd: 1,
  motionPathFollow: false,
  motionPathSpacing: 0.08,
  motionPathShapes: [],
  svgDrawEnabled: false,
  svgDrawSelector: 'path, line, circle, rect, polyline, polygon',
  svgDrawFrom: 0,
  svgDrawTo: 100,
  svgDrawPath: '',
  svgDrawShapes: [],
  svgMorphEnabled: false,
  svgMorphSelector: 'path',
  svgMorphTo: '',
  svgMorphShapes: [],
  textEffect: 'none',
  textStagger: 0.05,
  textScrambleChars: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
  textTypingSpeed: 24,
  textCursor: true,
  textCountFrom: undefined,
  textCountTo: undefined,
  textCountDecimals: 0,
  visualFilterFrom: '',
  visualFilterTo: '',
  visualClipFrom: '',
  visualClipTo: '',
  visualRadiusFrom: '',
  visualRadiusTo: '',
  visualShadowFrom: '',
  visualShadowTo: '',
  visualBackgroundFrom: '',
  visualBackgroundTo: '',
  flipEnabled: false,
  flipSelector: '',
  flipScale: true,
  flipFade: true,
  draggableEnabled: false,
  draggableType: 'x,y',
  draggableBounds: '',
  draggableMomentum: false,
  draggableMomentumFactor: 0.6,
  draggableSnap: 0,
  draggableCarousel: false,
  draggableCarouselSelector: '',
  draggableCarouselSnap: true,
  observerEnabled: false,
  observerType: 'wheel,touch',
  observerAxis: 'y',
  observerSpeed: 1,
  velocityEffect: 'none',
  velocityStrength: 0.15,
  velocityMax: 20,
  magnetEnabled: false,
  magnetStrength: 0.35,
  magnetRadius: 140,
  magnetAxis: 'x,y',
  magnetReturn: 0.35,
  timelineMode: 'none',
  timelineGap: 0.15,
  timelineOverlap: 0.2,
  timelineResponseOffset: 0.2,
  timelineStaggerEach: 0.12,
  timelineWaveAmount: 0.5,
  timelineRandomize: false,
  timelineLoop: false,
  timelineRepeat: -1,
  timelineYoyo: false,
  timelineRepeatDelay: 0.2,
  scrollMode: 'none',
  scrollScrub: 0.6,
  scrollPin: false,
  scrollSnap: false,
  scrollSnapDuration: 0.35,
  scrollStart: 'top 85%',
  scrollEnd: 'bottom top',
  revealStyle: 'none',
  customEase: '',
};
