import { renderHook } from '@testing-library/react';
import { describe, expect, it } from 'vitest';
import { useProductListSubContexts } from '../useProductListSubContexts';
import type { ProductListContextType } from '../../ProductListContext.types';

describe('useProductListSubContexts', () => {
  const mockValue = {
    page: 1,
    totalPages: 10,
    setPage: () => {},
    pageSize: 25,
    setPageSize: () => {},
    nameLocale: 'en',
    setNameLocale: () => {},
    languageOptions: [],
    currencyCode: 'USD',
    setCurrencyCode: () => {},
    currencyOptions: [],
    filtersCollapsedByDefault: false,
    catalogFilter: null,
    setCatalogFilter: () => {},
    catalogs: [],
    search: '',
    setSearch: () => {},
    productId: '',
    setProductId: () => {},
    idMatchMode: 'exact',
    setIdMatchMode: () => {},
    sku: '',
    setSku: () => {},
    description: '',
    setDescription: () => {},
    categoryId: null,
    setCategoryId: () => {},
    minPrice: null,
    setMinPrice: () => {},
    maxPrice: null,
    setMaxPrice: () => {},
    stockValue: null,
    setStockValue: () => {},
    stockOperator: 'eq',
    setStockOperator: () => {},
    startDate: null,
    setStartDate: () => {},
    endDate: null,
    setEndDate: () => {},
    advancedFilter: null,
    activeAdvancedFilterPresetId: null,
    advancedFilterPresets: [],
    setAdvancedFilterPresets: async () => {},
    setAdvancedFilter: () => {},
    setAdvancedFilterState: () => {},
    baseExported: null,
    setBaseExported: () => {},
    data: [],
    rowSelection: {},
    setRowSelection: () => {},
    onSelectAllGlobal: () => {},
    loadingGlobal: false,
    onDeleteSelected: async () => {},
    onAddToMarketplace: async () => {},
    handleProductsTableRender: () => null,
    tableColumns: [],
    getRowClassName: () => '',
    getRowId: () => '',
    isLoading: false,
    skeletonRows: 5,
    maxHeight: '500px',
    stickyHeader: true,
    loadError: null,
    actionError: null,
    onDismissActionError: () => {},
    onCreateProduct: () => {},
    onCreateFromDraft: () => {},
    activeDrafts: [],
    setRefreshTrigger: () => {},
    productNameKey: 'name',
    priceGroups: [],
    onPrefetchProductDetail: () => {},
    onProductNameClick: () => {},
    onProductEditClick: () => {},
    onProductDeleteClick: () => {},
    onDuplicateProduct: () => {},
    onIntegrationsClick: () => {},
    onExportSettingsClick: () => {},
    categoryNameById: {},
    thumbnailSource: 'internal',
    imageExternalBaseUrl: '',
    showTriggerRunFeedback: false,
    setShowTriggerRunFeedback: () => {},
    isCreateOpen: false,
    isPromptOpen: false,
    setIsPromptOpen: () => {},
    handleConfirmSku: async () => {},
    initialSku: '',
    createDraft: null,
    initialCatalogId: null,
    onCloseCreate: () => {},
    onCreateSuccess: () => {},
    editingProduct: null,
    isEditHydrating: false,
    onCloseEdit: () => {},
    onEditSuccess: () => {},
    onEditSave: async () => {},
    integrationsProduct: null,
    integrationsRecoveryContext: null,
    onCloseIntegrations: () => {},
    onStartListing: () => {},
    showListProductModal: false,
    onCloseListProduct: () => {},
    onListProductSuccess: () => {},
    listProductPreset: null,
    exportSettingsProduct: null,
    onCloseExportSettings: () => {},
    onListingsUpdated: () => {},
    massListIntegration: null,
    massListProductIds: [],
    onCloseMassList: () => {},
    onMassListSuccess: () => {},
    showIntegrationModal: false,
    onCloseIntegrationModal: () => {},
    onSelectIntegrationFromModal: () => {},
    integrationBadgeIds: new Set(),
    integrationBadgeStatuses: new Map(),
    traderaBadgeIds: new Set(),
    traderaBadgeStatuses: new Map(),
    queuedProductIds: new Set(),
    productAiRunStatusByProductId: new Map(),
    rowRuntimeReady: false,
  } as unknown as ProductListContextType;

  it('should split value into multiple memoized contexts', () => {
    const { result } = renderHook(() => useProductListSubContexts(mockValue));

    expect(result.current.filtersValue).toBeDefined();
    expect(result.current.selectionValue).toBeDefined();
    expect(result.current.tableValue).toBeDefined();
    expect(result.current.alertsValue).toBeDefined();
    expect(result.current.actionsValue).toBeDefined();
    expect(result.current.headerActionsValue).toBeDefined();
    expect(result.current.rowActionsValue).toBeDefined();
    expect(result.current.rowVisualsValue).toBeDefined();
    expect(result.current.modalsValue).toBeDefined();

    expect(result.current.filtersValue.page).toBe(1);
    expect(result.current.selectionValue.loadingGlobal).toBe(false);
    expect(result.current.filtersValue.advancedFilterPresets).toEqual([]);
    expect(result.current.headerActionsValue.triggerButtonsReady).toBe(false);
    expect(result.current.rowVisualsValue.triggerButtonsReady).toBe(false);
  });
});
