// @vitest-environment jsdom

import React from 'react';
import { render, screen } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

const mocks = vi.hoisted(() => ({
  useSystemLogsStateMock: vi.fn(),
  useSystemLogsActionsMock: vi.fn(),
}));

vi.mock('@/features/observability/context/SystemLogsContext', () => ({
  useSystemLogsState: mocks.useSystemLogsStateMock,
  useSystemLogsActions: mocks.useSystemLogsActionsMock,
}));

import { LogTriagePresets } from './SystemLogs.Presets';

describe('LogTriagePresets', () => {
  beforeEach(() => {
    mocks.useSystemLogsStateMock.mockReset().mockReturnValue({
      level: 'all',
      query: '',
      source: '',
      service: '',
      method: '',
      statusCode: '',
      minDurationMs: '',
      requestId: '',
      traceId: '',
      correlationId: '',
      userId: '',
      fingerprint: '',
      category: '',
      fromDate: '',
      toDate: '',
    });
    mocks.useSystemLogsActionsMock.mockReset().mockReturnValue({
      handleFilterChange: vi.fn(),
      handleResetFilters: vi.fn(),
    });
  });

  it('renders triage preset buttons with wrapping text and taller height', () => {
    render(<LogTriagePresets />);

    const button = screen.getByText('System Alerts').closest('button');
    expect(button).not.toBeNull();
    expect(button).toHaveClass('min-h-[5.75rem]');
    expect(button).toHaveClass('whitespace-normal');
    expect(button).toHaveClass('items-start');

    const label = screen.getByText('System Alerts');
    expect(label).toHaveClass('whitespace-normal');
    expect(label).toHaveClass('break-words');

    const description = screen.getByText(
      'Alert events generated by the observability worker in the last 24 hours.'
    );
    expect(description).toHaveClass('whitespace-normal');
    expect(description).toHaveClass('break-words');
  });
});
