'use client';

export type ProfileModalTabId = 'settings' | 'metrics';

export type LearnerManagementCopy = {
  activeSession: string;
  activeStatus: string;
  addLearner: string;
  ageLabel: string;
  agePlaceholder: string;
  ageValue: (age: number) => string;
  cancel: string;
  confirmRemoval: string;
  createModalClose: string;
  createModalDescription: string;
  createModalTitle: string;
  currentProfileDescriptionPrefix: string;
  currentProfileLabel: string;
  disabledStatus: string;
  durationLabel: string;
  endLabel: string;
  hidePassword: string;
  inProgress: string;
  lastActivityLabel: string;
  lastProfileUpdateLabel: string;
  learnerCardAriaLabel: (displayName: string, statusLabel: string) => string;
  learnerLoginDescription: (loginName: string) => string;
  learnerManagementDescription: string;
  learnerManagementEyebrow: string;
  learnerManagementTitle: string;
  learnerNameLabel: string;
  learnerNamePlaceholder: string;
  learnerNicknameLabel: string;
  learnerNicknamePlaceholder: string;
  learnerPasswordLabel: string;
  learnerProfileSettings: string;
  learnerStatusLabel: string;
  loadMoreSessions: string;
  loading: string;
  loginLabel: string;
  loginOwnershipNote: string;
  loginSessionsDescription: string;
  loginSessionsEmptyDescription: string;
  loginSessionsEmptyTitle: string;
  loginSessionsLabel: string;
  metricsDescription: string;
  metricsTab: string;
  metricsTitle: string;
  newPasswordOptional: string;
  newProfileEyebrow: string;
  noData: string;
  noSessionsError: string;
  olderSessionsError: string;
  optional: string;
  profileCreatedLabel: string;
  profileDetailsDescription: string;
  profileDetailsLabel: string;
  profileSettingsDescription: string;
  profileSettingsTitle: string;
  removeLearnerProfile: string;
  removalWarning: string;
  saveLearner: string;
  selectedProfileHint: string;
  settingsClose: string;
  settingsTab: string;
  sessionCompleted: string;
  sessionErrorDescription: string;
  sessionLabel: (index: number) => string;
  sessionsClose: string;
  sessionsLoadingDescription: string;
  sessionsLoadingTitle: string;
  showPassword: string;
  startLabel: string;
  statusLabel: string;
  switchProfileHint: string;
  tabListLabel: string;
  updatedProfileDescription: string;
  widgetFeedbackPrefix: string;
};
