export const settingSections = [
  'Categories',
  'Shipping Groups',
  'Tags',
  'Custom Fields',
  'Parameters',
  'Price Groups',
  'Catalogs',
  'Defaults',
  'Sync Settings',
  'Image Serving',
  'Studio',
  'Validator',
  'Internationalization',
] as const;
