export {
  TRADERA_LOGIN_SUCCESS_SELECTORS,
  LOGIN_SUCCESS_SELECTOR,
  TRADERA_LOGIN_FORM_SELECTORS,
  LOGIN_FORM_SELECTOR,
  USERNAME_SELECTORS,
  PASSWORD_SELECTORS,
  LOGIN_BUTTON_SELECTORS,
  TRADERA_EMAIL_VERIFICATION_CODE_INPUT_SELECTORS,
  TRADERA_EMAIL_VERIFICATION_SUBMIT_SELECTORS,
  TRADERA_COOKIE_ACCEPT_SELECTORS,
  TRADERA_AUTH_ERROR_SELECTORS,
  TRADERA_CAPTCHA_HINTS,
  TRADERA_MANUAL_VERIFICATION_TEXT_HINTS,
  TRADERA_MANUAL_VERIFICATION_URL_HINTS,
  TITLE_SELECTORS,
  DESCRIPTION_SELECTORS,
  PRICE_SELECTORS,
  SUBMIT_SELECTORS,
} from '@/shared/lib/browser-execution/selectors/tradera';

export const DEFAULT_TRADERA_API_CATEGORY_ID = 344481;
export const DEFAULT_TRADERA_API_PAYMENT_CONDITION =
  process.env['TRADERA_API_DEFAULT_PAYMENT_CONDITION'] ?? 'Payment within 3 days';
export const DEFAULT_TRADERA_API_SHIPPING_CONDITION =
  process.env['TRADERA_API_DEFAULT_SHIPPING_CONDITION'] ?? 'Shipping paid by buyer';

export type TraderaFailureCategory =
  | 'AUTH'
  | 'FORM'
  | 'SELECTOR'
  | 'NAVIGATION'
  | 'UNKNOWN';
