import type { ProductValidationPatternFormData as PatternFormData } from '@/shared/contracts/products/validation';

export const EMPTY_FORM: PatternFormData = {
  label: '',
  target: 'name',
  locale: '',
  regex: '',
  flags: '',
  message: '',
  severity: 'error',
  enabled: true,
  replacementEnabled: false,
  replacementAutoApply: false,
  skipNoopReplacementProposal: true,
  replacementValue: '',
  replacementFields: [],
  replacementAppliesToScopes: ['draft_template', 'product_create', 'product_edit'],
  postAcceptBehavior: 'revalidate',
  denyBehaviorOverride: 'inherit',
  validationDebounceMs: '0',
  replacementMode: 'static',
  sourceMode: 'current_field',
  sourceField: '',
  sourceRegex: '',
  sourceFlags: '',
  sourceMatchGroup: '',
  launchEnabled: false,
  launchAppliesToScopes: ['draft_template', 'product_create', 'product_edit'],
  launchScopeBehavior: 'gate',
  launchSourceMode: 'current_field',
  launchSourceField: '',
  launchOperator: 'equals',
  launchValue: '',
  launchFlags: '',
  mathOperation: 'none',
  mathOperand: '1',
  roundMode: 'none',
  padLength: '',
  padChar: '0',
  logicOperator: 'none',
  logicOperand: '',
  logicFlags: '',
  logicWhenTrueAction: 'keep',
  logicWhenTrueValue: '',
  logicWhenFalseAction: 'keep',
  logicWhenFalseValue: '',
  resultAssembly: 'segment_only',
  targetApply: 'replace_matched_segment',
  sequenceGroupId: '',
  sequence: '',
  chainMode: 'continue',
  maxExecutions: '1',
  passOutputToNext: true,
  runtimeEnabled: false,
  runtimeType: 'none',
  runtimeConfig: '',
  appliesToScopes: ['draft_template', 'product_create', 'product_edit'],
};
