import { DEFAULT_THEME, normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';

/** Kangur Daily theme — soft pastel studio palette (2026-03-13). */
export const KANGUR_DAILY_THEME: ThemeSettings = normalizeThemeSettings({
  ...DEFAULT_THEME,
  themePreset: 'kangur-daily',
  darkMode: false,
  primaryColor: '#6b63ff',
  secondaryColor: '#8d85ff',
  accentColor: '#b9b2ff',
  backgroundColor: '#f1ecf4',
  surfaceColor: '#f8f5fb',
  textColor: '#2f3b52',
  mutedTextColor: '#6b778f',
  borderColor: '#e4deef',
  errorColor: '#f06f7b',
  successColor: '#36b987',
  colorSchemes: [
    {
      id: 'kangur-daily-violet',
      name: 'Daily Violet',
      colors: {
        background: '#f1effb',
        surface: '#f8f6ff',
        text: '#2f3b52',
        accent: '#6b63ff',
        border: '#e4def4',
      },
    },
    {
      id: 'kangur-daily-sky',
      name: 'Daily Sky',
      colors: {
        background: '#eef4ff',
        surface: '#f7faff',
        text: '#2f3b52',
        accent: '#6aa8ff',
        border: '#dbe6f7',
      },
    },
    {
      id: 'kangur-daily-mint',
      name: 'Daily Mint',
      colors: {
        background: '#edf8f3',
        surface: '#f6fbf8',
        text: '#2f3b52',
        accent: '#5fc3a1',
        border: '#d8efe6',
      },
    },
    {
      id: 'kangur-daily-sand',
      name: 'Daily Sand',
      colors: {
        background: '#fdf2e7',
        surface: '#fff7ef',
        text: '#2f3b52',
        accent: '#f0a36d',
        border: '#f1e0d2',
      },
    },
  ],
  activeColorSchemeId: 'kangur-daily-violet',
  headingFont: 'Sora, sans-serif',
  bodyFont: "'DM Sans', sans-serif",
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1.05,
  bodySizeScale: 1,
  lineHeight: 1.6,
  headingLineHeight: 1.2,
  maxContentWidth: 1240,
  gridGutter: 28,
  sectionSpacing: 72,
  containerPadding: 28,
  borderRadius: 28,
  pagePaddingTop: 36,
  pagePaddingRight: 32,
  pagePaddingBottom: 84,
  pagePaddingLeft: 32,
  pagePadding: 32,
  pageMargin: 0,
  fullWidth: false,
  enableAnimations: true,
  animationDuration: 280,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.01,
  btnPaddingX: 22,
  btnPaddingY: 10,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 999,
  btnPrimaryBg: 'linear-gradient(135deg, #ffb36b 0%, #ff9a63 48%, #ff7f52 100%)',
  btnPrimaryText: '#ffffff',
  btnSecondaryBg: 'rgba(255, 255, 255, 0.86)',
  btnSecondaryText: '#3b4561',
  btnOutlineBorder: '#d9d3ee',
  btnBorderWidth: 1,
  btnBorderOpacity: 65,
  btnBorderRadius: 999,
  btnShadowOpacity: 0.18,
  btnShadowX: 0,
  btnShadowY: 10,
  btnShadowBlur: 30,
  btnGlossOpacity: 0.34,
  btnGlossHeight: 48,
  btnInsetHighlightOpacity: 0.35,
  pillRadius: 999,
  pillPaddingX: 14,
  pillPaddingY: 6,
  pillFontSize: 12,
  pillBg: 'rgba(255, 255, 255, 0.74)',
  pillText: '#5b6780',
  pillActiveBg: '#e8e4ff',
  pillActiveText: '#4338ca',
  pillBorderColor: '#ebe6f6',
  pillBorderWidth: 1,
  pillBorderOpacity: 70,
  pillShadowOpacity: 0.18,
  pillShadowX: 0,
  pillShadowY: 10,
  pillShadowBlur: 26,
  inputHeight: 50,
  inputRadius: 22,
  inputBorderColor: '#e4def0',
  inputBorderWidth: 1,
  inputBorderOpacity: 80,
  inputBg: '#ffffff',
  inputText: '#364158',
  inputFocusBorder: '#c3bbff',
  inputPlaceholder: '#8895ad',
  inputFontSize: 14,
  inputShadowOpacity: 0.12,
  inputShadowX: 0,
  inputShadowY: 12,
  inputShadowBlur: 30,
  homeActionLessonsLabelStart: '#7387ff',
  homeActionLessonsLabelMid: '#92a1ff',
  homeActionLessonsLabelEnd: '#c6a9ff',
  homeActionPlayLabelStart: '#6e79ff',
  homeActionPlayLabelMid: '#8c7cff',
  homeActionPlayLabelEnd: '#d48bff',
  homeActionTrainingLabelStart: '#59a9ff',
  homeActionTrainingLabelMid: '#67c7ff',
  homeActionTrainingLabelEnd: '#96dcff',
  homeActionKangurLabelStart: '#ffb368',
  homeActionKangurLabelMid: '#ff9b81',
  homeActionKangurLabelEnd: '#d8a0ff',
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardTextAlignment: 'left',
  cardColorScheme: 'kangur-daily-violet',
  cardRadius: 26,
  cardShadow: 'large',
  cardBg: '#f7f4fb',
  cardHoverShadow: 'large',
  showBadge: true,
  showQuickAdd: false,
  cardBorderWidth: 1,
  cardBorderOpacity: 70,
  cardBorderRadius: 26,
  cardShadowOpacity: 0.18,
  cardShadowX: 0,
  cardShadowY: 18,
  cardShadowBlur: 36,
  collectionRatio: '16:9',
  collectionRadius: 24,
  collectionStyle: 'overlay',
  collectionImagePadding: 8,
  collectionOverlay: true,
  collectionOverlayColor: 'rgba(255, 255, 255, 0.72)',
  collectionTextAlign: 'left',
  collectionColorScheme: 'kangur-daily-violet',
  collectionBorderWidth: 1,
  collectionBorderOpacity: 70,
  collectionShadowOpacity: 0.18,
  collectionShadowX: 0,
  collectionShadowY: 18,
  collectionShadowBlur: 36,
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 8,
  blogTextAlignment: 'left',
  blogColorScheme: 'kangur-daily-violet',
  blogRadius: 24,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 3,
  blogBorderWidth: 1,
  blogBorderOpacity: 70,
  blogBorderRadius: 24,
  blogShadowOpacity: 0.18,
  blogShadowX: 0,
  blogShadowY: 18,
  blogShadowBlur: 36,
  containerBg: '#f7f4fb',
  containerBorderColor: '#ece7f5',
  containerRadius: 30,
  containerPaddingInner: 24,
  containerShadow: 'large',
  containerBorderWidth: 1,
  containerBorderOpacity: 70,
  containerBorderRadius: 30,
  containerShadowOpacity: 0.2,
  containerShadowX: 0,
  containerShadowY: 20,
  containerShadowBlur: 50,
  imageRadius: 18,
  imageBorderColor: '#eee9f6',
  imageBorderWidth: 1,
  imageBorderOpacity: 60,
  imageShadowOpacity: 0.12,
  imageShadowX: 0,
  imageShadowY: 12,
  imageShadowBlur: 30,
  imagePlaceholderBg: '#f3eff8',
  dropdownBg: '#f8f5fb',
  dropdownBorder: '#e5e0ef',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 75,
  dropdownRadius: 20,
  dropdownShadow: 'large',
  dropdownShadowOpacity: 0.2,
  dropdownShadowX: 0,
  dropdownShadowY: 18,
  dropdownShadowBlur: 40,
  popupOverlayColor: 'rgba(47, 59, 82, 0.18)',
  popupRadius: 28,
  drawerWidth: 400,
  drawerBg: '#f7f4fb',
  drawerOverlayColor: 'rgba(47, 59, 82, 0.2)',
  drawerPosition: 'right',
  drawerBorderColor: '#e7e1f1',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 75,
  drawerRadius: 26,
  drawerShadowOpacity: 0.22,
  drawerShadowX: 0,
  drawerShadowY: 18,
  drawerShadowBlur: 48,
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#ece8f8',
  badgeDefaultText: '#4b5570',
  badgeSaleColorScheme: 'kangur-daily-sand',
  badgeSaleBg: '#ffd9c2',
  badgeSaleText: '#8a4b2b',
  badgeSoldOutColorScheme: 'kangur-daily-violet',
  badgeSoldOutBg: '#f1effb',
  badgeSoldOutText: '#64728a',
});

/**
 * Default daily theme — uses factory daily baseline.
 * Used as the daily reset target.
 */
export const KANGUR_DEFAULT_DAILY_THEME: ThemeSettings = KANGUR_DAILY_THEME;

export const KANGUR_DAILY_BLOOM_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_DAILY_THEME,
  themePreset: 'kangur-daily-bloom',
  primaryColor: '#2f7d7a',
  secondaryColor: '#e57d6b',
  accentColor: '#f2b255',
  backgroundColor: '#f7f1e8',
  surfaceColor: '#fffefc',
  textColor: '#2e2a30',
  mutedTextColor: '#6f6a73',
  borderColor: '#eadfce',
  errorColor: '#e36b6b',
  successColor: '#3fbf8f',
  colorSchemes: [
    {
      id: 'kangur-bloom-ivory',
      name: 'Bloom Ivory',
      colors: {
        background: '#f7f1e8',
        surface: '#fff8f1',
        text: '#2e2a30',
        accent: '#2f7d7a',
        border: '#eadfce',
      },
    },
    {
      id: 'kangur-bloom-rose',
      name: 'Bloom Rose',
      colors: {
        background: '#fff1f1',
        surface: '#fff7f7',
        text: '#2e2a30',
        accent: '#e57d6b',
        border: '#f0d6d2',
      },
    },
    {
      id: 'kangur-bloom-sky',
      name: 'Bloom Sky',
      colors: {
        background: '#eef6ff',
        surface: '#f7fbff',
        text: '#2e2a30',
        accent: '#5aa4ff',
        border: '#d7e6f7',
      },
    },
    {
      id: 'kangur-bloom-sage',
      name: 'Bloom Sage',
      colors: {
        background: '#edf7f1',
        surface: '#f6fbf8',
        text: '#2e2a30',
        accent: '#5fb38c',
        border: '#d6ece1',
      },
    },
  ],
  activeColorSchemeId: 'kangur-bloom-ivory',
  headingFont: 'Outfit, sans-serif',
  bodyFont: "'Plus Jakarta Sans', sans-serif",
  headingSizeScale: 1.06,
  lineHeight: 1.62,
  btnPrimaryBg: 'linear-gradient(135deg, #2f7d7a 0%, #3aa890 52%, #64cfb1 100%)',
  btnPrimaryText: '#ffffff',
  btnSecondaryBg: 'rgba(255, 255, 255, 0.9)',
  btnSecondaryText: '#3d3a40',
  btnOutlineBorder: '#e4d6c8',
  btnBorderOpacity: 70,
  btnShadowOpacity: 0.12,
  btnShadowY: 8,
  btnShadowBlur: 24,
  pillBg: 'rgba(255, 255, 255, 0.72)',
  pillText: '#5f5a63',
  pillActiveBg: '#e6f4ef',
  pillActiveText: '#2f7d7a',
  pillBorderColor: '#eadfce',
  pillBorderOpacity: 70,
  pillShadowOpacity: 0.08,
  inputBorderColor: '#e2d5c8',
  inputBg: '#ffffff',
  inputText: '#343038',
  inputFocusBorder: '#b7d7cc',
  inputPlaceholder: '#918b94',
  inputShadowOpacity: 0.06,
  inputShadowY: 8,
  inputShadowBlur: 22,
  cardColorScheme: 'kangur-bloom-ivory',
  cardBg: '#fffdfb',
  cardBorderOpacity: 70,
  cardShadowOpacity: 0.12,
  collectionColorScheme: 'kangur-bloom-ivory',
  collectionOverlayColor: 'rgba(255, 255, 255, 0.72)',
  blogColorScheme: 'kangur-bloom-ivory',
  containerBg: '#fffefc',
  containerBorderColor: '#f7efe6',
  panelGradientStart: 'rgba(255, 255, 255, 0.99)',
  panelGradientEnd: 'rgba(249, 243, 236, 0.94)',
  panelTransparency: 0.96,
  navGradientStart: 'rgba(255, 255, 255, 0.96)',
  navGradientEnd: 'rgba(249, 244, 237, 0.9)',
  navTransparency: 0.94,
  containerShadowOpacity: 0.12,
  imageBorderColor: '#eee2d6',
  imagePlaceholderBg: '#f4ede4',
  dropdownBg: '#fff8f2',
  dropdownBorder: '#e6d9cc',
  dropdownShadowOpacity: 0.12,
  dropdownShadowY: 12,
  dropdownShadowBlur: 30,
  popupOverlayColor: 'rgba(47, 45, 40, 0.18)',
  popupRadius: 28,
  drawerWidth: 400,
  drawerBg: '#fff6ef',
  drawerOverlayColor: 'rgba(47, 45, 40, 0.18)',
  drawerPosition: 'right',
  drawerBorderColor: '#efe2d5',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 75,
  drawerRadius: 26,
  drawerShadowOpacity: 0.14,
  drawerShadowX: 0,
  drawerShadowY: 18,
  drawerShadowBlur: 48,
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#f1e8dd',
  badgeDefaultText: '#5a5560',
  badgeSaleColorScheme: 'kangur-bloom-rose',
  badgeSaleBg: '#ffd7c2',
  badgeSaleText: '#8a4b2b',
  badgeSoldOutColorScheme: 'kangur-bloom-ivory',
  badgeSoldOutBg: '#f3ede6',
  badgeSoldOutText: '#7b7680',
});
