import { normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';
import { KANGUR_DAILY_THEME } from './daily';

/** Kangur Nightly Aurora theme — deep neon night palette (2026-03-13). */
export const KANGUR_NIGHTLY_AURORA_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_DAILY_THEME,
  themePreset: 'kangur-nightly-aurora',
  darkMode: true,
  primaryColor: '#64f4ff',
  secondaryColor: '#7aa2ff',
  accentColor: '#b08bff',
  backgroundColor: '#0a0f1d',
  surfaceColor: '#121a2b',
  textColor: '#e9f2ff',
  mutedTextColor: '#a1afc9',
  borderColor: '#1d2740',
  errorColor: '#ff7b88',
  successColor: '#52e0b7',
  gradientIndigoStart: '#4f62db',
  gradientIndigoEnd: '#7aa2ff',
  gradientVioletStart: '#6b86ff',
  gradientVioletEnd: '#b08bff',
  gradientEmeraldStart: '#52e0b7',
  gradientEmeraldEnd: '#66ffd2',
  gradientSkyStart: '#3ea1da',
  gradientSkyEnd: '#64f4ff',
  gradientAmberStart: '#ffb86b',
  gradientAmberEnd: '#ffd27a',
  gradientRoseStart: '#f0a3ff',
  gradientRoseEnd: '#ff7bd5',
  gradientTealStart: '#2ed0c4',
  gradientTealEnd: '#64f4ff',
  gradientSlateStart: '#8b9bbd',
  gradientSlateEnd: '#3b4663',
  homeActionLessonsTextColor: '#dbe7ff',
  homeActionLessonsTextActiveColor: '#f8fafc',
  homeActionLessonsLabelStart: '#4f62db',
  homeActionLessonsLabelMid: '#7aa2ff',
  homeActionLessonsLabelEnd: '#b08bff',
  homeActionLessonsAccentStart: '#4f62db',
  homeActionLessonsAccentMid: '#7aa2ff',
  homeActionLessonsAccentEnd: '#b08bff',
  homeActionLessonsUnderlayStart: 'rgba(79, 98, 219, 0.42)',
  homeActionLessonsUnderlayMid: 'rgba(122, 162, 255, 0.34)',
  homeActionLessonsUnderlayEnd: 'rgba(176, 139, 255, 0.46)',
  homeActionLessonsUnderlayTintStart: 'rgba(79, 98, 219, 0.24)',
  homeActionLessonsUnderlayTintMid: 'rgba(122, 162, 255, 0.48)',
  homeActionLessonsUnderlayTintEnd: 'rgba(176, 139, 255, 0.66)',
  homeActionLessonsAccentShadowColor: '#7aa2ff',
  homeActionLessonsUnderlayShadowColor: '#b08bff',
  homeActionLessonsSurfaceShadowColor: '#4f62db',
  homeActionPlayTextColor: '#efe9ff',
  homeActionPlayTextActiveColor: '#f8fafc',
  homeActionPlayLabelStart: '#6b86ff',
  homeActionPlayLabelMid: '#b08bff',
  homeActionPlayLabelEnd: '#f0a3ff',
  homeActionPlayAccentStart: '#6b86ff',
  homeActionPlayAccentMid: '#b08bff',
  homeActionPlayAccentEnd: '#f0a3ff',
  homeActionPlayUnderlayStart: 'rgba(107, 134, 255, 0.42)',
  homeActionPlayUnderlayMid: 'rgba(176, 139, 255, 0.34)',
  homeActionPlayUnderlayEnd: 'rgba(240, 163, 255, 0.44)',
  homeActionPlayUnderlayTintStart: 'rgba(107, 134, 255, 0.24)',
  homeActionPlayUnderlayTintMid: 'rgba(176, 139, 255, 0.48)',
  homeActionPlayUnderlayTintEnd: 'rgba(240, 163, 255, 0.64)',
  homeActionPlayAccentShadowColor: '#b08bff',
  homeActionPlayUnderlayShadowColor: '#f0a3ff',
  homeActionPlaySurfaceShadowColor: '#6b86ff',
  homeActionTrainingTextColor: '#d8f2ff',
  homeActionTrainingTextActiveColor: '#f8fafc',
  homeActionTrainingLabelStart: '#3ea1da',
  homeActionTrainingLabelMid: '#64f4ff',
  homeActionTrainingLabelEnd: '#7fd5ff',
  homeActionTrainingAccentStart: '#3ea1da',
  homeActionTrainingAccentMid: '#64f4ff',
  homeActionTrainingAccentEnd: '#7fd5ff',
  homeActionTrainingUnderlayStart: 'rgba(62, 161, 218, 0.42)',
  homeActionTrainingUnderlayMid: 'rgba(100, 244, 255, 0.34)',
  homeActionTrainingUnderlayEnd: 'rgba(127, 213, 255, 0.44)',
  homeActionTrainingUnderlayTintStart: 'rgba(62, 161, 218, 0.24)',
  homeActionTrainingUnderlayTintMid: 'rgba(100, 244, 255, 0.44)',
  homeActionTrainingUnderlayTintEnd: 'rgba(127, 213, 255, 0.62)',
  homeActionTrainingAccentShadowColor: '#64f4ff',
  homeActionTrainingUnderlayShadowColor: '#3ea1da',
  homeActionTrainingSurfaceShadowColor: '#3ea1da',
  homeActionKangurTextColor: '#d9fff2',
  homeActionKangurTextActiveColor: '#f8fafc',
  homeActionKangurLabelStart: '#52e0b7',
  homeActionKangurLabelMid: '#64f4ff',
  homeActionKangurLabelEnd: '#7aa2ff',
  homeActionKangurAccentStart: '#52e0b7',
  homeActionKangurAccentMid: '#64f4ff',
  homeActionKangurAccentEnd: '#7aa2ff',
  homeActionKangurUnderlayStart: 'rgba(82, 224, 183, 0.42)',
  homeActionKangurUnderlayMid: 'rgba(100, 244, 255, 0.34)',
  homeActionKangurUnderlayEnd: 'rgba(122, 162, 255, 0.44)',
  homeActionKangurUnderlayTintStart: 'rgba(82, 224, 183, 0.24)',
  homeActionKangurUnderlayTintMid: 'rgba(100, 244, 255, 0.44)',
  homeActionKangurUnderlayTintEnd: 'rgba(122, 162, 255, 0.64)',
  homeActionKangurAccentShadowColor: '#64f4ff',
  homeActionKangurUnderlayShadowColor: '#52e0b7',
  homeActionKangurSurfaceShadowColor: '#52e0b7',
  colorSchemes: [
    {
      id: 'kangur-aurora-teal',
      name: 'Aurora Teal',
      colors: {
        background: '#0a0f1d',
        surface: '#121a2b',
        text: '#e9f2ff',
        accent: '#64f4ff',
        border: '#1b2640',
      },
    },
    {
      id: 'kangur-aurora-violet',
      name: 'Aurora Violet',
      colors: {
        background: '#120f25',
        surface: '#1a1732',
        text: '#e9f2ff',
        accent: '#b08bff',
        border: '#2a2346',
      },
    },
    {
      id: 'kangur-aurora-blue',
      name: 'Aurora Blue',
      colors: {
        background: '#0b1326',
        surface: '#131f35',
        text: '#e9f2ff',
        accent: '#7aa2ff',
        border: '#1d2a48',
      },
    },
    {
      id: 'kangur-aurora-emerald',
      name: 'Aurora Mint',
      colors: {
        background: '#0c141c',
        surface: '#111d28',
        text: '#e9f2ff',
        accent: '#52e0b7',
        border: '#1b2b39',
      },
    },
  ],
  activeColorSchemeId: 'kangur-aurora-teal',
  headingFont: "'Space Grotesk', sans-serif",
  bodyFont: 'Manrope, sans-serif',
  headingSizeScale: 1.08,
  lineHeight: 1.62,
  headingLineHeight: 1.18,
  borderRadius: 26,
  hoverScale: 1.015,
  btnRadius: 18,
  btnPrimaryBg: 'linear-gradient(135deg, #64f4ff 0%, #7aa2ff 56%, #b08bff 100%)',
  btnPrimaryText: '#0a0f1d',
  btnSecondaryBg: 'rgba(12, 18, 35, 0.9)',
  btnSecondaryText: '#e9f2ff',
  btnOutlineBorder: '#263150',
  btnBorderOpacity: 70,
  btnBorderRadius: 18,
  btnShadowOpacity: 0.22,
  btnShadowY: 12,
  btnShadowBlur: 34,
  btnGlossOpacity: 0.34,
  btnGlossHeight: 48,
  btnInsetHighlightOpacity: 0.18,
  pillBg: 'rgba(18, 26, 46, 0.82)',
  pillText: '#c2d0eb',
  pillActiveBg: 'rgba(24, 50, 72, 0.9)',
  pillActiveText: '#64f4ff',
  pillBorderColor: '#263151',
  pillBorderOpacity: 60,
  pillShadowOpacity: 0.12,
  inputBorderColor: '#2a3552',
  inputBg: '#0f172c',
  inputText: '#e9f2ff',
  inputFocusBorder: '#64f4ff',
  inputPlaceholder: '#7f8fb3',
  inputShadowOpacity: 0.1,
  inputShadowY: 12,
  inputShadowBlur: 30,
  cardColorScheme: 'kangur-aurora-blue',
  cardBg: '#111a2e',
  cardBorderOpacity: 65,
  cardShadowOpacity: 0.2,
  cardShadowY: 20,
  cardShadowBlur: 42,
  collectionColorScheme: 'kangur-aurora-blue',
  collectionOverlayColor: 'rgba(6, 12, 26, 0.6)',
  blogColorScheme: 'kangur-aurora-blue',
  containerBg: '#0f172b',
  containerBorderColor: '#1f2a45',
  panelGradientStart: '#16223b',
  panelGradientEnd: '#0c1326',
  panelTransparency: 0.92,
  navGradientStart: '#131c33',
  navGradientEnd: '#0a1124',
  navTransparency: 0.9,
  containerShadowOpacity: 0.22,
  imageBorderColor: '#1f2a46',
  imagePlaceholderBg: '#0c1326',
  dropdownBg: '#131c33',
  dropdownBorder: '#283554',
  dropdownShadowOpacity: 0.24,
  dropdownShadowY: 16,
  dropdownShadowBlur: 38,
  popupOverlayColor: 'rgba(5, 8, 18, 0.55)',
  drawerBg: '#0f172b',
  drawerOverlayColor: 'rgba(5, 8, 18, 0.6)',
  drawerBorderColor: '#1f2a45',
  drawerShadowOpacity: 0.24,
  badgeDefaultBg: '#1a2541',
  badgeDefaultText: '#cbd6ef',
  badgeSaleColorScheme: 'kangur-aurora-violet',
  badgeSaleBg: '#f0a3ff',
  badgeSaleText: '#2a1430',
  badgeSoldOutColorScheme: 'kangur-aurora-blue',
  badgeSoldOutBg: '#132036',
  badgeSoldOutText: '#7f8fb3',
});

export const KANGUR_NIGHTLY_THEME: ThemeSettings = KANGUR_NIGHTLY_AURORA_THEME;
