import { normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';
import { KANGUR_NIGHTLY_AURORA_THEME } from './nightly';

/** Kangur Nightly Nocturne theme — darker Aurora variant with complementary colored borders. */
export const KANGUR_NIGHTLY_NOCTURNE_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_NIGHTLY_AURORA_THEME,
  themePreset: 'kangur-nightly-nocturne',
  primaryColor: '#9a8fff',
  secondaryColor: '#c3acff',
  accentColor: '#89d4ff',
  backgroundColor: '#080b16',
  surfaceColor: '#12182b',
  textColor: '#eef2ff',
  mutedTextColor: '#aab4d3',
  borderColor: '#3a2d61',
  gradientIndigoStart: '#736fff',
  gradientIndigoEnd: '#b5a8ff',
  gradientVioletStart: '#8d79ff',
  gradientVioletEnd: '#d896ff',
  gradientEmeraldStart: '#56cfb1',
  gradientEmeraldEnd: '#8be8d4',
  gradientSkyStart: '#60b6ff',
  gradientSkyEnd: '#95dcff',
  gradientAmberStart: '#ffbe74',
  gradientAmberEnd: '#ff927e',
  gradientRoseStart: '#c894ff',
  gradientRoseEnd: '#ff9ec7',
  gradientTealStart: '#56c1dd',
  gradientTealEnd: '#8be2ff',
  gradientSlateStart: '#abb4d4',
  gradientSlateEnd: '#505973',
  colorSchemes: [
    {
      id: 'kangur-nocturne-indigo',
      name: 'Nocturne Indigo',
      colors: {
        background: '#080b16',
        surface: '#12182b',
        text: '#eef2ff',
        accent: '#9a8fff',
        border: '#4a3775',
      },
    },
    {
      id: 'kangur-nocturne-lilac',
      name: 'Nocturne Lilac',
      colors: {
        background: '#110d1f',
        surface: '#171128',
        text: '#f3eeff',
        accent: '#d298ff',
        border: '#643359',
      },
    },
    {
      id: 'kangur-nocturne-sky',
      name: 'Nocturne Sky',
      colors: {
        background: '#07101a',
        surface: '#101c2c',
        text: '#ebf6ff',
        accent: '#8fd6ff',
        border: '#2c5c7c',
      },
    },
    {
      id: 'kangur-nocturne-meadow',
      name: 'Nocturne Meadow',
      colors: {
        background: '#07140f',
        surface: '#11211c',
        text: '#ebfaf4',
        accent: '#6fdcc1',
        border: '#2b6058',
      },
    },
  ],
  activeColorSchemeId: 'kangur-nocturne-indigo',
  btnPrimaryBg: 'linear-gradient(135deg, #857dff 0%, #c29cff 58%, #ff9f82 100%)',
  btnPrimaryText: '#111523',
  btnSecondaryBg: 'rgba(17, 23, 41, 0.94)',
  btnOutlineBorder: '#3a4a70',
  pillBg: 'rgba(18, 24, 42, 0.88)',
  pillText: '#c6cfeb',
  pillActiveBg: 'rgba(83, 66, 138, 0.34)',
  pillActiveText: '#f2efff',
  pillBorderColor: '#334866',
  inputBorderColor: '#384567',
  inputBg: '#13192d',
  inputText: '#edf2ff',
  inputFocusBorder: '#b6a8ff',
  inputPlaceholder: '#7886aa',
  cardColorScheme: 'kangur-nocturne-indigo',
  cardBg: '#141a2f',
  collectionColorScheme: 'kangur-nocturne-sky',
  collectionOverlayColor: 'rgba(4, 7, 18, 0.66)',
  blogColorScheme: 'kangur-nocturne-indigo',
  containerBg: '#141a2f',
  containerBorderColor: '#443264',
  panelGradientStart: '#1a2140',
  panelGradientEnd: '#0c1020',
  panelTransparency: 0.95,
  navGradientStart: '#151b36',
  navGradientEnd: '#0b0f1e',
  navTransparency: 0.94,
  containerShadowOpacity: 0.28,
  imageBorderColor: '#2d5474',
  imagePlaceholderBg: '#0d1121',
  dropdownBg: '#141a30',
  dropdownBorder: '#335a79',
  dropdownShadowOpacity: 0.28,
  dropdownShadowBlur: 42,
  popupOverlayColor: 'rgba(4, 6, 16, 0.68)',
  drawerBg: '#12182c',
  drawerOverlayColor: 'rgba(4, 6, 16, 0.72)',
  drawerBorderColor: '#2f5a74',
  badgeDefaultBg: '#232b4c',
  badgeDefaultText: '#d6ddf5',
  badgeSaleColorScheme: 'kangur-nocturne-lilac',
  badgeSaleBg: '#ffbf9f',
  badgeSaleText: '#3d2234',
  badgeSoldOutColorScheme: 'kangur-nocturne-sky',
  badgeSoldOutBg: '#18233d',
  badgeSoldOutText: '#97a7c7',
});
