import { DEFAULT_THEME, normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';

export const KANGUR_NIGHTLY_CRYSTAL_THEME: ThemeSettings = normalizeThemeSettings({
  ...DEFAULT_THEME,
  themePreset: 'kangur-nightly-crystal',
  darkMode: true,

  // ── Core Palette (deep sapphire night) ────────────────────
  primaryColor: '#60a5fa',
  secondaryColor: '#a78bfa',
  accentColor: '#fbbf24',
  backgroundColor: '#080c18',
  surfaceColor: '#0e1529',
  textColor: '#e8efff',
  mutedTextColor: '#8b9ec4',
  pageTextColor: '#e8efff',
  pageMutedTextColor: '#8b9ec4',
  cardTextColor: '#e0eaff',
  navTextColor: '#94a8d0',
  navActiveTextColor: '#60a5fa',
  navHoverTextColor: '#93c5fd',
  borderColor: '#1a2544',
  errorColor: '#fb7185',
  successColor: '#34d399',

  // ── Accent Gradients (luminous on dark) ───────────────────
  gradientIndigoStart: '#3b82f6',
  gradientIndigoEnd: '#6366f1',
  gradientVioletStart: '#8b5cf6',
  gradientVioletEnd: '#c084fc',
  gradientEmeraldStart: '#34d399',
  gradientEmeraldEnd: '#6ee7b7',
  gradientSkyStart: '#38bdf8',
  gradientSkyEnd: '#67e8f9',
  gradientAmberStart: '#fbbf24',
  gradientAmberEnd: '#fde68a',
  gradientRoseStart: '#fb7185',
  gradientRoseEnd: '#fda4af',
  gradientTealStart: '#2dd4bf',
  gradientTealEnd: '#5eead4',
  gradientSlateStart: '#94a3b8',
  gradientSlateEnd: '#475569',

  // ── Logo (Crystal branding → luminous night) ──────────────
  logoWordStart: '#60a5fa',
  logoWordMid: '#818cf8',
  logoWordEnd: '#a78bfa',
  logoRingStart: '#3b82f6',
  logoRingEnd: '#8b5cf6',
  logoAccentStart: '#fbbf24',
  logoAccentEnd: '#f97316',
  logoInnerStart: '#e0eaff',
  logoInnerEnd: '#1e3a5f',
  logoShadow: '#0c1a3a',
  logoGlint: '#fef9c3',

  // ── Home Actions — Lessons (sapphire-to-indigo glow) ──────
  homeActionLessonsTextColor: '#c7dbff',
  homeActionLessonsTextActiveColor: '#f8fafc',
  homeActionLessonsLabelStart: '#3b82f6',
  homeActionLessonsLabelMid: '#60a5fa',
  homeActionLessonsLabelEnd: '#6366f1',
  homeActionLessonsAccentStart: '#3b82f6',
  homeActionLessonsAccentMid: '#60a5fa',
  homeActionLessonsAccentEnd: '#6366f1',
  homeActionLessonsUnderlayStart: 'rgba(59, 130, 246, 0.38)',
  homeActionLessonsUnderlayMid: 'rgba(96, 165, 250, 0.28)',
  homeActionLessonsUnderlayEnd: 'rgba(99, 102, 241, 0.40)',
  homeActionLessonsUnderlayTintStart: 'rgba(59, 130, 246, 0.26)',
  homeActionLessonsUnderlayTintMid: 'rgba(96, 165, 250, 0.50)',
  homeActionLessonsUnderlayTintEnd: 'rgba(99, 102, 241, 0.70)',
  homeActionLessonsAccentShadowColor: '#60a5fa',
  homeActionLessonsUnderlayShadowColor: '#6366f1',
  homeActionLessonsSurfaceShadowColor: '#3b82f6',

  // ── Home Actions — Play (violet-to-purple glow) ───────────
  homeActionPlayTextColor: '#ddd6fe',
  homeActionPlayTextActiveColor: '#f8fafc',
  homeActionPlayLabelStart: '#8b5cf6',
  homeActionPlayLabelMid: '#a78bfa',
  homeActionPlayLabelEnd: '#c084fc',
  homeActionPlayAccentStart: '#8b5cf6',
  homeActionPlayAccentMid: '#a78bfa',
  homeActionPlayAccentEnd: '#c084fc',
  homeActionPlayUnderlayStart: 'rgba(139, 92, 246, 0.38)',
  homeActionPlayUnderlayMid: 'rgba(167, 139, 250, 0.28)',
  homeActionPlayUnderlayEnd: 'rgba(192, 132, 252, 0.40)',
  homeActionPlayUnderlayTintStart: 'rgba(139, 92, 246, 0.26)',
  homeActionPlayUnderlayTintMid: 'rgba(167, 139, 250, 0.50)',
  homeActionPlayUnderlayTintEnd: 'rgba(192, 132, 252, 0.70)',
  homeActionPlayAccentShadowColor: '#a78bfa',
  homeActionPlayUnderlayShadowColor: '#c084fc',
  homeActionPlaySurfaceShadowColor: '#8b5cf6',

  // ── Home Actions — Training (cyan-to-sky glow) ────────────
  homeActionTrainingTextColor: '#bae6fd',
  homeActionTrainingTextActiveColor: '#f8fafc',
  homeActionTrainingLabelStart: '#22d3ee',
  homeActionTrainingLabelMid: '#38bdf8',
  homeActionTrainingLabelEnd: '#67e8f9',
  homeActionTrainingAccentStart: '#22d3ee',
  homeActionTrainingAccentMid: '#38bdf8',
  homeActionTrainingAccentEnd: '#67e8f9',
  homeActionTrainingUnderlayStart: 'rgba(34, 211, 238, 0.38)',
  homeActionTrainingUnderlayMid: 'rgba(56, 189, 248, 0.28)',
  homeActionTrainingUnderlayEnd: 'rgba(103, 232, 249, 0.38)',
  homeActionTrainingUnderlayTintStart: 'rgba(34, 211, 238, 0.26)',
  homeActionTrainingUnderlayTintMid: 'rgba(56, 189, 248, 0.48)',
  homeActionTrainingUnderlayTintEnd: 'rgba(103, 232, 249, 0.66)',
  homeActionTrainingAccentShadowColor: '#38bdf8',
  homeActionTrainingUnderlayShadowColor: '#22d3ee',
  homeActionTrainingSurfaceShadowColor: '#0ea5e9',

  // ── Home Actions — Kangur (amber-to-gold glow) ────────────
  homeActionKangurTextColor: '#fef3c7',
  homeActionKangurTextActiveColor: '#f8fafc',
  homeActionKangurLabelStart: '#fbbf24',
  homeActionKangurLabelMid: '#f59e0b',
  homeActionKangurLabelEnd: '#fde68a',
  homeActionKangurAccentStart: '#fbbf24',
  homeActionKangurAccentMid: '#f59e0b',
  homeActionKangurAccentEnd: '#fde68a',
  homeActionKangurUnderlayStart: 'rgba(251, 191, 36, 0.38)',
  homeActionKangurUnderlayMid: 'rgba(245, 158, 11, 0.28)',
  homeActionKangurUnderlayEnd: 'rgba(253, 230, 138, 0.36)',
  homeActionKangurUnderlayTintStart: 'rgba(251, 191, 36, 0.26)',
  homeActionKangurUnderlayTintMid: 'rgba(245, 158, 11, 0.46)',
  homeActionKangurUnderlayTintEnd: 'rgba(253, 230, 138, 0.62)',
  homeActionKangurAccentShadowColor: '#f59e0b',
  homeActionKangurUnderlayShadowColor: '#fbbf24',
  homeActionKangurSurfaceShadowColor: '#d97706',

  // ── Color Schemes ─────────────────────────────────────────
  colorSchemes: [
    {
      id: 'kangur-ncrystal-sapphire',
      name: 'Night Sapphire',
      colors: {
        background: '#080c18',
        surface: '#0e1529',
        text: '#e8efff',
        accent: '#60a5fa',
        border: '#1a2544',
      },
    },
    {
      id: 'kangur-ncrystal-amethyst',
      name: 'Night Amethyst',
      colors: {
        background: '#0d0a1e',
        surface: '#15112f',
        text: '#ede8ff',
        accent: '#a78bfa',
        border: '#231e48',
      },
    },
    {
      id: 'kangur-ncrystal-cyan',
      name: 'Night Cyan',
      colors: {
        background: '#061218',
        surface: '#0c1c28',
        text: '#e0f7ff',
        accent: '#22d3ee',
        border: '#152e3e',
      },
    },
    {
      id: 'kangur-ncrystal-gold',
      name: 'Night Gold',
      colors: {
        background: '#100d06',
        surface: '#1a1610',
        text: '#fff8e1',
        accent: '#fbbf24',
        border: '#2e2614',
      },
    },
  ],
  activeColorSchemeId: 'kangur-ncrystal-sapphire',

  // ── Typography ────────────────────────────────────────────
  headingFont: '\'Space Grotesk\', sans-serif',
  bodyFont: '\'DM Sans\', sans-serif',
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1.08,
  bodySizeScale: 1,
  lineHeight: 1.62,
  headingLineHeight: 1.16,

  // ── Layout ────────────────────────────────────────────────
  maxContentWidth: 1240,
  gridGutter: 28,
  sectionSpacing: 72,
  containerPadding: 28,
  borderRadius: 24,
  pagePaddingTop: 36,
  pagePaddingRight: 32,
  pagePaddingBottom: 84,
  pagePaddingLeft: 32,
  pagePadding: 32,
  pageMargin: 0,
  fullWidth: false,

  // ── Animations ────────────────────────────────────────────
  enableAnimations: true,
  animationDuration: 280,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.02,

  // ── Buttons (high-gloss gel on dark) ──────────────────────
  btnPaddingX: 26,
  btnPaddingY: 13,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 999,
  btnPrimaryBg: 'linear-gradient(180deg, #93c5fd 0%, #60a5fa 40%, #3b82f6 100%)',
  btnPrimaryText: '#0a1628',
  btnSecondaryBg: 'linear-gradient(180deg, rgba(20, 30, 56, 0.95) 0%, rgba(14, 21, 41, 0.95) 100%)',
  btnSecondaryText: '#c7dbff',
  btnOutlineBorder: '#253a60',
  btnBorderWidth: 1,
  btnBorderOpacity: 50,
  btnBorderRadius: 999,
  btnShadowOpacity: 0.35,
  btnShadowX: 0,
  btnShadowY: 10,
  btnShadowBlur: 30,

  // ── Button Gel Effects (high-gloss showcase) ──────────────
  btnGlossOpacity: 0.55,
  btnGlossHeight: 50,
  btnGlossAngle: 178,
  btnGlossColor: '#bfdbfe',
  btnInsetHighlightOpacity: 0.55,
  btnInsetShadowOpacity: 0.45,
  btnInsetShadowBlur: 6,
  btnInsetShadowY: 3,
  btnTextShadowOpacity: 0.50,
  btnTextShadowY: 1,
  btnTextShadowBlur: 0,
  btnGlowOpacity: 0.35,
  btnGlowSpread: 14,
  btnGlowColor: '#60a5fa',

  // ── Variant Pills ─────────────────────────────────────────
  pillRadius: 999,
  pillPaddingX: 14,
  pillPaddingY: 6,
  pillFontSize: 12,
  pillBg: 'rgba(14, 21, 41, 0.85)',
  pillText: '#94a8d0',
  pillActiveBg: 'rgba(30, 64, 175, 0.4)',
  pillActiveText: '#93c5fd',
  pillBorderColor: '#1e3050',
  pillBorderWidth: 1,
  pillBorderOpacity: 55,
  pillShadowOpacity: 0.16,
  pillShadowX: 0,
  pillShadowY: 8,
  pillShadowBlur: 24,

  // ── Inputs ────────────────────────────────────────────────
  inputHeight: 50,
  inputRadius: 22,
  inputBorderColor: '#1e3050',
  inputBorderWidth: 1,
  inputBorderOpacity: 75,
  inputBg: '#0b1222',
  inputText: '#e8efff',
  inputFocusBorder: '#60a5fa',
  inputPlaceholder: '#6b82a8',
  inputFontSize: 14,
  inputShadowOpacity: 0.12,
  inputShadowX: 0,
  inputShadowY: 10,
  inputShadowBlur: 28,

  // ── Product Cards ─────────────────────────────────────────
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardTextAlignment: 'left',
  cardColorScheme: 'kangur-ncrystal-sapphire',
  cardRadius: 22,
  cardShadow: 'large',
  cardBg: '#0e1529',
  cardHoverShadow: 'large',
  showBadge: true,
  showQuickAdd: false,
  cardBorderWidth: 1,
  cardBorderOpacity: 55,
  cardBorderRadius: 22,
  cardShadowOpacity: 0.24,
  cardShadowX: 0,
  cardShadowY: 18,
  cardShadowBlur: 42,

  // ── Collections ───────────────────────────────────────────
  collectionRatio: '16:9',
  collectionRadius: 22,
  collectionStyle: 'overlay',
  collectionImagePadding: 8,
  collectionOverlay: true,
  collectionOverlayColor: 'rgba(8, 12, 24, 0.65)',
  collectionTextAlign: 'left',
  collectionColorScheme: 'kangur-ncrystal-sapphire',
  collectionBorderWidth: 1,
  collectionBorderOpacity: 55,
  collectionShadowOpacity: 0.24,
  collectionShadowX: 0,
  collectionShadowY: 18,
  collectionShadowBlur: 42,

  // ── Blog ──────────────────────────────────────────────────
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 8,
  blogTextAlignment: 'left',
  blogColorScheme: 'kangur-ncrystal-sapphire',
  blogRadius: 22,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 3,
  blogBorderWidth: 1,
  blogBorderOpacity: 55,
  blogBorderRadius: 22,
  blogShadowOpacity: 0.24,
  blogShadowX: 0,
  blogShadowY: 18,
  blogShadowBlur: 42,

  // ── Content Containers ────────────────────────────────────
  containerBg: '#0b1222',
  containerBorderColor: '#182640',
  containerRadius: 26,
  containerPaddingInner: 24,
  containerShadow: 'large',
  containerBorderWidth: 1,
  containerBorderOpacity: 60,
  containerBorderRadius: 26,
  containerShadowOpacity: 0.28,
  containerShadowX: 0,
  containerShadowY: 20,
  containerShadowBlur: 50,

  // ── Panel & Nav Gradients ─────────────────────────────────
  panelGradientStart: '#131d36',
  panelGradientEnd: '#080c18',
  panelTransparency: 0.93,
  navGradientStart: '#101a30',
  navGradientEnd: '#070b16',
  navTransparency: 0.92,

  // ── Media ─────────────────────────────────────────────────
  imageRadius: 16,
  imageBorderColor: '#1a2544',
  imageBorderWidth: 1,
  imageBorderOpacity: 50,
  imageShadowOpacity: 0.14,
  imageShadowX: 0,
  imageShadowY: 12,
  imageShadowBlur: 30,
  imagePlaceholderBg: '#0a1020',

  // ── Dropdowns ─────────────────────────────────────────────
  dropdownBg: '#0e1529',
  dropdownBorder: '#1e3050',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 65,
  dropdownRadius: 18,
  dropdownShadow: 'large',
  dropdownShadowOpacity: 0.30,
  dropdownShadowX: 0,
  dropdownShadowY: 16,
  dropdownShadowBlur: 42,
  popupOverlayColor: 'rgba(4, 6, 14, 0.65)',
  popupRadius: 24,

  // ── Drawers ───────────────────────────────────────────────
  drawerWidth: 400,
  drawerBg: '#0b1222',
  drawerOverlayColor: 'rgba(4, 6, 14, 0.70)',
  drawerPosition: 'right',
  drawerBorderColor: '#182640',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 60,
  drawerRadius: 24,
  drawerShadowOpacity: 0.28,
  drawerShadowX: 0,
  drawerShadowY: 18,
  drawerShadowBlur: 48,

  // ── Badges ────────────────────────────────────────────────
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#152244',
  badgeDefaultText: '#93c5fd',
  badgeSaleColorScheme: 'kangur-ncrystal-gold',
  badgeSaleBg: '#fef3c7',
  badgeSaleText: '#78350f',
  badgeSoldOutColorScheme: 'kangur-ncrystal-sapphire',
  badgeSoldOutBg: '#0e1832',
  badgeSoldOutText: '#6b82a8',
});
