import { DEFAULT_THEME, normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';
import { KANGUR_DAILY_THEME } from './daily';

export const KANGUR_LOGO_GLOW_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_DAILY_THEME,
  themePreset: 'kangur-logo-glow',
  primaryColor: '#4457d7',
  secondaryColor: '#8a5dff',
  accentColor: '#ffb35c',
  backgroundColor: '#f4f6ff',
  surfaceColor: '#ffffff',
  textColor: '#2a2f45',
  mutedTextColor: '#667089',
  borderColor: '#e1e6f4',
  errorColor: '#f06b7a',
  successColor: '#33bfa5',
  gradientIndigoStart: '#4457d7',
  gradientIndigoEnd: '#7c52ff',
  gradientVioletStart: '#4f63f8',
  gradientVioletEnd: '#8a5dff',
  gradientEmeraldStart: '#22cba0',
  gradientEmeraldEnd: '#62e7c9',
  gradientSkyStart: '#5aa9ff',
  gradientSkyEnd: '#8fd6ff',
  gradientAmberStart: '#ffd560',
  gradientAmberEnd: '#ff9a35',
  gradientRoseStart: '#fb7185',
  gradientRoseEnd: '#f9a8d4',
  gradientTealStart: '#2dd4bf',
  gradientTealEnd: '#5eead4',
  gradientSlateStart: '#9aa6c3',
  gradientSlateEnd: '#5a6480',
  logoWordStart: '#4457d7',
  logoWordMid: '#5566f2',
  logoWordEnd: '#7c52ff',
  logoRingStart: '#4f63f8',
  logoRingEnd: '#8a5dff',
  logoAccentStart: '#ffd560',
  logoAccentEnd: '#ff9a35',
  logoInnerStart: '#ffffff',
  logoInnerEnd: '#e6eeff',
  logoShadow: '#b4b7da',
  logoGlint: '#fff6c6',
  homeActionLessonsTextColor: '#2c3566',
  homeActionLessonsTextActiveColor: '#ffffff',
  homeActionLessonsLabelStart: '#4457d7',
  homeActionLessonsLabelMid: '#5566f2',
  homeActionLessonsLabelEnd: '#7c52ff',
  homeActionLessonsAccentStart: '#4457d7',
  homeActionLessonsAccentMid: '#5566f2',
  homeActionLessonsAccentEnd: '#7c52ff',
  homeActionLessonsUnderlayStart: 'rgba(203, 210, 255, 0.46)',
  homeActionLessonsUnderlayMid: 'rgba(195, 202, 255, 0.36)',
  homeActionLessonsUnderlayEnd: 'rgba(214, 205, 255, 0.48)',
  homeActionLessonsUnderlayTintStart: 'rgba(86, 94, 215, 0.22)',
  homeActionLessonsUnderlayTintMid: 'rgba(101, 105, 230, 0.48)',
  homeActionLessonsUnderlayTintEnd: 'rgba(154, 110, 255, 0.74)',
  homeActionLessonsAccentShadowColor: '#5566f2',
  homeActionLessonsUnderlayShadowColor: '#7c52ff',
  homeActionLessonsSurfaceShadowColor: '#5f6ad6',
  homeActionPlayTextColor: '#2f325f',
  homeActionPlayTextActiveColor: '#ffffff',
  homeActionPlayLabelStart: '#4f63f8',
  homeActionPlayLabelMid: '#6c6bff',
  homeActionPlayLabelEnd: '#8a5dff',
  homeActionPlayAccentStart: '#4f63f8',
  homeActionPlayAccentMid: '#6c6bff',
  homeActionPlayAccentEnd: '#8a5dff',
  homeActionPlayUnderlayStart: 'rgba(203, 210, 255, 0.44)',
  homeActionPlayUnderlayMid: 'rgba(197, 204, 255, 0.34)',
  homeActionPlayUnderlayEnd: 'rgba(214, 204, 255, 0.46)',
  homeActionPlayUnderlayTintStart: 'rgba(95, 101, 218, 0.22)',
  homeActionPlayUnderlayTintMid: 'rgba(113, 106, 232, 0.48)',
  homeActionPlayUnderlayTintEnd: 'rgba(168, 117, 255, 0.72)',
  homeActionPlayAccentShadowColor: '#6c6bff',
  homeActionPlayUnderlayShadowColor: '#8a5dff',
  homeActionPlaySurfaceShadowColor: '#6d6fd6',
  homeActionTrainingTextColor: '#1f4d7a',
  homeActionTrainingTextActiveColor: '#ffffff',
  homeActionTrainingLabelStart: '#5aa9ff',
  homeActionTrainingLabelMid: '#7bc3ff',
  homeActionTrainingLabelEnd: '#8fd6ff',
  homeActionTrainingAccentStart: '#5aa9ff',
  homeActionTrainingAccentMid: '#7bc3ff',
  homeActionTrainingAccentEnd: '#8fd6ff',
  homeActionTrainingUnderlayStart: 'rgba(192, 226, 255, 0.44)',
  homeActionTrainingUnderlayMid: 'rgba(190, 219, 255, 0.34)',
  homeActionTrainingUnderlayEnd: 'rgba(206, 214, 255, 0.46)',
  homeActionTrainingUnderlayTintStart: 'rgba(77, 147, 219, 0.22)',
  homeActionTrainingUnderlayTintMid: 'rgba(93, 175, 236, 0.46)',
  homeActionTrainingUnderlayTintEnd: 'rgba(122, 206, 255, 0.68)',
  homeActionKangurTextColor: '#7a4b20',
  homeActionKangurTextActiveColor: '#ffffff',
  homeActionKangurLabelStart: '#ffd560',
  homeActionKangurLabelMid: '#ffb35c',
  homeActionKangurLabelEnd: '#ff9a35',
  homeActionKangurAccentStart: '#ffd560',
  homeActionKangurAccentMid: '#ffb35c',
  homeActionKangurAccentEnd: '#ff9a35',
  homeActionKangurUnderlayStart: 'rgba(255, 226, 190, 0.46)',
  homeActionKangurUnderlayMid: 'rgba(255, 214, 186, 0.36)',
  homeActionKangurUnderlayEnd: 'rgba(255, 206, 170, 0.48)',
  homeActionKangurUnderlayTintStart: 'rgba(233, 140, 76, 0.22)',
  homeActionKangurUnderlayTintMid: 'rgba(244, 162, 88, 0.44)',
  homeActionKangurUnderlayTintEnd: 'rgba(235, 146, 78, 0.64)',
  homeActionKangurAccentShadowColor: '#ffb35c',
  homeActionKangurUnderlayShadowColor: '#ff9a35',
  homeActionKangurSurfaceShadowColor: '#d98b5a',
  colorSchemes: [
    {
      id: 'kangur-logo-indigo',
      name: 'Logo Indigo',
      colors: {
        background: '#f4f6ff',
        surface: '#ffffff',
        text: '#2a2f45',
        accent: '#4457d7',
        border: '#e1e6f4',
      },
    },
    {
      id: 'kangur-logo-violet',
      name: 'Logo Violet',
      colors: {
        background: '#f6f1ff',
        surface: '#ffffff',
        text: '#2a2f45',
        accent: '#8a5dff',
        border: '#e7ddfb',
      },
    },
    {
      id: 'kangur-logo-amber',
      name: 'Logo Amber',
      colors: {
        background: '#fff6ed',
        surface: '#ffffff',
        text: '#2a2f45',
        accent: '#ffb35c',
        border: '#f2e1d2',
      },
    },
    {
      id: 'kangur-logo-sky',
      name: 'Logo Sky',
      colors: {
        background: '#eef6ff',
        surface: '#ffffff',
        text: '#2a2f45',
        accent: '#5aa9ff',
        border: '#d9e6f6',
      },
    },
  ],
  activeColorSchemeId: 'kangur-logo-indigo',
  headingFont: '\'Space Grotesk\', sans-serif',
  bodyFont: '\'DM Sans\', sans-serif',
  headingSizeScale: 1.06,
  lineHeight: 1.62,
  headingLineHeight: 1.18,
  borderRadius: 26,
  btnPrimaryBg: 'linear-gradient(135deg, #4457d7 0%, #8a5dff 52%, #ffb35c 100%)',
  btnPrimaryText: '#ffffff',
  btnSecondaryBg: 'rgba(255, 255, 255, 0.92)',
  btnSecondaryText: '#2f3451',
  btnOutlineBorder: '#d9dff2',
  btnBorderOpacity: 70,
  btnShadowOpacity: 0.14,
  btnShadowY: 10,
  btnShadowBlur: 28,
  pillBg: 'rgba(255, 255, 255, 0.78)',
  pillText: '#5b637e',
  pillActiveBg: '#e3e7ff',
  pillActiveText: '#4457d7',
  pillBorderColor: '#dfe4f3',
  pillBorderOpacity: 70,
  pillShadowOpacity: 0.1,
  inputBorderColor: '#dfe4f3',
  inputBg: '#ffffff',
  inputText: '#2f3451',
  inputFocusBorder: '#9aa6ff',
  inputPlaceholder: '#8a92ad',
  inputShadowOpacity: 0.08,
  inputShadowY: 10,
  inputShadowBlur: 26,
  cardColorScheme: 'kangur-logo-indigo',
  cardBg: '#ffffff',
  cardBorderOpacity: 70,
  cardShadowOpacity: 0.14,
  collectionColorScheme: 'kangur-logo-indigo',
  collectionOverlayColor: 'rgba(255, 255, 255, 0.72)',
  blogColorScheme: 'kangur-logo-indigo',
  containerBg: '#ffffff',
  containerBorderColor: '#edf0fb',
  panelGradientStart: 'rgba(255, 255, 255, 0.98)',
  panelGradientEnd: 'rgba(242, 244, 255, 0.92)',
  panelTransparency: 0.95,
  navGradientStart: 'rgba(255, 255, 255, 0.96)',
  navGradientEnd: 'rgba(238, 241, 255, 0.9)',
  navTransparency: 0.94,
  containerShadowOpacity: 0.14,
  imageBorderColor: '#e3e7f6',
  imagePlaceholderBg: '#f1f4ff',
  dropdownBg: '#ffffff',
  dropdownBorder: '#e1e6f4',
  dropdownShadowOpacity: 0.14,
  dropdownShadowY: 12,
  dropdownShadowBlur: 30,
  popupOverlayColor: 'rgba(42, 49, 88, 0.14)',
  drawerBg: '#f9faff',
  drawerOverlayColor: 'rgba(42, 49, 88, 0.16)',
  drawerBorderColor: '#e3e7f6',
  drawerShadowOpacity: 0.16,
  badgeDefaultBg: '#edf0ff',
  badgeDefaultText: '#4b5676',
  badgeSaleColorScheme: 'kangur-logo-amber',
  badgeSaleBg: '#ffd7b3',
  badgeSaleText: '#8a4b2b',
  badgeSoldOutColorScheme: 'kangur-logo-indigo',
  badgeSoldOutBg: '#f2f4ff',
  badgeSoldOutText: '#6c7390',
});

export const KANGUR_DAILY_CRYSTAL_THEME: ThemeSettings = normalizeThemeSettings({
  ...DEFAULT_THEME,
  themePreset: 'kangur-daily-crystal',
  darkMode: false,

  // ── Core Palette ──────────────────────────────────────────
  primaryColor: '#2563eb',
  secondaryColor: '#7c3aed',
  accentColor: '#f59e0b',
  backgroundColor: '#eef3fa',
  surfaceColor: '#f7f9ff',
  textColor: '#1e293b',
  mutedTextColor: '#64748b',
  pageTextColor: '#1e293b',
  pageMutedTextColor: '#64748b',
  cardTextColor: '#1e293b',
  navTextColor: '#475569',
  navActiveTextColor: '#2563eb',
  navHoverTextColor: '#1d4ed8',
  borderColor: '#dde4f0',
  errorColor: '#ef4444',
  successColor: '#10b981',

  // ── Accent Gradients (all 8) ──────────────────────────────
  gradientIndigoStart: '#2563eb',
  gradientIndigoEnd: '#4f46e5',
  gradientVioletStart: '#7c3aed',
  gradientVioletEnd: '#a855f7',
  gradientEmeraldStart: '#10b981',
  gradientEmeraldEnd: '#34d399',
  gradientSkyStart: '#0ea5e9',
  gradientSkyEnd: '#38bdf8',
  gradientAmberStart: '#f59e0b',
  gradientAmberEnd: '#fbbf24',
  gradientRoseStart: '#f43f5e',
  gradientRoseEnd: '#fb7185',
  gradientTealStart: '#14b8a6',
  gradientTealEnd: '#2dd4bf',
  gradientSlateStart: '#94a3b8',
  gradientSlateEnd: '#64748b',

  // ── Logo ──────────────────────────────────────────────────
  logoWordStart: '#2563eb',
  logoWordMid: '#4f46e5',
  logoWordEnd: '#7c3aed',
  logoRingStart: '#3b82f6',
  logoRingEnd: '#7c3aed',
  logoAccentStart: '#f59e0b',
  logoAccentEnd: '#f97316',
  logoInnerStart: '#ffffff',
  logoInnerEnd: '#e0e7ff',
  logoShadow: '#a8b5d6',
  logoGlint: '#fffbe6',

  // ── Home Actions — Lessons (sapphire-to-indigo) ───────────
  homeActionLessonsTextColor: '#1e3a6e',
  homeActionLessonsTextActiveColor: '#f8fafc',
  homeActionLessonsLabelStart: '#2563eb',
  homeActionLessonsLabelMid: '#3b82f6',
  homeActionLessonsLabelEnd: '#4f46e5',
  homeActionLessonsLabelStartActive: '#ffffff',
  homeActionLessonsLabelMidActive: '#eaf2ff',
  homeActionLessonsLabelEndActive: '#dbe7ff',
  homeActionLessonsAccentStart: '#2563eb',
  homeActionLessonsAccentMid: '#3b82f6',
  homeActionLessonsAccentEnd: '#4f46e5',
  homeActionLessonsUnderlayStart: 'rgba(37, 99, 235, 0.18)',
  homeActionLessonsUnderlayMid: 'rgba(59, 130, 246, 0.14)',
  homeActionLessonsUnderlayEnd: 'rgba(79, 70, 229, 0.20)',
  homeActionLessonsUnderlayTintStart: 'rgba(37, 99, 235, 0.24)',
  homeActionLessonsUnderlayTintMid: 'rgba(59, 130, 246, 0.46)',
  homeActionLessonsUnderlayTintEnd: 'rgba(79, 70, 229, 0.68)',
  homeActionLessonsAccentShadowColor: '#3b82f6',
  homeActionLessonsUnderlayShadowColor: '#4f46e5',
  homeActionLessonsSurfaceShadowColor: '#2563eb',

  // ── Home Actions — Play (violet-to-purple) ────────────────
  homeActionPlayTextColor: '#3b1f7a',
  homeActionPlayTextActiveColor: '#f5f3ff',
  homeActionPlayLabelStart: '#7c3aed',
  homeActionPlayLabelMid: '#8b5cf6',
  homeActionPlayLabelEnd: '#a855f7',
  homeActionPlayLabelStartActive: '#ffffff',
  homeActionPlayLabelMidActive: '#f3e8ff',
  homeActionPlayLabelEndActive: '#e9d5ff',
  homeActionPlayAccentStart: '#7c3aed',
  homeActionPlayAccentMid: '#8b5cf6',
  homeActionPlayAccentEnd: '#a855f7',
  homeActionPlayUnderlayStart: 'rgba(124, 58, 237, 0.18)',
  homeActionPlayUnderlayMid: 'rgba(139, 92, 246, 0.14)',
  homeActionPlayUnderlayEnd: 'rgba(168, 85, 247, 0.20)',
  homeActionPlayUnderlayTintStart: 'rgba(124, 58, 237, 0.24)',
  homeActionPlayUnderlayTintMid: 'rgba(139, 92, 246, 0.46)',
  homeActionPlayUnderlayTintEnd: 'rgba(168, 85, 247, 0.68)',
  homeActionPlayAccentShadowColor: '#8b5cf6',
  homeActionPlayUnderlayShadowColor: '#a855f7',
  homeActionPlaySurfaceShadowColor: '#7c3aed',

  // ── Home Actions — Training (sky-to-cyan) ─────────────────
  homeActionTrainingTextColor: '#0c4a6e',
  homeActionTrainingTextActiveColor: '#f0f9ff',
  homeActionTrainingLabelStart: '#0ea5e9',
  homeActionTrainingLabelMid: '#22d3ee',
  homeActionTrainingLabelEnd: '#38bdf8',
  homeActionTrainingLabelStartActive: '#ffffff',
  homeActionTrainingLabelMidActive: '#e0f2fe',
  homeActionTrainingLabelEndActive: '#bae6fd',
  homeActionTrainingAccentStart: '#0ea5e9',
  homeActionTrainingAccentMid: '#22d3ee',
  homeActionTrainingAccentEnd: '#38bdf8',
  homeActionTrainingUnderlayStart: 'rgba(14, 165, 233, 0.18)',
  homeActionTrainingUnderlayMid: 'rgba(34, 211, 238, 0.14)',
  homeActionTrainingUnderlayEnd: 'rgba(56, 189, 248, 0.20)',
  homeActionTrainingUnderlayTintStart: 'rgba(14, 165, 233, 0.24)',
  homeActionTrainingUnderlayTintMid: 'rgba(34, 211, 238, 0.44)',
  homeActionTrainingUnderlayTintEnd: 'rgba(56, 189, 248, 0.66)',
  homeActionTrainingAccentShadowColor: '#22d3ee',
  homeActionTrainingUnderlayShadowColor: '#0ea5e9',
  homeActionTrainingSurfaceShadowColor: '#0284c7',

  // ── Home Actions — Kangur (amber-to-orange) ───────────────
  homeActionKangurTextColor: '#78350f',
  homeActionKangurTextActiveColor: '#fff7ed',
  homeActionKangurLabelStart: '#f59e0b',
  homeActionKangurLabelMid: '#f97316',
  homeActionKangurLabelEnd: '#fb923c',
  homeActionKangurLabelStartActive: '#fff7ed',
  homeActionKangurLabelMidActive: '#ffedd5',
  homeActionKangurLabelEndActive: '#fed7aa',
  homeActionKangurAccentStart: '#f59e0b',
  homeActionKangurAccentMid: '#f97316',
  homeActionKangurAccentEnd: '#fb923c',
  homeActionKangurUnderlayStart: 'rgba(245, 158, 11, 0.20)',
  homeActionKangurUnderlayMid: 'rgba(249, 115, 22, 0.14)',
  homeActionKangurUnderlayEnd: 'rgba(251, 146, 60, 0.22)',
  homeActionKangurUnderlayTintStart: 'rgba(245, 158, 11, 0.24)',
  homeActionKangurUnderlayTintMid: 'rgba(249, 115, 22, 0.44)',
  homeActionKangurUnderlayTintEnd: 'rgba(251, 146, 60, 0.64)',
  homeActionKangurAccentShadowColor: '#f97316',
  homeActionKangurUnderlayShadowColor: '#f59e0b',
  homeActionKangurSurfaceShadowColor: '#d97706',

  // ── Color Schemes ─────────────────────────────────────────
  colorSchemes: [
    {
      id: 'kangur-crystal-sapphire',
      name: 'Crystal Sapphire',
      colors: {
        background: '#eef3fa',
        surface: '#f7f9ff',
        text: '#1e293b',
        accent: '#2563eb',
        border: '#dde4f0',
      },
    },
    {
      id: 'kangur-crystal-amethyst',
      name: 'Crystal Amethyst',
      colors: {
        background: '#f3effe',
        surface: '#f9f7ff',
        text: '#1e293b',
        accent: '#7c3aed',
        border: '#e4daf8',
      },
    },
    {
      id: 'kangur-crystal-aqua',
      name: 'Crystal Aqua',
      colors: {
        background: '#ecf8ff',
        surface: '#f5fbff',
        text: '#1e293b',
        accent: '#0ea5e9',
        border: '#d4edf8',
      },
    },
    {
      id: 'kangur-crystal-amber',
      name: 'Crystal Amber',
      colors: {
        background: '#fef7ec',
        surface: '#fffbf5',
        text: '#1e293b',
        accent: '#f59e0b',
        border: '#f3e4c8',
      },
    },
  ],
  activeColorSchemeId: 'kangur-crystal-sapphire',

  // ── Typography ────────────────────────────────────────────
  headingFont: '\'Space Grotesk\', sans-serif',
  bodyFont: '\'DM Sans\', sans-serif',
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1.08,
  bodySizeScale: 1,
  lineHeight: 1.62,
  headingLineHeight: 1.16,

  // ── Layout ────────────────────────────────────────────────
  maxContentWidth: 1240,
  gridGutter: 28,
  sectionSpacing: 72,
  containerPadding: 28,
  borderRadius: 24,
  pagePaddingTop: 36,
  pagePaddingRight: 32,
  pagePaddingBottom: 84,
  pagePaddingLeft: 32,
  pagePadding: 32,
  pageMargin: 0,
  fullWidth: false,

  // ── Animations ────────────────────────────────────────────
  enableAnimations: true,
  animationDuration: 260,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.015,

  // ── Buttons (full gel showcase) ───────────────────────────
  btnPaddingX: 24,
  btnPaddingY: 12,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 999,
  btnPrimaryBg: 'linear-gradient(180deg, #e0e7ff 0%, #c7d2fe 46%, #818cf8 100%)',
  btnPrimaryText: '#1e3a6e',
  btnSecondaryBg: 'linear-gradient(180deg, rgba(255, 255, 255, 0.96) 0%, rgba(226, 238, 255, 0.92) 100%)',
  btnSecondaryText: '#1e3a6e',
  btnOutlineBorder: '#c7d6ef',
  btnBorderWidth: 1,
  btnBorderOpacity: 55,
  btnBorderRadius: 999,
  btnShadowOpacity: 0.22,
  btnShadowX: 0,
  btnShadowY: 8,
  btnShadowBlur: 24,

  // ── Button Gel Effects (all 12, full showcase) ────────────
  btnGlossOpacity: 0.38,
  btnGlossHeight: 52,
  btnGlossAngle: 178,
  btnInsetHighlightOpacity: 0.45,
  btnInsetShadowOpacity: 0.3,
  btnInsetShadowBlur: 5,
  btnInsetShadowY: 3,
  btnTextShadowOpacity: 0,
  btnTextShadowY: 1,
  btnTextShadowBlur: 0,
  btnGlowOpacity: 0.18,
  btnGlowSpread: 10,

  // ── Variant Pills ─────────────────────────────────────────
  pillRadius: 999,
  pillPaddingX: 14,
  pillPaddingY: 6,
  pillFontSize: 12,
  pillBg: 'rgba(255, 255, 255, 0.82)',
  pillText: '#475569',
  pillActiveBg: '#dbeafe',
  pillActiveText: '#1d4ed8',
  pillBorderColor: '#dde4f0',
  pillBorderWidth: 1,
  pillBorderOpacity: 65,
  pillShadowOpacity: 0.14,
  pillShadowX: 0,
  pillShadowY: 8,
  pillShadowBlur: 22,

  // ── Inputs ────────────────────────────────────────────────
  inputHeight: 50,
  inputRadius: 22,
  inputBorderColor: '#d4dbed',
  inputBorderWidth: 1,
  inputBorderOpacity: 80,
  inputBg: '#ffffff',
  inputText: '#1e293b',
  inputFocusBorder: '#93b4f6',
  inputPlaceholder: '#94a3b8',
  inputFontSize: 14,
  inputShadowOpacity: 0.1,
  inputShadowX: 0,
  inputShadowY: 10,
  inputShadowBlur: 28,

  // ── Product Cards ─────────────────────────────────────────
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardTextAlignment: 'left',
  cardColorScheme: 'kangur-crystal-sapphire',
  cardRadius: 22,
  cardShadow: 'large',
  cardBg: '#ffffff',
  cardHoverShadow: 'large',
  showBadge: true,
  showQuickAdd: false,
  cardBorderWidth: 1,
  cardBorderOpacity: 60,
  cardBorderRadius: 22,
  cardShadowOpacity: 0.14,
  cardShadowX: 0,
  cardShadowY: 16,
  cardShadowBlur: 36,

  // ── Collections ───────────────────────────────────────────
  collectionRatio: '16:9',
  collectionRadius: 22,
  collectionStyle: 'overlay',
  collectionImagePadding: 8,
  collectionOverlay: true,
  collectionOverlayColor: 'rgba(255, 255, 255, 0.68)',
  collectionTextAlign: 'left',
  collectionColorScheme: 'kangur-crystal-sapphire',
  collectionBorderWidth: 1,
  collectionBorderOpacity: 60,
  collectionShadowOpacity: 0.14,
  collectionShadowX: 0,
  collectionShadowY: 16,
  collectionShadowBlur: 36,

  // ── Blog ──────────────────────────────────────────────────
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 8,
  blogTextAlignment: 'left',
  blogColorScheme: 'kangur-crystal-sapphire',
  blogRadius: 22,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 3,
  blogBorderWidth: 1,
  blogBorderOpacity: 60,
  blogBorderRadius: 22,
  blogShadowOpacity: 0.14,
  blogShadowX: 0,
  blogShadowY: 16,
  blogShadowBlur: 36,

  // ── Content Containers ────────────────────────────────────
  containerBg: '#f7f9ff',
  containerBorderColor: '#e2e8f4',
  containerRadius: 26,
  containerPaddingInner: 24,
  containerShadow: 'large',
  containerBorderWidth: 1,
  containerBorderOpacity: 65,
  containerBorderRadius: 26,
  containerShadowOpacity: 0.16,
  containerShadowX: 0,
  containerShadowY: 18,
  containerShadowBlur: 44,

  // ── Panel & Nav Gradients ─────────────────────────────────
  panelGradientStart: 'rgba(255, 255, 255, 0.98)',
  panelGradientEnd: 'rgba(238, 243, 250, 0.94)',
  panelTransparency: 0.96,
  navGradientStart: 'rgba(255, 255, 255, 0.97)',
  navGradientEnd: 'rgba(240, 245, 255, 0.92)',
  navTransparency: 0.95,

  // ── Media ─────────────────────────────────────────────────
  imageRadius: 16,
  imageBorderColor: '#dde4f0',
  imageBorderWidth: 1,
  imageBorderOpacity: 55,
  imageShadowOpacity: 0.1,
  imageShadowX: 0,
  imageShadowY: 10,
  imageShadowBlur: 28,
  imagePlaceholderBg: '#f0f4ff',

  // ── Dropdowns ─────────────────────────────────────────────
  dropdownBg: '#ffffff',
  dropdownBorder: '#dde4f0',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 70,
  dropdownRadius: 18,
  dropdownShadow: 'large',
  dropdownShadowOpacity: 0.18,
  dropdownShadowX: 0,
  dropdownShadowY: 14,
  dropdownShadowBlur: 36,
  popupOverlayColor: 'rgba(30, 41, 59, 0.16)',
  popupRadius: 24,

  // ── Drawers ───────────────────────────────────────────────
  drawerWidth: 400,
  drawerBg: '#f7f9ff',
  drawerOverlayColor: 'rgba(30, 41, 59, 0.18)',
  drawerPosition: 'right',
  drawerBorderColor: '#e0e7f2',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 70,
  drawerRadius: 24,
  drawerShadowOpacity: 0.2,
  drawerShadowX: 0,
  drawerShadowY: 16,
  drawerShadowBlur: 44,

  // ── Badges ────────────────────────────────────────────────
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#e0e7ff',
  badgeDefaultText: '#3730a3',
  badgeSaleColorScheme: 'kangur-crystal-amber',
  badgeSaleBg: '#fef3c7',
  badgeSaleText: '#92400e',
  badgeSoldOutColorScheme: 'kangur-crystal-sapphire',
  badgeSoldOutBg: '#f0f4ff',
  badgeSoldOutText: '#64748b',
});

/** Kangur Nightly Crystal theme — deep sapphire night with high-gloss gel buttons (2026-03-14). */
export const KANGUR_NIGHTLY_CRYSTAL_THEME: ThemeSettings = normalizeThemeSettings({
  ...DEFAULT_THEME,
  themePreset: 'kangur-nightly-crystal',
  darkMode: true,

  // ── Core Palette (deep sapphire night) ────────────────────
  primaryColor: '#60a5fa',
  secondaryColor: '#a78bfa',
  accentColor: '#fbbf24',
  backgroundColor: '#080c18',
  surfaceColor: '#0e1529',
  textColor: '#e8efff',
  mutedTextColor: '#8b9ec4',
  pageTextColor: '#e8efff',
  pageMutedTextColor: '#8b9ec4',
  cardTextColor: '#e0eaff',
  navTextColor: '#94a8d0',
  navActiveTextColor: '#60a5fa',
  navHoverTextColor: '#93c5fd',
  borderColor: '#1a2544',
  errorColor: '#fb7185',
  successColor: '#34d399',

  // ── Accent Gradients (luminous on dark) ───────────────────
  gradientIndigoStart: '#3b82f6',
  gradientIndigoEnd: '#6366f1',
  gradientVioletStart: '#8b5cf6',
  gradientVioletEnd: '#c084fc',
  gradientEmeraldStart: '#34d399',
  gradientEmeraldEnd: '#6ee7b7',
  gradientSkyStart: '#38bdf8',
  gradientSkyEnd: '#67e8f9',
  gradientAmberStart: '#fbbf24',
  gradientAmberEnd: '#fde68a',
  gradientRoseStart: '#fb7185',
  gradientRoseEnd: '#fda4af',
  gradientTealStart: '#2dd4bf',
  gradientTealEnd: '#5eead4',
  gradientSlateStart: '#94a3b8',
  gradientSlateEnd: '#475569',

  // ── Logo (Crystal branding → luminous night) ──────────────
  logoWordStart: '#60a5fa',
  logoWordMid: '#818cf8',
  logoWordEnd: '#a78bfa',
  logoRingStart: '#3b82f6',
  logoRingEnd: '#8b5cf6',
  logoAccentStart: '#fbbf24',
  logoAccentEnd: '#f97316',
  logoInnerStart: '#e0eaff',
  logoInnerEnd: '#1e3a5f',
  logoShadow: '#0c1a3a',
  logoGlint: '#fef9c3',

  // ── Home Actions — Lessons (sapphire-to-indigo glow) ──────
  homeActionLessonsTextColor: '#c7dbff',
  homeActionLessonsTextActiveColor: '#f8fafc',
  homeActionLessonsLabelStart: '#3b82f6',
  homeActionLessonsLabelMid: '#60a5fa',
  homeActionLessonsLabelEnd: '#6366f1',
  homeActionLessonsAccentStart: '#3b82f6',
  homeActionLessonsAccentMid: '#60a5fa',
  homeActionLessonsAccentEnd: '#6366f1',
  homeActionLessonsUnderlayStart: 'rgba(59, 130, 246, 0.38)',
  homeActionLessonsUnderlayMid: 'rgba(96, 165, 250, 0.28)',
  homeActionLessonsUnderlayEnd: 'rgba(99, 102, 241, 0.40)',
  homeActionLessonsUnderlayTintStart: 'rgba(59, 130, 246, 0.26)',
  homeActionLessonsUnderlayTintMid: 'rgba(96, 165, 250, 0.50)',
  homeActionLessonsUnderlayTintEnd: 'rgba(99, 102, 241, 0.70)',
  homeActionLessonsAccentShadowColor: '#60a5fa',
  homeActionLessonsUnderlayShadowColor: '#6366f1',
  homeActionLessonsSurfaceShadowColor: '#3b82f6',

  // ── Home Actions — Play (violet-to-purple glow) ───────────
  homeActionPlayTextColor: '#ddd6fe',
  homeActionPlayTextActiveColor: '#f8fafc',
  homeActionPlayLabelStart: '#8b5cf6',
  homeActionPlayLabelMid: '#a78bfa',
  homeActionPlayLabelEnd: '#c084fc',
  homeActionPlayAccentStart: '#8b5cf6',
  homeActionPlayAccentMid: '#a78bfa',
  homeActionPlayAccentEnd: '#c084fc',
  homeActionPlayUnderlayStart: 'rgba(139, 92, 246, 0.38)',
  homeActionPlayUnderlayMid: 'rgba(167, 139, 250, 0.28)',
  homeActionPlayUnderlayEnd: 'rgba(192, 132, 252, 0.40)',
  homeActionPlayUnderlayTintStart: 'rgba(139, 92, 246, 0.26)',
  homeActionPlayUnderlayTintMid: 'rgba(167, 139, 250, 0.50)',
  homeActionPlayUnderlayTintEnd: 'rgba(192, 132, 252, 0.70)',
  homeActionPlayAccentShadowColor: '#a78bfa',
  homeActionPlayUnderlayShadowColor: '#c084fc',
  homeActionPlaySurfaceShadowColor: '#8b5cf6',

  // ── Home Actions — Training (cyan-to-sky glow) ────────────
  homeActionTrainingTextColor: '#bae6fd',
  homeActionTrainingTextActiveColor: '#f8fafc',
  homeActionTrainingLabelStart: '#22d3ee',
  homeActionTrainingLabelMid: '#38bdf8',
  homeActionTrainingLabelEnd: '#67e8f9',
  homeActionTrainingAccentStart: '#22d3ee',
  homeActionTrainingAccentMid: '#38bdf8',
  homeActionTrainingAccentEnd: '#67e8f9',
  homeActionTrainingUnderlayStart: 'rgba(34, 211, 238, 0.38)',
  homeActionTrainingUnderlayMid: 'rgba(56, 189, 248, 0.28)',
  homeActionTrainingUnderlayEnd: 'rgba(103, 232, 249, 0.38)',
  homeActionTrainingUnderlayTintStart: 'rgba(34, 211, 238, 0.26)',
  homeActionTrainingUnderlayTintMid: 'rgba(56, 189, 248, 0.48)',
  homeActionTrainingUnderlayTintEnd: 'rgba(103, 232, 249, 0.66)',
  homeActionTrainingAccentShadowColor: '#38bdf8',
  homeActionTrainingUnderlayShadowColor: '#22d3ee',
  homeActionTrainingSurfaceShadowColor: '#0ea5e9',

  // ── Home Actions — Kangur (amber-to-gold glow) ────────────
  homeActionKangurTextColor: '#fef3c7',
  homeActionKangurTextActiveColor: '#f8fafc',
  homeActionKangurLabelStart: '#fbbf24',
  homeActionKangurLabelMid: '#f59e0b',
  homeActionKangurLabelEnd: '#fde68a',
  homeActionKangurAccentStart: '#fbbf24',
  homeActionKangurAccentMid: '#f59e0b',
  homeActionKangurAccentEnd: '#fde68a',
  homeActionKangurUnderlayStart: 'rgba(251, 191, 36, 0.38)',
  homeActionKangurUnderlayMid: 'rgba(245, 158, 11, 0.28)',
  homeActionKangurUnderlayEnd: 'rgba(253, 230, 138, 0.36)',
  homeActionKangurUnderlayTintStart: 'rgba(251, 191, 36, 0.26)',
  homeActionKangurUnderlayTintMid: 'rgba(245, 158, 11, 0.46)',
  homeActionKangurUnderlayTintEnd: 'rgba(253, 230, 138, 0.62)',
  homeActionKangurAccentShadowColor: '#f59e0b',
  homeActionKangurUnderlayShadowColor: '#fbbf24',
  homeActionKangurSurfaceShadowColor: '#d97706',

  // ── Color Schemes ─────────────────────────────────────────
  colorSchemes: [
    {
      id: 'kangur-ncrystal-sapphire',
      name: 'Night Sapphire',
      colors: {
        background: '#080c18',
        surface: '#0e1529',
        text: '#e8efff',
        accent: '#60a5fa',
        border: '#1a2544',
      },
    },
    {
      id: 'kangur-ncrystal-amethyst',
      name: 'Night Amethyst',
      colors: {
        background: '#0d0a1e',
        surface: '#15112f',
        text: '#ede8ff',
        accent: '#a78bfa',
        border: '#231e48',
      },
    },
    {
      id: 'kangur-ncrystal-cyan',
      name: 'Night Cyan',
      colors: {
        background: '#061218',
        surface: '#0c1c28',
        text: '#e0f7ff',
        accent: '#22d3ee',
        border: '#152e3e',
      },
    },
    {
      id: 'kangur-ncrystal-gold',
      name: 'Night Gold',
      colors: {
        background: '#100d06',
        surface: '#1a1610',
        text: '#fff8e1',
        accent: '#fbbf24',
        border: '#2e2614',
      },
    },
  ],
  activeColorSchemeId: 'kangur-ncrystal-sapphire',

  // ── Typography ────────────────────────────────────────────
  headingFont: '\'Space Grotesk\', sans-serif',
  bodyFont: '\'DM Sans\', sans-serif',
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1.08,
  bodySizeScale: 1,
  lineHeight: 1.62,
  headingLineHeight: 1.16,

  // ── Layout ────────────────────────────────────────────────
  maxContentWidth: 1240,
  gridGutter: 28,
  sectionSpacing: 72,
  containerPadding: 28,
  borderRadius: 24,
  pagePaddingTop: 36,
  pagePaddingRight: 32,
  pagePaddingBottom: 84,
  pagePaddingLeft: 32,
  pagePadding: 32,
  pageMargin: 0,
  fullWidth: false,

  // ── Animations ────────────────────────────────────────────
  enableAnimations: true,
  animationDuration: 280,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.02,

  // ── Buttons (high-gloss gel on dark) ──────────────────────
  btnPaddingX: 26,
  btnPaddingY: 13,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 999,
  btnPrimaryBg: 'linear-gradient(180deg, #93c5fd 0%, #60a5fa 40%, #3b82f6 100%)',
  btnPrimaryText: '#0a1628',
  btnSecondaryBg: 'linear-gradient(180deg, rgba(20, 30, 56, 0.95) 0%, rgba(14, 21, 41, 0.95) 100%)',
  btnSecondaryText: '#c7dbff',
  btnOutlineBorder: '#253a60',
  btnBorderWidth: 1,
  btnBorderOpacity: 50,
  btnBorderRadius: 999,
  btnShadowOpacity: 0.35,
  btnShadowX: 0,
  btnShadowY: 10,
  btnShadowBlur: 30,

  // ── Button Gel Effects (high-gloss showcase) ──────────────
  btnGlossOpacity: 0.55,
  btnGlossHeight: 50,
  btnGlossAngle: 178,
  btnGlossColor: '#bfdbfe',
  btnInsetHighlightOpacity: 0.55,
  btnInsetShadowOpacity: 0.45,
  btnInsetShadowBlur: 6,
  btnInsetShadowY: 3,
  btnTextShadowOpacity: 0.50,
  btnTextShadowY: 1,
  btnTextShadowBlur: 0,
  btnGlowOpacity: 0.35,
  btnGlowSpread: 14,
  btnGlowColor: '#60a5fa',

  // ── Variant Pills ─────────────────────────────────────────
  pillRadius: 999,
  pillPaddingX: 14,
  pillPaddingY: 6,
  pillFontSize: 12,
  pillBg: 'rgba(14, 21, 41, 0.85)',
  pillText: '#94a8d0',
  pillActiveBg: 'rgba(30, 64, 175, 0.4)',
  pillActiveText: '#93c5fd',
  pillBorderColor: '#1e3050',
  pillBorderWidth: 1,
  pillBorderOpacity: 55,
  pillShadowOpacity: 0.16,
  pillShadowX: 0,
  pillShadowY: 8,
  pillShadowBlur: 24,

  // ── Inputs ────────────────────────────────────────────────
  inputHeight: 50,
  inputRadius: 22,
  inputBorderColor: '#1e3050',
  inputBorderWidth: 1,
  inputBorderOpacity: 75,
  inputBg: '#0b1222',
  inputText: '#e8efff',
  inputFocusBorder: '#60a5fa',
  inputPlaceholder: '#6b82a8',
  inputFontSize: 14,
  inputShadowOpacity: 0.12,
  inputShadowX: 0,
  inputShadowY: 10,
  inputShadowBlur: 28,

  // ── Product Cards ─────────────────────────────────────────
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardTextAlignment: 'left',
  cardColorScheme: 'kangur-ncrystal-sapphire',
  cardRadius: 22,
  cardShadow: 'large',
  cardBg: '#0e1529',
  cardHoverShadow: 'large',
  showBadge: true,
  showQuickAdd: false,
  cardBorderWidth: 1,
  cardBorderOpacity: 55,
  cardBorderRadius: 22,
  cardShadowOpacity: 0.24,
  cardShadowX: 0,
  cardShadowY: 18,
  cardShadowBlur: 42,

  // ── Collections ───────────────────────────────────────────
  collectionRatio: '16:9',
  collectionRadius: 22,
  collectionStyle: 'overlay',
  collectionImagePadding: 8,
  collectionOverlay: true,
  collectionOverlayColor: 'rgba(8, 12, 24, 0.65)',
  collectionTextAlign: 'left',
  collectionColorScheme: 'kangur-ncrystal-sapphire',
  collectionBorderWidth: 1,
  collectionBorderOpacity: 55,
  collectionShadowOpacity: 0.24,
  collectionShadowX: 0,
  collectionShadowY: 18,
  collectionShadowBlur: 42,

  // ── Blog ──────────────────────────────────────────────────
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 8,
  blogTextAlignment: 'left',
  blogColorScheme: 'kangur-ncrystal-sapphire',
  blogRadius: 22,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 3,
  blogBorderWidth: 1,
  blogBorderOpacity: 55,
  blogBorderRadius: 22,
  blogShadowOpacity: 0.24,
  blogShadowX: 0,
  blogShadowY: 18,
  blogShadowBlur: 42,

  // ── Content Containers ────────────────────────────────────
  containerBg: '#0b1222',
  containerBorderColor: '#182640',
  containerRadius: 26,
  containerPaddingInner: 24,
  containerShadow: 'large',
  containerBorderWidth: 1,
  containerBorderOpacity: 60,
  containerBorderRadius: 26,
  containerShadowOpacity: 0.28,
  containerShadowX: 0,
  containerShadowY: 20,
  containerShadowBlur: 50,

  // ── Panel & Nav Gradients ─────────────────────────────────
  panelGradientStart: '#131d36',
  panelGradientEnd: '#080c18',
  panelTransparency: 0.93,
  navGradientStart: '#101a30',
  navGradientEnd: '#070b16',
  navTransparency: 0.92,

  // ── Media ─────────────────────────────────────────────────
  imageRadius: 16,
  imageBorderColor: '#1a2544',
  imageBorderWidth: 1,
  imageBorderOpacity: 50,
  imageShadowOpacity: 0.14,
  imageShadowX: 0,
  imageShadowY: 12,
  imageShadowBlur: 30,
  imagePlaceholderBg: '#0a1020',

  // ── Dropdowns ─────────────────────────────────────────────
  dropdownBg: '#0e1529',
  dropdownBorder: '#1e3050',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 65,
  dropdownRadius: 18,
  dropdownShadow: 'large',
  dropdownShadowOpacity: 0.30,
  dropdownShadowX: 0,
  dropdownShadowY: 16,
  dropdownShadowBlur: 42,
  popupOverlayColor: 'rgba(4, 6, 14, 0.65)',
  popupRadius: 24,

  // ── Drawers ───────────────────────────────────────────────
  drawerWidth: 400,
  drawerBg: '#0b1222',
  drawerOverlayColor: 'rgba(4, 6, 14, 0.70)',
  drawerPosition: 'right',
  drawerBorderColor: '#182640',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 60,
  drawerRadius: 24,
  drawerShadowOpacity: 0.28,
  drawerShadowX: 0,
  drawerShadowY: 18,
  drawerShadowBlur: 48,

  // ── Badges ────────────────────────────────────────────────
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#152244',
  badgeDefaultText: '#93c5fd',
  badgeSaleColorScheme: 'kangur-ncrystal-gold',
  badgeSaleBg: '#fef3c7',
  badgeSaleText: '#78350f',
  badgeSoldOutColorScheme: 'kangur-ncrystal-sapphire',
  badgeSoldOutBg: '#0e1832',
  badgeSoldOutText: '#6b82a8',
});
