import type {
  FilemakerMailAccount,
  FilemakerMailAccountDraft,
  FilemakerMailAccountStatus,
  FilemakerMailComposeInput,
  FilemakerMailFlagPatch,
  FilemakerMailFolderRole,
  FilemakerMailFolderSummary,
  FilemakerMailMessage,
  FilemakerMailOutboxEntry,
  FilemakerMailParticipant,
  FilemakerMailSearchHit,
  FilemakerMailSearchResponse,
  FilemakerMailSearchResultGroup,
  FilemakerMailSyncResult,
  FilemakerMailThread,
  FilemakerMailThreadDetail,
} from '../../types';

export type {
  FilemakerMailAccount,
  FilemakerMailAccountDraft,
  FilemakerMailAccountStatus,
  FilemakerMailComposeInput,
  FilemakerMailFlagPatch,
  FilemakerMailFolderRole,
  FilemakerMailFolderSummary,
  FilemakerMailMessage,
  FilemakerMailOutboxEntry,
  FilemakerMailParticipant,
  FilemakerMailSearchHit,
  FilemakerMailSearchResponse,
  FilemakerMailSearchResultGroup,
  FilemakerMailSyncResult,
  FilemakerMailThread,
  FilemakerMailThreadDetail,
};
