import {
  Activity,
  Airplay,
  AlarmClock,
  Aperture,
  Archive,
  Atom,
  BadgeCheck,
  Banknote,
  Barcode,
  Bell,
  Book,
  Bookmark,
  Bot,
  Brain,
  Brush,
  Bug,
  Camera,
  Clipboard,
  Cloud,
  Code,
  Cpu,
  Database,
  FileText,
  Globe,
  Image,
  Key,
  Layers,
  List,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Palette,
  Package,
  PenTool,
  Phone,
  Play,
  Puzzle,
  Search,
  Shield,
  ShoppingCart,
  Tag,
  Target,
  Terminal,
  Timer,
  Star,
  Sun,
  Heart,
  User,
  Users,
  Wand2,
  Wrench,
  Zap,
  Gift,
  Truck,
  DollarSign,
  Award,
  Box,
  Sparkles,
  Pin,
  AreaChart,
  BarChart3,
  BarChart4,
  CandlestickChart,
  ChartBar,
  ChartLine,
  ChartPie,
  LineChart,
  Gauge,
  GaugeCircle,
  TrendingUp,
  TrendingDown,
  Briefcase,
  Building2,
  Home,
  Store,
  Warehouse,
  Factory,
  Construction,
  HardHat,
  Calendar,
  CalendarClock,
  Clock3,
  CheckCircle2,
  CheckSquare,
  CircleHelp,
  CircleDollarSign,
  BadgeInfo,
  Compass,
  Route,
  Navigation,
  Navigation2,
  Map,
  MapPinned,
  Plane,
  Car,
  Bike,
  Bus,
  Train,
  Ship,
  Footprints,
  Contact,
  ContactRound,
  IdCard,
  Copy,
  Download,
  Upload,
  ExternalLink,
  Link,
  Share2,
  Save,
  Send,
  Menu,
  CreditCard,
  Wallet,
  Receipt,
  Percent,
  Folder,
  FolderOpen,
  FileSearch,
  FileSpreadsheet,
  FileCode2,
  FileJson,
  NotepadText,
  NotebookTabs,
  BookOpen,
  Filter,
  ListChecks,
  ClipboardCheck,
  ClipboardList,
  ClipboardPen,
  Library,
  Languages,
  Laptop,
  Computer,
  HardDrive,
  MonitorCog,
  Smartphone,
  Wifi,
  Radio,
  Headphones,
  Podcast,
  Settings,
  Settings2,
  Workflow,
  FlaskConical,
  Lightbulb,
  LampDesk,
  Rocket,
  Gem,
  Crown,
  Diamond,
  Trophy,
  PartyPopper,
  ImagePlus,
  ImageOff,
  Crop,
  Paintbrush2,
  PaintBucket,
  PenSquare,
  PencilRuler,
  Clapperboard,
  Film,
  Music2,
  Gamepad2,
  Joystick,
  PackageSearch,
  PackagePlus,
  PackageMinus,
  Boxes,
  ShoppingBag,
  ShoppingBasket,
  ShieldCheck,
  ShieldAlert,
  ShieldMinus,
  ShieldPlus,
  ShieldQuestion,
  ShieldEllipsis,
  LockKeyhole,
  KeyRound,
  Fingerprint,
  Binary,
  Code2,
  CodeXml,
  Braces,
  BugOff,
  MessageSquare,
  MessageCircleQuestion,
  MessageCircleHeart,
  MailCheck,
  MailWarning,
  MailPlus,
  PhoneCall,
  PhoneForwarded,
  Megaphone,
  Siren,
  Newspaper,
  ScanBarcode,
  ScanLine,
  ScanSearch,
  QrCode,
  SwatchBook,
  SunMoon,
  ThumbsUp,
  Smile,
  Frown,
  Laugh,
  Meh,
  Stethoscope,
  Utensils,
  CookingPot,
  ChefHat,
  Handshake,
  Inbox,
  Info,
  LocateFixed,
  type LucideIcon,
} from 'lucide-react';

export const ICON_LIBRARY = [
  { id: 'activity', icon: Activity, label: 'Activity' },
  { id: 'airplay', icon: Airplay, label: 'Airplay' },
  { id: 'alarm-clock', icon: AlarmClock, label: 'Alarm Clock' },
  { id: 'aperture', icon: Aperture, label: 'Aperture' },
  { id: 'archive', icon: Archive, label: 'Archive' },
  { id: 'atom', icon: Atom, label: 'Atom' },
  { id: 'badge-check', icon: BadgeCheck, label: 'Badge Check' },
  { id: 'banknote', icon: Banknote, label: 'Banknote' },
  { id: 'barcode', icon: Barcode, label: 'Barcode' },
  { id: 'bell', icon: Bell, label: 'Bell' },
  { id: 'book', icon: Book, label: 'Book' },
  { id: 'bookmark', icon: Bookmark, label: 'Bookmark' },
  { id: 'bot', icon: Bot, label: 'Bot' },
  { id: 'brain', icon: Brain, label: 'Brain' },
  { id: 'brush', icon: Brush, label: 'Brush' },
  { id: 'bug', icon: Bug, label: 'Bug' },
  { id: 'camera', icon: Camera, label: 'Camera' },
  { id: 'clipboard', icon: Clipboard, label: 'Clipboard' },
  { id: 'cloud', icon: Cloud, label: 'Cloud' },
  { id: 'code', icon: Code, label: 'Code' },
  { id: 'cpu', icon: Cpu, label: 'CPU' },
  { id: 'database', icon: Database, label: 'Database' },
  { id: 'file-text', icon: FileText, label: 'File Text' },
  { id: 'globe', icon: Globe, label: 'Globe' },
  { id: 'image', icon: Image, label: 'Image' },
  { id: 'key', icon: Key, label: 'Key' },
  { id: 'layers', icon: Layers, label: 'Layers' },
  { id: 'list', icon: List, label: 'List' },
  { id: 'lock', icon: Lock, label: 'Lock' },
  { id: 'mail', icon: Mail, label: 'Mail' },
  { id: 'map-pin', icon: MapPin, label: 'Map Pin' },
  { id: 'message-circle', icon: MessageCircle, label: 'Message Circle' },
  { id: 'mic', icon: Mic, label: 'Mic' },
  { id: 'monitor', icon: Monitor, label: 'Monitor' },
  { id: 'moon', icon: Moon, label: 'Moon' },
  { id: 'music', icon: Music, label: 'Music' },
  { id: 'palette', icon: Palette, label: 'Palette' },
  { id: 'package', icon: Package, label: 'Package' },
  { id: 'pen-tool', icon: PenTool, label: 'Pen Tool' },
  { id: 'phone', icon: Phone, label: 'Phone' },
  { id: 'play', icon: Play, label: 'Play' },
  { id: 'puzzle', icon: Puzzle, label: 'Puzzle' },
  { id: 'search', icon: Search, label: 'Search' },
  { id: 'shield', icon: Shield, label: 'Shield' },
  { id: 'shopping-cart', icon: ShoppingCart, label: 'Shopping Cart' },
  { id: 'tag', icon: Tag, label: 'Tag' },
  { id: 'target', icon: Target, label: 'Target' },
  { id: 'terminal', icon: Terminal, label: 'Terminal' },
  { id: 'timer', icon: Timer, label: 'Timer' },
  { id: 'star', icon: Star, label: 'Star' },
  { id: 'sun', icon: Sun, label: 'Sun' },
  { id: 'heart', icon: Heart, label: 'Heart' },
  { id: 'user', icon: User, label: 'User' },
  { id: 'users', icon: Users, label: 'Users' },
  { id: 'wand-2', icon: Wand2, label: 'Wand 2' },
  { id: 'wrench', icon: Wrench, label: 'Wrench' },
  { id: 'zap', icon: Zap, label: 'Zap' },
  { id: 'gift', icon: Gift, label: 'Gift' },
  { id: 'truck', icon: Truck, label: 'Truck' },
  { id: 'dollar-sign', icon: DollarSign, label: 'Dollar Sign' },
  { id: 'award', icon: Award, label: 'Award' },
  { id: 'box', icon: Box, label: 'Box' },
  { id: 'sparkles', icon: Sparkles, label: 'Sparkles' },
  { id: 'pin', icon: Pin, label: 'Pin' },
  { id: 'area-chart', icon: AreaChart, label: 'Area Chart' },
  { id: 'bar-chart-3', icon: BarChart3, label: 'Bar Chart 3' },
  { id: 'bar-chart-4', icon: BarChart4, label: 'Bar Chart 4' },
  { id: 'candlestick-chart', icon: CandlestickChart, label: 'Candlestick Chart' },
  { id: 'chart-bar', icon: ChartBar, label: 'Chart Bar' },
  { id: 'chart-line', icon: ChartLine, label: 'Chart Line' },
  { id: 'chart-pie', icon: ChartPie, label: 'Chart Pie' },
  { id: 'line-chart', icon: LineChart, label: 'Line Chart' },
  { id: 'gauge', icon: Gauge, label: 'Gauge' },
  { id: 'gauge-circle', icon: GaugeCircle, label: 'Gauge Circle' },
  { id: 'trending-up', icon: TrendingUp, label: 'Trending Up' },
  { id: 'trending-down', icon: TrendingDown, label: 'Trending Down' },
  { id: 'briefcase', icon: Briefcase, label: 'Briefcase' },
  { id: 'building-2', icon: Building2, label: 'Building 2' },
  { id: 'home', icon: Home, label: 'Home' },
  { id: 'store', icon: Store, label: 'Store' },
  { id: 'warehouse', icon: Warehouse, label: 'Warehouse' },
  { id: 'factory', icon: Factory, label: 'Factory' },
  { id: 'construction', icon: Construction, label: 'Construction' },
  { id: 'hard-hat', icon: HardHat, label: 'Hard Hat' },
  { id: 'calendar', icon: Calendar, label: 'Calendar' },
  { id: 'calendar-clock', icon: CalendarClock, label: 'Calendar Clock' },
  { id: 'clock-3', icon: Clock3, label: 'Clock 3' },
  { id: 'check-circle-2', icon: CheckCircle2, label: 'Check Circle 2' },
  { id: 'check-square', icon: CheckSquare, label: 'Check Square' },
  { id: 'circle-help', icon: CircleHelp, label: 'Circle Help' },
  { id: 'circle-dollar-sign', icon: CircleDollarSign, label: 'Circle Dollar Sign' },
  { id: 'badge-info', icon: BadgeInfo, label: 'Badge Info' },
  { id: 'compass', icon: Compass, label: 'Compass' },
  { id: 'route', icon: Route, label: 'Route' },
  { id: 'navigation', icon: Navigation, label: 'Navigation' },
  { id: 'navigation-2', icon: Navigation2, label: 'Navigation 2' },
  { id: 'map', icon: Map, label: 'Map' },
  { id: 'map-pinned', icon: MapPinned, label: 'Map Pinned' },
  { id: 'plane', icon: Plane, label: 'Plane' },
  { id: 'car', icon: Car, label: 'Car' },
  { id: 'bike', icon: Bike, label: 'Bike' },
  { id: 'bus', icon: Bus, label: 'Bus' },
  { id: 'train', icon: Train, label: 'Train' },
  { id: 'ship', icon: Ship, label: 'Ship' },
  { id: 'footprints', icon: Footprints, label: 'Footprints' },
  { id: 'contact', icon: Contact, label: 'Contact' },
  { id: 'contact-round', icon: ContactRound, label: 'Contact Round' },
  { id: 'id-card', icon: IdCard, label: 'ID Card' },
  { id: 'copy', icon: Copy, label: 'Copy' },
  { id: 'download', icon: Download, label: 'Download' },
  { id: 'upload', icon: Upload, label: 'Upload' },
  { id: 'external-link', icon: ExternalLink, label: 'External Link' },
  { id: 'link', icon: Link, label: 'Link' },
  { id: 'share-2', icon: Share2, label: 'Share 2' },
  { id: 'save', icon: Save, label: 'Save' },
  { id: 'send', icon: Send, label: 'Send' },
  { id: 'menu', icon: Menu, label: 'Menu' },
  { id: 'credit-card', icon: CreditCard, label: 'Credit Card' },
  { id: 'wallet', icon: Wallet, label: 'Wallet' },
  { id: 'receipt', icon: Receipt, label: 'Receipt' },
  { id: 'percent', icon: Percent, label: 'Percent' },
  { id: 'folder', icon: Folder, label: 'Folder' },
  { id: 'folder-open', icon: FolderOpen, label: 'Folder Open' },
  { id: 'file-search', icon: FileSearch, label: 'File Search' },
  { id: 'file-spreadsheet', icon: FileSpreadsheet, label: 'File Spreadsheet' },
  { id: 'file-code-2', icon: FileCode2, label: 'File Code 2' },
  { id: 'file-json', icon: FileJson, label: 'File Json' },
  { id: 'notepad-text', icon: NotepadText, label: 'Notepad Text' },
  { id: 'notebook-tabs', icon: NotebookTabs, label: 'Notebook Tabs' },
  { id: 'book-open', icon: BookOpen, label: 'Book Open' },
  { id: 'filter', icon: Filter, label: 'Filter' },
  { id: 'list-checks', icon: ListChecks, label: 'List Checks' },
  { id: 'clipboard-check', icon: ClipboardCheck, label: 'Clipboard Check' },
  { id: 'clipboard-list', icon: ClipboardList, label: 'Clipboard List' },
  { id: 'clipboard-pen', icon: ClipboardPen, label: 'Clipboard Pen' },
  { id: 'library', icon: Library, label: 'Library' },
  { id: 'languages', icon: Languages, label: 'Languages' },
  { id: 'laptop', icon: Laptop, label: 'Laptop' },
  { id: 'computer', icon: Computer, label: 'Computer' },
  { id: 'hard-drive', icon: HardDrive, label: 'Hard Drive' },
  { id: 'monitor-cog', icon: MonitorCog, label: 'Monitor Cog' },
  { id: 'smartphone', icon: Smartphone, label: 'Smartphone' },
  { id: 'wifi', icon: Wifi, label: 'Wifi' },
  { id: 'radio', icon: Radio, label: 'Radio' },
  { id: 'headphones', icon: Headphones, label: 'Headphones' },
  { id: 'podcast', icon: Podcast, label: 'Podcast' },
  { id: 'settings', icon: Settings, label: 'Settings' },
  { id: 'settings-2', icon: Settings2, label: 'Settings 2' },
  { id: 'workflow', icon: Workflow, label: 'Workflow' },
  { id: 'flask-conical', icon: FlaskConical, label: 'Flask Conical' },
  { id: 'lightbulb', icon: Lightbulb, label: 'Lightbulb' },
  { id: 'lamp-desk', icon: LampDesk, label: 'Lamp Desk' },
  { id: 'rocket', icon: Rocket, label: 'Rocket' },
  { id: 'gem', icon: Gem, label: 'Gem' },
  { id: 'crown', icon: Crown, label: 'Crown' },
  { id: 'diamond', icon: Diamond, label: 'Diamond' },
  { id: 'trophy', icon: Trophy, label: 'Trophy' },
  { id: 'party-popper', icon: PartyPopper, label: 'Party Popper' },
  { id: 'image-plus', icon: ImagePlus, label: 'Image Plus' },
  { id: 'image-off', icon: ImageOff, label: 'Image Off' },
  { id: 'crop', icon: Crop, label: 'Crop' },
  { id: 'paintbrush-2', icon: Paintbrush2, label: 'Paintbrush 2' },
  { id: 'paint-bucket', icon: PaintBucket, label: 'Paint Bucket' },
  { id: 'pen-square', icon: PenSquare, label: 'Pen Square' },
  { id: 'pencil-ruler', icon: PencilRuler, label: 'Pencil Ruler' },
  { id: 'clapperboard', icon: Clapperboard, label: 'Clapperboard' },
  { id: 'film', icon: Film, label: 'Film' },
  { id: 'music-2', icon: Music2, label: 'Music 2' },
  { id: 'gamepad-2', icon: Gamepad2, label: 'Gamepad 2' },
  { id: 'joystick', icon: Joystick, label: 'Joystick' },
  { id: 'package-search', icon: PackageSearch, label: 'Package Search' },
  { id: 'package-plus', icon: PackagePlus, label: 'Package Plus' },
  { id: 'package-minus', icon: PackageMinus, label: 'Package Minus' },
  { id: 'boxes', icon: Boxes, label: 'Boxes' },
  { id: 'shopping-bag', icon: ShoppingBag, label: 'Shopping Bag' },
  { id: 'shopping-basket', icon: ShoppingBasket, label: 'Shopping Basket' },
  { id: 'shield-check', icon: ShieldCheck, label: 'Shield Check' },
  { id: 'shield-alert', icon: ShieldAlert, label: 'Shield Alert' },
  { id: 'shield-minus', icon: ShieldMinus, label: 'Shield Minus' },
  { id: 'shield-plus', icon: ShieldPlus, label: 'Shield Plus' },
  { id: 'shield-question', icon: ShieldQuestion, label: 'Shield Question' },
  { id: 'shield-ellipsis', icon: ShieldEllipsis, label: 'Shield Ellipsis' },
  { id: 'lock-keyhole', icon: LockKeyhole, label: 'Lock Keyhole' },
  { id: 'key-round', icon: KeyRound, label: 'Key Round' },
  { id: 'fingerprint', icon: Fingerprint, label: 'Fingerprint' },
  { id: 'binary', icon: Binary, label: 'Binary' },
  { id: 'code-2', icon: Code2, label: 'Code 2' },
  { id: 'code-xml', icon: CodeXml, label: 'Code XML' },
  { id: 'braces', icon: Braces, label: 'Braces' },
  { id: 'bug-off', icon: BugOff, label: 'Bug Off' },
  { id: 'message-square', icon: MessageSquare, label: 'Message Square' },
  { id: 'message-circle-question', icon: MessageCircleQuestion, label: 'Message Circle Question' },
  { id: 'message-circle-heart', icon: MessageCircleHeart, label: 'Message Circle Heart' },
  { id: 'mail-check', icon: MailCheck, label: 'Mail Check' },
  { id: 'mail-warning', icon: MailWarning, label: 'Mail Warning' },
  { id: 'mail-plus', icon: MailPlus, label: 'Mail Plus' },
  { id: 'phone-call', icon: PhoneCall, label: 'Phone Call' },
  { id: 'phone-forwarded', icon: PhoneForwarded, label: 'Phone Forwarded' },
  { id: 'megaphone', icon: Megaphone, label: 'Megaphone' },
  { id: 'siren', icon: Siren, label: 'Siren' },
  { id: 'newspaper', icon: Newspaper, label: 'Newspaper' },
  { id: 'scan-barcode', icon: ScanBarcode, label: 'Scan Barcode' },
  { id: 'scan-line', icon: ScanLine, label: 'Scan Line' },
  { id: 'scan-search', icon: ScanSearch, label: 'Scan Search' },
  { id: 'qr-code', icon: QrCode, label: 'QR Code' },
  { id: 'swatch-book', icon: SwatchBook, label: 'Swatch Book' },
  { id: 'sun-moon', icon: SunMoon, label: 'Sun Moon' },
  { id: 'thumbs-up', icon: ThumbsUp, label: 'Thumbs Up' },
  { id: 'smile', icon: Smile, label: 'Smile' },
  { id: 'frown', icon: Frown, label: 'Frown' },
  { id: 'laugh', icon: Laugh, label: 'Laugh' },
  { id: 'meh', icon: Meh, label: 'Meh' },
  { id: 'stethoscope', icon: Stethoscope, label: 'Stethoscope' },
  { id: 'utensils', icon: Utensils, label: 'Utensils' },
  { id: 'cooking-pot', icon: CookingPot, label: 'Cooking Pot' },
  { id: 'chef-hat', icon: ChefHat, label: 'Chef Hat' },
  { id: 'handshake', icon: Handshake, label: 'Handshake' },
  { id: 'inbox', icon: Inbox, label: 'Inbox' },
  { id: 'info', icon: Info, label: 'Info' },
  { id: 'locate-fixed', icon: LocateFixed, label: 'Locate Fixed' },
] as const;

export type IconLibraryId = (typeof ICON_LIBRARY)[number]['id'];

export const ICON_LIBRARY_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map(({ id, icon }: { id: string; icon: LucideIcon }) => [id, icon])
) as Record<string, LucideIcon>;
