import {
  Activity,
  Airplay,
  AlarmClock,
  Aperture,
  Archive,
  Atom,
  BadgeCheck,
  Banknote,
  Barcode,
  Bell,
  Book,
  Bookmark,
  Bot,
  Brain,
  Brush,
  Bug,
  Camera,
  Clipboard,
  Cloud,
  Code,
  Cpu,
  Database,
  FileText,
  Globe,
  Image,
  Key,
  Layers,
  List,
  Lock,
  Mail,
  MapPin,
  MessageCircle,
  Mic,
  Monitor,
  Moon,
  Music,
  Palette,
  Package,
  PenTool,
  Phone,
  Play,
  Puzzle,
  Search,
  Shield,
  ShoppingCart,
  Tag,
  Target,
  Terminal,
  Timer,
  Star,
  Sun,
  Heart,
  User,
  Users,
  Wand2,
  Wrench,
  Zap,
  Gift,
  Truck,
  DollarSign,
  Award,
  Box,
  Sparkles,
  Pin,
  type LucideIcon,
} from 'lucide-react';

export const ICON_LIBRARY = [
  { id: 'activity', icon: Activity, label: 'Activity' },
  { id: 'airplay', icon: Airplay, label: 'Airplay' },
  { id: 'alarm-clock', icon: AlarmClock, label: 'Alarm Clock' },
  { id: 'aperture', icon: Aperture, label: 'Aperture' },
  { id: 'archive', icon: Archive, label: 'Archive' },
  { id: 'atom', icon: Atom, label: 'Atom' },
  { id: 'badge-check', icon: BadgeCheck, label: 'Badge Check' },
  { id: 'banknote', icon: Banknote, label: 'Banknote' },
  { id: 'barcode', icon: Barcode, label: 'Barcode' },
  { id: 'bell', icon: Bell, label: 'Bell' },
  { id: 'book', icon: Book, label: 'Book' },
  { id: 'bookmark', icon: Bookmark, label: 'Bookmark' },
  { id: 'bot', icon: Bot, label: 'Bot' },
  { id: 'brain', icon: Brain, label: 'Brain' },
  { id: 'brush', icon: Brush, label: 'Brush' },
  { id: 'bug', icon: Bug, label: 'Bug' },
  { id: 'camera', icon: Camera, label: 'Camera' },
  { id: 'clipboard', icon: Clipboard, label: 'Clipboard' },
  { id: 'cloud', icon: Cloud, label: 'Cloud' },
  { id: 'code', icon: Code, label: 'Code' },
  { id: 'cpu', icon: Cpu, label: 'CPU' },
  { id: 'database', icon: Database, label: 'Database' },
  { id: 'file-text', icon: FileText, label: 'File Text' },
  { id: 'globe', icon: Globe, label: 'Globe' },
  { id: 'image', icon: Image, label: 'Image' },
  { id: 'key', icon: Key, label: 'Key' },
  { id: 'layers', icon: Layers, label: 'Layers' },
  { id: 'list', icon: List, label: 'List' },
  { id: 'lock', icon: Lock, label: 'Lock' },
  { id: 'mail', icon: Mail, label: 'Mail' },
  { id: 'map-pin', icon: MapPin, label: 'Map Pin' },
  { id: 'message-circle', icon: MessageCircle, label: 'Message' },
  { id: 'mic', icon: Mic, label: 'Microphone' },
  { id: 'monitor', icon: Monitor, label: 'Monitor' },
  { id: 'moon', icon: Moon, label: 'Moon' },
  { id: 'music', icon: Music, label: 'Music' },
  { id: 'palette', icon: Palette, label: 'Palette' },
  { id: 'package', icon: Package, label: 'Package' },
  { id: 'pen-tool', icon: PenTool, label: 'Pen Tool' },
  { id: 'phone', icon: Phone, label: 'Phone' },
  { id: 'play', icon: Play, label: 'Play' },
  { id: 'puzzle', icon: Puzzle, label: 'Puzzle' },
  { id: 'search', icon: Search, label: 'Search' },
  { id: 'shield', icon: Shield, label: 'Shield' },
  { id: 'shopping-cart', icon: ShoppingCart, label: 'Shopping Cart' },
  { id: 'sun', icon: Sun, label: 'Sun' },
  { id: 'tag', icon: Tag, label: 'Tag' },
  { id: 'target', icon: Target, label: 'Target' },
  { id: 'terminal', icon: Terminal, label: 'Terminal' },
  { id: 'timer', icon: Timer, label: 'Timer' },
  { id: 'star', icon: Star, label: 'Star' },
  { id: 'heart', icon: Heart, label: 'Heart' },
  { id: 'user', icon: User, label: 'User' },
  { id: 'users', icon: Users, label: 'Users' },
  { id: 'wand-2', icon: Wand2, label: 'Wand' },
  { id: 'wrench', icon: Wrench, label: 'Wrench' },
  { id: 'zap', icon: Zap, label: 'Lightning' },
  { id: 'gift', icon: Gift, label: 'Gift' },
  { id: 'truck', icon: Truck, label: 'Truck' },
  { id: 'dollar-sign', icon: DollarSign, label: 'Dollar' },
  { id: 'award', icon: Award, label: 'Award' },
  { id: 'box', icon: Box, label: 'Box' },
  { id: 'sparkles', icon: Sparkles, label: 'Sparkles' },
  { id: 'pin', icon: Pin, label: 'Pin' },
] as const;

export type IconLibraryId = (typeof ICON_LIBRARY)[number]['id'];

export const ICON_LIBRARY_MAP: Record<string, LucideIcon> = Object.fromEntries(
  ICON_LIBRARY.map(({ id, icon }: { id: string; icon: LucideIcon }) => [id, icon])
) as Record<string, LucideIcon>;
