import type { PatternLicense, PatternProduct } from './types';

const licenses = (base: number): PatternLicense[] => [
  {
    id: 'personal',
    label: 'Personal',
    price: base,
    summary: 'Single buyer, non-commercial downloads.',
  },
  {
    id: 'studio',
    label: 'Studio',
    price: Math.round(base * 1.8),
    summary: 'Commercial work for one studio or client.',
  },
  {
    id: 'extended',
    label: 'Extended',
    price: Math.round(base * 3.4),
    summary: 'Products, packaging, and broad campaign use.',
  },
];

export const DEFAULT_PATTERN_PRODUCTS: PatternProduct[] = [
  {
    id: 'pat-canal-grid',
    slug: 'canal-grid',
    name: 'Canal Grid',
    collection: 'Amsterdam Systems',
    edition: 'MBD-P01',
    category: 'architecture',
    description: 'A measured architectural repeat built from quay lines, thresholds, and small calibration marks.',
    tags: ['grid', 'minimal', 'architectural'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '240 x 240',
    fileSize: '3.8 MB',
    updatedAt: '2026-05-01T09:00:00.000Z',
    featured: true,
    status: 'published',
    preview: { motif: 'grid', paper: '#F9F8F5', ink: '#1A1918', accent: '#857A72', density: 5 },
    defaultLicense: 'studio',
    licenses: licenses(38),
  },
  {
    id: 'pat-quiet-arches',
    slug: 'quiet-arches',
    name: 'Quiet Arches',
    collection: 'Amsterdam Systems',
    edition: 'MBD-P02',
    category: 'interior',
    description: 'A calm arch rhythm for interior surfaces, packaging papers, and editorial page furniture.',
    tags: ['arches', 'interior', 'soft geometry'],
    formats: ['SVG', 'PDF', 'AI', 'EPS'],
    repeatSize: '300 x 300',
    fileSize: '4.1 MB',
    updatedAt: '2026-04-26T09:00:00.000Z',
    featured: true,
    status: 'published',
    preview: { motif: 'arches', paper: '#F2F1ED', ink: '#1A1918', accent: '#C6C1B8', density: 4 },
    defaultLicense: 'studio',
    licenses: licenses(42),
  },
  {
    id: 'pat-cut-stone',
    slug: 'cut-stone',
    name: 'Cut Stone',
    collection: 'Material Notes',
    edition: 'MBD-P03',
    category: 'architecture',
    description: 'Irregular blocks and fine construction joints drawn for large scale surface applications.',
    tags: ['stone', 'facade', 'modular'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '360 x 240',
    fileSize: '5.2 MB',
    updatedAt: '2026-04-18T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'cut-stone', paper: '#ECEAE6', ink: '#1A1918', accent: '#9C978F', density: 5 },
    defaultLicense: 'studio',
    licenses: licenses(46),
  },
  {
    id: 'pat-botanical-trace',
    slug: 'botanical-trace',
    name: 'Botanical Trace',
    collection: 'Garden Index',
    edition: 'MBD-P04',
    category: 'botanical',
    description: 'Fine leaf contours and dotted stems, kept sparse enough for stationery and textile repeats.',
    tags: ['botanical', 'linework', 'organic'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '260 x 320',
    fileSize: '6.4 MB',
    updatedAt: '2026-05-10T09:00:00.000Z',
    featured: true,
    status: 'published',
    preview: { motif: 'botanical-trace', paper: '#F9F8F5', ink: '#1A1918', accent: '#857A72', density: 6 },
    defaultLicense: 'studio',
    licenses: licenses(48),
  },
  {
    id: 'pat-paper-fold',
    slug: 'paper-fold',
    name: 'Paper Fold',
    collection: 'Material Notes',
    edition: 'MBD-P05',
    category: 'editorial',
    description: 'Subtle diagonal folds and crop marks for book covers, posters, and presentation systems.',
    tags: ['editorial', 'paper', 'diagonal'],
    formats: ['SVG', 'PDF', 'AI', 'EPS'],
    repeatSize: '420 x 280',
    fileSize: '2.9 MB',
    updatedAt: '2026-03-29T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'paper-fold', paper: '#F2F1ED', ink: '#1A1918', accent: '#DEDAD4', density: 4 },
    defaultLicense: 'studio',
    licenses: licenses(34),
  },
  {
    id: 'pat-metro-joinery',
    slug: 'metro-joinery',
    name: 'Metro Joinery',
    collection: 'Measured City',
    edition: 'MBD-P06',
    category: 'interior',
    description: 'A joinery-led tile repeat with panel breaks, countersunk dots, and quiet directional seams.',
    tags: ['tile', 'joinery', 'interior'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '320 x 320',
    fileSize: '4.7 MB',
    updatedAt: '2026-02-20T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'tile', paper: '#F9F8F5', ink: '#1A1918', accent: '#857A72', density: 4 },
    defaultLicense: 'studio',
    licenses: licenses(44),
  },
  {
    id: 'pat-soft-weave',
    slug: 'soft-weave',
    name: 'Soft Weave',
    collection: 'Textile Studies',
    edition: 'MBD-P07',
    category: 'textile',
    description: 'Alternating woven lanes for fabric mockups, woven labels, and muted digital backgrounds.',
    tags: ['textile', 'woven', 'linear'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '280 x 280',
    fileSize: '3.5 MB',
    updatedAt: '2026-05-12T09:00:00.000Z',
    featured: true,
    status: 'published',
    preview: { motif: 'weave', paper: '#ECEAE6', ink: '#1A1918', accent: '#9C978F', density: 6 },
    defaultLicense: 'studio',
    licenses: licenses(40),
  },
  {
    id: 'pat-line-garden',
    slug: 'line-garden',
    name: 'Line Garden',
    collection: 'Garden Index',
    edition: 'MBD-P08',
    category: 'botanical',
    description: 'A denser garden construction with mirrored stems and small registration flowers.',
    tags: ['botanical', 'garden', 'repeat'],
    formats: ['SVG', 'PDF', 'AI', 'EPS'],
    repeatSize: '300 x 420',
    fileSize: '7.1 MB',
    updatedAt: '2026-04-03T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'botanical-trace', paper: '#F2F1ED', ink: '#1A1918', accent: '#6A6560', density: 8 },
    defaultLicense: 'studio',
    licenses: licenses(52),
  },
  {
    id: 'pat-dot-constellation',
    slug: 'dot-constellation',
    name: 'Dot Constellation',
    collection: 'Measured City',
    edition: 'MBD-P09',
    category: 'editorial',
    description: 'A map-like constellation pattern with measured connections and small reference points.',
    tags: ['dots', 'map', 'editorial'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '260 x 260',
    fileSize: '2.7 MB',
    updatedAt: '2026-01-28T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'constellation', paper: '#F9F8F5', ink: '#1A1918', accent: '#857A72', density: 6 },
    defaultLicense: 'studio',
    licenses: licenses(36),
  },
  {
    id: 'pat-waterline',
    slug: 'waterline',
    name: 'Waterline',
    collection: 'Amsterdam Systems',
    edition: 'MBD-P10',
    category: 'textile',
    description: 'Low contrast wave paths designed for subtle cloth, wrapping paper, and tiled backgrounds.',
    tags: ['wave', 'water', 'textile'],
    formats: ['SVG', 'PDF', 'AI', 'EPS'],
    repeatSize: '420 x 220',
    fileSize: '3.2 MB',
    updatedAt: '2026-02-08T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'wave', paper: '#ECEAE6', ink: '#1A1918', accent: '#9C978F', density: 5 },
    defaultLicense: 'studio',
    licenses: licenses(32),
  },
  {
    id: 'pat-terrazzo-register',
    slug: 'terrazzo-register',
    name: 'Terrazzo Register',
    collection: 'Material Notes',
    edition: 'MBD-P11',
    category: 'interior',
    description: 'Large flecks, small index marks, and construction dots for decorative surfaces.',
    tags: ['terrazzo', 'surface', 'interior'],
    formats: ['SVG', 'PDF', 'AI', 'EPS', 'PNG'],
    repeatSize: '340 x 340',
    fileSize: '5.9 MB',
    updatedAt: '2026-03-12T09:00:00.000Z',
    featured: false,
    status: 'published',
    preview: { motif: 'terrazzo', paper: '#F9F8F5', ink: '#1A1918', accent: '#857A72', density: 7 },
    defaultLicense: 'studio',
    licenses: licenses(45),
  },
  {
    id: 'pat-villa-tiles',
    slug: 'villa-tiles',
    name: 'Villa Tiles',
    collection: 'Measured City',
    edition: 'MBD-P12',
    category: 'architecture',
    description: 'A square tile field interrupted by offset thresholds and narrow service marks.',
    tags: ['tile', 'architectural', 'square'],
    formats: ['SVG', 'PDF', 'AI', 'EPS'],
    repeatSize: '280 x 280',
    fileSize: '3.6 MB',
    updatedAt: '2026-04-30T09:00:00.000Z',
    featured: true,
    status: 'published',
    preview: { motif: 'tile', paper: '#F2F1ED', ink: '#1A1918', accent: '#C6C1B8', density: 6 },
    defaultLicense: 'studio',
    licenses: licenses(43),
  },
];
