export const KANGUR_DUELS_DEFAULT_LOBBY_LIMIT = 12;
export const KANGUR_DUELS_DEFAULT_OPPONENTS_LIMIT = 8;
export const KANGUR_DUELS_DEFAULT_SEARCH_LIMIT = 8;
export const KANGUR_DUELS_SEARCH_MIN_CHARS = 2;
