import type { KangurGameDefinition } from '@/shared/contracts/kangur-games';

import {
  createAgenticInlineGame,
  createAgenticLessonVariantGame,
  createVariant,
  withAgenticTags,
} from './factories';

export const KANGUR_GROWN_UP_GAMES: readonly KangurGameDefinition[] = [
  createAgenticInlineGame({
    id: 'agentic_brief_builder',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4'],
    label: 'Brief Builder',
    title: 'Brief Builder',
    emoji: '🧾',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('brief', 'sorting', 'foundations'),
    sortOrder: 2000,
  }),
  createAgenticInlineGame({
    id: 'agentic_loop_sketch',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4'],
    label: 'Loop Sketch',
    title: 'Loop Sketch',
    emoji: '🔁',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('workflow', 'drawing', 'foundations'),
    sortOrder: 2010,
  }),
  createAgenticInlineGame({
    id: 'agentic_contract_box',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4'],
    label: 'Contract Box',
    title: 'Contract Box',
    emoji: '📦',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('contract', 'drawing', 'brief'),
    sortOrder: 2020,
  }),
  createAgenticInlineGame({
    id: 'agentic_fit_scanner',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_fit'],
    label: 'Fit Scanner',
    title: 'Fit Scanner',
    emoji: '🧭',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('fit', 'triage', 'scoping'),
    sortOrder: 2030,
  }),
  {
    id: 'agentic_surface_match',
    engineId: 'classification-engine',
    subject: 'agentic_coding',
    ageGroup: 'grown_ups',
    lessonComponentIds: ['agentic_coding_codex_5_4_surfaces'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Surface Match',
    title: 'Surface Match',
    description:
      'Surface Match is cataloged as a shared game so its engine can evolve independently from the lesson flow that routes scenarios across Codex surfaces.',
    emoji: '🧩',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: withAgenticTags('surfaces', 'routing', 'selection'),
    variants: [
      createVariant({
        id: 'agentic_surface_match.lesson-inline',
        label: 'Lesson inline',
        title: 'Surface Match in lessons',
        description:
          'Inline lesson variant for Surface Match, exposed through the shared games library.',
        surface: 'lesson_inline',
      }),
      createVariant({
        id: 'agentic_surface_match.lesson-stage',
        label: 'Lesson variant',
        title: 'Surface Match as a lesson variant',
        description:
          'Lesson-facing variant for Surface Match, shared between the Codex surfaces lesson flow and the games library.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'agentic_surface_match.library-preview',
        label: 'Library preview',
        title: 'Surface Match preview',
        description: 'Catalog preview for Surface Match in the shared games library.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'agentic_surface_match.game-screen',
        label: 'Game screen',
        title: 'Surface Match fullscreen',
        description: 'Launches Surface Match through the shared standalone game runtime.',
        surface: 'game_screen',
        launchableRuntimeId: 'agentic_surface_match_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 2040,
  },
  createAgenticInlineGame({
    id: 'agentic_surface_arrow',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_surfaces'],
    label: 'Surface Arrow',
    title: 'Surface Arrow',
    emoji: '➡️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('surfaces', 'diagram', 'flow'),
    sortOrder: 2050,
  }),
  createAgenticInlineGame({
    id: 'agentic_operating_loop',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_operating_model'],
    label: 'Operating Loop',
    title: 'Operating Loop',
    emoji: '🔄',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('workflow', 'drawing', 'loop'),
    sortOrder: 2060,
  }),
  createAgenticInlineGame({
    id: 'agentic_prompt_trim',
    engineId: 'token-trim-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_prompting'],
    label: 'Prompt Trim',
    title: 'Prompt Trim',
    emoji: '✂️',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    tags: withAgenticTags('prompting', 'tokens', 'editing'),
    sortOrder: 2070,
  }),
  createAgenticLessonVariantGame({
    id: 'agentic_prompt_trim_stage',
    engineId: 'token-trim-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_prompting'],
    label: 'Prompt Trim Game',
    title: 'Prompt Trim Game',
    emoji: '🪄',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'agentic_prompt_trim_quiz',
    tags: withAgenticTags('prompting', 'trim', 'focus'),
    sortOrder: 2080,
  }),
  createAgenticInlineGame({
    id: 'agentic_response_flow',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_responses'],
    label: 'Response Flow',
    title: 'Response Flow',
    emoji: '📡',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('responses', 'sequence', 'audit'),
    sortOrder: 2090,
  }),
  createAgenticInlineGame({
    id: 'agentic_agents_map',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_agents_md'],
    label: 'AGENTS.md Map',
    title: 'AGENTS.md Map',
    emoji: '🗂️',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('agents-md', 'sorting', 'documentation'),
    sortOrder: 2100,
  }),
  createAgenticInlineGame({
    id: 'agentic_approval_ladder',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_approvals'],
    label: 'Approval Ladder',
    title: 'Approval Ladder',
    emoji: '🪜',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('approvals', 'sequence', 'safety'),
    sortOrder: 2110,
  }),
  createAgenticInlineGame({
    id: 'agentic_approval_tiers_chart',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_approvals'],
    label: 'Approval Tiers Chart',
    title: 'Approval Tiers Chart',
    emoji: '🛡️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('approvals', 'diagram', 'risk'),
    sortOrder: 2120,
  }),
  createAgenticLessonVariantGame({
    id: 'agentic_approval_gate',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_approvals'],
    label: 'Approval Gate',
    title: 'Approval Gate',
    emoji: '🚦',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    launchableRuntimeId: 'agentic_approval_gate_quiz',
    tags: withAgenticTags('approvals', 'gating', 'safety'),
    sortOrder: 2130,
  }),
  createAgenticInlineGame({
    id: 'agentic_safety_gate',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_safety'],
    label: 'Safety Gate',
    title: 'Safety Gate',
    emoji: '🔒',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('safety', 'triage', 'risk'),
    sortOrder: 2140,
  }),
  createAgenticInlineGame({
    id: 'agentic_config_stack',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_config_layers'],
    label: 'Config Stack',
    title: 'Config Stack',
    emoji: '⚙️',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('config', 'sequence', 'profiles'),
    sortOrder: 2150,
  }),
  createAgenticInlineGame({
    id: 'agentic_layer_sketch',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_config_layers'],
    label: 'Layer Sketch',
    title: 'Layer Sketch',
    emoji: '🧱',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('config', 'diagram', 'layers'),
    sortOrder: 2160,
  }),
  createAgenticInlineGame({
    id: 'agentic_rules_triage',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_rules'],
    label: 'Rules Triage',
    title: 'Rules Triage',
    emoji: '📏',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('rules', 'triage', 'policy'),
    sortOrder: 2170,
  }),
  createAgenticInlineGame({
    id: 'agentic_citation_check',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_web_citations'],
    label: 'Citation Check',
    title: 'Citation Check',
    emoji: '🌐',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('web', 'citations', 'verification'),
    sortOrder: 2180,
  }),
  createAgenticInlineGame({
    id: 'agentic_tooling_match',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_tooling'],
    label: 'Tooling Match',
    title: 'Tooling Match',
    emoji: '🧰',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('tooling', 'selection', 'workflow'),
    sortOrder: 2190,
  }),
  createAgenticInlineGame({
    id: 'agentic_response_contract',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_response_contract'],
    label: 'Response Contract',
    title: 'Response Contract',
    emoji: '📋',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('response', 'sequence', 'contract'),
    sortOrder: 2200,
  }),
  createAgenticInlineGame({
    id: 'agentic_docs_hierarchy',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_ai_documentation'],
    label: 'Docs Hierarchy',
    title: 'Docs Hierarchy',
    emoji: '📚',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('documentation', 'ordering', 'hierarchy'),
    sortOrder: 2210,
  }),
  createAgenticInlineGame({
    id: 'agentic_delegation_loop',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_delegation'],
    label: 'Delegation Loop',
    title: 'Delegation Loop',
    emoji: '🤝',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('delegation', 'sequence', 'parallelism'),
    sortOrder: 2220,
  }),
  createAgenticInlineGame({
    id: 'agentic_model_routing',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_models'],
    label: 'Model Routing',
    title: 'Model Routing',
    emoji: '🧠',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('models', 'routing', 'reasoning'),
    sortOrder: 2230,
  }),
  createAgenticLessonVariantGame({
    id: 'agentic_reasoning_router',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_models'],
    label: 'Reasoning Router',
    title: 'Reasoning Router',
    emoji: '🎛️',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    launchableRuntimeId: 'agentic_reasoning_router_quiz',
    tags: withAgenticTags('models', 'routing', 'classification'),
    sortOrder: 2240,
  }),
  createAgenticInlineGame({
    id: 'agentic_ide_cli_flow',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_cli_ide'],
    label: 'IDE to CLI Flow',
    title: 'IDE to CLI Flow',
    emoji: '🖥️',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('cli', 'ide', 'workflow'),
    sortOrder: 2250,
  }),
  createAgenticInlineGame({
    id: 'agentic_worktree_split',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_app_workflows'],
    label: 'Worktree Split',
    title: 'Worktree Split',
    emoji: '🌿',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('app', 'worktrees', 'parallelism'),
    sortOrder: 2260,
  }),
  createAgenticInlineGame({
    id: 'agentic_skill_contract',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_skills'],
    label: 'Skill Contract',
    title: 'Skill Contract',
    emoji: '🛠️',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('skills', 'sequence', 'contracts'),
    sortOrder: 2270,
  }),
  createAgenticInlineGame({
    id: 'agentic_mcp_roles',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_mcp_integrations'],
    label: 'MCP Roles',
    title: 'MCP Roles',
    emoji: '🔌',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('mcp', 'roles', 'integrations'),
    sortOrder: 2280,
  }),
  createAgenticInlineGame({
    id: 'agentic_automation_cadence',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_automations'],
    label: 'Automation Cadence',
    title: 'Automation Cadence',
    emoji: '⏱️',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('automations', 'sequence', 'cadence'),
    sortOrder: 2290,
  }),
  createAgenticInlineGame({
    id: 'agentic_state_scale',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_state_scale'],
    label: 'State and Scale',
    title: 'State and Scale',
    emoji: '📈',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('state', 'scale', 'sequence'),
    sortOrder: 2300,
  }),
  createAgenticInlineGame({
    id: 'agentic_evidence_pack',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_review'],
    label: 'Evidence Pack',
    title: 'Evidence Pack',
    emoji: '✅',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('review', 'verification', 'evidence'),
    sortOrder: 2310,
  }),
  createAgenticInlineGame({
    id: 'agentic_milestone_flow',
    engineId: 'diagram-sketch-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_long_horizon'],
    label: 'Milestone Flow',
    title: 'Milestone Flow',
    emoji: '🗺️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: withAgenticTags('milestones', 'drawing', 'planning'),
    sortOrder: 2320,
  }),
  createAgenticInlineGame({
    id: 'agentic_do_dont',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_dos_donts'],
    label: 'Do and Don’t',
    title: 'Do and Don’t',
    emoji: '⚖️',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('policy', 'sorting', 'behavior'),
    sortOrder: 2330,
  }),
  createAgenticInlineGame({
    id: 'agentic_delegation_clarity',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_non_engineers'],
    label: 'Delegation Clarity',
    title: 'Delegation Clarity',
    emoji: '💬',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('delegation', 'clarity', 'communication'),
    sortOrder: 2340,
  }),
  createAgenticInlineGame({
    id: 'agentic_prompt_patterns',
    engineId: 'classification-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_prompt_patterns'],
    label: 'Prompt Patterns',
    title: 'Prompt Patterns',
    emoji: '🪄',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: withAgenticTags('prompting', 'patterns', 'selection'),
    sortOrder: 2350,
  }),
  createAgenticInlineGame({
    id: 'agentic_rollout_stages',
    engineId: 'pattern-sequence-engine',
    lessonComponentIds: ['agentic_coding_codex_5_4_rollout'],
    label: 'Rollout Stages',
    title: 'Rollout Stages',
    emoji: '🚀',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    tags: withAgenticTags('rollout', 'sequence', 'teams'),
    sortOrder: 2360,
  }),
];
