import type { KangurGameDefinition } from '@/shared/contracts/kangur-games';

import {
  createSixYearOldInlineGame,
  createSixYearOldStageGame,
} from './factories';

export const KANGUR_SIX_YEAR_OLD_GAMES: readonly KangurGameDefinition[] = [
  createSixYearOldStageGame({
    id: 'art_color_harmony_studio',
    engineId: 'color-harmony-engine',
    subject: 'art',
    lessonComponentIds: ['art_colors_harmony'],
    label: 'Color harmony studio',
    title: 'Color Harmony Studio',
    emoji: '🎨',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'art_color_harmony_studio_lesson_stage',
    tags: ['art', 'colors', 'warm-cool'],
    sortOrder: 55,
  }),
  createSixYearOldInlineGame({
    id: 'alphabet_trace_letters',
    engineId: 'symbol-tracing-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_basics'],
    label: 'Trace the letters',
    title: 'Trace the Letters',
    emoji: '✍️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: ['alphabet', 'tracing', 'letters'],
    sortOrder: 10,
  }),
  createSixYearOldInlineGame({
    id: 'alphabet_copy_letters',
    engineId: 'symbol-tracing-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_copy'],
    label: 'Copy the letters',
    title: 'Copy the Letters',
    emoji: '📝',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: ['alphabet', 'copying', 'handwriting'],
    sortOrder: 20,
  }),
  createSixYearOldStageGame({
    id: 'alphabet_first_words',
    engineId: 'letter-match-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_words'],
    label: 'First words',
    title: 'First Words',
    emoji: '📖',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'alphabet_first_words_lesson_stage',
    tags: ['alphabet', 'words', 'matching'],
    sortOrder: 30,
  }),
  createSixYearOldStageGame({
    id: 'alphabet_letter_matching',
    engineId: 'letter-match-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_matching'],
    label: 'Letter matching',
    title: 'Letter Matching',
    emoji: '🔤',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'alphabet_letter_matching_lesson_stage',
    tags: ['alphabet', 'matching', 'pairs'],
    sortOrder: 40,
  }),
  createSixYearOldStageGame({
    id: 'alphabet_letter_order',
    engineId: 'pattern-sequence-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_sequence'],
    label: 'Letter order',
    title: 'Letter Order',
    emoji: '🧠',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'alphabet_letter_order_lesson_stage',
    tags: ['alphabet', 'sequence', 'order'],
    sortOrder: 50,
  }),
  createSixYearOldStageGame({
    id: 'art_shape_rotation_puzzle',
    engineId: 'shape-recognition-engine',
    subject: 'art',
    lessonComponentIds: ['art_shapes_basic'],
    label: 'Shape rotation puzzle',
    title: 'Shape Rotation Puzzle',
    emoji: '🌀',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'art_shape_rotation_puzzle_lesson_stage',
    tags: ['art', 'shapes', 'rotation'],
    sortOrder: 60,
  }),
  createSixYearOldStageGame({
    id: 'geometry_shape_spotter',
    engineId: 'shape-recognition-engine',
    subject: 'geometry',
    lessonComponentIds: ['geometry_shape_recognition'],
    label: 'Shape spotter',
    title: 'Shape Spotter',
    emoji: '🔷',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'geometry_shape_spotter_lesson_stage',
    tags: ['geometry', 'shapes', 'recognition'],
    sortOrder: 70,
  }),
  createSixYearOldStageGame({
    id: 'geometry_shape_drawing',
    engineId: 'shape-drawing-engine',
    subject: 'geometry',
    lessonComponentIds: ['geometry_shape_recognition'],
    label: 'Shape drawing',
    title: 'Shape Drawing',
    emoji: '✏️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    lessonStageRuntimeId: 'geometry_shape_drawing_lesson_stage',
    tags: ['geometry', 'drawing', 'shapes'],
    sortOrder: 80,
  }),
  createSixYearOldStageGame({
    id: 'music_melody_repeat',
    engineId: 'melody-repeat-engine',
    subject: 'music',
    lessonComponentIds: ['music_diatonic_scale'],
    label: 'Melody repeat',
    title: 'Melody Repeat',
    emoji: '🎵',
    mechanic: 'rhythm',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'music_melody_repeat_lesson_stage',
    tags: ['music', 'melody', 'memory'],
    sortOrder: 90,
  }),
  createSixYearOldStageGame({
    id: 'music_piano_roll_free_play',
    engineId: 'piano-roll-engine',
    subject: 'music',
    lessonComponentIds: ['music_diatonic_scale'],
    label: 'Piano roll free play',
    title: 'Piano Roll Free Play',
    emoji: '🎹',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    lessonStageRuntimeId: 'music_piano_roll_free_play_lesson_stage',
    tags: ['music', 'keyboard', 'free-play'],
    sortOrder: 95,
  }),
];
