import type { KangurGameDefinition } from '@/shared/contracts/kangur-games';

import {
  createSixYearOldInlineGame,
  createSixYearOldLessonVariantGame,
} from './factories';
import {
  KANGUR_MUSIC_PIANO_ROLL_LESSON_VARIANT_GAME_CONFIGS,
} from '../music-piano-roll-contract';

export const KANGUR_SIX_YEAR_OLD_GAMES: readonly KangurGameDefinition[] = [
  createSixYearOldLessonVariantGame({
    id: 'art_color_harmony_studio',
    engineId: 'color-harmony-engine',
    subject: 'art',
    lessonComponentIds: ['art_colors_harmony'],
    label: 'Color harmony studio',
    title: 'Color Harmony Studio',
    emoji: '🎨',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'art_color_harmony_quiz',
    tags: ['art', 'colors', 'warm-cool'],
    sortOrder: 55,
  }),
  createSixYearOldInlineGame({
    id: 'alphabet_trace_letters',
    engineId: 'symbol-tracing-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_basics'],
    label: 'Trace the letters',
    title: 'Trace the Letters',
    emoji: '✍️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: ['alphabet', 'tracing', 'letters'],
    sortOrder: 10,
  }),
  createSixYearOldInlineGame({
    id: 'alphabet_copy_letters',
    engineId: 'symbol-tracing-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_copy'],
    label: 'Copy the letters',
    title: 'Copy the Letters',
    emoji: '📝',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: ['alphabet', 'copying', 'handwriting'],
    sortOrder: 20,
  }),
  createSixYearOldLessonVariantGame({
    id: 'alphabet_first_words',
    engineId: 'letter-match-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_words'],
    label: 'First words',
    title: 'First Words',
    emoji: '📖',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'alphabet_first_words_quiz',
    tags: ['alphabet', 'words', 'matching'],
    sortOrder: 30,
  }),
  createSixYearOldLessonVariantGame({
    id: 'alphabet_letter_matching',
    engineId: 'letter-match-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_matching'],
    label: 'Letter matching',
    title: 'Letter Matching',
    emoji: '🔤',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'alphabet_letter_matching_quiz',
    tags: ['alphabet', 'matching', 'pairs'],
    sortOrder: 40,
  }),
  createSixYearOldLessonVariantGame({
    id: 'alphabet_letter_order',
    engineId: 'pattern-sequence-engine',
    subject: 'alphabet',
    lessonComponentIds: ['alphabet_sequence'],
    label: 'Letter order',
    title: 'Letter Order',
    emoji: '🧠',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    launchableRuntimeId: 'alphabet_letter_order_quiz',
    tags: ['alphabet', 'sequence', 'order'],
    sortOrder: 50,
  }),
  createSixYearOldLessonVariantGame({
    id: 'art_shape_rotation_puzzle',
    engineId: 'shape-recognition-engine',
    subject: 'art',
    lessonComponentIds: ['art_shapes_basic'],
    label: 'Shape rotation puzzle',
    title: 'Shape Rotation Puzzle',
    emoji: '🌀',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'art_shape_rotation_quiz',
    tags: ['art', 'shapes', 'rotation'],
    sortOrder: 60,
  }),
  createSixYearOldLessonVariantGame({
    id: 'geometry_shape_spotter',
    engineId: 'shape-recognition-engine',
    subject: 'geometry',
    lessonComponentIds: ['geometry_shape_recognition'],
    label: 'Shape spotter',
    title: 'Shape Spotter',
    emoji: '🔷',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    launchableRuntimeId: 'geometry_shape_spotter_quiz',
    tags: ['geometry', 'shapes', 'recognition'],
    sortOrder: 70,
  }),
  createSixYearOldLessonVariantGame({
    id: 'geometry_shape_drawing',
    engineId: 'shape-drawing-engine',
    subject: 'geometry',
    lessonComponentIds: ['geometry_shape_recognition'],
    label: 'Shape drawing',
    title: 'Shape Drawing',
    emoji: '✏️',
    mechanic: 'drawing',
    interactionMode: 'draw',
    tags: ['geometry', 'drawing', 'shapes'],
    sortOrder: 80,
  }),
  ...KANGUR_MUSIC_PIANO_ROLL_LESSON_VARIANT_GAME_CONFIGS.map((config) =>
    createSixYearOldLessonVariantGame({
      ...config,
      lessonComponentIds: [...config.lessonComponentIds],
      tags: [...config.tags],
    })
  ),
];
