import path from 'node:path';

export const COMPONENT_FAMILY_RE =
  /(Modal|Panel|Table|List|Form|Picker|Filter|Toolbar|Header|Sidebar|Tabs|Tab|Card|Dialog|Drawer|Section|Settings)\.tsx$/;

export const GENERIC_FILE_NAMES = new Set([
  'index.tsx',
  'page.tsx',
  'layout.tsx',
  'error.tsx',
  'not-found.tsx',
  'loading.tsx',
  'template.tsx',
  'ClientPage.tsx',
]);

export const NON_CONSOLIDATION_NAME_RE = /(Context|Provider)\.tsx$/;

export const CLUSTER_FAMILY_ALLOWLIST = new Set([
  'Modal',
  'Panel',
  'Table',
  'List',
  'Form',
  'Picker',
  'Filter',
  'Toolbar',
  'Header',
  'Sidebar',
  'Tabs',
  'Tab',
  'Card',
  'Dialog',
  'Drawer',
  'Section',
  'Settings',
]);

export const STOP_WORDS = new Set([
  'const',
  'function',
  'return',
  'true',
  'false',
  'null',
  'undefined',
  'from',
  'import',
  'export',
  'default',
  'class',
  'classname',
  'react',
  'props',
  'children',
  'type',
  'interface',
  'string',
  'number',
  'boolean',
  'void',
  'async',
  'await',
  'this',
  'that',
  'with',
  'without',
  'for',
  'while',
  'case',
  'break',
  'continue',
  'switch',
  'value',
  'values',
  'label',
  'labels',
  'items',
  'item',
  'open',
  'close',
  'set',
  'get',
  'then',
  'else',
  'new',
  'use',
  'data',
  'state',
  'context',
  'option',
  'options',
  'button',
  'input',
  'select',
  'dialog',
  'modal',
  'panel',
  'table',
  'card',
  'header',
  'body',
  'footer',
  'div',
  'span',
  'grid',
  'flex',
  'text',
  'size',
  'style',
  'props',
  'tsx',
  'tsxs',
]);

export const THIN_RE_EXPORT_RE =
  /^export\s+(?:\{[\s\S]*?\}\s+from\s+['"][^'"]+['"]|(?:\*\s+from\s+['"][^'"]+['"]))\s*;?$/;

export const FAMILY_WEIGHTS = {
  Modal: 1.4,
  Dialog: 1.4,
  Drawer: 1.35,
  Panel: 1.35,
  Filter: 1.3,
  Picker: 1.2,
  Form: 1.15,
  Table: 1.1,
  List: 1.1,
  Toolbar: 1.05,
  Header: 1,
  Sidebar: 1,
  Tabs: 1,
  Tab: 1,
  Card: 0.95,
  Section: 0.95,
  Settings: 1,
  Unknown: 0.85,
};

export const METHOD_WEIGHTS = {
  token_similarity: 1.3,
  prop_signature: 1.2,
  duplicate_name: 1.1,
};

export const toPosix = (value) => value.split(path.sep).join('/');
