import { z } from 'zod';

/**
 * CMS Theme Settings DTOs
 */

export const colorSchemeColorsSchema = z.object({
  background: z.string(),
  surface: z.string(),
  text: z.string(),
  accent: z.string(),
  border: z.string(),
});

export type ColorSchemeColorsDto = z.infer<typeof colorSchemeColorsSchema>;
export type ColorSchemeColors = ColorSchemeColorsDto;

export const colorSchemeSchema = z.object({
  id: z.string(),
  name: z.string(),
  colors: colorSchemeColorsSchema,
});

export type ColorSchemeDto = z.infer<typeof colorSchemeSchema>;
export type ColorScheme = ColorSchemeDto;

export const themeSettingsSchema = z.object({
  // Colors
  primaryColor: z.string(),
  secondaryColor: z.string(),
  accentColor: z.string(),
  backgroundColor: z.string(),
  surfaceColor: z.string(),
  textColor: z.string(),
  mutedTextColor: z.string(),
  borderColor: z.string(),
  errorColor: z.string(),
  successColor: z.string(),
  colorSchemes: z.array(colorSchemeSchema),
  activeColorSchemeId: z.string(),
  // Typography
  headingFont: z.string(),
  bodyFont: z.string(),
  baseSize: z.number(),
  headingWeight: z.string(),
  bodyWeight: z.string(),
  headingSizeScale: z.number(),
  bodySizeScale: z.number(),
  lineHeight: z.number(),
  headingLineHeight: z.number(),
  // Layout
  maxContentWidth: z.number(),
  gridGutter: z.number(),
  sectionSpacing: z.number(),
  containerPadding: z.number(),
  borderRadius: z.number(),
  pagePaddingTop: z.number(),
  pagePaddingRight: z.number(),
  pagePaddingBottom: z.number(),
  pagePaddingLeft: z.number(),
  pageMarginTop: z.number(),
  pageMarginRight: z.number(),
  pageMarginBottom: z.number(),
  pageMarginLeft: z.number(),
  pagePadding: z.number(),
  pageMargin: z.number(),
  fullWidth: z.boolean(),
  // Animations
  enableAnimations: z.boolean(),
  animationDuration: z.number(),
  animationEasing: z.string(),
  scrollReveal: z.boolean(),
  hoverEffect: z.string(),
  hoverScale: z.number(),
  // Buttons
  btnPaddingX: z.number(),
  btnPaddingY: z.number(),
  btnFontSize: z.number(),
  btnFontWeight: z.string(),
  btnRadius: z.number(),
  btnPrimaryBg: z.string(),
  btnPrimaryText: z.string(),
  btnSecondaryBg: z.string(),
  btnSecondaryText: z.string(),
  btnOutlineBorder: z.string(),
  // Button Border
  btnBorderWidth: z.number(),
  btnBorderOpacity: z.number(),
  btnBorderRadius: z.number(),
  // Button Shadow
  btnShadowOpacity: z.number(),
  btnShadowX: z.number(),
  btnShadowY: z.number(),
  btnShadowBlur: z.number(),
  // Variant Pills
  pillRadius: z.number(),
  pillPaddingX: z.number(),
  pillPaddingY: z.number(),
  pillFontSize: z.number(),
  pillBg: z.string(),
  pillText: z.string(),
  pillActiveBg: z.string(),
  pillActiveText: z.string(),
  pillBorderColor: z.string(),
  pillBorderWidth: z.number(),
  pillBorderOpacity: z.number(),
  pillShadowOpacity: z.number(),
  pillShadowX: z.number(),
  pillShadowY: z.number(),
  pillShadowBlur: z.number(),
  // Inputs
  inputHeight: z.number(),
  inputRadius: z.number(),
  inputBorderColor: z.string(),
  inputBorderWidth: z.number(),
  inputBorderOpacity: z.number(),
  inputBg: z.string(),
  inputText: z.string(),
  inputFocusBorder: z.string(),
  inputPlaceholder: z.string(),
  inputFontSize: z.number(),
  inputShadowOpacity: z.number(),
  inputShadowX: z.number(),
  inputShadowY: z.number(),
  inputShadowBlur: z.number(),
  // Product Cards
  cardStyle: z.string(),
  cardImageRatio: z.string(),
  cardImagePadding: z.number(),
  cardTextAlignment: z.string(),
  cardColorScheme: z.string(),
  cardRadius: z.number(),
  cardShadow: z.string(),
  cardBg: z.string(),
  cardHoverShadow: z.string(),
  showBadge: z.boolean(),
  showQuickAdd: z.boolean(),
  cardBorderWidth: z.number(),
  cardBorderOpacity: z.number(),
  cardBorderRadius: z.number(),
  cardShadowOpacity: z.number(),
  cardShadowX: z.number(),
  cardShadowY: z.number(),
  cardShadowBlur: z.number(),
  // Collection Cards
  collectionRatio: z.string(),
  collectionRadius: z.number(),
  collectionStyle: z.string(),
  collectionImagePadding: z.number(),
  collectionOverlay: z.boolean(),
  collectionOverlayColor: z.string(),
  collectionTextAlign: z.string(),
  collectionColorScheme: z.string(),
  collectionBorderWidth: z.number(),
  collectionBorderOpacity: z.number(),
  collectionShadowOpacity: z.number(),
  collectionShadowX: z.number(),
  collectionShadowY: z.number(),
  collectionShadowBlur: z.number(),
  // Blog Cards
  blogStyle: z.string(),
  blogRatio: z.string(),
  blogImagePadding: z.number(),
  blogTextAlignment: z.string(),
  blogColorScheme: z.string(),
  blogRadius: z.number(),
  blogShowDate: z.boolean(),
  blogShowExcerpt: z.boolean(),
  blogExcerptLines: z.number(),
  blogBorderWidth: z.number(),
  blogBorderOpacity: z.number(),
  blogBorderRadius: z.number(),
  blogShadowOpacity: z.number(),
  blogShadowX: z.number(),
  blogShadowY: z.number(),
  blogShadowBlur: z.number(),
  // Content Containers
  containerBg: z.string(),
  containerBorderColor: z.string(),
  containerRadius: z.number(),
  containerPaddingInner: z.number(),
  containerShadow: z.string(),
  containerBorderWidth: z.number(),
  containerBorderOpacity: z.number(),
  containerBorderRadius: z.number(),
  containerShadowOpacity: z.number(),
  containerShadowX: z.number(),
  containerShadowY: z.number(),
  containerShadowBlur: z.number(),
  // Media
  imageRadius: z.number(),
  imageBorderColor: z.string(),
  imageBorderWidth: z.number(),
  imageBorderOpacity: z.number(),
  imageShadowOpacity: z.number(),
  imageShadowX: z.number(),
  imageShadowY: z.number(),
  imageShadowBlur: z.number(),
  imagePlaceholderBg: z.string(),
  videoRatio: z.string(),
  // Dropdowns and pop-ups
  dropdownBg: z.string(),
  dropdownBorder: z.string(),
  dropdownBorderWidth: z.number(),
  dropdownBorderOpacity: z.number(),
  dropdownRadius: z.number(),
  dropdownShadow: z.string(),
  dropdownShadowOpacity: z.number(),
  dropdownShadowX: z.number(),
  dropdownShadowY: z.number(),
  dropdownShadowBlur: z.number(),
  popupOverlayColor: z.string(),
  popupRadius: z.number(),
  // Drawers
  drawerWidth: z.number(),
  drawerBg: z.string(),
  drawerOverlayColor: z.string(),
  drawerPosition: z.string(),
  drawerBorderColor: z.string(),
  drawerBorderWidth: z.number(),
  drawerBorderOpacity: z.number(),
  drawerRadius: z.number(),
  drawerShadowOpacity: z.number(),
  drawerShadowX: z.number(),
  drawerShadowY: z.number(),
  drawerShadowBlur: z.number(),
  // Badges
  badgePosition: z.string(),
  badgeFontSize: z.number(),
  badgeRadius: z.number(),
  badgePaddingX: z.number(),
  badgePaddingY: z.number(),
  badgeDefaultBg: z.string(),
  badgeDefaultText: z.string(),
  badgeSaleColorScheme: z.string(),
  badgeSaleBg: z.string(),
  badgeSaleText: z.string(),
  badgeSoldOutColorScheme: z.string(),
  // Brand Information
  brandName: z.string(),
  brandTagline: z.string(),
  brandEmail: z.string(),
  brandPhone: z.string(),
  brandAddress: z.string(),
  brandFooterHeadline: z.string(),
  brandFooterDescription: z.string(),
  brandFooterImage: z.string(),
  brandFooterImageWidth: z.number(),
  // Social Media
  socialFacebook: z.string(),
  socialInstagram: z.string(),
  socialTwitter: z.string(),
  socialLinkedin: z.string(),
  socialYoutube: z.string(),
  socialTiktok: z.string(),
  socialSnapchat: z.string(),
  socialPinterest: z.string(),
  socialTumblr: z.string(),
  socialVimeo: z.string(),
  // Search Behaviour
  searchPlaceholder: z.string(),
  searchMinChars: z.number(),
  searchShowSuggestions: z.boolean(),
  searchShowVendor: z.boolean(),
  searchShowPrice: z.boolean(),
  searchType: z.enum(['instant', 'submit']).optional(),
  searchMaxResults: z.number(),
  // Currency Format
  currencyCode: z.string(),
  currencySymbol: z.string(),
  currencyPosition: z.string(),
  currencyShowCode: z.boolean(),
  thousandsSeparator: z.string(),
  decimalSeparator: z.string(),
  decimalPlaces: z.number(),
  // Cart
  cartStyle: z.string(),
  cartIconStyle: z.string(),
  showCartCount: z.boolean(),
  cartEmptyText: z.string(),
  cartShowVendor: z.boolean(),
  cartEnableNote: z.boolean(),
  cartDrawerCollectionId: z.string(),
  cartDrawerShowWhenEmpty: z.boolean(),
  cartDrawerColorScheme: z.string(),
  // Custom CSS
  customCssSelectors: z.string(),
  customCss: z.string(),
  // Theme Style
  themePreset: z.string(),
  darkMode: z.boolean(),
});

export type ThemeSettingsDto = z.infer<typeof themeSettingsSchema>;
export type ThemeSettings = ThemeSettingsDto;

export const CMS_THEME_SETTINGS_KEY = 'cms_theme_settings.v1';

export const DEFAULT_THEME: ThemeSettings = {
  primaryColor: '#3b82f6',
  secondaryColor: '#6366f1',
  accentColor: '#f59e0b',
  backgroundColor: '#030712',
  surfaceColor: '#111827',
  textColor: '#f3f4f6',
  mutedTextColor: '#9ca3af',
  borderColor: '#1f2937',
  errorColor: '#ef4444',
  successColor: '#22c55e',
  colorSchemes: [
    {
      id: 'scheme-1',
      name: 'Scheme 1',
      colors: {
        background: '#030712',
        surface: '#111827',
        text: '#f3f4f6',
        accent: '#3b82f6',
        border: '#1f2937',
      },
    },
  ],
  activeColorSchemeId: 'scheme-1',
  headingFont: 'Inter, sans-serif',
  bodyFont: 'Inter, sans-serif',
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1,
  bodySizeScale: 1,
  lineHeight: 1.6,
  headingLineHeight: 1.2,
  maxContentWidth: 1200,
  gridGutter: 24,
  sectionSpacing: 64,
  containerPadding: 24,
  borderRadius: 8,
  pagePaddingTop: 16,
  pagePaddingRight: 16,
  pagePaddingBottom: 16,
  pagePaddingLeft: 16,
  pageMarginTop: 0,
  pageMarginRight: 0,
  pageMarginBottom: 0,
  pageMarginLeft: 0,
  pagePadding: 16,
  pageMargin: 0,
  fullWidth: false,
  enableAnimations: true,
  animationDuration: 300,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.02,
  btnPaddingX: 20,
  btnPaddingY: 10,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 8,
  btnPrimaryBg: '#3b82f6',
  btnPrimaryText: '#ffffff',
  btnSecondaryBg: '#374151',
  btnSecondaryText: '#f3f4f6',
  btnOutlineBorder: '#4b5563',
  btnBorderWidth: 1,
  btnBorderOpacity: 100,
  btnBorderRadius: 8,
  btnShadowOpacity: 0,
  btnShadowX: 0,
  btnShadowY: 2,
  btnShadowBlur: 4,
  pillRadius: 999,
  pillPaddingX: 12,
  pillPaddingY: 4,
  pillFontSize: 12,
  pillBg: '#1f2937',
  pillText: '#d1d5db',
  pillActiveBg: '#3b82f6',
  pillActiveText: '#ffffff',
  pillBorderColor: '#1f2937',
  pillBorderWidth: 0,
  pillBorderOpacity: 100,
  pillShadowOpacity: 0,
  pillShadowX: 0,
  pillShadowY: 0,
  pillShadowBlur: 0,
  inputHeight: 40,
  inputRadius: 8,
  inputBorderColor: '#374151',
  inputBorderWidth: 1,
  inputBorderOpacity: 100,
  inputBg: '#111827',
  inputText: '#f3f4f6',
  inputFocusBorder: '#3b82f6',
  inputPlaceholder: '#6b7280',
  inputFontSize: 14,
  inputShadowOpacity: 0,
  inputShadowX: 0,
  inputShadowY: 0,
  inputShadowBlur: 0,
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardImagePadding: 0,
  cardTextAlignment: 'left',
  cardColorScheme: 'scheme-1',
  cardRadius: 12,
  cardShadow: 'small',
  cardBg: '#111827',
  cardHoverShadow: 'medium',
  showBadge: true,
  showQuickAdd: true,
  cardBorderWidth: 0,
  cardBorderOpacity: 100,
  cardBorderRadius: 12,
  cardShadowOpacity: 0,
  cardShadowX: 0,
  cardShadowY: 2,
  cardShadowBlur: 4,
  collectionRatio: '16:9',
  collectionRadius: 12,
  collectionStyle: 'standard',
  collectionImagePadding: 0,
  collectionOverlay: true,
  collectionOverlayColor: '#00000066',
  collectionTextAlign: 'center',
  collectionColorScheme: 'scheme-1',
  collectionBorderWidth: 0,
  collectionBorderOpacity: 100,
  collectionShadowOpacity: 0,
  collectionShadowX: 0,
  collectionShadowY: 2,
  collectionShadowBlur: 4,
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 0,
  blogTextAlignment: 'left',
  blogColorScheme: 'scheme-1',
  blogRadius: 12,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 2,
  blogBorderWidth: 0,
  blogBorderOpacity: 100,
  blogBorderRadius: 12,
  blogShadowOpacity: 0,
  blogShadowX: 0,
  blogShadowY: 2,
  blogShadowBlur: 4,
  containerBg: '#111827',
  containerBorderColor: '#1f2937',
  containerRadius: 12,
  containerPaddingInner: 24,
  containerShadow: 'none',
  containerBorderWidth: 1,
  containerBorderOpacity: 100,
  containerBorderRadius: 12,
  containerShadowOpacity: 0,
  containerShadowX: 0,
  containerShadowY: 2,
  containerShadowBlur: 4,
  imageRadius: 8,
  imageBorderColor: '#1f2937',
  imageBorderWidth: 0,
  imageBorderOpacity: 100,
  imageShadowOpacity: 0,
  imageShadowX: 0,
  imageShadowY: 0,
  imageShadowBlur: 0,
  imagePlaceholderBg: '#1f2937',
  videoRatio: '16:9',
  dropdownBg: '#1f2937',
  dropdownBorder: '#374151',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 100,
  dropdownRadius: 8,
  dropdownShadow: 'medium',
  dropdownShadowOpacity: 20,
  dropdownShadowX: 0,
  dropdownShadowY: 8,
  dropdownShadowBlur: 24,
  popupOverlayColor: '#000000aa',
  popupRadius: 16,
  drawerWidth: 400,
  drawerBg: '#111827',
  drawerOverlayColor: '#000000aa',
  drawerPosition: 'right',
  drawerBorderColor: '#1f2937',
  drawerBorderWidth: 0,
  drawerBorderOpacity: 100,
  drawerRadius: 16,
  drawerShadowOpacity: 0,
  drawerShadowX: 0,
  drawerShadowY: 8,
  drawerShadowBlur: 24,
  badgePosition: 'top-left',
  badgeFontSize: 11,
  badgeRadius: 4,
  badgePaddingX: 8,
  badgePaddingY: 2,
  badgeDefaultBg: '#374151',
  badgeDefaultText: '#d1d5db',
  badgeSaleColorScheme: 'scheme-1',
  badgeSaleBg: '#ef4444',
  badgeSaleText: '#ffffff',
  badgeSoldOutColorScheme: 'scheme-1',
  brandName: '',
  brandTagline: '',
  brandEmail: '',
  brandPhone: '',
  brandAddress: '',
  brandFooterHeadline: '',
  brandFooterDescription: '',
  brandFooterImage: '',
  brandFooterImageWidth: 240,
  socialFacebook: '',
  socialInstagram: '',
  socialTwitter: '',
  socialLinkedin: '',
  socialYoutube: '',
  socialTiktok: '',
  socialSnapchat: '',
  socialPinterest: '',
  socialTumblr: '',
  socialVimeo: '',
  searchPlaceholder: 'Search...',
  searchMinChars: 2,
  searchShowSuggestions: true,
  searchShowVendor: true,
  searchShowPrice: true,
  searchMaxResults: 8,
  currencyCode: 'USD',
  currencySymbol: '$',
  currencyPosition: 'before',
  currencyShowCode: false,
  thousandsSeparator: ',',
  decimalSeparator: '.',
  decimalPlaces: 2,
  cartStyle: 'drawer',
  cartIconStyle: 'bag',
  showCartCount: true,
  cartEmptyText: 'Your cart is empty',
  cartShowVendor: true,
  cartEnableNote: false,
  cartDrawerCollectionId: '',
  cartDrawerShowWhenEmpty: true,
  cartDrawerColorScheme: 'scheme-1',
  customCssSelectors: '',
  customCss: '',
  themePreset: 'default',
  darkMode: true,
};

export function normalizeThemeSettings(input?: Partial<ThemeSettings> | null): ThemeSettings {
  const exact = themeSettingsSchema.safeParse(input);
  if (exact.success) {
    return exact.data;
  }

  if (!input || typeof input !== 'object' || Array.isArray(input)) return DEFAULT_THEME;

  const merged = {
    ...DEFAULT_THEME,
    ...input,
  };
  const mergedResult = themeSettingsSchema.safeParse(merged);
  if (mergedResult.success) return mergedResult.data;

  return DEFAULT_THEME;
}

export function buildColorSchemeMap(
  input: ThemeSettings | ColorScheme[]
): Record<string, ColorSchemeColors> {
  const schemes = Array.isArray(input) ? input : input.colorSchemes;
  const map: Record<string, ColorSchemeColors> = {};
  schemes.forEach((s) => {
    map[s.id] = s.colors;
  });
  return map;
}
