import { z } from 'zod';

/**
 * CMS Theme Settings DTOs
 */

export const colorSchemeColorsSchema = z.object({
  background: z.string(),
  surface: z.string(),
  text: z.string(),
  accent: z.string(),
  border: z.string(),
});

export type ColorSchemeColorsDto = z.infer<typeof colorSchemeColorsSchema>;

export const colorSchemeSchema = z.object({
  id: z.string(),
  name: z.string(),
  colors: colorSchemeColorsSchema,
});

export type ColorSchemeDto = z.infer<typeof colorSchemeSchema>;

export const themeSettingsSchema = z.object({
  // Colors
  primaryColor: z.string(),
  secondaryColor: z.string(),
  accentColor: z.string(),
  backgroundColor: z.string(),
  surfaceColor: z.string(),
  textColor: z.string(),
  mutedTextColor: z.string(),
  borderColor: z.string(),
  errorColor: z.string(),
  successColor: z.string(),
  colorSchemes: z.array(colorSchemeSchema),
  activeColorSchemeId: z.string(),
  // Typography
  headingFont: z.string(),
  bodyFont: z.string(),
  baseSize: z.number(),
  headingWeight: z.string(),
  bodyWeight: z.string(),
  headingSizeScale: z.number(),
  bodySizeScale: z.number(),
  lineHeight: z.number(),
  headingLineHeight: z.number(),
  // Layout
  maxContentWidth: z.number(),
  gridGutter: z.number(),
  sectionSpacing: z.number(),
  containerPadding: z.number(),
  borderRadius: z.number(),
  pagePaddingTop: z.number(),
  pagePaddingRight: z.number(),
  pagePaddingBottom: z.number(),
  pagePaddingLeft: z.number(),
  pageMarginTop: z.number(),
  pageMarginRight: z.number(),
  pageMarginBottom: z.number(),
  pageMarginLeft: z.number(),
  pagePadding: z.number(),
  pageMargin: z.number(),
  fullWidth: z.boolean(),
  // Animations
  enableAnimations: z.boolean(),
  animationDuration: z.number(),
  animationEasing: z.string(),
  scrollReveal: z.boolean(),
  hoverEffect: z.string(),
  hoverScale: z.number(),
  // Buttons
  btnPaddingX: z.number(),
  btnPaddingY: z.number(),
  btnFontSize: z.number(),
  btnFontWeight: z.string(),
  btnRadius: z.number(),
  btnPrimaryBg: z.string(),
  btnPrimaryText: z.string(),
  btnSecondaryBg: z.string(),
  btnSecondaryText: z.string(),
  btnOutlineBorder: z.string(),
  // Button Border
  btnBorderWidth: z.number(),
  btnBorderOpacity: z.number(),
  btnBorderRadius: z.number(),
  // Button Shadow
  btnShadowOpacity: z.number(),
  btnShadowX: z.number(),
  btnShadowY: z.number(),
  btnShadowBlur: z.number(),
  // Variant Pills
  pillRadius: z.number(),
  pillPaddingX: z.number(),
  pillPaddingY: z.number(),
  pillFontSize: z.number(),
  pillBg: z.string(),
  pillText: z.string(),
  pillActiveBg: z.string(),
  pillActiveText: z.string(),
  pillBorderColor: z.string(),
  pillBorderWidth: z.number(),
  pillBorderOpacity: z.number(),
  pillShadowOpacity: z.number(),
  pillShadowX: z.number(),
  pillShadowY: z.number(),
  pillShadowBlur: z.number(),
  // Inputs
  inputHeight: z.number(),
  inputRadius: z.number(),
  inputBorderColor: z.string(),
  inputBorderWidth: z.number(),
  inputBorderOpacity: z.number(),
  inputBg: z.string(),
  inputText: z.string(),
  inputFocusBorder: z.string(),
  inputPlaceholder: z.string(),
  inputFontSize: z.number(),
  inputShadowOpacity: z.number(),
  inputShadowX: z.number(),
  inputShadowY: z.number(),
  inputShadowBlur: z.number(),
  // Product Cards
  cardStyle: z.string(),
  cardImageRatio: z.string(),
  cardImagePadding: z.number(),
  cardTextAlignment: z.string(),
  cardColorScheme: z.string(),
  cardRadius: z.number(),
  cardShadow: z.string(),
  cardBg: z.string(),
  cardHoverShadow: z.string(),
  showBadge: z.boolean(),
  showQuickAdd: z.boolean(),
  cardBorderWidth: z.number(),
  cardBorderOpacity: z.number(),
  cardBorderRadius: z.number(),
  cardShadowOpacity: z.number(),
  cardShadowX: z.number(),
  cardShadowY: z.number(),
  cardShadowBlur: z.number(),
  // Collection Cards
  collectionRatio: z.string(),
  collectionRadius: z.number(),
  collectionStyle: z.string(),
  collectionImagePadding: z.number(),
  collectionOverlay: z.boolean(),
  collectionOverlayColor: z.string(),
  collectionTextAlign: z.string(),
  collectionColorScheme: z.string(),
  collectionBorderWidth: z.number(),
  collectionBorderOpacity: z.number(),
  collectionShadowOpacity: z.number(),
  collectionShadowX: z.number(),
  collectionShadowY: z.number(),
  collectionShadowBlur: z.number(),
  // Blog Cards
  blogStyle: z.string(),
  blogRatio: z.string(),
  blogImagePadding: z.number(),
  blogTextAlignment: z.string(),
  blogColorScheme: z.string(),
  blogRadius: z.number(),
  blogShowDate: z.boolean(),
  blogShowExcerpt: z.boolean(),
  blogExcerptLines: z.number(),
  blogBorderWidth: z.number(),
  blogBorderOpacity: z.number(),
  blogBorderRadius: z.number(),
  blogShadowOpacity: z.number(),
  blogShadowX: z.number(),
  blogShadowY: z.number(),
  blogShadowBlur: z.number(),
  // Content Containers
  containerBg: z.string(),
  containerBorderColor: z.string(),
  containerRadius: z.number(),
  containerPaddingInner: z.number(),
  containerShadow: z.string(),
  containerBorderWidth: z.number(),
  containerBorderOpacity: z.number(),
  containerBorderRadius: z.number(),
  containerShadowOpacity: z.number(),
  containerShadowX: z.number(),
  containerShadowY: z.number(),
  containerShadowBlur: z.number(),
  // Media
  imageRadius: z.number(),
  imageBorderColor: z.string(),
  imageBorderWidth: z.number(),
  imageBorderOpacity: z.number(),
  imageShadowOpacity: z.number(),
  imageShadowX: z.number(),
  imageShadowY: z.number(),
  imageShadowBlur: z.number(),
  imagePlaceholderBg: z.string(),
  videoRatio: z.string(),
  // Dropdowns and pop-ups
  dropdownBg: z.string(),
  dropdownBorder: z.string(),
  dropdownBorderWidth: z.number(),
  dropdownBorderOpacity: z.number(),
  dropdownRadius: z.number(),
  dropdownShadow: z.string(),
  dropdownShadowOpacity: z.number(),
  dropdownShadowX: z.number(),
  dropdownShadowY: z.number(),
  dropdownShadowBlur: z.number(),
  popupOverlayColor: z.string(),
  popupRadius: z.number(),
  // Drawers
  drawerWidth: z.number(),
  drawerBg: z.string(),
  drawerOverlayColor: z.string(),
  drawerPosition: z.string(),
  drawerBorderColor: z.string(),
  drawerBorderWidth: z.number(),
  drawerBorderOpacity: z.number(),
  drawerRadius: z.number(),
  drawerShadowOpacity: z.number(),
  drawerShadowX: z.number(),
  drawerShadowY: z.number(),
  drawerShadowBlur: z.number(),
  // Badges
  badgePosition: z.string(),
  badgeFontSize: z.number(),
  badgeRadius: z.number(),
  badgePaddingX: z.number(),
  badgePaddingY: z.number(),
  badgeDefaultBg: z.string(),
  badgeDefaultText: z.string(),
  badgeSaleColorScheme: z.string(),
  badgeSaleBg: z.string(),
  badgeSaleText: z.string(),
  badgeSoldOutColorScheme: z.string(),
  // Brand Information
  brandName: z.string(),
  brandTagline: z.string(),
  brandEmail: z.string(),
  brandPhone: z.string(),
  brandAddress: z.string(),
  brandFooterHeadline: z.string(),
  brandFooterDescription: z.string(),
  brandFooterImage: z.string(),
  brandFooterImageWidth: z.number(),
  // Social Media
  socialFacebook: z.string(),
  socialInstagram: z.string(),
  socialTwitter: z.string(),
  socialLinkedin: z.string(),
  socialYoutube: z.string(),
  socialTiktok: z.string(),
  socialSnapchat: z.string(),
  socialPinterest: z.string(),
  socialTumblr: z.string(),
  socialVimeo: z.string(),
  // Search Behaviour
  searchPlaceholder: z.string(),
  searchMinChars: z.number(),
  searchShowSuggestions: z.boolean(),
  searchShowVendor: z.boolean(),
  searchShowPrice: z.boolean(),
  searchMaxResults: z.number(),
  // Currency Format
  currencyCode: z.string(),
  currencySymbol: z.string(),
  currencyPosition: z.string(),
  currencyShowCode: z.boolean(),
  thousandsSeparator: z.string(),
  decimalSeparator: z.string(),
  decimalPlaces: z.number(),
  // Cart
  cartStyle: z.string(),
  cartIconStyle: z.string(),
  showCartCount: z.boolean(),
  cartEmptyText: z.string(),
  cartShowVendor: z.boolean(),
  cartEnableNote: z.boolean(),
  cartDrawerCollectionId: z.string(),
  cartDrawerShowWhenEmpty: z.boolean(),
  cartDrawerColorScheme: z.string(),
  // Custom CSS
  customCssSelectors: z.string(),
  customCss: z.string(),
  // Theme Style
  themePreset: z.string(),
  darkMode: z.boolean(),
});

export type ThemeSettingsDto = z.infer<typeof themeSettingsSchema>;
