import type { KangurTutorAnchorKind } from '@/features/kangur/ui/context/kangur-tutor-types';
import type { KangurAiTutorSurface } from '@/shared/contracts/kangur-ai-tutor';

export type KangurAiTutorCoveragePageKey =
  | 'Game'
  | 'Lessons'
  | 'Tests'
  | 'LearnerProfile'
  | 'ParentDashboard'
  | 'Login'
  | 'SharedChrome';

export type KangurAiTutorCoverageStatus =
  | 'native_guide_ready'
  | 'context_only'
  | 'contract_gap';

export type KangurAiTutorPageCoverageEntry = {
  id: string;
  pageKey: KangurAiTutorCoveragePageKey;
  screenKey: string;
  surface: KangurAiTutorSurface | null;
  componentId: string;
  title: string;
  widget: string;
  sourcePath: string;
  status: KangurAiTutorCoverageStatus;
  anchorIdPrefix: string | null;
  focusKind: KangurTutorAnchorKind | null;
  contentIdPrefixes: readonly string[];
  currentKnowledgeEntryIds: readonly string[];
  notes: string;
};

export type KangurAiTutorPageCoverageSummary = {
  total: number;
  nativeGuideReady: number;
  contextOnly: number;
  contractGap: number;
};

const createCoverageEntry = (
  input: Omit<
    KangurAiTutorPageCoverageEntry,
    'anchorIdPrefix' | 'focusKind' | 'contentIdPrefixes' | 'currentKnowledgeEntryIds'
  > & {
    anchorIdPrefix?: string | null;
    focusKind?: KangurTutorAnchorKind | null;
    contentIdPrefixes?: string[];
    currentKnowledgeEntryIds?: string[];
  }
): KangurAiTutorPageCoverageEntry =>
  Object.freeze({
    ...input,
    anchorIdPrefix: input.anchorIdPrefix ?? null,
    focusKind: input.focusKind ?? null,
    contentIdPrefixes: Object.freeze([...(input.contentIdPrefixes ?? [])]),
    currentKnowledgeEntryIds: Object.freeze([...(input.currentKnowledgeEntryIds ?? [])]),
  });

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST: readonly KangurAiTutorPageCoverageEntry[] =
  Object.freeze([
    createCoverageEntry({
      id: 'game-home-actions',
      pageKey: 'Game',
      screenKey: 'home',
      surface: 'game',
      componentId: 'home-actions',
      title: 'Szybkie akcje',
      widget: 'KangurGameHomeActionsWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-home-actions',
      focusKind: 'home_actions',
      contentIdPrefixes: ['game:home'],
      currentKnowledgeEntryIds: ['shared-home-actions'],
      notes: 'Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-home-quest',
      pageKey: 'Game',
      screenKey: 'home',
      surface: 'game',
      componentId: 'home-quest',
      title: 'Misja dnia',
      widget: 'KangurGameHomeQuestWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-home-quest',
      focusKind: 'home_quest',
      contentIdPrefixes: ['game:home'],
      currentKnowledgeEntryIds: ['shared-home-quest'],
      notes: 'Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-home-priority-assignments',
      pageKey: 'Game',
      screenKey: 'home',
      surface: 'game',
      componentId: 'priority-assignments',
      title: 'Priorytetowe zadania',
      widget: 'KangurPriorityAssignments',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-home-assignments',
      focusKind: 'priority_assignments',
      contentIdPrefixes: ['game:home'],
      currentKnowledgeEntryIds: ['shared-priority-assignments'],
      notes: 'Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-home-leaderboard',
      pageKey: 'Game',
      screenKey: 'home',
      surface: 'game',
      componentId: 'leaderboard',
      title: 'Ranking na stronie głównej',
      widget: 'Leaderboard',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-home-leaderboard',
      focusKind: 'leaderboard',
      contentIdPrefixes: ['game:home'],
      currentKnowledgeEntryIds: ['shared-leaderboard'],
      notes: 'Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-home-progress',
      pageKey: 'Game',
      screenKey: 'home',
      surface: 'game',
      componentId: 'progress-card',
      title: 'Postęp na stronie głównej',
      widget: 'PlayerProgressCard',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-home-progress',
      focusKind: 'progress',
      contentIdPrefixes: ['game:home'],
      currentKnowledgeEntryIds: ['shared-progress'],
      notes: 'Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-training-setup',
      pageKey: 'Game',
      screenKey: 'training',
      surface: 'game',
      componentId: 'training-setup',
      title: 'Konfiguracja treningu',
      widget: 'KangurGameTrainingSetupWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-training-setup',
      focusKind: 'screen',
      contentIdPrefixes: ['game:training-setup'],
      currentKnowledgeEntryIds: ['game-training-setup'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-operation-selector',
      pageKey: 'Game',
      screenKey: 'operation',
      surface: 'game',
      componentId: 'operation-selector',
      title: 'Wybór rodzaju gry',
      widget: 'KangurGameOperationSelectorWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-operation-selector',
      focusKind: 'screen',
      contentIdPrefixes: ['game:operation-selector'],
      currentKnowledgeEntryIds: ['game-operation-selector'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-kangur-setup',
      pageKey: 'Game',
      screenKey: 'kangur_setup',
      surface: 'game',
      componentId: 'kangur-setup',
      title: 'Konfiguracja sesji Kangura Matematycznego',
      widget: 'KangurGameKangurSetupWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-kangur-setup',
      focusKind: 'screen',
      contentIdPrefixes: ['game:kangur:setup'],
      currentKnowledgeEntryIds: ['game-kangur-setup'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-kangur-session',
      pageKey: 'Game',
      screenKey: 'kangur',
      surface: 'game',
      componentId: 'kangur-session',
      title: 'Sesja Kangura Matematycznego',
      widget: 'KangurGameKangurSessionWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-kangur-session',
      focusKind: 'screen',
      contentIdPrefixes: ['game:kangur:'],
      currentKnowledgeEntryIds: ['game-kangur-session'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-calendar-quiz',
      pageKey: 'Game',
      screenKey: 'calendar_quiz',
      surface: 'game',
      componentId: 'calendar-quiz',
      title: 'Ćwiczenia z kalendarzem',
      widget: 'KangurGameCalendarTrainingWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-calendar-quiz',
      focusKind: 'screen',
      contentIdPrefixes: ['game:calendar_quiz'],
      currentKnowledgeEntryIds: ['game-calendar-quiz'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-geometry-quiz',
      pageKey: 'Game',
      screenKey: 'geometry_quiz',
      surface: 'game',
      componentId: 'geometry-quiz',
      title: 'Ćwiczenia z figurami',
      widget: 'KangurGameGeometryTrainingWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-geometry-quiz',
      focusKind: 'screen',
      contentIdPrefixes: ['game:geometry_quiz'],
      currentKnowledgeEntryIds: ['game-geometry-quiz'],
      notes: 'Ekran ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-playing-assignment-banner',
      pageKey: 'Game',
      screenKey: 'playing',
      surface: 'game',
      componentId: 'assignment-banner',
      title: 'Baner aktywnego zadania treningowego',
      widget: 'KangurPracticeAssignmentBanner',
      sourcePath: 'src/features/kangur/ui/components/KangurGameQuestionWidget.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-assignment-banner',
      focusKind: 'assignment',
      contentIdPrefixes: ['game:assignment:'],
      currentKnowledgeEntryIds: ['game-assignment'],
      notes: 'Baner ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-playing-question',
      pageKey: 'Game',
      screenKey: 'playing',
      surface: 'game',
      componentId: 'question-card',
      title: 'Pytanie w grze',
      widget: 'KangurGameQuestionWidget',
      sourcePath: 'src/features/kangur/ui/components/KangurGameQuestionWidget.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-question-anchor',
      focusKind: 'question',
      contentIdPrefixes: ['game:practice:'],
      currentKnowledgeEntryIds: ['game-question'],
      notes: 'Pytanie ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-result-summary',
      pageKey: 'Game',
      screenKey: 'result',
      surface: 'game',
      componentId: 'result-summary',
      title: 'Podsumowanie wyniku gry',
      widget: 'KangurGameResultWidget',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-result-summary',
      focusKind: 'review',
      contentIdPrefixes: ['game:result', 'game:practice:', 'game:assignment:'],
      currentKnowledgeEntryIds: ['game-review'],
      notes: 'Wynik ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'game-result-leaderboard',
      pageKey: 'Game',
      screenKey: 'result',
      surface: 'game',
      componentId: 'result-leaderboard',
      title: 'Ranking po zakończeniu gry',
      widget: 'Leaderboard',
      sourcePath: 'src/features/kangur/ui/pages/Game.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-game-result-leaderboard',
      focusKind: 'leaderboard',
      contentIdPrefixes: ['game:result', 'game:practice:', 'game:assignment:'],
      currentKnowledgeEntryIds: ['game-result-leaderboard'],
      notes: 'Ranking po rundzie ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-list-intro',
      pageKey: 'Lessons',
      screenKey: 'list',
      surface: 'lesson',
      componentId: 'list-intro',
      title: 'Intro listy lekcji',
      widget: 'KangurPageIntroCard',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lessons-list-intro',
      focusKind: 'hero',
      contentIdPrefixes: ['lesson:list'],
      currentKnowledgeEntryIds: ['lesson-list-intro'],
      notes:
        'Karta wprowadzająca do ekranu Lekcje. Wyjaśnia, że tutaj wybiera się temat i przechodzi do nauki lub powtórki. Sekcja ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-library',
      pageKey: 'Lessons',
      screenKey: 'list',
      surface: 'lesson',
      componentId: 'lesson-library',
      title: 'Karty tematów na liście lekcji',
      widget: 'KangurOptionCardButton',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lessons-library',
      focusKind: 'library',
      contentIdPrefixes: ['lesson:list'],
      currentKnowledgeEntryIds: ['lesson-library'],
      notes:
        'Lista kart lekcji. Każda karta pokazuje tytuł, opis, poziom opanowania i ewentualny priorytet od rodzica; kliknięcie otwiera lekcję. Dostępne tematy: Nauka zegara, Nauka kalendarza, Dodawanie, Odejmowanie, Mnożenie, Dzielenie, Podstawy geometrii, Figury geometryczne, Symetria, Obwód figur, Myślenie logiczne, Wzorce i ciągi, Klasyfikacja, Wnioskowanie, Analogie. Biblioteka lekcji ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-list-empty-state',
      pageKey: 'Lessons',
      screenKey: 'list',
      surface: 'lesson',
      componentId: 'list-empty-state',
      title: 'Pusty stan listy lekcji',
      widget: 'KangurEmptyState',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lessons-list-empty-state',
      focusKind: 'empty_state',
      contentIdPrefixes: ['lesson:list'],
      currentKnowledgeEntryIds: ['lesson-empty-state'],
      notes:
        'Stan pustej listy pokazuje, że nie ma aktywnych lekcji do wyboru. Zwykle oznacza to brak włączonych tematów w panelu admina lub brak dostępnej treści. Pusty stan listy ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-header',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'active-header',
      title: 'Nagłówek aktywnej lekcji',
      widget: 'KangurActiveLessonHeader',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-header',
      focusKind: 'lesson_header',
      currentKnowledgeEntryIds: ['lesson-header'],
      notes:
        'Nagłówek aktywnej lekcji pokazuje tytuł, krótki opis tematu i najważniejszy kontekst startowy. To punkt orientacyjny przed przejściem do treści. Nagłówek aktywnej lekcji ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-assignment',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'active-assignment',
      title: 'Zadanie powiązane z aktywna lekcja',
      widget: 'KangurActiveLessonHeader',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-assignment',
      focusKind: 'assignment',
      currentKnowledgeEntryIds: ['lesson-assignment'],
      notes:
        'Sekcja zadania informuje o priorytecie od rodzica lub statusie wykonania powiązanego zadania. Pomaga zdecydować, czy ta lekcja jest teraz najważniejsza. Sekcja zadania ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-document',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'active-document',
      title: 'Główna treść aktywnej lekcji',
      widget: 'KangurLessonDocumentRenderer',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-document',
      focusKind: 'document',
      currentKnowledgeEntryIds: ['lesson-document'],
      notes:
        'Główna treść aktywnej lekcji zawiera dokument, przykłady, ilustracje i bloki wyjaśniające. To miejsce do spokojnego czytania i zrozumienia materiału. Główna treść aktywnej lekcji ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-secret-panel',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'secret-panel',
      title: 'Ukryty finisz w lekcji',
      widget: 'KangurGlassPanel',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-screen-secret',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['lesson-screen'],
      notes:
        'Specjalna plansza pojawia się w wyjątkowych stanach (np. ukryty finisz). Częściej podsumowuje postęp niż wprowadza nową treść. Sekretna plansza ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-empty-document',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'empty-document-summary',
      title: 'Brak zapisanej zawartosci dokumentu lekcji',
      widget: 'KangurSummaryPanel',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-empty-document',
      focusKind: 'empty_state',
      currentKnowledgeEntryIds: ['lesson-empty-state'],
      notes:
        'Komunikat informuje, że lekcja ma tryb dokumentu, ale treść nie została jeszcze zapisana. Warto wrócić do listy lub wybrać inną lekcję. Stan pustej zawartości dokumentu ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'lessons-active-navigation',
      pageKey: 'Lessons',
      screenKey: 'active',
      surface: 'lesson',
      componentId: 'lesson-navigation',
      title: 'Nawigacja między lekcjami',
      widget: 'KangurLessonNavigationWidget',
      sourcePath: 'src/features/kangur/ui/pages/Lessons.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-lesson-navigation',
      focusKind: 'navigation',
      currentKnowledgeEntryIds: ['lesson-navigation'],
      notes:
        'Nawigacja pozwala przejść do poprzedniej lub następnej lekcji bez wracania do listy. Ułatwia płynne przechodzenie między tematami. Nawigacja lekcji ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'tests-empty-state',
      pageKey: 'Tests',
      screenKey: 'suite',
      surface: 'test',
      componentId: 'empty-state',
      title: 'Pusty stan zestawu testowego',
      widget: 'KangurEmptyState',
      sourcePath: 'src/features/kangur/ui/components/KangurTestSuitePlayer.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-test-empty-state:',
      focusKind: 'empty_state',
      currentKnowledgeEntryIds: ['test-empty-state'],
      notes: 'Pusty test ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'tests-question',
      pageKey: 'Tests',
      screenKey: 'suite',
      surface: 'test',
      componentId: 'question',
      title: 'Pytanie testowe',
      widget: 'KangurTestQuestionRenderer',
      sourcePath: 'src/features/kangur/ui/components/KangurTestSuitePlayer.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-test-question:',
      focusKind: 'question',
      currentKnowledgeEntryIds: ['test-question'],
      notes: 'Pytanie testowe ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'tests-selection',
      pageKey: 'Tests',
      screenKey: 'suite',
      surface: 'test',
      componentId: 'selected-choice',
      title: 'Wybrana odpowiedź testowa',
      widget: 'KangurTestQuestionRenderer',
      sourcePath: 'src/features/kangur/ui/components/KangurTestQuestionRenderer.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-test-selection:',
      focusKind: 'selection',
      currentKnowledgeEntryIds: ['test-selection'],
      notes:
        'Zaznaczona odpowiedź ma własny tutor anchor, żeby Tutor-AI mógł odwoływać się do konkretnej karty wyboru przed pokazaniem wyniku.',
    }),
    createCoverageEntry({
      id: 'tests-review',
      pageKey: 'Tests',
      screenKey: 'suite',
      surface: 'test',
      componentId: 'review',
      title: 'Omówienie odpowiedzi testowej',
      widget: 'KangurTestQuestionRenderer',
      sourcePath: 'src/features/kangur/ui/components/KangurTestSuitePlayer.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-test-question:',
      focusKind: 'review',
      currentKnowledgeEntryIds: ['test-review'],
      notes: 'Omówienie po odpowiedzi reuse-uje pytaniowy anchor i ma wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'tests-summary',
      pageKey: 'Tests',
      screenKey: 'summary',
      surface: 'test',
      componentId: 'summary',
      title: 'Podsumowanie testu',
      widget: 'KangurSummaryPanel',
      sourcePath: 'src/features/kangur/ui/components/KangurTestSuitePlayer.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-test-summary:',
      focusKind: 'summary',
      currentKnowledgeEntryIds: ['test-summary'],
      notes: 'Podsumowanie testu ma dedykowany anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-hero',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'hero',
      title: 'Hero profilu ucznia',
      widget: 'KangurLearnerProfileHeroWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-hero',
      focusKind: 'hero',
      currentKnowledgeEntryIds: ['profile-hero'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-ai-tutor-mood',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'ai-tutor-mood',
      title: 'Nastrój i wskazówki Tutor-AI na profilu',
      widget: 'KangurLearnerProfileAiTutorMoodWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-ai-tutor-mood',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['profile-ai-tutor-mood'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-level-progress',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'level-progress',
      title: 'Postęp poziomu ucznia',
      widget: 'KangurLearnerProfileLevelProgressWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-level-progress',
      focusKind: 'progress',
      currentKnowledgeEntryIds: ['profile-level-progress'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-overview',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'overview',
      title: 'Przegląd wyników ucznia',
      widget: 'KangurLearnerProfileOverviewWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-overview',
      focusKind: 'summary',
      currentKnowledgeEntryIds: ['profile-stats-overview'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-recommendations',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'recommendations',
      title: 'Rekomendacje na profilu ucznia',
      widget: 'KangurLearnerProfileRecommendationsWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-recommendations',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['profile-recommendations'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-assignments',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'assignments',
      title: 'Zadania na profilu ucznia',
      widget: 'KangurLearnerProfileAssignmentsWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-assignments',
      focusKind: 'assignment',
      currentKnowledgeEntryIds: ['profile-assignments'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-mastery',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'mastery',
      title: 'Opanowanie materiału ucznia',
      widget: 'KangurLearnerProfileMasteryWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-mastery',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['profile-mastery'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-performance',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'performance',
      title: 'Skuteczność ucznia',
      widget: 'KangurLearnerProfilePerformanceWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-performance',
      focusKind: 'summary',
      currentKnowledgeEntryIds: ['profile-performance'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'learner-profile-sessions',
      pageKey: 'LearnerProfile',
      screenKey: 'profile',
      surface: 'profile',
      componentId: 'sessions',
      title: 'Historia sesji ucznia',
      widget: 'KangurLearnerProfileSessionsWidget',
      sourcePath: 'src/features/kangur/ui/pages/LearnerProfile.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-profile-sessions',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['profile-sessions'],
      notes: 'Profil ucznia ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-guest-hero',
      pageKey: 'ParentDashboard',
      screenKey: 'guest',
      surface: 'parent_dashboard',
      componentId: 'guest-hero',
      title: 'Hero dashboardu rodzica bez dostępu',
      widget: 'KangurParentDashboardHeroWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-guest-hero',
      focusKind: 'hero',
      currentKnowledgeEntryIds: ['parent-dashboard-guest-hero'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-hero',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'hero',
      title: 'Hero dashboardu rodzica',
      widget: 'KangurParentDashboardHeroWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-hero',
      focusKind: 'hero',
      currentKnowledgeEntryIds: ['parent-dashboard-hero'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-learner-management',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'learner-management',
      title: 'Zarządzanie uczniami',
      widget: 'KangurParentDashboardLearnerManagementWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-learner-management',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['parent-dashboard-learner-management'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-tabs',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'tabs',
      title: 'Zakładki dashboardu rodzica',
      widget: 'KangurParentDashboardTabsWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-tabs',
      focusKind: 'navigation',
      currentKnowledgeEntryIds: ['parent-dashboard-tabs'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-progress',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'progress-tab',
      title: 'Postęp ucznia w dashboardzie rodzica',
      widget: 'KangurParentDashboardProgressWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-progress',
      focusKind: 'progress',
      currentKnowledgeEntryIds: ['parent-dashboard-progress'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-scores',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'scores-tab',
      title: 'Wyniki ucznia w dashboardzie rodzica',
      widget: 'KangurParentDashboardScoresWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-scores',
      focusKind: 'summary',
      currentKnowledgeEntryIds: ['parent-dashboard-scores'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-assignments',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'assignments-tab',
      title: 'Zadania ucznia w dashboardzie rodzica',
      widget: 'KangurParentDashboardAssignmentsWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-assignments',
      focusKind: 'assignment',
      currentKnowledgeEntryIds: ['parent-dashboard-assignments'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'parent-dashboard-ai-tutor',
      pageKey: 'ParentDashboard',
      screenKey: 'dashboard',
      surface: 'parent_dashboard',
      componentId: 'ai-tutor-tab',
      title: 'Zakładka Tutor-AI dla rodzica',
      widget: 'KangurParentDashboardAiTutorWidget',
      sourcePath: 'src/features/kangur/ui/pages/ParentDashboard.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-parent-dashboard-ai-tutor',
      focusKind: 'screen',
      currentKnowledgeEntryIds: ['parent-dashboard-ai-tutor'],
      notes: 'Dashboard rodzica ma dedykowany tutor anchor i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'login-page-form',
      pageKey: 'Login',
      screenKey: 'auth',
      surface: 'auth',
      componentId: 'login-form',
      title: 'Formularz logowania Kangur',
      widget: 'KangurLoginPage',
      sourcePath: 'src/features/kangur/ui/KangurLoginPage.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-auth-login-form',
      focusKind: 'login_form',
      currentKnowledgeEntryIds: ['auth-login-form'],
      notes: 'Login page ma dedykowany auth session context i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'login-page-identifier-field',
      pageKey: 'Login',
      screenKey: 'auth',
      surface: 'auth',
      componentId: 'login-identifier-field',
      title: 'Pole identyfikatora logowania',
      widget: 'KangurLoginPage',
      sourcePath: 'src/features/kangur/ui/KangurLoginPage.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-auth-login-identifier-field',
      focusKind: 'login_identifier_field',
      currentKnowledgeEntryIds: ['auth-login-identifier-field'],
      notes: 'Login page ma dedykowany auth session context i wpis Mongo native guide.',
    }),
    createCoverageEntry({
      id: 'shared-nav-create-account-action',
      pageKey: 'SharedChrome',
      screenKey: 'navigation',
      surface: 'auth',
      componentId: 'create-account-action',
      title: 'Akcja utworzenia konta w nawigacji',
      widget: 'KangurPrimaryNavigation',
      sourcePath: 'src/features/kangur/ui/components/KangurPrimaryNavigation.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-auth-create-account-action',
      focusKind: 'create_account_action',
      currentKnowledgeEntryIds: ['auth-create-account-action'],
      notes: 'Nawigacja ma auth anchor, a sekcja korzysta z Mongo native guide przez surface override.',
    }),
    createCoverageEntry({
      id: 'shared-nav-login-action',
      pageKey: 'SharedChrome',
      screenKey: 'navigation',
      surface: 'auth',
      componentId: 'login-action',
      title: 'Akcja logowania w nawigacji',
      widget: 'KangurPrimaryNavigation',
      sourcePath: 'src/features/kangur/ui/components/KangurPrimaryNavigation.tsx',
      status: 'native_guide_ready',
      anchorIdPrefix: 'kangur-auth-login-action',
      focusKind: 'login_action',
      currentKnowledgeEntryIds: ['auth-login-action'],
      notes: 'Nawigacja ma auth anchor, a sekcja korzysta z Mongo native guide przez surface override.',
    }),
  ]);

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_CONTEXT_ONLY: readonly KangurAiTutorPageCoverageEntry[] =
  Object.freeze(
    KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST.filter((entry) => entry.status === 'context_only')
  );

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_CONTRACT_GAPS: readonly KangurAiTutorPageCoverageEntry[] =
  Object.freeze(
    KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST.filter((entry) => entry.status === 'contract_gap')
  );

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_READY_FOR_MONGO: readonly KangurAiTutorPageCoverageEntry[] =
  Object.freeze(
    KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST.filter((entry) => entry.status === 'native_guide_ready')
  );

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_GAPS: readonly KangurAiTutorPageCoverageEntry[] =
  Object.freeze(
    KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST.filter((entry) => entry.status !== 'native_guide_ready')
  );

export const KANGUR_AI_TUTOR_PAGE_COVERAGE_SUMMARY: Readonly<KangurAiTutorPageCoverageSummary> =
  Object.freeze({
    total: KANGUR_AI_TUTOR_PAGE_COVERAGE_MANIFEST.length,
    nativeGuideReady: KANGUR_AI_TUTOR_PAGE_COVERAGE_READY_FOR_MONGO.length,
    contextOnly: KANGUR_AI_TUTOR_PAGE_COVERAGE_CONTEXT_ONLY.length,
    contractGap: KANGUR_AI_TUTOR_PAGE_COVERAGE_CONTRACT_GAPS.length,
  });
