export { KangurFeaturePage } from '@/features/kangur/ui/KangurFeaturePage';
export { KangurPublicApp } from '@/features/kangur/ui/KangurPublicApp';
export { FrontendPublicOwnerProvider } from '@/features/kangur/ui/FrontendPublicOwnerContext';
export { FrontendPublicOwnerKangurShell } from '@/features/kangur/ui/FrontendPublicOwnerKangurShell';
export * from '@/features/kangur/config/routing';
export * from '@/features/kangur/cms-builder/project';
export * from '@/features/kangur/context-registry/refs';
export * from '@/features/kangur/ui/context';
export * from '@/features/kangur/ui/hooks/useKangurProgressState';
export { default as Game } from '@/features/kangur/ui/pages/Game';
export { default as LearnerProfile } from '@/features/kangur/ui/pages/LearnerProfile';
export { default as Lessons } from '@/features/kangur/ui/pages/Lessons';
export { default as ParentDashboard } from '@/features/kangur/ui/pages/ParentDashboard';
export { default as KangurAssignmentSpotlight } from '@/features/kangur/ui/components/assignments/KangurAssignmentSpotlight';
export * from '@/features/kangur/ui/components/assignments/KangurLearnerAssignmentsPanel';
export * from '@/features/kangur/ui/components/assignments/KangurPriorityAssignments';
export * from '@/features/kangur/ui/components/KangurActiveLessonPanelWidget';
export * from '@/features/kangur/ui/components/KangurGameCalendarTrainingWidget';
export * from '@/features/kangur/ui/components/KangurGameGeometryTrainingWidget';
export * from '@/features/kangur/ui/components/KangurGameHomeActionsWidget';
export * from '@/features/kangur/ui/components/KangurGameHomeHeroWidget';
export * from '@/features/kangur/ui/components/KangurGameKangurSessionWidget';
export * from '@/features/kangur/ui/components/KangurGameKangurSetupWidget';
export * from '@/features/kangur/ui/components/KangurGameNavigationWidget';
export * from '@/features/kangur/ui/components/game-setup/KangurGameOperationSelectorWidget';
export * from '@/features/kangur/ui/components/KangurGameQuestionWidget';
export * from '@/features/kangur/ui/components/KangurGameResultWidget';
export * from '@/features/kangur/ui/components/KangurGameTrainingSetupWidget';
export * from '@/features/kangur/ui/components/KangurGameXpToastWidget';
export * from '@/features/kangur/ui/components/lesson-runtime/KangurLessonNavigationWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileAssignmentsWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileHeroWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileLevelProgressWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileMasteryWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileOverviewWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfilePerformanceWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileResultsWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileRecommendationsWidget';
export * from '@/features/kangur/ui/components/learner-profile/KangurLearnerProfileSessionsWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardAssignmentsWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardAssignmentsMonitoringWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardHeroWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardLearnerManagementWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardProgressWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardScoresWidget';
export * from '@/features/kangur/ui/components/parent-dashboard/KangurParentDashboardTabsWidget';
export { default as Leaderboard } from '@/features/kangur/ui/components/Leaderboard';
export * from '@/features/kangur/ui/components/lesson-library/KangurLessonsCatalogWidget';
export { default as PlayerProgressCard } from '@/features/kangur/ui/components/PlayerProgressCard';
export { KangurSocialPipelineQueuePanel } from '@/features/kangur/social/admin/workspace/KangurSocialPipelineQueuePanel';
export { AdminKangurPageShell } from '@/features/kangur/admin/AdminKangurPageShell';
export { AdminKangurAppearancePage } from '@/features/kangur/admin/AdminKangurAppearancePage';
export { AdminKangurBuilderPage } from '@/features/kangur/admin/AdminKangurBuilderPage';
export { AdminKangurContentManagerPage } from '@/features/kangur/admin/AdminKangurContentManagerPage';
export { AdminKangurDocumentationPage } from '@/features/kangur/admin/AdminKangurDocumentationPage';
export { AdminKangurLessonsManagerPage } from '@/features/kangur/admin/AdminKangurLessonsManagerPage';
export { AdminKangurObservabilityPage } from '@/features/kangur/admin/AdminKangurObservabilityPage';
export { AdminKangurAiTutorContentPage } from '@/features/kangur/admin/AdminKangurAiTutorContentPage';
export { default as AdminKangurSettingsPage } from '@/features/kangur/admin/AdminKangurSettingsPage';
export { AdminKangurSocialPage } from '@/features/kangur/social/admin/AdminKangurSocialPage';
export { AdminKangurTestSuitesManagerPage } from '@/features/kangur/admin/AdminKangurTestSuitesManagerPage';
export { FrontendRouteLoadingFallback } from '@/features/kangur/ui/FrontendRouteLoadingFallback';
export { KangurFeatureRouteShell } from '@/features/kangur/ui/KangurFeatureRouteShell';
export { KangurSSRSkeleton } from '@/features/kangur/ui/KangurSSRSkeleton';
export { KangurSurfaceClassSync } from '@/features/kangur/ui/KangurSurfaceClassSync';
export { default as FrontendPublicOwnerShellClient } from '@/features/kangur/ui/FrontendPublicOwnerShellClient';
export type { FrontendPublicOwnerShellProps } from '@/features/kangur/ui/FrontendPublicOwnerShellClient';
export { KangurStorefrontAppearanceProvider } from '@/features/kangur/ui/KangurStorefrontAppearanceProvider';
export { KangurStandardPageLayout } from '@/features/kangur/ui/components/KangurStandardPageLayout';
export { KangurServerShell } from '@/features/kangur/ui/components/KangurServerShell';
export { logKangurClientError } from '@/features/kangur/observability/client';
