export const PARAMETER_INFERENCE_PATH_EDGES = [
  {
    id: 'edge-params-trigger-fetcher',
    from: 'node-trigger-params',
    to: 'node-fetcher-params',
    fromPort: 'trigger',
    toPort: 'trigger',
  },
  {
    id: 'edge-params-00',
    from: 'node-parser-params',
    to: 'node-query-params',
    fromPort: 'bundle',
    toPort: 'bundle',
  },
  {
    id: 'edge-params-01',
    from: 'node-fetcher-params',
    to: 'node-parser-params',
    fromPort: 'context',
    toPort: 'context',
  },
  {
    id: 'edge-params-02',
    from: 'node-fetcher-params',
    to: 'node-query-params',
    fromPort: 'context',
    toPort: 'context',
  },
  {
    id: 'edge-params-03',
    from: 'node-query-params',
    to: 'node-prompt-template-params',
    fromPort: 'result',
    toPort: 'result',
  },
  {
    id: 'edge-params-04',
    from: 'node-prompt-template-params',
    to: 'node-model-template-params',
    fromPort: 'prompt',
    toPort: 'prompt',
  },
  {
    id: 'edge-params-05',
    from: 'node-model-template-params',
    to: 'node-vp-template-params',
    fromPort: 'result',
    toPort: 'result',
  },
  {
    id: 'edge-params-vp-lc',
    from: 'node-vp-template-params',
    to: 'node-lc-template-params',
    fromPort: 'value',
    toPort: 'value',
  },
  {
    id: 'edge-params-lc-router-valid',
    from: 'node-lc-template-params',
    to: 'node-router-seed-params',
    fromPort: 'valid',
    toPort: 'valid',
  },
  {
    id: 'edge-params-vp-router-value',
    from: 'node-vp-template-params',
    to: 'node-router-seed-params',
    fromPort: 'value',
    toPort: 'value',
  },
  {
    id: 'edge-params-router-seed',
    from: 'node-router-seed-params',
    to: 'node-seed-params',
    fromPort: 'value',
    toPort: 'value',
  },
  {
    id: 'edge-params-07',
    from: 'node-fetcher-params',
    to: 'node-seed-params',
    fromPort: 'entityId',
    toPort: 'entityId',
  },
  {
    id: 'edge-params-08',
    from: 'node-fetcher-params',
    to: 'node-seed-params',
    fromPort: 'entityType',
    toPort: 'entityType',
  },
  {
    id: 'edge-params-09',
    from: 'node-parser-params',
    to: 'node-prompt-params',
    fromPort: 'bundle',
    toPort: 'bundle',
  },
  {
    id: 'edge-params-10',
    from: 'node-query-params',
    to: 'node-prompt-params',
    fromPort: 'result',
    toPort: 'result',
  },
  {
    id: 'edge-params-11',
    from: 'node-prompt-params',
    to: 'node-model-params',
    fromPort: 'prompt',
    toPort: 'prompt',
  },
  {
    id: 'edge-params-12',
    from: 'node-prompt-params',
    to: 'node-model-params',
    fromPort: 'images',
    toPort: 'images',
  },
  {
    id: 'edge-params-13',
    from: 'node-model-params',
    to: 'node-regex-params',
    fromPort: 'result',
    toPort: 'value',
  },
  {
    id: 'edge-params-14',
    from: 'node-regex-params',
    to: 'node-update-params',
    fromPort: 'value',
    toPort: 'value',
  },
  {
    id: 'edge-params-15',
    from: 'node-fetcher-params',
    to: 'node-update-params',
    fromPort: 'entityId',
    toPort: 'entityId',
  },
  {
    id: 'edge-params-16',
    from: 'node-fetcher-params',
    to: 'node-update-params',
    fromPort: 'entityType',
    toPort: 'entityType',
  },
  {
    id: 'edge-params-17',
    from: 'node-query-params',
    to: 'node-update-params',
    fromPort: 'result',
    toPort: 'result',
  },
  {
    id: 'edge-params-fetcher-update-ctx',
    from: 'node-fetcher-params',
    to: 'node-update-params',
    fromPort: 'context',
    toPort: 'context',
  },
];
