import { DOCUMENTATION_MODULE_IDS, type DocumentationEntry } from '@/features/documentation/types';

export const SHARED_TOOLTIP_DOCUMENTATION_CATALOG: DocumentationEntry[] = [
  {
    id: 'vector_toolbar_tool_select',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Select Tool',
    summary: 'Switches to selection/edit mode for existing vector shapes and points.',
    section: 'Toolbar',
    aliases: ['select', 'edit'],
  },
  {
    id: 'vector_toolbar_tool_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Polygon Tool',
    summary: 'Draws polygon points to build closed or open shape paths.',
    section: 'Toolbar',
    aliases: ['polygon', 'pen'],
  },
  {
    id: 'vector_toolbar_tool_lasso',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Lasso Tool',
    summary: 'Draws freeform lasso paths for organic mask and shape selection.',
    section: 'Toolbar',
    aliases: ['lasso'],
  },
  {
    id: 'vector_toolbar_tool_rect',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Rectangle Tool',
    summary: 'Creates axis-aligned rectangle vector shapes.',
    section: 'Toolbar',
    aliases: ['rectangle', 'rect'],
  },
  {
    id: 'vector_toolbar_tool_ellipse',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Ellipse Tool',
    summary: 'Creates circular or elliptical vector shapes.',
    section: 'Toolbar',
    aliases: ['ellipse', 'circle'],
  },
  {
    id: 'vector_toolbar_tool_brush',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Brush Tool',
    summary: 'Paints freehand brush-like vector strokes.',
    section: 'Toolbar',
    aliases: ['brush'],
  },
  {
    id: 'vector_toolbar_action_undo',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Undo',
    summary: 'Reverts the most recent vector editing action.',
    section: 'Actions',
    aliases: ['undo', 'ctrl+z'],
  },
  {
    id: 'vector_toolbar_action_redo',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Redo',
    summary: 'Reapplies the last undone vector editing action.',
    section: 'Actions',
    aliases: ['redo', 'ctrl+shift+z'],
  },
  {
    id: 'vector_toolbar_action_close_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Close Polygon',
    summary: 'Closes the active polygon by connecting last and first points.',
    section: 'Actions',
    aliases: ['close polygon'],
  },
  {
    id: 'vector_toolbar_action_detach_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Detach Polygon',
    summary: 'Detaches selected polygon from linked editing context.',
    section: 'Actions',
    aliases: ['detach polygon'],
  },
  {
    id: 'vector_toolbar_action_clear_shapes',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Clear Shapes',
    summary: 'Removes all current vector shapes from the active layer.',
    section: 'Actions',
    aliases: ['clear shapes'],
  },
  {
    id: 'vector_toolbar_action_smooth_path',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Smooth Path',
    summary: 'Applies path smoothing to reduce jagged edges.',
    section: 'Actions',
    aliases: ['smooth path'],
  },
  {
    id: 'vector_toolbar_action_simplify_path',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Simplify Path',
    summary: 'Reduces path complexity by removing excess points.',
    section: 'Actions',
    aliases: ['simplify path'],
  },
  {
    id: 'import_sku_exists_warning',
    moduleId: DOCUMENTATION_MODULE_IDS.dataImportExport,
    title: 'SKU Exists Warning',
    summary: 'Indicates this SKU already exists in the current database.',
    section: 'Import Grid',
    aliases: ['sku exists'],
  },
  {
    id: 'rule_item_copy_json',
    moduleId: DOCUMENTATION_MODULE_IDS.promptEngine,
    title: 'Copy JSON',
    summary: 'Copies the current rule JSON payload to clipboard.',
    section: 'Rule Actions',
    aliases: ['copy json'],
  },
  {
    id: 'system_logs_ai_interpretation',
    moduleId: DOCUMENTATION_MODULE_IDS.observability,
    title: 'AI Interpretation',
    summary: 'Runs AI-assisted interpretation for the selected log event.',
    section: 'System Logs',
    aliases: ['ai interpretation'],
  },
  {
    id: 'component_settings_hide_right_panel',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Hide Right Panel',
    summary: 'Collapses the right-side component settings panel.',
    section: 'Component Settings Header',
    aliases: ['hide right panel'],
  },
  {
    id: 'component_settings_toggle_inspector',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Toggle Inspector',
    summary: 'Enables or disables on-canvas inspector targeting mode.',
    section: 'Component Settings Header',
    aliases: ['toggle inspector'],
  },
  {
    id: 'component_settings_desktop_preview',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Desktop Preview',
    summary: 'Switches builder preview to desktop viewport mode.',
    section: 'Component Settings Header',
    aliases: ['desktop preview'],
  },
  {
    id: 'component_settings_mobile_preview',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Mobile Preview',
    summary: 'Switches builder preview to mobile viewport mode.',
    section: 'Component Settings Header',
    aliases: ['mobile preview'],
  },
  {
    id: 'component_settings_toggle_editor_chrome',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Toggle Editor Chrome',
    summary: 'Shows or hides editor chrome overlays in preview.',
    section: 'Component Settings Header',
    aliases: ['toggle editor chrome'],
  },
  {
    id: 'animation_draw_path_canvas',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Draw Path On Canvas',
    summary: 'Opens vector overlay to draw a path directly on the preview canvas.',
    section: 'Animation Advanced',
    aliases: ['draw path'],
  },
  {
    id: 'animation_clear_path_canvas',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Clear Path',
    summary: 'Clears path input and vector overlay path shapes for this control.',
    section: 'Animation Advanced',
    aliases: ['clear path'],
  },
  {
    id: 'product_imported_badge',
    moduleId: DOCUMENTATION_MODULE_IDS.products,
    title: 'Imported Product Badge',
    summary: 'Marks products that originated from external import flows.',
    section: 'Product List',
    aliases: ['imported product'],
  },
];
