import type { ProductDataHookResult, ProductDataResultInput } from './useProductData.types';

export const createProductDataResult = ({
  actions,
  data,
  isFetching,
  isLoading,
  loadError,
  refresh,
  state,
  totalPages,
}: ProductDataResultInput): ProductDataHookResult => ({
  data,
  totalPages,
  page: state.page,
  setPage: actions.setPage,
  pageSize: state.pageSize,
  setPageSize: actions.setPageSize,
  search: state.search,
  setSearch: actions.setSearch,
  productId: state.productId,
  setProductId: actions.setProductId,
  idMatchMode: state.idMatchMode,
  setIdMatchMode: actions.setIdMatchMode,
  sku: state.sku,
  setSku: actions.setSku,
  description: state.description,
  setDescription: actions.setDescription,
  categoryId: state.categoryId,
  setCategoryId: actions.setCategoryId,
  minPrice: state.minPrice,
  setMinPrice: actions.setMinPrice,
  maxPrice: state.maxPrice,
  setMaxPrice: actions.setMaxPrice,
  stockValue: state.stockValue,
  setStockValue: actions.setStockValue,
  stockOperator: state.stockOperator,
  setStockOperator: actions.setStockOperator,
  startDate: state.startDate,
  setStartDate: actions.setStartDate,
  endDate: state.endDate,
  setEndDate: actions.setEndDate,
  advancedFilter: state.advancedFilter,
  setAdvancedFilter: actions.setAdvancedFilter,
  activeAdvancedFilterPresetId: state.activeAdvancedFilterPresetId,
  setAdvancedFilterState: actions.setAdvancedFilterState,
  catalogFilter: state.catalogFilter,
  setCatalogFilter: actions.setCatalogFilter,
  baseExported: state.baseExported,
  setBaseExported: actions.setBaseExported,
  includeArchived: state.includeArchived,
  setIncludeArchived: actions.setIncludeArchived,
  parsedMatchProductIds: state.parsedMatchProductIds,
  setParsedMatchProductIds: actions.setParsedMatchProductIds,
  clearParsedMatchProductIds: actions.clearParsedMatchProductIds,
  loadError,
  isLoading,
  isFetching,
  refresh,
});
