import type { DocumentationEntry } from '@/shared/contracts/documentation';

import { AI_PATHS_DOCUMENTATION_CATALOG } from './ai-paths';
import { IMAGE_STUDIO_DOCUMENTATION_CATALOG } from './image-studio';
import { PROMPT_EXPLODER_DOCUMENTATION_CATALOG } from './prompt-exploder';
import { SHARED_TOOLTIP_DOCUMENTATION_CATALOG } from './shared-tooltip-docs';
import { VALIDATOR_DOCUMENTATION_CATALOG } from './validator';

export const DOCUMENTATION_CATALOG: DocumentationEntry[] = [
  ...AI_PATHS_DOCUMENTATION_CATALOG,
  ...IMAGE_STUDIO_DOCUMENTATION_CATALOG,
  ...PROMPT_EXPLODER_DOCUMENTATION_CATALOG,
  ...SHARED_TOOLTIP_DOCUMENTATION_CATALOG,
  ...VALIDATOR_DOCUMENTATION_CATALOG,
];

export {
  AI_PATHS_DOCUMENTATION_CATALOG,
  IMAGE_STUDIO_DOCUMENTATION_CATALOG,
  PROMPT_EXPLODER_DOCUMENTATION_CATALOG,
  SHARED_TOOLTIP_DOCUMENTATION_CATALOG,
  VALIDATOR_DOCUMENTATION_CATALOG,
};
