import { DOCUMENTATION_MODULE_IDS, type DocumentationEntry } from '@/shared/lib/documentation/types';

export const SHARED_TOOLTIP_DOCUMENTATION_CATALOG: DocumentationEntry[] = [
  {
    id: 'vector_toolbar_tool_select',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Select Tool',
    content: 'Switches to selection/edit mode for existing vector shapes and points.',
    keywords: ['select', 'edit'],
  },
  {
    id: 'vector_toolbar_tool_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Polygon Tool',
    content: 'Draws polygon points to build closed or open shape paths.',
    keywords: ['polygon', 'pen'],
  },
  {
    id: 'vector_toolbar_tool_lasso',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Lasso Tool',
    content: 'Draws freeform lasso paths for organic mask and shape selection.',
    keywords: ['lasso'],
  },
  {
    id: 'vector_toolbar_tool_rect',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Rectangle Tool',
    content: 'Creates axis-aligned rectangle vector shapes.',
    keywords: ['rectangle', 'rect'],
  },
  {
    id: 'vector_toolbar_tool_ellipse',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Ellipse Tool',
    content: 'Creates circular or elliptical vector shapes.',
    keywords: ['ellipse', 'circle'],
  },
  {
    id: 'vector_toolbar_tool_brush',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Brush Tool',
    content: 'Paints freehand brush-like vector strokes.',
    keywords: ['brush'],
  },
  {
    id: 'vector_toolbar_action_undo',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Undo',
    content: 'Reverts the most recent vector editing action.',
    keywords: ['undo', 'ctrl+z'],
  },
  {
    id: 'vector_toolbar_action_redo',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Redo',
    content: 'Reapplies the last undone vector editing action.',
    keywords: ['redo', 'ctrl+shift+z'],
  },
  {
    id: 'vector_toolbar_action_close_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Close Polygon',
    content: 'Closes the active polygon by connecting last and first points.',
    keywords: ['close polygon'],
  },
  {
    id: 'vector_toolbar_action_detach_polygon',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Detach Polygon',
    content: 'Detaches selected polygon from linked editing context.',
    keywords: ['detach polygon'],
  },
  {
    id: 'vector_toolbar_action_clear_shapes',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Clear Shapes',
    content: 'Removes all current vector shapes from the active layer.',
    keywords: ['clear shapes'],
  },
  {
    id: 'vector_toolbar_action_smooth_path',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Smooth Path',
    content: 'Applies path smoothing to reduce jagged edges.',
    keywords: ['smooth path'],
  },
  {
    id: 'vector_toolbar_action_simplify_path',
    moduleId: DOCUMENTATION_MODULE_IDS.vectorDrawing,
    title: 'Simplify Path',
    content: 'Reduces path complexity by removing excess points.',
    keywords: ['simplify path'],
  },
  {
    id: 'import_sku_exists_warning',
    moduleId: DOCUMENTATION_MODULE_IDS.dataImportExport,
    title: 'SKU Exists Warning',
    content: 'Indicates this SKU already exists in the current database.',
    keywords: ['sku exists'],
  },
  {
    id: 'rule_item_copy_json',
    moduleId: DOCUMENTATION_MODULE_IDS.promptEngine,
    title: 'Copy JSON',
    content: 'Copies the current rule JSON payload to clipboard.',
    keywords: ['copy json'],
  },
  {
    id: 'system_logs_ai_interpretation',
    moduleId: DOCUMENTATION_MODULE_IDS.observability,
    title: 'AI Interpretation',
    content: 'Runs AI-assisted interpretation for the selected log event.',
    keywords: ['ai interpretation'],
  },
  {
    id: 'component_settings_hide_right_panel',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Hide Right Panel',
    content: 'Collapses the right-side component settings panel.',
    keywords: ['hide right panel'],
  },
  {
    id: 'component_settings_toggle_inspector',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Toggle Inspector',
    content: 'Enables or disables on-canvas inspector targeting mode.',
    keywords: ['toggle inspector'],
  },
  {
    id: 'component_settings_desktop_preview',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Desktop Preview',
    content: 'Switches builder preview to desktop viewport mode.',
    keywords: ['desktop preview'],
  },
  {
    id: 'component_settings_mobile_preview',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Mobile Preview',
    content: 'Switches builder preview to mobile viewport mode.',
    keywords: ['mobile preview'],
  },
  {
    id: 'component_settings_toggle_editor_chrome',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Toggle Editor Chrome',
    content: 'Shows or hides editor chrome overlays in preview.',
    keywords: ['toggle editor chrome'],
  },
  {
    id: 'animation_draw_path_canvas',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Draw Path On Canvas',
    content: 'Opens vector overlay to draw a path directly on the preview canvas.',
    keywords: ['draw path'],
  },
  {
    id: 'animation_clear_path_canvas',
    moduleId: DOCUMENTATION_MODULE_IDS.cms,
    title: 'Clear Path',
    content: 'Clears path input and vector overlay path shapes for this control.',
    keywords: ['clear path'],
  },
  {
    id: 'product_imported_badge',
    moduleId: DOCUMENTATION_MODULE_IDS.products,
    title: 'Imported Product Badge',
    content: 'Marks products that originated from external import flows.',
    keywords: ['imported product'],
  },
  {
    id: 'case_resolver_advanced_filters',
    moduleId: DOCUMENTATION_MODULE_IDS.caseResolver,
    title: 'Advanced Filters',
    content: 'Opens extended filtering options for document attributes.',
    keywords: ['filters', 'search'],
  },
  {
    id: 'case_resolver_locked_indicator',
    moduleId: DOCUMENTATION_MODULE_IDS.caseResolver,
    title: 'Document Locked',
    content: 'Indicates this document is locked and cannot be edited.',
    keywords: ['locked', 'security'],
  },
  {
    id: 'case_resolver_link_document',
    moduleId: DOCUMENTATION_MODULE_IDS.caseResolver,
    title: 'Link Document',
    content: 'Creates a relationship link to the target document.',
    keywords: ['link', 'relation'],
  },
  {
    id: 'case_resolver_browse_case_docs',
    moduleId: DOCUMENTATION_MODULE_IDS.caseResolver,
    title: 'Browse Case Documents',
    content: 'Drills down into the document list for this specific case.',
    keywords: ['browse', 'drill'],
  },
];
