export type ValidatorFunctionDoc = {
  id: string;
  symbol: string;
  file: string;
  purpose: string;
  params: string[];
  returns: string;
  errors: string[];
  edgeCases: string[];
  example: string;
};

export type ValidatorUiDoc = {
  id: string;
  title: string;
  description: string;
  relatedFunctions: string[];
};

export const VALIDATOR_FUNCTION_DOCS: ValidatorFunctionDoc[] = [
  {
    id: 'core.normalizeValidationDebounceMs',
    symbol: 'normalizeValidationDebounceMs',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Clamps and normalizes debounce value to an integer between 0 and 30000 ms.',
    params: ['value: unknown raw debounce value from persisted settings or request payload.'],
    returns: 'Safe debounce delay in milliseconds.',
    errors: ['No throws.'],
    edgeCases: ['Non-finite numbers resolve to 0.', 'Negative values clamp to 0.'],
    example: 'normalizeValidationDebounceMs(31200.8) // 30000',
  },
  {
    id: 'core.normalizePostAcceptBehavior',
    symbol: 'normalizePostAcceptBehavior',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Normalizes post-accept behavior to supported enum values.',
    params: ['value: unknown incoming post-accept behavior.'],
    returns: 'revalidate or stop_after_accept.',
    errors: ['No throws.'],
    edgeCases: ['Unknown values fallback to revalidate.'],
    example: "normalizePostAcceptBehavior('stop_after_accept')",
  },
  {
    id: 'core.normalizePatternSequence',
    symbol: 'normalizePatternSequence',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Produces a deterministic sequence index for ordering patterns.',
    params: ['pattern: pattern record.', 'fallbackIndex: array index when sequence is unset.'],
    returns: 'Non-negative integer sequence number.',
    errors: ['No throws.'],
    edgeCases: ['Missing sequence uses (fallbackIndex + 1) * 10.'],
    example: 'normalizePatternSequence(pattern, 3)',
  },
  {
    id: 'core.normalizePatternChainMode',
    symbol: 'normalizePatternChainMode',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Normalizes chain execution mode for grouped patterns.',
    params: ['pattern: pattern containing optional chainMode.'],
    returns: 'continue, stop_on_match, or stop_on_replace.',
    errors: ['No throws.'],
    edgeCases: ['Unsupported values fallback to continue.'],
    example: 'normalizePatternChainMode(pattern)',
  },
  {
    id: 'core.normalizePatternMaxExecutions',
    symbol: 'normalizePatternMaxExecutions',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Bounds max execution count for iterative regex processing.',
    params: ['pattern: pattern with optional maxExecutions.'],
    returns: 'Integer in range 1..20.',
    errors: ['No throws.'],
    edgeCases: ['Invalid values fallback to 1.'],
    example: 'normalizePatternMaxExecutions(pattern)',
  },
  {
    id: 'core.buildSequenceGroupCounts',
    symbol: 'buildSequenceGroupCounts',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Counts enabled sequence-grouped patterns by scope key.',
    params: ['patterns: ordered pattern list.'],
    returns: 'Map keyed by group+target+locale scope.',
    errors: ['No throws.'],
    edgeCases: ['Disabled patterns are excluded.'],
    example: 'buildSequenceGroupCounts(patterns)',
  },
  {
    id: 'core.isPatternInSequenceGroup',
    symbol: 'isPatternInSequenceGroup',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Determines if a pattern belongs to a multi-step sequence.',
    params: ['pattern: candidate pattern.', 'counts: map produced by buildSequenceGroupCounts.'],
    returns: 'True when group size is greater than one.',
    errors: ['No throws.'],
    edgeCases: ['Missing group id returns false.'],
    example: 'isPatternInSequenceGroup(pattern, counts)',
  },
  {
    id: 'core.sortValidatorPatterns',
    symbol: 'sortValidatorPatterns',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Sorts patterns by sequence, target, and label for deterministic runtime order.',
    params: ['patterns: unsorted pattern list.'],
    returns: 'New sorted array.',
    errors: ['No throws.'],
    edgeCases: ['Stable fallback ordering uses target and label.'],
    example: 'sortValidatorPatterns(patterns)',
  },
  {
    id: 'core.resolveFieldTargetAndLocale',
    symbol: 'resolveFieldTargetAndLocale',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Maps form field names to validator target and locale context.',
    params: ['fieldName: form key such as name_en or sku.'],
    returns: 'target and locale tuple.',
    errors: ['No throws.'],
    edgeCases: ['Unknown fields return target=null.'],
    example: "resolveFieldTargetAndLocale('name_pl')",
  },
  {
    id: 'core.isPatternLocaleMatch',
    symbol: 'isPatternLocaleMatch',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Checks locale compatibility between pattern and field.',
    params: [
      'patternLocale: locale configured on pattern.',
      'fieldLocale: locale inferred from field name.',
    ],
    returns: 'Boolean locale match decision.',
    errors: ['No throws.'],
    edgeCases: ['Pattern without locale matches any locale.'],
    example: "isPatternLocaleMatch('pl', 'pl')",
  },
  {
    id: 'core.normalizeReplacementFields',
    symbol: 'normalizeReplacementFields',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Validates, deduplicates, and normalizes replacement field allowlist.',
    params: ['fields: optional replacement field list.'],
    returns: 'Filtered unique list of allowed fields.',
    errors: ['No throws.'],
    edgeCases: ['Invalid entries are dropped silently.'],
    example: "normalizeReplacementFields(['sku', 'sku'])",
  },
  {
    id: 'core.isReplacementAllowedForField',
    symbol: 'isReplacementAllowedForField',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Checks whether replacement is permitted for a specific form field.',
    params: ['pattern: pattern with replacement configuration.', 'fieldName: form field name.'],
    returns: 'Boolean allow/deny.',
    errors: ['No throws.'],
    edgeCases: ['Empty allowlist means global replacement.'],
    example: "isReplacementAllowedForField(pattern, 'name_en')",
  },
  {
    id: 'core.isLatestPriceStockMirrorPattern',
    symbol: 'isLatestPriceStockMirrorPattern',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Detects dynamic mirror patterns pulling latest price or stock values.',
    params: ['pattern: candidate pattern.'],
    returns: 'True when pattern is latest_product_field mirror for price/stock.',
    errors: ['No throws.'],
    edgeCases: ['Non-dynamic replacement values return false.'],
    example: 'isLatestPriceStockMirrorPattern(pattern)',
  },
  {
    id: 'core.isRuntimePatternEnabled',
    symbol: 'isRuntimePatternEnabled',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Identifies patterns delegated to runtime evaluator.',
    params: ['pattern: candidate pattern.'],
    returns: 'True when runtimeEnabled is set and runtimeType is not none.',
    errors: ['No throws.'],
    edgeCases: ['Disabled runtimeType none always returns false.'],
    example: 'isRuntimePatternEnabled(pattern)',
  },
  {
    id: 'core.resolvePatternLaunchSourceValue',
    symbol: 'resolvePatternLaunchSourceValue',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Resolves the value used to evaluate launch condition.',
    params: [
      'pattern: pattern launch settings.',
      'fieldValue: current field value.',
      'values: full form values.',
      'latestProductValues: latest persisted product snapshot.',
    ],
    returns: 'Source value string used by launch operator.',
    errors: ['No throws.'],
    edgeCases: ['Missing source field resolves to empty string.'],
    example:
      'resolvePatternLaunchSourceValue({ pattern, fieldValue, values, latestProductValues })',
  },
  {
    id: 'core.shouldLaunchPattern',
    symbol: 'shouldLaunchPattern',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Evaluates launch gates for static and sequence patterns.',
    params: [
      'pattern: candidate pattern.',
      'validationScope: current form instance scope.',
      'fieldValue: field value under validation.',
      'values: full form values.',
      'latestProductValues: latest persisted product snapshot.',
    ],
    returns: 'Boolean launch decision.',
    errors: ['No throws.'],
    edgeCases: [
      'Missing external source field blocks launch.',
      'Out-of-scope behavior depends on launchScopeBehavior.',
    ],
    example:
      'shouldLaunchPattern({ pattern, validationScope, fieldValue, values, latestProductValues })',
  },
  {
    id: 'core.resolvePatternReplacementValue',
    symbol: 'resolvePatternReplacementValue',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Resolves static or dynamic replacement payload for matched pattern.',
    params: [
      'pattern: candidate pattern.',
      'fieldValue: current field value.',
      'values: full form values.',
      'latestProductValues: latest persisted product snapshot.',
    ],
    returns: 'Resolved replacement object or null.',
    errors: ['No throws.'],
    edgeCases: [
      'Invalid dynamic recipe returns null.',
      'Dynamic recipes always use replace_whole_field.',
    ],
    example: 'resolvePatternReplacementValue({ pattern, fieldValue, values, latestProductValues })',
  },
  {
    id: 'core.applyResolvedReplacement',
    symbol: 'applyResolvedReplacement',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Applies replacement to value using recipe apply mode.',
    params: [
      'value: current field value.',
      'pattern: pattern regex/flags context.',
      'replacement: resolved replacement data.',
    ],
    returns: 'Rewritten field value.',
    errors: ['Regex compilation errors are swallowed and original value is returned.'],
    edgeCases: ['No replacement value returns original input.'],
    example: 'applyResolvedReplacement({ value, pattern, replacement })',
  },
  {
    id: 'core.deriveDiffSegment',
    symbol: 'deriveDiffSegment',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Computes minimal changed segment between original and replaced values.',
    params: ['before: original value.', 'after: final value.'],
    returns: 'Diff index, length, and matchText snippet.',
    errors: ['No throws.'],
    edgeCases: ['Equal strings produce a single-character fallback segment.'],
    example: "deriveDiffSegment('abc', 'axc')",
  },
  {
    id: 'core.buildFieldIssues',
    symbol: 'buildFieldIssues',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Builds static validator issues by applying eligible patterns to each field.',
    params: [
      'values: form values map.',
      'patterns: all validation patterns.',
      'latestProductValues: latest persisted product values.',
      'validationScope: form instance scope.',
    ],
    returns: 'Map of field names to issue arrays.',
    errors: ['Invalid regex in persisted pattern is skipped defensively.'],
    edgeCases: [
      'Sequence groups merge outputs into one issue.',
      'No-op replacements can be suppressed per pattern setting.',
    ],
    example: 'buildFieldIssues({ values, patterns, latestProductValues, validationScope })',
  },
  {
    id: 'core.mergeFieldIssueMaps',
    symbol: 'mergeFieldIssueMaps',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Merges static and runtime issue maps by field.',
    params: [
      'staticIssues: issues from static engine.',
      'runtimeIssues: issues from runtime evaluator.',
    ],
    returns: 'Combined issue map.',
    errors: ['No throws.'],
    edgeCases: ['Fields existing in one map are preserved.'],
    example: 'mergeFieldIssueMaps(staticIssues, runtimeIssues)',
  },
  {
    id: 'core.areIssueMapsEquivalent',
    symbol: 'areIssueMapsEquivalent',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Performs deep structural equality check for issue maps.',
    params: ['left: previous issue map.', 'right: next issue map.'],
    returns: 'True when both maps contain identical ordered issues.',
    errors: ['No throws.'],
    edgeCases: ['Order differences count as non-equivalent.'],
    example: 'areIssueMapsEquivalent(prev, next)',
  },
  {
    id: 'core.getIssueReplacementPreview',
    symbol: 'getIssueReplacementPreview',
    file: 'src/features/products/validation-engine/core.ts',
    purpose: 'Generates preview value for a single issue replacement.',
    params: ['value: current field value.', 'issue: issue record with replacement metadata.'],
    returns: 'Preview value after applying issue replacement.',
    errors: ['Regex errors are swallowed and original value is returned.'],
    edgeCases: ['Whole-field apply mode bypasses regex replace path.'],
    example: 'getIssueReplacementPreview(value, issue)',
  },
  {
    id: 'helpers.normalizeReplacementFields',
    symbol: 'normalizeReplacementFields',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Normalizes replacement fields selected in modal/controller state.',
    params: ['fields: candidate replacement field list.'],
    returns: 'Validated and deduplicated replacement fields.',
    errors: ['No throws.'],
    edgeCases: ['Invalid fields are removed.'],
    example: "normalizeReplacementFields(['name_en', 'name_en'])",
  },
  {
    id: 'helpers.formatReplacementFields',
    symbol: 'formatReplacementFields',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Formats replacement field list into user-facing label string.',
    params: ['fields: replacement fields list.'],
    returns: 'Localized display text.',
    errors: ['No throws.'],
    edgeCases: ['Empty list maps to all matching fields.'],
    example: 'formatReplacementFields(pattern.replacementFields)',
  },
  {
    id: 'helpers.getReplacementFieldsForTarget',
    symbol: 'getReplacementFieldsForTarget',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Returns replacement fields allowed for target.',
    params: ['target: pattern target from form state.'],
    returns: 'List of allowed replacement field keys.',
    errors: ['No throws.'],
    edgeCases: ['Unknown target falls back to sku.'],
    example: "getReplacementFieldsForTarget('name')",
  },
  {
    id: 'helpers.isLocaleTarget',
    symbol: 'isLocaleTarget',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Indicates if target supports locale selector.',
    params: ['target: pattern target.'],
    returns: 'True for name and description targets.',
    errors: ['No throws.'],
    edgeCases: ['Non-localized targets return false.'],
    example: "isLocaleTarget('sku')",
  },
  {
    id: 'helpers.isLatestFieldMirrorPattern',
    symbol: 'isLatestFieldMirrorPattern',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Detects auto-template latest value mirror patterns for price/stock.',
    params: ['pattern: existing pattern.', 'field: price or stock target.'],
    returns: 'Boolean match result.',
    errors: ['No throws.'],
    edgeCases: ['Static replacers are not treated as mirror patterns.'],
    example: "isLatestFieldMirrorPattern(pattern, 'price')",
  },
  {
    id: 'helpers.isNameSecondSegmentDimensionPattern',
    symbol: 'isNameSecondSegmentDimensionPattern',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Detects name segment templates used for length/height mapping.',
    params: ['pattern: existing pattern.', 'target: size_length or length.'],
    returns: 'Boolean match result.',
    errors: ['No throws.'],
    edgeCases: ['Requires form_field name_en dynamic recipe.'],
    example: "isNameSecondSegmentDimensionPattern(pattern, 'length')",
  },
  {
    id: 'helpers.getSourceFieldOptionsForTarget',
    symbol: 'getSourceFieldOptionsForTarget',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Returns source-field options for dynamic replacement and launch settings.',
    params: ['target: pattern target currently selected.'],
    returns: 'Array of selectable source field options.',
    errors: ['No throws.'],
    edgeCases: ['Current implementation returns common source list for all targets.'],
    example: 'getSourceFieldOptionsForTarget(formData.target)',
  },
  {
    id: 'helpers.buildDynamicRecipeFromForm',
    symbol: 'buildDynamicRecipeFromForm',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Builds dynamic replacement recipe object from modal form state.',
    params: ['formData: full pattern modal state.'],
    returns: 'Dynamic recipe or null when required source data is missing.',
    errors: ['No throws.'],
    edgeCases: ['Numeric fields are normalized to finite numbers or null.'],
    example: 'buildDynamicRecipeFromForm(formData)',
  },
  {
    id: 'helpers.buildLatestFieldRecipe',
    symbol: 'buildLatestFieldRecipe',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Builds encoded dynamic recipe for latest product field mirror templates.',
    params: ['field: price or stock.'],
    returns: 'Encoded recipe string.',
    errors: ['No throws.'],
    edgeCases: ['Always sets replace_whole_field target apply mode.'],
    example: "buildLatestFieldRecipe('stock')",
  },
  {
    id: 'helpers.buildDuplicateLabel',
    symbol: 'buildDuplicateLabel',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Generates unique duplicate label with copy suffix.',
    params: ['label: base pattern label.', 'existingLabels: lowercase label set.'],
    returns: 'Unique duplicate label.',
    errors: ['No throws.'],
    edgeCases: ['Empty label falls back to Pattern.'],
    example: 'buildDuplicateLabel(pattern.label, existingLabels)',
  },
  {
    id: 'helpers.buildUniqueLabel',
    symbol: 'buildUniqueLabel',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Builds unique label by incrementing numeric suffix.',
    params: ['label: desired label.', 'existingLabels: lowercase label set.'],
    returns: 'Unique label not present in existing set.',
    errors: ['No throws.'],
    edgeCases: ['Empty label falls back to Pattern.'],
    example: "buildUniqueLabel('Price from latest product', labels)",
  },
  {
    id: 'helpers.getPatternSequence',
    symbol: 'getPatternSequence',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Normalizes sequence value used in settings sorting.',
    params: ['pattern: candidate pattern.', 'fallbackIndex: index fallback.'],
    returns: 'Non-negative integer sequence.',
    errors: ['No throws.'],
    edgeCases: ['Missing sequence uses fallback slot spacing.'],
    example: 'getPatternSequence(pattern, index)',
  },
  {
    id: 'helpers.getSequenceGroupId',
    symbol: 'getSequenceGroupId',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Returns normalized sequence group identifier or null.',
    params: ['pattern: candidate pattern.'],
    returns: 'Trimmed group id or null.',
    errors: ['No throws.'],
    edgeCases: ['Whitespace-only ids are treated as null.'],
    example: 'getSequenceGroupId(pattern)',
  },
  {
    id: 'helpers.sortPatternsBySequence',
    symbol: 'sortPatternsBySequence',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Sorts pattern table records by sequence then target then label.',
    params: ['patterns: unsorted patterns list.'],
    returns: 'Sorted pattern array.',
    errors: ['No throws.'],
    edgeCases: ['Ties are resolved using target and label lexical order.'],
    example: 'sortPatternsBySequence(patterns)',
  },
  {
    id: 'helpers.reorderPatterns',
    symbol: 'reorderPatterns',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Reorders pattern list for drag-and-drop sequencing operations.',
    params: [
      'patterns: ordered list.',
      'draggedId: dragged pattern id.',
      'targetId: drop target pattern id.',
    ],
    returns: 'Reordered list or null when no-op/invalid.',
    errors: ['No throws.'],
    edgeCases: ['Dropping onto same id returns null.'],
    example: "reorderPatterns(patterns, 'a', 'b')",
  },
  {
    id: 'helpers.createSequenceGroupId',
    symbol: 'createSequenceGroupId',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Creates unique sequence group id for ad-hoc grouping.',
    params: [],
    returns: 'String id with seq_ prefix.',
    errors: ['No throws.'],
    edgeCases: ['Uses Date.now plus random suffix for collision resistance.'],
    example: 'createSequenceGroupId()',
  },
  {
    id: 'helpers.normalizeSequenceGroupDebounceMs',
    symbol: 'normalizeSequenceGroupDebounceMs',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Clamps sequence group debounce to 0..30000 integer range.',
    params: ['value: candidate debounce value.'],
    returns: 'Safe debounce number.',
    errors: ['No throws.'],
    edgeCases: ['Non-number values fallback to 0.'],
    example: 'normalizeSequenceGroupDebounceMs(1200.8)',
  },
  {
    id: 'helpers.canCompileRegex',
    symbol: 'canCompileRegex',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Validates regex source/flags in UI before save.',
    params: ['pattern: regex source.', 'flags: regex flags.'],
    returns: 'True when RegExp constructor succeeds.',
    errors: ['No throws (exceptions are caught).'],
    edgeCases: ['Empty flags are treated as undefined.'],
    example: "canCompileRegex('^KEY', 'i')",
  },
  {
    id: 'helpers.buildSequenceGroups',
    symbol: 'buildSequenceGroups',
    file: 'src/features/products/components/settings/validator-settings/helpers.ts',
    purpose: 'Builds grouped sequence metadata for table rendering and editing.',
    params: ['patterns: ordered patterns list.'],
    returns: 'Map of sequence group views keyed by group id.',
    errors: ['No throws.'],
    edgeCases: ['First non-empty label in a group becomes display label.'],
    example: 'buildSequenceGroups(orderedPatterns)',
  },
  {
    id: 'controller.buildFormDataFromPattern',
    symbol: 'buildFormDataFromPattern',
    file: 'src/features/products/components/settings/validator-settings/controller-form-utils.ts',
    purpose: 'Converts persisted pattern entity into editable modal form state.',
    params: ['pattern: persisted pattern object.'],
    returns: 'PatternFormData ready for modal editing.',
    errors: ['No throws.'],
    edgeCases: ['Runtime none is remapped to database_query when runtime toggle is enabled.'],
    example: 'buildFormDataFromPattern(pattern)',
  },
  {
    id: 'controller.createSequenceActions',
    symbol: 'createSequenceActions',
    file: 'src/features/products/components/settings/validator-settings/controller-sequence-actions.ts',
    purpose:
      'Builds all advanced template/group action handlers used by validator settings controller.',
    params: ['input: dependencies and mutation callbacks for sequence/template actions.'],
    returns: 'Action handlers object consumed by controller.',
    errors: ['Handlers catch errors and route failures to notifyError + logClientError.'],
    edgeCases: ['Some template actions fallback to local creation when template endpoints fail.'],
    example: 'const actions = createSequenceActions({...})',
  },
  {
    id: 'controller.useValidatorSettingsController',
    symbol: 'useValidatorSettingsController',
    file: 'src/features/products/components/settings/validator-settings/useValidatorSettingsController.ts',
    purpose: 'Main orchestration hook for validator settings data, modal state, and mutations.',
    params: [],
    returns: 'ValidatorSettingsController interface consumed by UI panels.',
    errors: ['Mutation errors are surfaced via toasts and observability logs.'],
    edgeCases: [
      'Reorder flow includes optimistic grouping draft updates and stale timestamp checks.',
    ],
    example: 'const controller = useValidatorSettingsController()',
  },
  {
    id: 'scope.defaultValidatorPatternLists',
    symbol: 'defaultValidatorPatternLists',
    file: 'src/features/admin/pages/validator-scope.ts',
    purpose: 'Builds default pattern list configuration for each validator scope.',
    params: [],
    returns: 'Default list array with current timestamps.',
    errors: ['No throws.'],
    edgeCases: ['All default lists are deletion locked.'],
    example: 'defaultValidatorPatternLists()',
  },
  {
    id: 'scope.parseValidatorScope',
    symbol: 'parseValidatorScope',
    file: 'src/features/admin/pages/validator-scope.ts',
    purpose: 'Normalizes URL/query scope values to known validator scope enum.',
    params: ['value: raw scope string from query or persisted payload.'],
    returns: 'Validated scope enum value.',
    errors: ['No throws.'],
    edgeCases: ['Unknown values fallback to products scope.'],
    example: "parseValidatorScope('image-studio')",
  },
  {
    id: 'scope.normalizeValidatorPatternLists',
    symbol: 'normalizeValidatorPatternLists',
    file: 'src/features/admin/pages/validator-scope.ts',
    purpose: 'Normalizes and sanitizes persisted list manager payload.',
    params: ['value: candidate list array.'],
    returns: 'Validated unique-id list array.',
    errors: ['No throws.'],
    edgeCases: ['Empty input returns defaults.'],
    example: 'normalizeValidatorPatternLists(lists)',
  },
  {
    id: 'scope.parseValidatorPatternLists',
    symbol: 'parseValidatorPatternLists',
    file: 'src/features/admin/pages/validator-scope.ts',
    purpose: 'Parses settings JSON payload into normalized validator pattern lists.',
    params: ['value: persisted setting payload.'],
    returns: 'Normalized list array.',
    errors: ['JSON parse errors fallback to defaults.'],
    edgeCases: [
      'Requires canonical envelope shape `{ version: 2, lists: [...] }`; unsupported payload variants fallback to defaults.',
    ],
    example: 'parseValidatorPatternLists(rawSetting)',
  },
  {
    id: 'ui.ValidatorSettings',
    symbol: 'ValidatorSettings',
    file: 'src/features/products/components/settings/ValidatorSettings.tsx',
    purpose: 'Top-level validator settings composition root.',
    params: [],
    returns: 'Composed validator settings UI with modal and deletion confirmation.',
    errors: ['No throws.'],
    edgeCases: ['Provider boundary is required for child panels.'],
    example: '<ValidatorSettings />',
  },
  {
    id: 'ui.ValidatorSettingsProvider',
    symbol: 'ValidatorSettingsProvider',
    file: 'src/features/products/components/settings/validator-settings/ValidatorSettingsContext.tsx',
    purpose: 'Provides controller instance via React context.',
    params: ['value: controller object.', 'children: subtree.'],
    returns: 'Context provider element.',
    errors: ['No throws.'],
    edgeCases: ['useValidatorSettingsContext throws if provider is missing.'],
    example: '<ValidatorSettingsProvider value={controller}>{children}</ValidatorSettingsProvider>',
  },
  {
    id: 'ui.useValidatorSettingsContext',
    symbol: 'useValidatorSettingsContext',
    file: 'src/features/products/components/settings/validator-settings/ValidatorSettingsContext.tsx',
    purpose: 'Reads validator settings controller from context.',
    params: [],
    returns: 'ValidatorSettingsController object.',
    errors: ['Throws internalError when used outside provider.'],
    edgeCases: ['No fallback controller is provided intentionally.'],
    example: 'const controller = useValidatorSettingsContext()',
  },
  {
    id: 'ui.ValidatorDefaultPanel',
    symbol: 'ValidatorDefaultPanel',
    file: 'src/features/products/components/settings/validator-settings/ValidatorDefaultPanel.tsx',
    purpose: 'Renders default-on/off validator behavior toggle for product forms.',
    params: [],
    returns: 'Panel section component.',
    errors: ['No throws.'],
    edgeCases: ['Toggle disabled while settings mutation is pending.'],
    example: '<ValidatorDefaultPanel />',
  },
  {
    id: 'ui.ValidatorInstanceBehaviorPanel',
    symbol: 'ValidatorInstanceBehaviorPanel',
    file: 'src/features/products/components/settings/validator-settings/ValidatorInstanceBehaviorPanel.tsx',
    purpose: 'Renders deny behavior selectors for each validation scope.',
    params: [],
    returns: 'Panel section component.',
    errors: ['No throws.'],
    edgeCases: ['Options lock while settings mutation is pending.'],
    example: '<ValidatorInstanceBehaviorPanel />',
  },
  {
    id: 'ui.ValidatorPatternTablePanel',
    symbol: 'ValidatorPatternTablePanel',
    file: 'src/features/products/components/settings/validator-settings/ValidatorPatternTablePanel.tsx',
    purpose: 'Renders pattern table, sequence controls, and row-level actions.',
    params: [],
    returns: 'Pattern management panel component.',
    errors: ['No throws.'],
    edgeCases: ['Drag-drop is disabled while reorder mutations are active.'],
    example: '<ValidatorPatternTablePanel />',
  },
  {
    id: 'ui.ValidatorPatternModal',
    symbol: 'ValidatorPatternModal',
    file: 'src/features/products/components/settings/validator-settings/ValidatorPatternModal.tsx',
    purpose: 'Renders modal for creating/editing validation patterns and runtime configuration.',
    params: [],
    returns: 'Modal component or null when closed.',
    errors: ['No throws.'],
    edgeCases: ['Returns null when showModal is false.'],
    example: '<ValidatorPatternModal />',
  },
  {
    id: 'ui.AdminGlobalValidatorPage',
    symbol: 'AdminGlobalValidatorPage',
    file: 'src/features/admin/pages/AdminGlobalValidatorPage.tsx',
    purpose: 'Switches active validator panel based on selected pattern list/scope.',
    params: [],
    returns: 'Global validator admin page.',
    errors: ['No throws.'],
    edgeCases: ['Falls back to first available list when query params are missing.'],
    example: '<AdminGlobalValidatorPage />',
  },
  {
    id: 'ui.AdminValidatorPatternListsPage',
    symbol: 'AdminValidatorPatternListsPage',
    file: 'src/features/admin/pages/AdminValidatorPatternListsPage.tsx',
    purpose: 'Manages creation, editing, locking, and persistence of validator pattern lists.',
    params: [],
    returns: 'List manager page component.',
    errors: ['Save errors are surfaced via toast.'],
    edgeCases: ['At least one list must remain after delete.'],
    example: '<AdminValidatorPatternListsPage />',
  },
];

export const VALIDATOR_UI_DOCS: ValidatorUiDoc[] = [
  {
    id: 'validator.docs.toggle',
    title: 'Docs Tooltip Toggle',
    description: 'Enables inline docs hover tooltips for validator actions and controls.',
    relatedFunctions: ['ui.ValidatorSettings'],
  },
  {
    id: 'validator.default.toggle',
    title: 'Validator Default Toggle',
    description: 'Controls if validation is enabled by default in product create/edit screens.',
    relatedFunctions: ['ui.ValidatorDefaultPanel', 'controller.useValidatorSettingsController'],
  },
  {
    id: 'validator.instance.behavior.select',
    title: 'Instance Deny Behavior',
    description:
      'Sets whether denial stops future prompts in session or asks again next validation.',
    relatedFunctions: [
      'ui.ValidatorInstanceBehaviorPanel',
      'controller.useValidatorSettingsController',
    ],
  },
  {
    id: 'validator.patterns.add',
    title: 'Add Pattern',
    description: 'Opens pattern modal to create a new validator rule.',
    relatedFunctions: ['controller.useValidatorSettingsController', 'ui.ValidatorPatternModal'],
  },
  {
    id: 'validator.patterns.sequence.sku',
    title: 'SKU Auto Sequence',
    description: 'Creates SKU auto-increment + guard sequence templates.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.patterns.sequence.latestPriceStock',
    title: 'Latest Price & Stock',
    description: 'Creates or updates mirror templates for latest price and stock values.',
    relatedFunctions: ['controller.createSequenceActions', 'helpers.buildLatestFieldRecipe'],
  },
  {
    id: 'validator.patterns.sequence.nameDimensions',
    title: 'Name Segment -> Dimensions',
    description: 'Creates templates to infer length/height from name segment #2.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.patterns.sequence.nameCategory',
    title: 'Name Segment -> Category',
    description: 'Creates template to map name segment to category.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.patterns.sequence.nameMirrorPl',
    title: 'Name EN -> PL Sequence',
    description:
      'Creates sequence that mirrors English name into Polish and applies category replacements.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.pattern.drag',
    title: 'Pattern Drag Handle',
    description: 'Drag pattern row onto another row to create or extend sequence group.',
    relatedFunctions: ['controller.useValidatorSettingsController', 'helpers.reorderPatterns'],
  },
  {
    id: 'validator.pattern.toggle',
    title: 'Pattern Enabled Toggle',
    description: 'Enables or disables a single pattern without editing details.',
    relatedFunctions: ['controller.useValidatorSettingsController'],
  },
  {
    id: 'validator.pattern.duplicate',
    title: 'Duplicate Pattern',
    description: 'Copies pattern with a unique label and independent sequence assignment.',
    relatedFunctions: ['controller.useValidatorSettingsController', 'helpers.buildDuplicateLabel'],
  },
  {
    id: 'validator.pattern.edit',
    title: 'Edit Pattern',
    description: 'Loads selected pattern into modal for editing.',
    relatedFunctions: [
      'controller.useValidatorSettingsController',
      'controller.buildFormDataFromPattern',
    ],
  },
  {
    id: 'validator.pattern.delete',
    title: 'Delete Pattern',
    description: 'Marks pattern for deletion and opens confirmation dialog.',
    relatedFunctions: ['controller.useValidatorSettingsController'],
  },
  {
    id: 'validator.group.save',
    title: 'Save Group',
    description: 'Persists group label and debounce to all patterns in sequence group.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.group.ungroup',
    title: 'Ungroup',
    description: 'Removes sequence group metadata from all grouped patterns.',
    relatedFunctions: ['controller.createSequenceActions'],
  },
  {
    id: 'validator.modal.save',
    title: 'Save Pattern',
    description: 'Validates form data, then creates or updates pattern entity.',
    relatedFunctions: ['controller.useValidatorSettingsController'],
  },
  {
    id: 'validator.modal.target',
    title: 'Target Selector',
    description: 'Selects product field target for regex validation.',
    relatedFunctions: [
      'helpers.getReplacementFieldsForTarget',
      'helpers.getSourceFieldOptionsForTarget',
    ],
  },
  {
    id: 'validator.modal.applyScopes',
    title: 'Apply In Forms',
    description: 'Controls which form contexts execute this pattern.',
    relatedFunctions: ['core.shouldLaunchPattern'],
  },
  {
    id: 'validator.modal.launch.toggle',
    title: 'Launch Condition Toggle',
    description: 'Enables launch gate block for pattern execution.',
    relatedFunctions: ['core.shouldLaunchPattern', 'core.resolvePatternLaunchSourceValue'],
  },
  {
    id: 'validator.modal.runtime.toggle',
    title: 'Runtime Validator Toggle',
    description: 'Enables runtime evaluation through DB query or AI prompt.',
    relatedFunctions: ['core.isRuntimePatternEnabled'],
  },
  {
    id: 'validator.modal.replacement.toggle',
    title: 'Replacement Toggle',
    description: 'Enables replacement proposal generation for pattern matches.',
    relatedFunctions: ['core.resolvePatternReplacementValue', 'core.applyResolvedReplacement'],
  },
  {
    id: 'validator.modal.replacement.autoApply',
    title: 'Auto-Apply Replacement',
    description: 'Applies replacement directly without manual accept step.',
    relatedFunctions: ['core.buildFieldIssues'],
  },
  {
    id: 'validator.modal.replacement.skipNoop',
    title: 'Skip No-Op Proposals',
    description: 'Hides replacement proposals when replacement equals current value.',
    relatedFunctions: ['core.buildFieldIssues'],
  },
  {
    id: 'validator.modal.regex',
    title: 'Regex & Flags',
    description: 'Defines pattern matching logic and regex engine flags.',
    relatedFunctions: ['helpers.canCompileRegex', 'core.buildFieldIssues'],
  },
  {
    id: 'validator.modal.launch.config',
    title: 'Launch Config',
    description: 'Controls source, operator, and value used to gate execution.',
    relatedFunctions: ['core.resolvePatternLaunchSourceValue', 'core.shouldLaunchPattern'],
  },
  {
    id: 'validator.modal.runtime.config',
    title: 'Runtime Config',
    description: 'JSON configuration consumed by runtime evaluator endpoint.',
    relatedFunctions: ['core.isRuntimePatternEnabled'],
  },
  {
    id: 'validator.modal.sequence',
    title: 'Sequence Controls',
    description: 'Controls execution order, chaining, and max executions in sequence mode.',
    relatedFunctions: [
      'core.normalizePatternSequence',
      'core.normalizePatternChainMode',
      'core.normalizePatternMaxExecutions',
    ],
  },
];

export const VALIDATOR_FUNCTION_DOC_IDS = new Set(
  VALIDATOR_FUNCTION_DOCS.map((entry: ValidatorFunctionDoc) => entry.id)
);

export const VALIDATOR_UI_DOC_BY_ID = new Map(
  VALIDATOR_UI_DOCS.map((entry: ValidatorUiDoc) => [entry.id, entry])
);

export const VALIDATOR_FUNCTION_DOC_BY_ID = new Map(
  VALIDATOR_FUNCTION_DOCS.map((entry: ValidatorFunctionDoc) => [entry.id, entry])
);
