import type { AgenticCodingGameConfig, AgenticCodingGameId } from './AgenticCodingMiniGames.types';

export const AGENTIC_CODING_GAMES: Record<AgenticCodingGameId, AgenticCodingGameConfig> = {
  foundations: {
    mode: 'sort',
    title: 'Brief Builder',
    prompt: 'Przeciągnij elementy briefu do właściwych koszyków.',
    bins: [
      { id: 'goal', label: 'Goal' },
      { id: 'context', label: 'Context' },
      { id: 'constraints', label: 'Constraints' },
      { id: 'done', label: 'Done when' },
    ],
    items: [
      { id: 'item-goal', label: 'Skróć czas odpowiedzi API do <300 ms.', binId: 'goal' },
      { id: 'item-context', label: 'Pliki, logi i stan repo.', binId: 'context' },
      { id: 'item-constraints', label: 'Bez nowych deps, bez zmian API.', binId: 'constraints' },
      { id: 'item-done', label: 'Testy + proof loop, diff reviewed.', binId: 'done' },
    ],
    success: 'Brief gotowy. Kontrakt jest jasny i kompletny.',
    accent: 'indigo',
    svgLabel: 'Animacja: karty briefu wpadają do właściwych koszyków.',
  },
  fit: {
    mode: 'sort',
    title: 'Fit Scanner',
    prompt: 'Przeciągnij zadania do kategorii: pasuje vs. nie pasuje.',
    bins: [
      { id: 'fit', label: 'Dobry fit' },
      { id: 'no-fit', label: 'Słaby fit' },
    ],
    items: [
      { id: 'fit-bugfix', label: 'Bugfix w małym module z testami.', binId: 'fit' },
      { id: 'fit-refactor', label: 'Refactor z jasnymi guardrails.', binId: 'fit' },
      { id: 'no-fit-migration', label: 'Duża migracja bez testów.', binId: 'no-fit' },
      { id: 'no-fit-unknown', label: 'Niejasny scope bez kontekstu.', binId: 'no-fit' },
    ],
    success: 'Masz jasność, kiedy Codex daje największy zwrot.',
    accent: 'violet',
    svgLabel: 'Animacja: radar dopasowania z dwoma strefami.',
  },
  surfaces: {
    mode: 'sort',
    title: 'Surface Match',
    prompt: 'Przeciągnij scenariusze do najlepszej powierzchni.',
    bins: [
      { id: 'cli', label: 'CLI' },
      { id: 'ide', label: 'IDE' },
      { id: 'app', label: 'App/Cloud' },
      { id: 'api', label: 'API' },
    ],
    items: [
      { id: 'surface-cli', label: 'Szybki hotfix w lokalnym repo.', binId: 'cli' },
      { id: 'surface-ide', label: 'Praca na otwartych plikach i selekcjach.', binId: 'ide' },
      { id: 'surface-app', label: 'Równoległe wątki i automations w tle.', binId: 'app' },
      { id: 'surface-api', label: 'Własny harness i integracje produktowe.', binId: 'api' },
    ],
    success: 'Dobór powierzchni jest spójny z kontekstem zadania.',
    accent: 'emerald',
    svgLabel: 'Animacja: cztery kafle CLI/IDE/App/API pulsują.',
  },
  operating_model: {
    mode: 'draw',
    title: 'Operating Loop',
    prompt: 'Narysuj pętlę pracy, łącząc wszystkie punkty.',
    success: 'Pętla pracy zamknięta. Masz pełną kontrolę jakości.',
    accent: 'indigo',
    svgLabel: 'Animacja: pętla pracy z punktami kontrolnymi.',
    guide: 'loop',
    checkpoints: [
      { id: 'intent', label: 'Intent', x: 90, y: 90 },
      { id: 'exec', label: 'Exec', x: 180, y: 40 },
      { id: 'verify', label: 'Verify', x: 270, y: 90 },
    ],
  },
  prompting: {
    mode: 'trim',
    title: 'Prompt Trim',
    prompt: 'Click the unnecessary words to trim the prompt to its clean contract.',
    success: 'Prompt trimmed. The contract is clear and audit-ready.',
    accent: 'rose',
    svgLabel: 'Animation: scissors glide along the prompt line.',
    tokens: [
      { id: 'trim-please', text: 'Please', keep: false },
      { id: 'trim-goal', text: 'Goal:', keep: true },
      {
        id: 'trim-goal-text',
        text: 'Reduce API response time below 300ms for /api/search.',
        keep: true,
      },
      { id: 'trim-ideally', text: 'Ideally', keep: false },
      { id: 'trim-context', text: 'Context:', keep: true },
      {
        id: 'trim-context-text',
        text: 'Files include src/app/api/search/route.ts and logs/api-search.log.',
        keep: true,
      },
      { id: 'trim-if-you-can', text: 'If you can', keep: false },
      { id: 'trim-constraints', text: 'Constraints:', keep: true },
      {
        id: 'trim-constraints-text',
        text: 'No new dependencies; keep response shape and tests unchanged.',
        keep: true,
      },
      { id: 'trim-for-now', text: 'For now', keep: false },
      { id: 'trim-done', text: 'Done when:', keep: true },
      {
        id: 'trim-done-text',
        text: 'p95 < 300ms locally, tests pass, and provide a diff summary.',
        keep: true,
      },
      { id: 'trim-asap', text: 'as soon as possible', keep: false },
      { id: 'trim-thanks', text: 'Thank you', keep: false },
    ],
  },
  responses: {
    mode: 'sequence',
    title: 'Response Flow',
    prompt: 'Ułóż odpowiedź agenta w najlepszej kolejności.',
    steps: ['Summary', 'Changes', 'Tests', 'Risks'],
    success: 'Odpowiedź jest łatwa do audytu i review.',
    accent: 'sky',
    svgLabel: 'Animacja: pasek odpowiedzi z czterema segmentami.',
  },
  agents_md: {
    mode: 'sort',
    title: 'AGENTS.md Map',
    prompt: 'Przeciągnij informacje do właściwego dokumentu.',
    bins: [
      { id: 'agents', label: 'AGENTS.md' },
      { id: 'gemini', label: 'GEMINI.md' },
    ],
    items: [
      { id: 'agents-rules', label: 'Repo rules i working conventions.', binId: 'agents' },
      { id: 'agents-scope', label: 'Zakres i guardrails agentów.', binId: 'agents' },
      { id: 'gemini-arch', label: 'Dłuższy opis architektury.', binId: 'gemini' },
      { id: 'gemini-deep', label: 'Głębokie referencje i skany.', binId: 'gemini' },
    ],
    success: 'Wiesz, gdzie trzymać kontrakt i gdzie głęboką wiedzę.',
    accent: 'indigo',
    svgLabel: 'Animacja: stos dokumentów z AGENTS.md na wierzchu.',
  },
  approvals: {
    mode: 'sequence',
    title: 'Approval Ladder',
    prompt: 'Kliknij poziomy eskalacji w poprawnej kolejności.',
    steps: ['Read-only', 'Workspace-write', 'Network'],
    success: 'Eskalacja jest minimalna i uzasadniona.',
    accent: 'slate',
    svgLabel: 'Animacja: poziomy dostępu z ruchem dotu.',
  },
  safety: {
    mode: 'sort',
    title: 'Safety Gate',
    prompt: 'Oceń działania jako bezpieczne lub ryzykowne.',
    bins: [
      { id: 'safe', label: 'Bezpieczne' },
      { id: 'risky', label: 'Ryzykowne' },
    ],
    items: [
      { id: 'safe-readonly', label: 'Read-only scan bez sieci.', binId: 'safe' },
      { id: 'safe-approved', label: 'Testy po aprobacie.', binId: 'safe' },
      { id: 'risky-network', label: 'Nagły dostęp do sieci bez potrzeby.', binId: 'risky' },
      { id: 'risky-delete', label: 'Usuwanie plików bez potwierdzenia.', binId: 'risky' },
    ],
    success: 'Ryzyko jest pod kontrolą, a approvals są świadome.',
    accent: 'indigo',
    svgLabel: 'Animacja: bramka bezpieczeństwa z pulsującym ostrzeżeniem.',
  },
  config_layers: {
    mode: 'sequence',
    title: 'Config Stack',
    prompt: 'Ułóż warstwy konfiguracji od najsilniejszej do najsłabszej.',
    steps: ['CLI flag', 'Profile', 'config.toml', 'Default'],
    success: 'Warstwy config są jasne i przewidywalne.',
    accent: 'slate',
    svgLabel: 'Animacja: układ warstw konfiguracji przesuwa się w górę.',
  },
  rules: {
    mode: 'sort',
    title: 'Rules Triage',
    prompt: 'Przeciągnij zachowania do odpowiedniej kategorii.',
    bins: [
      { id: 'allowed', label: 'OK' },
      { id: 'needs-approval', label: 'Requires approval' },
      { id: 'blocked', label: 'Blocked' },
    ],
    items: [
      { id: 'rule-read', label: 'Read-only repo scan.', binId: 'allowed' },
      { id: 'rule-tests', label: 'Uruchomienie testów.', binId: 'needs-approval' },
      { id: 'rule-reset', label: 'git reset --hard', binId: 'blocked' },
    ],
    success: 'Reguły są egzekwowane bez wątpliwości.',
    accent: 'violet',
    svgLabel: 'Animacja: trzy kolumny reguł z pulsami.',
  },
  web_citations: {
    mode: 'sort',
    title: 'Citation Check',
    prompt: 'Rozdziel zadania na wymagające web.run i lokalne.',
    bins: [
      { id: 'web', label: 'Requires web.run' },
      { id: 'local', label: 'No web' },
    ],
    items: [
      { id: 'web-latest', label: 'Sprawdź najnowsze dane rynkowe.', binId: 'web' },
      { id: 'web-unknown', label: 'Nieznany termin/skrót w briefie.', binId: 'web' },
      { id: 'local-rewrite', label: 'Przeredaguj podany tekst.', binId: 'local' },
      { id: 'local-code', label: 'Refactor na podstawie lokalnego kodu.', binId: 'local' },
    ],
    success: 'Wiesz, kiedy potrzebujesz weryfikacji z web.',
    accent: 'sky',
    svgLabel: 'Animacja: dwa panele (web/local) z ruchomymi punktami.',
  },
  tooling: {
    mode: 'sort',
    title: 'Tooling Match',
    prompt: 'Dopasuj działanie do właściwego narzędzia.',
    bins: [
      { id: 'cli', label: 'CLI' },
      { id: 'ide', label: 'IDE' },
      { id: 'app', label: 'Codex App' },
    ],
    items: [
      { id: 'tool-cli', label: 'Plan + review + test w jednej sesji.', binId: 'cli' },
      { id: 'tool-ide', label: 'Zmiany na selekcji w edytorze.', binId: 'ide' },
      { id: 'tool-app', label: 'Worktree + automations w tle.', binId: 'app' },
    ],
    success: 'Dobierasz narzędzie do kontekstu i celu.',
    accent: 'sky',
    svgLabel: 'Animacja: trzy ikony narzędzi pulsują naprzemiennie.',
  },
  response_contract: {
    mode: 'sequence',
    title: 'Response Contract',
    prompt: 'Ułóż kontrakt odpowiedzi w kolejności auditowej.',
    steps: ['Changed', 'Tests', 'Risks', 'Next'],
    success: 'Kontrakt odpowiedzi jest kompletny i spójny.',
    accent: 'slate',
    svgLabel: 'Animacja: cztery segmenty kontraktu.',
  },
  delegation: {
    mode: 'sequence',
    title: 'Delegation Loop',
    prompt: 'Kliknij kroki delegacji w najlepszej kolejności.',
    steps: ['Goal', 'Context', 'Constraints', 'Verify'],
    success: 'Delegacja jest gotowa do wykonania.',
    accent: 'indigo',
    svgLabel: 'Animacja: pętla delegacji z pulsami.',
  },
  models: {
    mode: 'sort',
    title: 'Model Routing',
    prompt: 'Przeciągnij zadania do właściwego poziomu.',
    bins: [
      { id: 'fast', label: 'Fast/Low' },
      { id: 'balanced', label: 'Balanced/Medium' },
      { id: 'deep', label: 'Deep/High' },
    ],
    items: [
      { id: 'model-bugfix', label: 'Prosty bugfix w UI.', binId: 'fast' },
      { id: 'model-feature', label: 'Typowe zadanie produktowe.', binId: 'balanced' },
      { id: 'model-arch', label: 'Decyzja architektoniczna.', binId: 'deep' },
    ],
    success: 'Routing modelu jest spójny z ryzykiem.',
    accent: 'teal',
    svgLabel: 'Animacja: trzy pokrętła z ruchem wskazówki.',
  },
  cli_ide: {
    mode: 'sequence',
    title: 'IDE → CLI Flow',
    prompt: 'Ułóż flow pracy od kontekstu do weryfikacji.',
    steps: ['IDE context', 'CLI plan', 'CLI review', 'Run tests'],
    success: 'Flow jest szybkie i powtarzalne.',
    accent: 'sky',
    svgLabel: 'Animacja: przepływ między IDE a CLI.',
  },
  app_workflows: {
    mode: 'sort',
    title: 'Worktree Split',
    prompt: 'Przeciągnij scenariusze do Local lub Worktree.',
    bins: [
      { id: 'local', label: 'Local' },
      { id: 'worktree', label: 'Worktree' },
    ],
    items: [
      { id: 'app-local', label: 'Szybka poprawka w bieżącym WIP.', binId: 'local' },
      { id: 'app-worktree', label: 'Równoległy wątek bez konfliktów.', binId: 'worktree' },
    ],
    success: 'Środowisko pracy dobrane do ryzyka.',
    accent: 'teal',
    svgLabel: 'Animacja: rozgałęzienie repo na lokalny i worktree.',
  },
  skills: {
    mode: 'sequence',
    title: 'Skill Contract',
    prompt: 'Ułóż minimalny kontrakt skilla w kolejności.',
    steps: ['Inputs', 'Tools', 'Outputs', 'Safety'],
    success: 'Skill ma jasny kontrakt i jest gotowy do reuse.',
    accent: 'emerald',
    svgLabel: 'Animacja: pipeline skilla pulsuje od wejścia do outputu.',
  },
  mcp_integrations: {
    mode: 'sort',
    title: 'MCP Roles',
    prompt: 'Przeciągnij opisy do roli MCP.',
    bins: [
      { id: 'host', label: 'Host' },
      { id: 'client', label: 'Client' },
      { id: 'server', label: 'Server' },
    ],
    items: [
      { id: 'mcp-host', label: 'Codex jako środowisko wykonawcze.', binId: 'host' },
      { id: 'mcp-client', label: 'Połączenie MCP w środku Codex.', binId: 'client' },
      { id: 'mcp-server', label: 'Zewnętrzny serwer dostarczający narzędzia.', binId: 'server' },
    ],
    success: 'Role MCP są dobrze rozdzielone.',
    accent: 'sky',
    svgLabel: 'Animacja: trzy węzły host/client/server.',
  },
  automations: {
    mode: 'sequence',
    title: 'Automation Cadence',
    prompt: 'Ułóż kroki ustawienia automations.',
    steps: ['Manual run', 'Define constraints', 'Schedule', 'Triage output'],
    success: 'Automation jest bezpieczna i przewidywalna.',
    accent: 'indigo',
    svgLabel: 'Animacja: kalendarz z pulsującymi slotami.',
  },
  state_scale: {
    mode: 'sequence',
    title: 'State & Scale',
    prompt: 'Ułóż działania, gdy rozmowa rośnie.',
    steps: ['Summarize', 'Compact', 'Cache', 'Resume'],
    success: 'Stan rozmowy jest kontrolowany i skalowalny.',
    accent: 'indigo',
    svgLabel: 'Animacja: mapa stanu z segmentami.',
  },
  review: {
    mode: 'sequence',
    title: 'Evidence Pack',
    prompt: 'Ułóż dowód działania w właściwej kolejności.',
    steps: ['Diff', 'Tests', 'Proof', 'Risks'],
    success: 'Masz kompletny evidence pack.',
    accent: 'amber',
    svgLabel: 'Animacja: pakiet dowodów z checkmarkami.',
  },
  long_horizon: {
    mode: 'draw',
    title: 'Milestone Flow',
    prompt: 'Poprowadź linię przez wszystkie checkpointy.',
    success: 'Milestone flow jest spójny i kontrolowany.',
    accent: 'sky',
    svgLabel: 'Animacja: timeline z checkpointami.',
    guide: 'line',
    checkpoints: [
      { id: 'spec', label: 'Spec', x: 70, y: 70 },
      { id: 'plan', label: 'Plan', x: 150, y: 70 },
      { id: 'build', label: 'Build', x: 230, y: 70 },
      { id: 'verify', label: 'Verify', x: 310, y: 70 },
    ],
  },
  dos_donts: {
    mode: 'sort',
    title: 'Do / Don’t',
    prompt: 'Przeciągnij zachowania do właściwej kolumny.',
    bins: [
      { id: 'do', label: 'Do\'s' },
      { id: 'dont', label: 'Don\'ts' },
    ],
    items: [
      { id: 'do-brief', label: 'Jasny brief i guardrails.', binId: 'do' },
      { id: 'do-proof', label: 'Proof loop przed akceptacją.', binId: 'do' },
      { id: 'dont-scope', label: 'Rozmyty scope bez kontekstu.', binId: 'dont' },
      { id: 'dont-autonomy', label: 'Brak constraints i kontroli.', binId: 'dont' },
    ],
    success: 'Zasady współpracy są klarowne.',
    accent: 'violet',
    svgLabel: 'Animacja: check i cross pulsują na przemian.',
  },
  non_engineers: {
    mode: 'sort',
    title: 'Delegation Clarity',
    prompt: 'Wybierz briefy, które są gotowe do delegacji.',
    bins: [
      { id: 'ready', label: 'Gotowe' },
      { id: 'unclear', label: 'Niejasne' },
    ],
    items: [
      { id: 'ne-ready', label: 'Goal, scope, constraints, done.', binId: 'ready' },
      { id: 'ne-unclear', label: 'Zrób coś z tym kodem.', binId: 'unclear' },
      { id: 'ne-ready-2', label: 'Wskazane pliki + testy do uruchomienia.', binId: 'ready' },
      { id: 'ne-unclear-2', label: 'Popraw wydajność bez kontekstu.', binId: 'unclear' },
    ],
    success: 'Delegacja jest jasna nawet bez bycia devem.',
    accent: 'amber',
    svgLabel: 'Animacja: dwie kolumny briefów.',
  },
  prompt_patterns: {
    mode: 'sort',
    title: 'Prompt Patterns',
    prompt: 'Przeciągnij scenariusze do właściwego wzoru promptu.',
    bins: [
      { id: 'bugfix', label: 'Bugfix' },
      { id: 'refactor', label: 'Refactor' },
      { id: 'review', label: 'Review' },
    ],
    items: [
      { id: 'pp-bug', label: 'Migotanie UI w /albums.', binId: 'bugfix' },
      { id: 'pp-refactor', label: 'Wspólny retry utility.', binId: 'refactor' },
      { id: 'pp-review', label: 'Sprawdź diff i ryzyka.', binId: 'review' },
    ],
    success: 'Wzór promptu jest dopasowany do zadania.',
    accent: 'indigo',
    svgLabel: 'Animacja: trzy szablony promptu.',
  },
  rollout: {
    mode: 'sequence',
    title: 'Rollout Stages',
    prompt: 'Kliknij etapy wdrożenia w kolejności.',
    steps: ['Pilot', 'Playbook', 'Metrics', 'Scale'],
    success: 'Rollout ma stabilny rytm i kontrolę.',
    accent: 'teal',
    svgLabel: 'Animacja: etapy rollout na osi czasu.',
  },
};
