export const KANGUR_CLOCK_THEME_COLORS = {
  accentAmberText: 'var(--kangur-accent-amber-text, #f59e0b)',
  accentIndigoSoftFill: 'var(--kangur-accent-indigo-soft-fill, #c7d2fe)',
  accentIndigoText: 'var(--kangur-accent-indigo-text, #4f46e5)',
  accentIndigoSolidFill: 'var(--kangur-accent-indigo-solid-fill, #6366f1)',
  atmosphereEnd:
    'color-mix(in srgb, var(--kangur-accent-indigo-solid-fill, #6366f1) 0%, transparent)',
  atmosphereStart:
    'color-mix(in srgb, var(--kangur-accent-indigo-solid-fill, #6366f1) 18%, transparent)',
  center: 'var(--kangur-accent-indigo-text, #4f46e5)',
  challengeHigh: 'var(--kangur-accent-amber-solid-fill, #f59e0b)',
  challengeLow: 'var(--kangur-accent-rose-text, #dc2626)',
  challengeMid: 'var(--kangur-accent-amber-text, #f97316)',
  challengeTrack: 'var(--kangur-accent-amber-soft-fill, #fde68a)',
  contrastText: 'var(--kangur-contrast-text, #ffffff)',
  faceFill: 'var(--kangur-soft-card-background, #ffffff)',
  faceGradientEnd:
    'color-mix(in srgb, var(--kangur-soft-card-background, #ffffff) 82%, var(--kangur-accent-sky-soft-fill, #dbeafe))',
  faceGradientMid:
    'color-mix(in srgb, var(--kangur-soft-card-background, #ffffff) 94%, var(--kangur-page-background, #f8fafc))',
  faceGradientStart:
    'color-mix(in srgb, var(--kangur-soft-card-background, #ffffff) 92%, white)',
  faceStroke: 'var(--kangur-accent-indigo-border, #6366f1)',
  frame: 'var(--kangur-soft-card-border, rgba(255, 255, 255, 0.72))',
  highlightHourHand: 'var(--kangur-accent-rose-text, #dc2626)',
  highlightMinuteHand: 'var(--kangur-accent-emerald-text, #16a34a)',
  interactiveHourHand: 'var(--kangur-accent-rose-text, #dc2626)',
  interactiveMinuteHand: 'var(--kangur-accent-emerald-text, #16a34a)',
  label: 'var(--kangur-page-text, #1e293b)',
  lessonHourHand:
    'color-mix(in srgb, var(--kangur-page-text, #1e293b) 84%, var(--kangur-accent-indigo-text, #4f46e5))',
  lessonMinuteHand: 'var(--kangur-accent-indigo-text, #4f46e5)',
  majorTick: 'var(--kangur-accent-indigo-text, #4f46e5)',
  minorTick: 'var(--kangur-accent-indigo-muted-text, #c7d2fe)',
  numeral: 'var(--kangur-page-text, #1e293b)',
  feedbackCorrectBackground: 'var(--kangur-accent-emerald-solid-fill, #10b981)',
  feedbackCorrectBorder: 'var(--kangur-accent-emerald-border, #10b981)',
  feedbackCorrectSoftBackground: 'var(--kangur-accent-emerald-soft-fill, #d1fae5)',
  feedbackCorrectText: 'var(--kangur-accent-emerald-text, #047857)',
  feedbackWrongBackground: 'var(--kangur-accent-rose-solid-fill, #f43f5e)',
  feedbackWrongBorder: 'var(--kangur-accent-rose-border, #f43f5e)',
  feedbackWrongSoftBackground: 'var(--kangur-accent-rose-soft-fill, #ffe4e6)',
  feedbackWrongText: 'var(--kangur-accent-rose-text, #be123c)',
  progressChallengeActive: 'var(--kangur-accent-amber-solid-fill, #f59e0b)',
  progressChallengeDone: 'var(--kangur-accent-amber-soft-fill, #fde68a)',
  progressPracticeActive: 'var(--kangur-accent-indigo-solid-fill, #6366f1)',
  progressPracticeDone: 'var(--kangur-accent-indigo-soft-fill, #c7d2fe)',
  promptText: 'color-mix(in srgb, var(--kangur-accent-amber-text, #f59e0b) 80%, transparent)',
  secondHand: 'var(--kangur-accent-rose-text, #ef4444)',
  stepFill: 'var(--kangur-accent-emerald-solid-fill, #34d399)',
  stepLabel: 'var(--kangur-accent-emerald-text, #0f766e)',
} as const;
