export const KANGUR_CLOCK_THEME_COLORS = {
  accentAmberText: 'var(--kangur-clock-accent-amber-text, #f59e0b)',
  accentIndigoSoftFill: 'var(--kangur-clock-accent-indigo-soft-fill, #c7d2fe)',
  accentIndigoText: 'var(--kangur-clock-accent-indigo-text, #4f46e5)',
  accentIndigoSolidFill: 'var(--kangur-clock-accent-indigo-solid-fill, #6366f1)',
  atmosphereEnd: 'var(--kangur-clock-atmosphere-end, rgba(99, 102, 241, 0))',
  atmosphereStart: 'var(--kangur-clock-atmosphere-start, rgba(99, 102, 241, 0.18))',
  center: 'var(--kangur-clock-center, #4f46e5)',
  challengeHigh: 'var(--kangur-clock-challenge-high, #f59e0b)',
  challengeLow: 'var(--kangur-clock-challenge-low, #dc2626)',
  challengeMid: 'var(--kangur-clock-challenge-mid, #f97316)',
  challengeTrack: 'var(--kangur-clock-challenge-track, #fde68a)',
  contrastText: 'var(--kangur-clock-contrast-text, #ffffff)',
  faceFill: 'var(--kangur-clock-face-fill, #ffffff)',
  faceGradientEnd: 'var(--kangur-clock-face-gradient-end, #dbeafe)',
  faceGradientMid: 'var(--kangur-clock-face-gradient-mid, #f8fafc)',
  faceGradientStart: 'var(--kangur-clock-face-gradient-start, #ffffff)',
  faceStroke: 'var(--kangur-clock-face-stroke, #6366f1)',
  frame: 'var(--kangur-clock-frame, rgba(255, 255, 255, 0.72))',
  highlightHourHand: 'var(--kangur-clock-highlight-hour-hand, #dc2626)',
  highlightMinuteHand: 'var(--kangur-clock-highlight-minute-hand, #16a34a)',
  interactiveHourHand: 'var(--kangur-clock-interactive-hour-hand, #dc2626)',
  interactiveMinuteHand: 'var(--kangur-clock-interactive-minute-hand, #16a34a)',
  label: 'var(--kangur-clock-label, #1e293b)',
  lessonHourHand: 'var(--kangur-clock-lesson-hour-hand, #334155)',
  lessonMinuteHand: 'var(--kangur-clock-lesson-minute-hand, #4f46e5)',
  majorTick: 'var(--kangur-clock-major-tick, #4f46e5)',
  minorTick: 'var(--kangur-clock-minor-tick, #c7d2fe)',
  numeral: 'var(--kangur-clock-numeral, #1e293b)',
  feedbackCorrectBackground: 'var(--kangur-clock-feedback-correct-background, #10b981)',
  feedbackCorrectBorder: 'var(--kangur-clock-feedback-correct-border, #10b981)',
  feedbackCorrectSoftBackground:
    'var(--kangur-clock-feedback-correct-soft-background, #d1fae5)',
  feedbackCorrectText: 'var(--kangur-clock-feedback-correct-text, #047857)',
  feedbackWrongBackground: 'var(--kangur-clock-feedback-wrong-background, #f43f5e)',
  feedbackWrongBorder: 'var(--kangur-clock-feedback-wrong-border, #f43f5e)',
  feedbackWrongSoftBackground: 'var(--kangur-clock-feedback-wrong-soft-background, #ffe4e6)',
  feedbackWrongText: 'var(--kangur-clock-feedback-wrong-text, #be123c)',
  progressChallengeActive: 'var(--kangur-clock-progress-challenge-active, #f59e0b)',
  progressChallengeDone: 'var(--kangur-clock-progress-challenge-done, #fde68a)',
  progressPracticeActive: 'var(--kangur-clock-progress-practice-active, #6366f1)',
  progressPracticeDone: 'var(--kangur-clock-progress-practice-done, #c7d2fe)',
  promptText: 'var(--kangur-clock-prompt-text, #d97706)',
  secondHand: 'var(--kangur-clock-second-hand, #ef4444)',
  stepFill: 'var(--kangur-clock-step-fill, #34d399)',
  stepLabel: 'var(--kangur-clock-step-label, #0f766e)',
} as const;
