import type {
  OperationSelectorFallbackCopy,
} from './game-setup/KangurGameOperationSelectorWidget.types';
import { KANGUR_GEOMETRY_LESSON_COMPONENT_IDS } from '@/features/kangur/settings';
import { normalizeSiteLocale } from '@/shared/lib/i18n/site-locale';

export const getOperationSelectorFallbackCopy = (
  locale: ReturnType<typeof normalizeSiteLocale>
): OperationSelectorFallbackCopy => {
  if (locale === 'uk') {
    return {
      operationSelectorTitle: 'Граймо!',
      trainingSetupTitle: 'Налаштування тренування',
      trainingSetupWordmarkLabel: 'Тренування',
      trainingSetupDescription: 'Налаштуйте змішане тренування й виберіть діапазон запитань.',
      intro: {
        maths: 'Виберіть тип гри й переходьте просто до математичної забави.',
        alphabet: 'Виберіть літерну забаву й тренуйте алфавіт.',
        art: 'Виберіть урок мистецтва й досліджуйте кольори та форми.',
        music: 'Виберіть музичний урок і співайте звуки діатонічної гами крок за кроком.',
        geometry: 'Виберіть забаву з формами й тренуйте геометрію.',
        language: 'Виберіть тип мовної гри й переходьте просто до вправ.',
      },
      quickPractice: {
        title: 'Швидкі вправи',
        description: 'Швидкі вікторини на основі тем з уроків.',
        groupAria: (group) => `${group} швидкі вправи`,
        cardAria: (label) => `Швидка вправа: ${label}`,
        gameChip: 'Гра',
      },
      lessonQuizDefinitions: [
        {
          accent: 'indigo',
          description: 'Тренуйте читання годин і хвилин у режимі вікторини.',
          emoji: '🕐',
          label: 'Вправи з годинником',
          lessonComponentIds: ['clock'],
          onSelectScreen: 'clock_quiz',
        },
        {
          accent: 'emerald',
          description: 'Перевіряйте дати, дні тижня і місяці в коротких завданнях.',
          emoji: '📅',
          label: 'Вправи з календарем',
          lessonComponentIds: ['calendar'],
          onSelectScreen: 'calendar_quiz',
        },
        {
          accent: 'amber',
          description: 'Швидка вікторина з додавання в ритмі гри з уроку.',
          emoji: '➕',
          label: 'Вікторина з додавання',
          lessonComponentIds: ['adding'],
          onSelectScreen: 'addition_quiz',
        },
        {
          accent: 'rose',
          description: 'Швидка серія віднімання з миттєвою відповіддю.',
          emoji: '➖',
          label: 'Вікторина з віднімання',
          lessonComponentIds: ['subtracting'],
          onSelectScreen: 'subtraction_quiz',
        },
        {
          accent: 'violet',
          description: 'Перевіряйте таблицю множення в короткій вікторині.',
          emoji: '✖️',
          label: 'Вікторина з множення',
          lessonComponentIds: ['multiplication'],
          onSelectScreen: 'multiplication_quiz',
        },
        {
          accent: 'emerald',
          description: 'Швидка вікторина з ділення на рівні групи.',
          emoji: '➗',
          label: 'Вікторина з ділення',
          lessonComponentIds: ['division'],
          onSelectScreen: 'division_quiz',
        },
        {
          accent: 'violet',
          description: 'Розпізнавайте фігури, симетрію та периметри в коротких викликах.',
          emoji: '🔷',
          label: 'Вправи з фігурами',
          lessonComponentIds: KANGUR_GEOMETRY_LESSON_COMPONENT_IDS,
          onSelectScreen: 'geometry_quiz',
        },
        {
          accent: 'violet',
          description: 'Доповнюйте послідовності й перевіряйте правила візерунків.',
          emoji: '🔢',
          label: 'Вікторина з візерунків',
          lessonComponentIds: ['logical_patterns'],
          onSelectScreen: 'logical_patterns_quiz',
        },
        {
          accent: 'teal',
          description: 'Групуйте елементи й знаходьте спільні ознаки.',
          emoji: '📦',
          label: 'Вікторина з класифікації',
          lessonComponentIds: ['logical_classification'],
          onSelectScreen: 'logical_classification_quiz',
        },
        {
          accent: 'rose',
          description: 'Добирайте зв’язки й знаходьте правильні аналогії.',
          emoji: '🔗',
          label: 'Вікторина з аналогій',
          lessonComponentIds: ['logical_analogies'],
          onSelectScreen: 'logical_analogies_quiz',
        },
        {
          accent: 'violet',
          description: 'Тренуйте порядок речення, питання і сполучники в коротких раундах.',
          emoji: '🧩',
          label: 'Вікторина з будови речення',
          lessonComponentIds: ['english_sentence_structure'],
          onSelectScreen: 'english_sentence_quiz',
        },
        {
          accent: 'sky',
          description: 'Сортуйте слова за частинами мови в коротких раундах.',
          emoji: '🎮',
          label: 'Вікторина з частин мови',
          lessonComponentIds: ['english_parts_of_speech'],
          onSelectScreen: 'english_parts_of_speech_quiz',
        },
      ],
      recommendation: {
        actions: {
          playAddition: 'Грати в додавання',
          playSubtraction: 'Грати у віднімання',
          playMultiplication: 'Грати в множення',
          playDivision: 'Грати в ділення',
          playClock: 'Грати з годинником',
          startMixedTraining: 'Запустити змішане тренування',
          playFractions: 'Грати в дроби',
          playPowers: 'Грати в степені',
          playRoots: 'Грати в корені',
          practiceCalendar: 'Тренувати календар',
          practiceGeometry: 'Тренувати фігури',
          practiceSubtraction: 'Тренувати віднімання',
          practiceDivision: 'Тренувати ділення',
          practiceMultiplication: 'Тренувати множення',
          startTraining: 'Запустити тренування',
          playNow: 'Грати зараз',
        },
        questLabel: 'Місія дня',
        weakestLesson: {
          description: (masteryPercent) =>
            `Опрацювання ${masteryPercent}%. Один вдалий раунд допоможе швидше закрити цю тему перед наступним уроком.`,
          label: 'Наздоганяємо уроки',
          title: (title) => `Спершу покращ: ${title}`,
        },
        track: {
          descriptionWithActivity: (track, activity) =>
            `Доріжка ${track} зараз найближча до нагороди. Найсильніше її просуває ${activity}.`,
          descriptionDefault: (track) => `Доріжка ${track} зараз найближча до наступного значка.`,
          label: 'Доріжка значків',
          title: (track) => `Розжени доріжку: ${track}`,
        },
        guided: {
          descriptionWithActivity: (summary, activity, nextBadgeName) =>
            `У тебе вже є ${summary} у рекомендованому ритмі. Ще один сильний раунд ${activity} допоможе закрити значок ${nextBadgeName}.`,
          descriptionDefault: (summary, nextBadgeName) =>
            `У тебе вже є ${summary} у рекомендованому ритмі. Ще один сильний раунд допоможе закрити значок ${nextBadgeName}.`,
          label: 'Рекомендований напрям',
          title: (nextBadgeName) => `Закрий: ${nextBadgeName}`,
        },
        fallback: {
          description: (activity, averageXpPerSession) =>
            `${activity} зараз дає в середньому ${averageXpPerSession} XP за гру. Це найкращий хід на наступний раунд.`,
          label: 'Сильна серія',
          title: (activity) => `Грай далі в: ${activity}`,
        },
      },
    };
  }

  if (locale === 'de') {
    return {
      operationSelectorTitle: 'Los geht\'s!',
      trainingSetupTitle: 'Gemischtes Training',
      trainingSetupWordmarkLabel: 'Training',
      trainingSetupDescription:
        'Wahle Niveau, Kategorien und die Anzahl der Fragen fur eine Sitzung.',
      intro: {
        maths: 'Wahle einen Spieltyp und starte direkt mit dem Mathematiktraining.',
        alphabet: 'Wahle ein Buchstabenspiel und ube das Alphabet.',
        art: 'Wahle eine Kunstlektion und entdecke Farben und Formen.',
        music: 'Wahle eine Musiklektion und singe die Toene der diatonischen Tonleiter Schritt fur Schritt.',
        geometry: 'Wahle ein Formenspiel und ube Geometrie.',
        language: 'Wahle einen Sprachspieltyp und starte direkt ins Uben.',
      },
      quickPractice: {
        title: 'Schnelles Uben',
        description: 'Kurze Quizrunden auf Basis von Lektionsthemen.',
        groupAria: (group) => `${group} schnelles Uben`,
        cardAria: (label) => `Schnelles Uben: ${label}`,
        gameChip: 'Spiel',
      },
      lessonQuizDefinitions: [
        {
          accent: 'indigo',
          description: 'Ube das Lesen von Stunden und Minuten im Quizmodus.',
          emoji: '🕐',
          label: 'Uhrzeitubung',
          lessonComponentIds: ['clock'],
          onSelectScreen: 'clock_quiz',
        },
        {
          accent: 'emerald',
          description: 'Prufe Daten, Wochentage und Monate in kurzen Aufgaben.',
          emoji: '📅',
          label: 'Kalenderubung',
          lessonComponentIds: ['calendar'],
          onSelectScreen: 'calendar_quiz',
        },
        {
          accent: 'amber',
          description: 'Ein schnelles Additionsquiz im Rhythmus des Lernspiels.',
          emoji: '➕',
          label: 'Additionsquiz',
          lessonComponentIds: ['adding'],
          onSelectScreen: 'addition_quiz',
        },
        {
          accent: 'rose',
          description: 'Eine schnelle Subtraktionsserie mit sofortiger Antwort.',
          emoji: '➖',
          label: 'Subtraktionsquiz',
          lessonComponentIds: ['subtracting'],
          onSelectScreen: 'subtraction_quiz',
        },
        {
          accent: 'violet',
          description: 'Prufe das Einmaleins in einem kurzen Quiz.',
          emoji: '✖️',
          label: 'Multiplikationsquiz',
          lessonComponentIds: ['multiplication'],
          onSelectScreen: 'multiplication_quiz',
        },
        {
          accent: 'emerald',
          description: 'Ein schnelles Divisionsquiz mit gleichen Gruppen.',
          emoji: '➗',
          label: 'Divisionsquiz',
          lessonComponentIds: ['division'],
          onSelectScreen: 'division_quiz',
        },
        {
          accent: 'violet',
          description: 'Erkenne Formen, Symmetrie und Umfang in kurzen Herausforderungen.',
          emoji: '🔷',
          label: 'Formenubung',
          lessonComponentIds: KANGUR_GEOMETRY_LESSON_COMPONENT_IDS,
          onSelectScreen: 'geometry_quiz',
        },
        {
          accent: 'violet',
          description: 'Erganze Reihen und prufe Musterregeln.',
          emoji: '🔢',
          label: 'Musterquiz',
          lessonComponentIds: ['logical_patterns'],
          onSelectScreen: 'logical_patterns_quiz',
        },
        {
          accent: 'teal',
          description: 'Ordne Elemente und finde gemeinsame Merkmale.',
          emoji: '📦',
          label: 'Klassifikationsquiz',
          lessonComponentIds: ['logical_classification'],
          onSelectScreen: 'logical_classification_quiz',
        },
        {
          accent: 'rose',
          description: 'Ordne Beziehungen zu und finde die passenden Analogien.',
          emoji: '🔗',
          label: 'Analogiequiz',
          lessonComponentIds: ['logical_analogies'],
          onSelectScreen: 'logical_analogies_quiz',
        },
        {
          accent: 'violet',
          description: 'Satzbau, Fragen und Konjunktionen in kurzen Runden uben.',
          emoji: '🧩',
          label: 'Satzbauquiz',
          lessonComponentIds: ['english_sentence_structure'],
          onSelectScreen: 'english_sentence_quiz',
        },
        {
          accent: 'sky',
          description: 'Sortiere Worter nach Wortarten in kurzen Runden.',
          emoji: '🎮',
          label: 'Wortartenquiz',
          lessonComponentIds: ['english_parts_of_speech'],
          onSelectScreen: 'english_parts_of_speech_quiz',
        },
      ],
      recommendation: {
        actions: {
          playAddition: 'Addition spielen',
          playSubtraction: 'Subtraktion spielen',
          playMultiplication: 'Multiplikation spielen',
          playDivision: 'Division spielen',
          playClock: 'Uhr spielen',
          startMixedTraining: 'Gemischtes Training starten',
          playFractions: 'Bruche spielen',
          playPowers: 'Potenzen spielen',
          playRoots: 'Wurzeln spielen',
          practiceCalendar: 'Kalender uben',
          practiceGeometry: 'Formen uben',
          practiceSubtraction: 'Subtraktion uben',
          practiceDivision: 'Division uben',
          practiceMultiplication: 'Multiplikation uben',
          startTraining: 'Training starten',
          playNow: 'Jetzt spielen',
        },
        questLabel: 'Mission des Tages',
        weakestLesson: {
          description: (masteryPercent) =>
            `Beherrschung ${masteryPercent}%. Eine gute Runde schliesst dieses Thema vor der nachsten Lektion schneller.`,
          label: 'Lektionen nachholen',
          title: (title) => `Zuerst verbessern: ${title}`,
        },
        track: {
          descriptionWithActivity: (track, activity) =>
            `Der Pfad ${track} ist einer Belohnung am nachsten. Gerade schiebt ${activity} ihn am starksten.`,
          descriptionDefault: (track) =>
            `Der Pfad ${track} ist dem nachsten Abzeichen am nachsten.`,
          label: 'Abzeichenpfad',
          title: (track) => `Pfad anschieben: ${track}`,
        },
        guided: {
          descriptionWithActivity: (summary, activity, nextBadgeName) =>
            `Du hast bereits ${summary} im empfohlenen Rhythmus. Noch eine starke Runde ${activity} hilft, das Abzeichen ${nextBadgeName} abzuschliessen.`,
          descriptionDefault: (summary, nextBadgeName) =>
            `Du hast bereits ${summary} im empfohlenen Rhythmus. Noch eine starke Runde hilft, das Abzeichen ${nextBadgeName} abzuschliessen.`,
          label: 'Empfohlene Richtung',
          title: (nextBadgeName) => `Schliesse ab: ${nextBadgeName}`,
        },
        fallback: {
          description: (activity, averageXpPerSession) =>
            `${activity} bringt derzeit durchschnittlich ${averageXpPerSession} XP pro Spiel. Das ist der beste Zug fur die nachste Runde.`,
          label: 'Starke Serie',
          title: (activity) => `Spiel weiter in: ${activity}`,
        },
      },
    };
  }

  if (locale === 'en') {
    return {
      operationSelectorTitle: 'Let\'s play!',
      trainingSetupTitle: 'Mixed training',
      trainingSetupWordmarkLabel: 'Training',
      trainingSetupDescription: 'Choose the level, categories, and number of questions for one session.',
      intro: {
        maths: 'Choose a game type and jump straight into maths practice.',
        alphabet: 'Choose a letter game and practise the alphabet.',
        art: 'Choose an art lesson and explore colors and shapes.',
        music: 'Choose a music lesson and sing the notes of the diatonic scale step by step.',
        geometry: 'Choose a shapes game and practise geometry.',
        language: 'Choose a language game type and jump straight into practice.',
      },
      quickPractice: {
        title: 'Quick practice',
        description: 'Quick quizzes based on lesson topics.',
        groupAria: (group) => `${group} quick practice`,
        cardAria: (label) => `Quick practice: ${label}`,
        gameChip: 'Game',
      },
      lessonQuizDefinitions: [
        {
          accent: 'indigo',
          description: 'Practise reading hours and minutes in quiz mode.',
          emoji: '🕐',
          label: 'Clock practice',
          lessonComponentIds: ['clock'],
          onSelectScreen: 'clock_quiz',
        },
        {
          accent: 'emerald',
          description: 'Check dates, weekdays, and months in short tasks.',
          emoji: '📅',
          label: 'Calendar practice',
          lessonComponentIds: ['calendar'],
          onSelectScreen: 'calendar_quiz',
        },
        {
          accent: 'amber',
          description: 'A quick addition quiz in the rhythm of the lesson game.',
          emoji: '➕',
          label: 'Addition quiz',
          lessonComponentIds: ['adding'],
          onSelectScreen: 'addition_quiz',
        },
        {
          accent: 'rose',
          description: 'A quick subtraction streak with instant feedback.',
          emoji: '➖',
          label: 'Subtraction quiz',
          lessonComponentIds: ['subtracting'],
          onSelectScreen: 'subtraction_quiz',
        },
        {
          accent: 'violet',
          description: 'Check the times table in a short multiplication quiz.',
          emoji: '✖️',
          label: 'Multiplication quiz',
          lessonComponentIds: ['multiplication'],
          onSelectScreen: 'multiplication_quiz',
        },
        {
          accent: 'emerald',
          description: 'A quick division quiz based on equal groups.',
          emoji: '➗',
          label: 'Division quiz',
          lessonComponentIds: ['division'],
          onSelectScreen: 'division_quiz',
        },
        {
          accent: 'violet',
          description: 'Recognize shapes, symmetry, and perimeter in short challenges.',
          emoji: '🔷',
          label: 'Shapes practice',
          lessonComponentIds: KANGUR_GEOMETRY_LESSON_COMPONENT_IDS,
          onSelectScreen: 'geometry_quiz',
        },
        {
          accent: 'violet',
          description: 'Complete sequences and check the rules behind patterns.',
          emoji: '🔢',
          label: 'Patterns quiz',
          lessonComponentIds: ['logical_patterns'],
          onSelectScreen: 'logical_patterns_quiz',
        },
        {
          accent: 'teal',
          description: 'Group items and find shared traits.',
          emoji: '📦',
          label: 'Classification quiz',
          lessonComponentIds: ['logical_classification'],
          onSelectScreen: 'logical_classification_quiz',
        },
        {
          accent: 'rose',
          description: 'Match relationships and find the right analogies.',
          emoji: '🔗',
          label: 'Analogies quiz',
          lessonComponentIds: ['logical_analogies'],
          onSelectScreen: 'logical_analogies_quiz',
        },
        {
          accent: 'violet',
          description: 'Practise sentence order, questions, and conjunctions in short rounds.',
          emoji: '🧩',
          label: 'Sentence structure quiz',
          lessonComponentIds: ['english_sentence_structure'],
          onSelectScreen: 'english_sentence_quiz',
        },
        {
          accent: 'sky',
          description: 'Sort words by parts of speech in short rounds.',
          emoji: '🎮',
          label: 'Parts of speech quiz',
          lessonComponentIds: ['english_parts_of_speech'],
          onSelectScreen: 'english_parts_of_speech_quiz',
        },
      ],
      recommendation: {
        actions: {
          playAddition: 'Play addition',
          playSubtraction: 'Play subtraction',
          playMultiplication: 'Play multiplication',
          playDivision: 'Play division',
          playClock: 'Play the clock',
          startMixedTraining: 'Start mixed training',
          playFractions: 'Play fractions',
          playPowers: 'Play powers',
          playRoots: 'Play roots',
          practiceCalendar: 'Practise calendar',
          practiceGeometry: 'Practise shapes',
          practiceSubtraction: 'Practise subtraction',
          practiceDivision: 'Practise division',
          practiceMultiplication: 'Practise multiplication',
          startTraining: 'Start training',
          playNow: 'Play now',
        },
        questLabel: 'Mission of the day',
        weakestLesson: {
          description: (masteryPercent) =>
            `Mastery ${masteryPercent}%. One good round will close this topic faster before the next lesson.`,
          label: 'Recover lessons',
          title: (title) => `Fix first: ${title}`,
        },
        track: {
          descriptionWithActivity: (track, activity) =>
            `The ${track} track is closest to a reward. Right now ${activity} pushes it the most.`,
          descriptionDefault: (track) => `The ${track} track is closest to the next badge.`,
          label: 'Badge track',
          title: (track) => `Push the track: ${track}`,
        },
        guided: {
          descriptionWithActivity: (summary, activity, nextBadgeName) =>
            `You already have ${summary} in the recommended rhythm. One more strong round of ${activity} will help finish the ${nextBadgeName} badge.`,
          descriptionDefault: (summary, nextBadgeName) =>
            `You already have ${summary} in the recommended rhythm. One more strong round will help finish the ${nextBadgeName} badge.`,
          label: 'Recommended direction',
          title: (nextBadgeName) => `Finish: ${nextBadgeName}`,
        },
        fallback: {
          description: (activity, averageXpPerSession) =>
            `${activity} is currently worth about ${averageXpPerSession} XP per game. It is the best move for the next round.`,
          label: 'Strong streak',
          title: (activity) => `Keep playing: ${activity}`,
        },
      },
    };
  }

  return {
    operationSelectorTitle: 'Grajmy!',
    trainingSetupTitle: 'Trening mieszany',
    trainingSetupWordmarkLabel: 'Trening',
    trainingSetupDescription: 'Dobierz poziom, kategorie i liczbę pytań do jednej sesji.',
    intro: {
      maths: 'Wybierz rodzaj gry i przejdź od razu do matematycznej zabawy.',
      alphabet: 'Wybierz literową zabawę i ćwicz alfabet.',
      art: 'Wybierz lekcję plastyczną i odkrywaj kolory oraz kształty.',
      music: 'Wybierz lekcję muzyki i śpiewaj dźwięki skali diatonicznej krok po kroku.',
      geometry: 'Wybierz zabawę z kształtami i ćwicz geometrię.',
      language: 'Wybierz typ gry językowej i przejdź od razu do ćwiczeń.',
    },
    quickPractice: {
      title: 'Szybkie ćwiczenia',
      description: 'Szybkie quizy oparte na tematach z Lekcji.',
      groupAria: (group) => `${group} szybkie ćwiczenia`,
      cardAria: (label) => `Szybkie ćwiczenie: ${label}`,
      gameChip: 'Gra',
    },
    lessonQuizDefinitions: [
      {
        accent: 'indigo',
        description: 'Ćwicz odczytywanie godzin i minut w trybie quizu.',
        emoji: '🕐',
        label: 'Ćwiczenia z Zegarem',
        lessonComponentIds: ['clock'],
        onSelectScreen: 'clock_quiz',
      },
      {
        accent: 'emerald',
        description: 'Sprawdź daty, dni tygodnia i miesiące w krótkich zadaniach.',
        emoji: '📅',
        label: 'Ćwiczenia z Kalendarzem',
        lessonComponentIds: ['calendar'],
        onSelectScreen: 'calendar_quiz',
      },
      {
        accent: 'amber',
        description: 'Szybki quiz z dodawania w rytmie gry z lekcji.',
        emoji: '➕',
        label: 'Quiz dodawania',
        lessonComponentIds: ['adding'],
        onSelectScreen: 'addition_quiz',
      },
      {
        accent: 'rose',
        description: 'Szybka seria odejmowania z natychmiastową odpowiedzią.',
        emoji: '➖',
        label: 'Quiz odejmowania',
        lessonComponentIds: ['subtracting'],
        onSelectScreen: 'subtraction_quiz',
      },
      {
        accent: 'violet',
        description: 'Sprawdź tabliczkę w krótkim quizie z mnożenia.',
        emoji: '✖️',
        label: 'Quiz mnożenia',
        lessonComponentIds: ['multiplication'],
        onSelectScreen: 'multiplication_quiz',
      },
      {
        accent: 'emerald',
        description: 'Szybki quiz z dzielenia na równe grupy.',
        emoji: '➗',
        label: 'Quiz dzielenia',
        lessonComponentIds: ['division'],
        onSelectScreen: 'division_quiz',
      },
      {
        accent: 'violet',
        description: 'Rozpoznawaj figury, symetrię i obwody w krótkich wyzwaniach.',
        emoji: '🔷',
        label: 'Ćwiczenia z Figurami',
        lessonComponentIds: KANGUR_GEOMETRY_LESSON_COMPONENT_IDS,
        onSelectScreen: 'geometry_quiz',
      },
      {
        accent: 'violet',
        description: 'Uzupełniaj ciągi i sprawdzaj reguły wzorców.',
        emoji: '🔢',
        label: 'Quiz wzorców',
        lessonComponentIds: ['logical_patterns'],
        onSelectScreen: 'logical_patterns_quiz',
      },
      {
        accent: 'teal',
        description: 'Grupuj elementy i znajdź wspólne cechy.',
        emoji: '📦',
        label: 'Quiz klasyfikacji',
        lessonComponentIds: ['logical_classification'],
        onSelectScreen: 'logical_classification_quiz',
      },
      {
        accent: 'rose',
        description: 'Dopasuj relacje i znajdź właściwe analogie.',
        emoji: '🔗',
        label: 'Quiz analogii',
        lessonComponentIds: ['logical_analogies'],
        onSelectScreen: 'logical_analogies_quiz',
      },
      {
        accent: 'violet',
        description: 'Ćwicz szyk zdania, pytania i spójniki w krótkich rundach.',
        emoji: '🧩',
        label: 'Quiz składni zdania',
        lessonComponentIds: ['english_sentence_structure'],
        onSelectScreen: 'english_sentence_quiz',
      },
      {
        accent: 'sky',
        description: 'Sortuj słowa według części mowy w krótkich rundach.',
        emoji: '🎮',
        label: 'Quiz części mowy',
        lessonComponentIds: ['english_parts_of_speech'],
        onSelectScreen: 'english_parts_of_speech_quiz',
      },
    ],
    recommendation: {
      actions: {
        playAddition: 'Zagraj w dodawanie',
        playSubtraction: 'Zagraj w odejmowanie',
        playMultiplication: 'Zagraj w mnożenie',
        playDivision: 'Zagraj w dzielenie',
        playClock: 'Zagraj na zegarze',
        startMixedTraining: 'Uruchom trening mieszany',
        playFractions: 'Zagraj we ułamki',
        playPowers: 'Zagraj w potęgi',
        playRoots: 'Zagraj w pierwiastki',
        practiceCalendar: 'Ćwicz kalendarz',
        practiceGeometry: 'Ćwicz figury',
        practiceSubtraction: 'Ćwicz odejmowanie',
        practiceDivision: 'Ćwicz dzielenie',
        practiceMultiplication: 'Ćwicz mnożenie',
        startTraining: 'Uruchom trening',
        playNow: 'Zagraj teraz',
      },
      questLabel: 'Misja dnia',
      weakestLesson: {
        description: (masteryPercent) =>
          `Opanowanie ${masteryPercent}%. Jedna dobra runda pomoże szybciej domknąć ten temat przed kolejną lekcją.`,
        label: 'Nadrabiamy lekcje',
        title: (title) => `Najpierw popraw: ${title}`,
      },
      track: {
        descriptionWithActivity: (track, activity) =>
          `Tor ${track} jest najbliżej nagrody. Najmocniej pcha go teraz ${activity}.`,
        descriptionDefault: (track) => `Tor ${track} jest najbliżej kolejnej odznaki.`,
        label: 'Tor odznak',
        title: (track) => `Rozpędź tor: ${track}`,
      },
      guided: {
        descriptionWithActivity: (summary, activity, nextBadgeName) =>
          `Masz już ${summary} w polecanym rytmie. Jeszcze jedna mocna runda ${activity} pomoże domknąć odznakę ${nextBadgeName}.`,
        descriptionDefault: (summary, nextBadgeName) =>
          `Masz już ${summary} w polecanym rytmie. Jeszcze jedna mocna runda pomoże domknąć odznakę ${nextBadgeName}.`,
        label: 'Polecony kierunek',
        title: (nextBadgeName) => `Dopnij: ${nextBadgeName}`,
      },
      fallback: {
        description: (activity, averageXpPerSession) =>
          `${activity} daje teraz średnio ${averageXpPerSession} XP na grę. To najlepszy ruch na kolejną rundę.`,
        label: 'Mocna passa',
        title: (activity) => `Zagraj dalej w: ${activity}`,
      },
    },
  };
};
