const KANGUR_MOBILE_ACTION_LABEL_MAP: Record<string, string> = {
  'All sessions': 'Wszystkie sesje',
  Arithmetic: 'Arytmetyka',
  Assignments: 'Zadania',
  Back: 'Wroc',
  'Back to profile': 'Wroc do profilu',
  'Daily plan': 'Plan dnia',
  Leaderboard: 'Ranking',
  Logic: 'Logika',
  'Mode history': 'Historia trybu',
  'Open auth screen': 'Otworz ekran logowania',
  'Open daily plan': 'Otworz plan dnia',
  'Open full history': 'Otworz cala historie',
  'Open history': 'Otworz historie',
  'Open lesson': 'Otworz lekcje',
  'Open matching lesson': 'Otworz pasujaca lekcje',
  'Practice now': 'Trenuj teraz',
  'Practice weakest': 'Trenuj najslabszy tryb',
  'Recent results': 'Ostatnie wyniki',
  Refresh: 'Odswiez',
  'Refresh plan': 'Odswiez plan',
  'Refresh proof': 'Odswiez podglad',
  'Sign in demo session': 'Zaloguj sesje demo',
  'Start mixed practice': 'Uruchom trening mieszany',
  'Strongest mode': 'Najmocniejszy tryb',
  'Train again': 'Trenuj ponownie',
  'Train this mode': 'Trenuj ten tryb',
  'Training focus': 'Fokus treningowy',
  Time: 'Czas',
  'View mode history': 'Zobacz historie trybu',
  'Weakest mode': 'Do powtorki',
};

export const translateKangurMobileActionLabel = (label: string): string =>
  KANGUR_MOBILE_ACTION_LABEL_MAP[label] ?? label;
