const KANGUR_MOBILE_ACTION_LABEL_MAP: Record<string, string> = {
  'All sessions': 'Wszystkie sesje',
  Arithmetic: 'Arytmetyka',
  Assignments: 'Zadania',
  Back: 'Wróć',
  'Back to profile': 'Wróć do profilu',
  'Daily plan': 'Plan dnia',
  Leaderboard: 'Ranking',
  Logic: 'Logika',
  'Mode history': 'Historia trybu',
  'Open auth screen': 'Otwórz ekran logowania',
  'Open daily plan': 'Otwórz plan dnia',
  'Open full history': 'Otwórz całą historię',
  'Open history': 'Otwórz historię',
  'Open lesson': 'Otwórz lekcję',
  'Open matching lesson': 'Otwórz pasującą lekcję',
  'Practice now': 'Trenuj teraz',
  'Practice weakest': 'Trenuj najsłabszy tryb',
  'Recent results': 'Ostatnie wyniki',
  Refresh: 'Odśwież',
  'Refresh plan': 'Odśwież plan',
  'Refresh proof': 'Odśwież podgląd',
  'Sign in demo session': 'Zaloguj sesję demo',
  'Start mixed practice': 'Uruchom trening mieszany',
  'Strongest mode': 'Najmocniejszy tryb',
  'Train again': 'Trenuj ponownie',
  'Train this mode': 'Trenuj ten tryb',
  'Training focus': 'Fokus treningowy',
  Time: 'Czas',
  'View mode history': 'Zobacz historię trybu',
  'Weakest mode': 'Do powtórki',
};

export const translateKangurMobileActionLabel = (label: string): string =>
  KANGUR_MOBILE_ACTION_LABEL_MAP[label] ?? label;
