import { ToastProvider } from "@/shared/ui";
import type { Metadata } from "next";
import { Suspense } from "react";

import { ThemeProvider } from "@/shared/providers/theme-provider";

import { QueryProvider } from "@/shared/providers/QueryProvider";
import { BackgroundSyncProvider } from "@/shared/providers/BackgroundSyncProvider";
import ClientErrorReporter from "@/features/observability";
import { SessionProvider } from "next-auth/react";
import { cn } from "@/shared/utils";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=DM+Sans:wght@400;500;700&family=Manrope:wght@300;400;500;600;700;800&family=Outfit:wght@300;400;500;600;700;800;900&family=Plus+Jakarta+Sans:wght@300;400;500;600;700;800&family=Space+Grotesk:wght@300;400;500;600;700&family=Sora:wght@300;400;500;600;700&display=swap"
        />
      </head>
      <body className={cn("font-sans")}>
        <ToastProvider>
          <QueryProvider>
            <BackgroundSyncProvider>
              <SessionProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <Suspense fallback={null}>
                    <ClientErrorReporter />
                  </Suspense>
                  {children}
                </ThemeProvider>
              </SessionProvider>
            </BackgroundSyncProvider>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
