import { ToastProvider } from "@/shared/ui";
import type { Metadata } from "next";
import { Suspense } from "react";

import { ThemeProvider } from "@/shared/providers/theme-provider";

import { QueryProvider } from "@/shared/providers/QueryProvider";
import { BackgroundSyncProvider } from "@/shared/providers/BackgroundSyncProvider";
import ClientErrorReporter from "@/features/observability";
import { SessionProvider } from "next-auth/react";
import { cn } from "@/shared/utils";
import { AppFontProvider } from "@/shared/providers/AppFontProvider";
import { CsrfProvider } from "@/shared/providers/CsrfProvider";
import PageAnalyticsTracker from "@/features/analytics/components/PageAnalyticsTracker";

import "./fonts.css";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("font-sans")}>
        <ToastProvider>
          <QueryProvider>
            <AppFontProvider />
            <BackgroundSyncProvider>
              <SessionProvider>
                <ThemeProvider
                  attribute="class"
                  defaultTheme="system"
                  enableSystem
                  disableTransitionOnChange
                >
                  <CsrfProvider />
                  <Suspense fallback={null}>
                    <ClientErrorReporter />
                  </Suspense>
                  <Suspense fallback={null}>
                    <PageAnalyticsTracker />
                  </Suspense>
                  {children}
                </ThemeProvider>
              </SessionProvider>
            </BackgroundSyncProvider>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
