import { SessionProvider } from 'next-auth/react';
import { Suspense } from 'react';

import PageAnalyticsTracker from '@/features/analytics/components/PageAnalyticsTracker';
import ClientErrorReporter from '@/features/observability/components/ClientErrorReporter';
import { AppFontProvider } from '@/shared/providers/AppFontProvider';
import { BackgroundSyncProvider } from '@/shared/providers/BackgroundSyncProvider';
import { CsrfProvider } from '@/shared/providers/CsrfProvider';
import { QueryProvider } from '@/shared/providers/QueryProvider';
import { SettingsStoreProvider } from '@/shared/providers/SettingsStoreProvider';
import { ThemeProvider } from '@/shared/providers/theme-provider';
import { UrlGuardProvider } from '@/shared/providers/UrlGuardProvider';
import { ToastProvider } from '@/shared/ui/toast';
import { cn } from '@/shared/utils';

import type { Metadata } from 'next';

import './fonts.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn('font-sans')}>
        <ToastProvider>
          <QueryProvider>
            <SettingsStoreProvider mode="lite">
              <AppFontProvider />
              <BackgroundSyncProvider>
                <SessionProvider>
                  <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                  >
                    <CsrfProvider />
                    <UrlGuardProvider />
                    <Suspense fallback={null}>
                      <ClientErrorReporter />
                    </Suspense>
                    <Suspense fallback={null}>
                      <PageAnalyticsTracker />
                    </Suspense>
                    {children}
                  </ThemeProvider>
                </SessionProvider>
              </BackgroundSyncProvider>
            </SettingsStoreProvider>
          </QueryProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
