import type { LabeledOptionDto } from '@/shared/contracts/base';

export const DB_COLLECTION_OPTIONS = [
  { value: 'products', label: 'Products' },
  { value: 'product_drafts', label: 'Product Drafts' },
  { value: 'product_categories', label: 'Product Categories' },
  { value: 'product_parameters', label: 'Product Parameters' },
  { value: 'product_tags', label: 'Product Tags' },
  { value: 'catalogs', label: 'Catalogs' },
  { value: 'image_files', label: 'Image Files' },
  { value: 'product_listings', label: 'Product Listings' },
  { value: 'product_ai_jobs', label: 'Product AI Jobs' },
  { value: 'integrations', label: 'Integrations' },
  { value: 'integration_connections', label: 'Integration Connections' },
  { value: 'settings', label: 'Settings' },
  { value: 'users', label: 'Users' },
  { value: 'user_preferences', label: 'User Preferences' },
  { value: 'languages', label: 'Languages' },
  { value: 'system_logs', label: 'System Logs' },
  { value: 'notes', label: 'Notes' },
  { value: 'tags', label: 'Note Tags' },
  { value: 'categories', label: 'Note Categories' },
  { value: 'notebooks', label: 'Note Notebooks' },
  { value: 'noteFiles', label: 'Note Files' },
  { value: 'themes', label: 'Note Themes' },
  { value: 'chatbot_sessions', label: 'Chatbot Sessions' },
  { value: 'auth_security_attempts', label: 'Auth Security Attempts' },
  { value: 'auth_security_profiles', label: 'Auth Security Profiles' },
  { value: 'auth_login_challenges', label: 'Auth Login Challenges' },
  { value: 'custom', label: 'Custom (allowlisted only)' },
] as const satisfies ReadonlyArray<LabeledOptionDto<string>>;

export const CONTEXT_PRESET_FIELDS: Record<
  string,
  { light: string[]; medium: string[]; full: string[]; suggested: string[] }
> = {
  product: {
    light: ['id', 'sku', 'name_en', 'name_pl', 'name_de', 'price', 'stock', 'imageLinks'],
    medium: [
      'id',
      'sku',
      'name_en',
      'name_pl',
      'name_de',
      'price',
      'stock',
      'imageLinks',
      'description_en',
      'description_pl',
      'description_de',
      'catalogs',
      'parameters',
      'supplierName',
      'supplierLink',
      'createdAt',
      'updatedAt',
    ],
    full: [],
    suggested: [
      'id',
      'sku',
      'name_en',
      'name_pl',
      'name_de',
      'description_en',
      'price',
      'stock',
      'imageLinks',
      'catalogs',
      'parameters',
      'supplierName',
      'supplierLink',
      'createdAt',
      'updatedAt',
    ],
  },
  note: {
    light: ['id', 'title', 'content', 'notebookId', 'isPinned', 'isFavorite', 'updatedAt'],
    medium: [
      'id',
      'title',
      'content',
      'notebookId',
      'isPinned',
      'isFavorite',
      'isArchived',
      'editorType',
      'color',
      'tags',
      'categories',
      'createdAt',
      'updatedAt',
    ],
    full: [],
    suggested: [
      'id',
      'title',
      'content',
      'notebookId',
      'tags',
      'categories',
      'relationsFrom',
      'relationsTo',
      'isPinned',
      'isFavorite',
      'isArchived',
      'editorType',
      'color',
      'createdAt',
      'updatedAt',
    ],
  },
  default: {
    light: ['id', 'name', 'title', 'status', 'updatedAt'],
    medium: ['id', 'name', 'title', 'status', 'createdAt', 'updatedAt', 'meta'],
    full: [],
    suggested: ['id', 'name', 'title', 'status', 'createdAt', 'updatedAt', 'meta'],
  },
};
