import type { LabeledOptionDto } from '@/shared/contracts/base';

export const PARSER_PRESETS = [
  {
    id: 'product_core',
    label: 'Product: Core',
    description: 'id, title, images, content_en, sku, price, stock',
    mappings: {
      productId: '$.id',
      title: '$.title',
      images: '$.images',
      content_en: '$.content_en',
      sku: '$.sku',
      price: '$.price',
      stock: '$.stock',
    },
  },
  {
    id: 'product_media',
    label: 'Product: Media',
    description: 'imageLinks, gallery, videos',
    mappings: {
      images: '$.imageLinks',
      gallery: '$.gallery',
      videos: '$.videos',
    },
  },
  {
    id: 'note_core',
    label: 'Note: Core',
    description: 'id, title, content, tags, updatedAt',
    mappings: {
      noteId: '$.id',
      title: '$.title',
      content: '$.content',
      tags: '$.tags',
      updatedAt: '$.updatedAt',
    },
  },
  {
    id: 'chat_message',
    label: 'Chat: Message',
    description: 'id, role, content, createdAt',
    mappings: {
      messageId: '$.id',
      role: '$.role',
      content: '$.content',
      createdAt: '$.createdAt',
    },
  },
  {
    id: 'generic_audit',
    label: 'Generic: Audit',
    description: 'id, name, title, status, createdAt, updatedAt',
    mappings: {
      id: '$.id',
      name: '$.name',
      title: '$.title',
      status: '$.status',
      createdAt: '$.createdAt',
      updatedAt: '$.updatedAt',
    },
  },
];

export const PARSER_PATH_OPTIONS = [
  { label: 'Common: id', value: '$.id' },
  { label: 'Common: title', value: '$.title' },
  { label: 'Common: name', value: '$.name' },
  { label: 'Common: status', value: '$.status' },
  { label: 'Common: createdAt', value: '$.createdAt' },
  { label: 'Common: updatedAt', value: '$.updatedAt' },
  { label: 'Product: sku', value: '$.sku' },
  { label: 'Product: price', value: '$.price' },
  { label: 'Product: stock', value: '$.stock' },
  { label: 'Product: content_en', value: '$.content_en' },
  { label: 'Product: name_en', value: '$.name_en' },
  { label: 'Product: name_pl', value: '$.name_pl' },
  { label: 'Product: imageLinks', value: '$.imageLinks' },
  { label: 'Product: images', value: '$.images' },
  { label: 'Product: media', value: '$.media' },
  { label: 'Product: gallery', value: '$.gallery' },
  { label: 'Product: supplierName', value: '$.supplierName' },
  { label: 'Product: catalogs', value: '$.catalogs' },
  { label: 'Note: content', value: '$.content' },
  { label: 'Note: tags', value: '$.tags' },
  { label: 'Note: notebookId', value: '$.notebookId' },
  { label: 'Chat: role', value: '$.role' },
  { label: 'Chat: messages[0].content', value: '$.messages[0].content' },
] as const satisfies ReadonlyArray<LabeledOptionDto<string>>;
