import { type NodeType } from '@/shared/contracts/ai-paths-core';

export const allowedConnections: Record<NodeType, NodeType[]> = {
  trigger: ['fetcher', 'simulation', 'context', 'constant', 'database', 'ai_description'],
  fetcher: ['parser', 'regex', 'mapper', 'validator', 'template', 'bundle', 'database'],
  simulation: ['fetcher', 'context', 'constant', 'database'],
  context: ['parser', 'regex', 'mapper', 'validator', 'template', 'bundle', 'database'],
  audio_oscillator: ['audio_speaker', 'viewer'],
  audio_speaker: ['viewer'],
  parser: ['mutator', 'mapper', 'validator', 'template', 'bundle', 'database', 'prompt'],
  regex: ['mutator', 'mapper', 'validator', 'template', 'bundle', 'database', 'prompt'],
  iterator: ['mutator', 'mapper', 'validator', 'template', 'bundle', 'database', 'prompt'],
  mapper: ['mutator', 'validator', 'template', 'bundle', 'database', 'prompt'],
  mutator: ['validator', 'template', 'bundle', 'database', 'prompt'],
  string_mutator: ['validator', 'template', 'bundle', 'database', 'prompt'],
  validator: ['gate', 'compare', 'logical_condition', 'router', 'database', 'notification'],
  validation_pattern: ['gate', 'compare', 'logical_condition', 'router', 'database'],
  constant: [
    'mutator',
    'mapper',
    'validator',
    'template',
    'bundle',
    'database',
    'prompt',
    'model',
    'agent',
  ],
  math: ['mutator', 'mapper', 'validator', 'template', 'bundle', 'database', 'compare'],
  template: ['mutator', 'mapper', 'validator', 'bundle', 'database', 'prompt', 'model', 'agent'],
  bundle: [
    'mutator',
    'mapper',
    'validator',
    'template',
    'database',
    'prompt',
    'model',
    'agent',
    'http',
    'api_advanced',
  ],
  gate: ['mutator', 'mapper', 'template', 'bundle', 'database', 'prompt', 'model', 'agent'],
  compare: ['gate', 'logical_condition', 'router', 'database', 'notification', 'delay'],
  logical_condition: ['gate', 'router', 'database', 'notification', 'delay'],
  router: ['mutator', 'mapper', 'template', 'bundle', 'database', 'prompt', 'model', 'agent'],
  delay: ['mutator', 'mapper', 'template', 'bundle', 'database', 'prompt', 'model', 'agent'],
  poll: ['viewer', 'database', 'notification', 'delay'],
  http: ['parser', 'regex', 'mapper', 'validator', 'template', 'bundle', 'database', 'viewer'],
  api_advanced: [
    'parser',
    'regex',
    'mapper',
    'validator',
    'template',
    'bundle',
    'database',
    'viewer',
  ],
  database: ['viewer', 'parser', 'regex', 'mapper', 'validator', 'template', 'bundle', 'compare'],
  db_schema: ['viewer', 'prompt', 'model', 'agent', 'database'],
  document: ['viewer', 'parser', 'regex', 'mapper', 'validator', 'template', 'bundle'],
  scanfile: ['viewer', 'parser', 'regex', 'mapper', 'validator', 'template', 'bundle'],
  prompt: ['model', 'agent', 'learner_agent', 'playwright'],
  model: [
    'viewer',
    'parser',
    'regex',
    'mapper',
    'validator',
    'template',
    'bundle',
    'database',
    'notification',
    'delay',
  ],
  agent: [
    'viewer',
    'parser',
    'regex',
    'mapper',
    'validator',
    'template',
    'bundle',
    'database',
    'notification',
    'delay',
    'learner_agent',
  ],
  learner_agent: ['viewer', 'bundle', 'template', 'prompt', 'database', 'notification', 'delay'],
  playwright: [
    'viewer',
    'bundle',
    'template',
    'prompt',
    'database',
    'poll',
    'notification',
    'delay',
  ],
  viewer: [],
  ai_description: ['viewer', 'description_updater', 'bundle', 'delay', 'poll'],
  description_updater: ['viewer', 'bundle', 'delay', 'poll'],
  notification: ['viewer', 'bundle', 'delay', 'poll'],
  bounds_normalizer: [
    'viewer',
    'canvas_output',
    'bundle',
    'mapper',
    'validator',
    'template',
    'database',
    'prompt',
  ],
  canvas_output: [],
  function: [],
  state: [],
  switch: [],
  subgraph: [],
};

export const typeStyles: Record<NodeType, { border: string; glow: string }> = {
  trigger: { border: 'border-lime-500/40', glow: 'shadow-lime-500/20' },
  fetcher: { border: 'border-cyan-400/40', glow: 'shadow-cyan-400/20' },
  simulation: { border: 'border-cyan-500/40', glow: 'shadow-cyan-500/20' },
  context: { border: 'border-emerald-500/40', glow: 'shadow-emerald-500/20' },
  audio_oscillator: { border: 'border-violet-400/40', glow: 'shadow-violet-400/20' },
  audio_speaker: { border: 'border-indigo-500/40', glow: 'shadow-indigo-500/20' },
  parser: { border: 'border-sky-500/40', glow: 'shadow-sky-500/20' },
  regex: { border: 'border-cyan-500/40', glow: 'shadow-cyan-500/20' },
  iterator: { border: 'border-amber-500/40', glow: 'shadow-amber-500/20' },
  mapper: { border: 'border-blue-500/40', glow: 'shadow-blue-500/20' },
  mutator: { border: 'border-teal-500/40', glow: 'shadow-teal-500/20' },
  string_mutator: { border: 'border-cyan-500/40', glow: 'shadow-cyan-500/20' },
  validator: { border: 'border-orange-500/40', glow: 'shadow-orange-500/20' },
  validation_pattern: { border: 'border-amber-500/40', glow: 'shadow-amber-500/20' },
  constant: { border: 'border-slate-400/40', glow: 'shadow-slate-500/20' },
  math: { border: 'border-yellow-500/40', glow: 'shadow-yellow-500/20' },
  gate: { border: 'border-red-500/40', glow: 'shadow-red-500/20' },
  bundle: { border: 'border-cyan-400/40', glow: 'shadow-cyan-500/20' },
  template: { border: 'border-lime-500/40', glow: 'shadow-lime-500/20' },
  compare: { border: 'border-amber-300/40', glow: 'shadow-amber-300/20' },
  logical_condition: { border: 'border-violet-400/40', glow: 'shadow-violet-400/20' },
  router: { border: 'border-pink-500/40', glow: 'shadow-pink-500/20' },
  delay: { border: 'border-indigo-400/40', glow: 'shadow-indigo-400/20' },
  poll: { border: 'border-cyan-300/40', glow: 'shadow-cyan-300/20' },
  http: { border: 'border-sky-400/40', glow: 'shadow-sky-400/20' },
  api_advanced: { border: 'border-blue-300/40', glow: 'shadow-blue-300/20' },
  database: { border: 'border-emerald-500/40', glow: 'shadow-emerald-500/20' },
  db_schema: { border: 'border-purple-500/40', glow: 'shadow-purple-500/20' },
  document: { border: 'border-emerald-400/40', glow: 'shadow-emerald-400/20' },
  scanfile: { border: 'border-cyan-400/40', glow: 'shadow-cyan-400/20' },
  prompt: { border: 'border-amber-500/40', glow: 'shadow-amber-500/20' },
  model: { border: 'border-fuchsia-500/40', glow: 'shadow-fuchsia-500/20' },
  agent: { border: 'border-emerald-400/40', glow: 'shadow-emerald-400/20' },
  playwright: { border: 'border-blue-400/40', glow: 'shadow-blue-400/20' },
  learner_agent: { border: 'border-emerald-300/40', glow: 'shadow-emerald-300/20' },
  viewer: { border: 'border-violet-500/40', glow: 'shadow-violet-500/20' },
  notification: { border: 'border-amber-400/40', glow: 'shadow-amber-500/20' },
  ai_description: { border: 'border-indigo-500/40', glow: 'shadow-indigo-500/20' },
  description_updater: { border: 'border-rose-400/40', glow: 'shadow-rose-400/20' },
  bounds_normalizer: { border: 'border-teal-400/40', glow: 'shadow-teal-500/20' },
  canvas_output: { border: 'border-sky-400/40', glow: 'shadow-sky-500/20' },
  function: { border: 'border-blue-400/40', glow: 'shadow-blue-500/20' },
  state: { border: 'border-emerald-400/40', glow: 'shadow-emerald-500/20' },
  switch: { border: 'border-pink-400/40', glow: 'shadow-pink-500/20' },
  subgraph: { border: 'border-violet-400/40', glow: 'shadow-violet-500/20' },
};

export const triggers = [
  'Product Modal - Context Filter',
  'Bulk Action - Generate Descriptions',
  'On Product Save',
];
