export const accessibilityRouteCrawlRoutes = [
  {
    id: 'public-home',
    name: 'Public Home',
    route: '/',
    audience: 'public',
  },
  {
    id: 'auth-signin',
    name: 'Auth Sign In',
    route: '/auth/signin',
    audience: 'public',
  },
  {
    id: 'auth-register',
    name: 'Auth Register',
    route: '/auth/register',
    audience: 'public',
  },
  {
    id: 'kangur-login',
    name: 'Kangur Login',
    route: '/kangur/login',
    audience: 'public',
  },
  {
    id: 'kangur-home',
    name: 'Kangur Home',
    route: '/kangur',
    audience: 'public',
  },
  {
    id: 'kangur-game',
    name: 'Kangur Game',
    route: '/kangur/game',
    audience: 'public',
    navigationWaitUntil: 'commit',
  },
  {
    id: 'kangur-lessons',
    name: 'Kangur Lessons',
    route: '/kangur/lessons',
    audience: 'public',
  },
  {
    id: 'kangur-profile',
    name: 'Kangur Profile',
    route: '/kangur/profile',
    audience: 'public',
  },
  {
    id: 'kangur-tests',
    name: 'Kangur Tests',
    route: '/kangur/tests',
    audience: 'public',
  },
  {
    id: 'kangur-parent-dashboard',
    name: 'Kangur Parent Dashboard',
    route: '/kangur/parent-dashboard',
    audience: 'public',
  },
  {
    id: 'kangur-duels',
    name: 'Kangur Duels',
    route: '/kangur/duels',
    audience: 'public',
  },
  {
    id: 'kangur-social-updates',
    name: 'Kangur Social Updates',
    route: '/kangur/social-updates',
    audience: 'public',
  },
  {
    id: 'kangur-competition',
    name: 'Kangur Competition',
    route: '/kangur/competition',
    audience: 'public',
  },
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard',
    route: '/admin',
    audience: 'admin',
  },
  {
    id: 'admin-prompt-engine-validation',
    name: 'Admin Prompt Engine Validation',
    route: '/admin/prompt-engine/validation',
    audience: 'admin',
  },
  {
    id: 'admin-products',
    name: 'Admin Products',
    route: '/admin/products',
    audience: 'admin',
  },
  {
    id: 'admin-notes',
    name: 'Admin Notes',
    route: '/admin/notes',
    audience: 'admin',
  },
  {
    id: 'admin-integrations',
    name: 'Admin Integrations',
    route: '/admin/integrations',
    audience: 'admin',
  },
  {
    id: 'admin-case-resolver',
    name: 'Admin Case Resolver',
    route: '/admin/case-resolver',
    audience: 'admin',
  },
  {
    id: 'admin-cms',
    name: 'Admin CMS',
    route: '/admin/cms',
    audience: 'admin',
  },
  {
    id: 'admin-ai-paths',
    name: 'Admin AI Paths',
    route: '/admin/ai-paths',
    audience: 'admin',
  },
  {
    id: 'admin-image-studio',
    name: 'Admin Image Studio',
    route: '/admin/image-studio',
    audience: 'admin',
  },
  {
    id: 'admin-chatbot',
    name: 'Admin Chatbot',
    route: '/admin/chatbot',
    audience: 'admin',
  },
  {
    id: 'admin-agentcreator',
    name: 'Admin Agent Creator',
    route: '/admin/agentcreator',
    audience: 'admin',
  },
  {
    id: 'admin-kangur',
    name: 'Admin Kangur',
    route: '/admin/kangur',
    audience: 'admin',
  },
  {
    id: 'admin-kangur-builder',
    name: 'Admin Kangur Builder',
    route: '/admin/kangur/builder',
    audience: 'admin',
  },
  {
    id: 'admin-kangur-lessons',
    name: 'Admin Kangur Lessons Manager',
    route: '/admin/kangur/lessons-manager',
    audience: 'admin',
  },
  {
    id: 'admin-kangur-observability',
    name: 'Admin Kangur Observability',
    route: '/admin/kangur/observability',
    audience: 'admin',
  },
  {
    id: 'admin-kangur-appearance',
    name: 'Admin Kangur Appearance',
    route: '/admin/kangur/appearance',
    audience: 'admin',
  },
  {
    id: 'admin-kangur-settings',
    name: 'Admin Kangur Settings',
    route: '/admin/kangur/settings',
    audience: 'admin',
  },
  {
    id: 'admin-databases',
    name: 'Admin Databases',
    route: '/admin/databases/engine',
    audience: 'admin',
  },
  {
    id: 'admin-brain-settings',
    name: 'Admin Brain Settings',
    route: '/admin/brain?tab=routing',
    audience: 'admin',
  },
];
