export const accessibilityRouteCrawlRoutes = [
  {
    id: 'public-home',
    name: 'Public Home',
    route: '/',
    audience: 'public',
  },
  {
    id: 'auth-signin',
    name: 'Auth Sign In',
    route: '/auth/signin',
    audience: 'public',
  },
  {
    id: 'auth-register',
    name: 'Auth Register',
    route: '/auth/register',
    audience: 'public',
  },
  {
    id: 'kangur-login',
    name: 'Kangur Login',
    route: '/kangur/login',
    audience: 'public',
  },
  {
    id: 'admin-dashboard',
    name: 'Admin Dashboard',
    route: '/admin',
    audience: 'admin',
  },
  {
    id: 'admin-products',
    name: 'Admin Products',
    route: '/admin/products',
    audience: 'admin',
  },
  {
    id: 'admin-notes',
    name: 'Admin Notes',
    route: '/admin/notes',
    audience: 'admin',
  },
  {
    id: 'admin-integrations',
    name: 'Admin Integrations',
    route: '/admin/integrations',
    audience: 'admin',
  },
  {
    id: 'admin-case-resolver',
    name: 'Admin Case Resolver',
    route: '/admin/case-resolver',
    audience: 'admin',
  },
  {
    id: 'admin-cms',
    name: 'Admin CMS',
    route: '/admin/cms',
    audience: 'admin',
  },
  {
    id: 'admin-ai-paths',
    name: 'Admin AI Paths',
    route: '/admin/ai-paths',
    audience: 'admin',
  },
  {
    id: 'admin-image-studio',
    name: 'Admin Image Studio',
    route: '/admin/image-studio',
    audience: 'admin',
  },
  {
    id: 'admin-chatbot',
    name: 'Admin Chatbot',
    route: '/admin/chatbot',
    audience: 'admin',
  },
  {
    id: 'admin-agentcreator',
    name: 'Admin Agent Creator',
    route: '/admin/agentcreator',
    audience: 'admin',
  },
  {
    id: 'admin-prompt-engine-validation',
    name: 'Admin Prompt Engine Validation',
    route: '/admin/prompt-engine/validation',
    audience: 'admin',
  },
  {
    id: 'admin-kangur',
    name: 'Admin Kangur',
    route: '/admin/kangur',
    audience: 'admin',
  },
  {
    id: 'admin-databases',
    name: 'Admin Databases',
    route: '/admin/databases/engine',
    audience: 'admin',
  },
  {
    id: 'admin-brain-settings',
    name: 'Admin Brain Settings',
    route: '/admin/brain?tab=routing',
    audience: 'admin',
  },
];
