export const DOCS_WIRING_SNIPPET = [
  'Trigger.trigger → Simulation.trigger',
  'Simulation.context → Trigger.context',
  'Trigger.context → ContextFilter.context',
  'ContextFilter.entityJson → Parser.entityJson',
  'Trigger.context → ResultViewer.context',
  'Trigger.meta → ResultViewer.meta',
  'Trigger.trigger → ResultViewer.trigger',
  'Trigger.triggerName → ResultViewer.triggerName',
].join('\n');

export const DOCS_OVERVIEW_SNIPPET = [
  'AI Paths is a node-and-wire runtime that turns a graph into a reproducible workflow.',
  'Each path stores its nodes, edges, and optional runtime state in settings; runs are tracked separately.',
  '',
  'Execution lifecycle:',
  '1) A Trigger node starts the run (manual, simulation, or scheduled events).',
  '2) The runtime evaluates connected nodes in dependency order, passing port values along edges.',
  '3) Each node emits outputs under named ports; downstream inputs must match by name.',
  '4) Run history captures inputs, outputs, timings, and failures per node.',
  '',
  'Data flow basics:',
  '- Ports are strict by name (e.g., result → result).',
  '- Multiple wires into one input collect as arrays; most nodes use the first value unless configured.',
  '- Image data flows as URLs; Model nodes resolve to base64 when invoking vision models.',
  '',
  'Core node roles:',
  '- Trigger: start signal + triggerName + context/meta payloads.',
  '- Simulation: mock trigger data to test paths without live events.',
  '- Context / Parser: select an entity and shape it into structured fields.',
  '- Mapper / Mutator / Template / Math / Compare / Gate / Router / Validator: transform, validate, and branch.',
  '- Prompt / Model: build prompts and run LLM or vision tasks (inline or async).',
  '- Poll: wait on async jobs or database conditions.',
  '- Database / DB Schema: query or update storage, optionally using presets.',
  '- Viewer: inspect runtime outputs.',
  '',
  'Jobs & async:',
  '- Model nodes can run inline (wait) or enqueue a job and return a jobId.',
  '- Poll nodes can resolve job results or query database state until success.',
  '',
  'Persistence & observability:',
  '- Runs are stored with status, timestamps, and runtime snapshots.',
  '- Node history and events are stored for debugging.',
  '- Failed runs can be retried or re-queued from the Jobs queue.',
].join('\n');

export const DOCS_DESCRIPTION_SNIPPET = [
  'ContextFilter.entityJson → Parser.entityJson',
  'Parser.title → AI Description Generator.title',
  'Parser.images → AI Description Generator.images',
  'AI Description Generator.description_en → Database.content_en',
  'Parser.productId → Database.entityId',
  'Database.result → Result Viewer.result',
].join('\n');

export const DOCS_JOBS_SNIPPET = [
  '# Inline (Model waits for result)',
  'Prompt.prompt → Model.prompt',
  'Prompt.images → Model.images',
  'Model.result → Result Viewer.result',
  'Model.result → Database.result',
  'Parser.productId → Database.entityId',
  '',
  '# Async (Model enqueue-only + Poll)',
  'Prompt.prompt → Model.prompt',
  'Prompt.images → Model.images',
  'Model.jobId → Poll.jobId',
  'Poll.result → Result Viewer.result',
  'Poll.result → Database.result',
  'Parser.productId → Database.entityId',
].join('\n');
