import { describe, expect, it } from 'vitest';

import { buildAiBrainWorkspaceContextBundle } from '../workspace';

describe('buildAiBrainWorkspaceContextBundle', () => {
  it('builds an AI Brain runtime document with routing, schedule, and telemetry context', () => {
    const bundle = buildAiBrainWorkspaceContextBundle({
      activeTab: 'operations',
      operationsRange: '6h',
      saving: true,
      analyticsScheduleEnabled: true,
      analyticsScheduleMinutes: 30,
      runtimeAnalyticsScheduleEnabled: true,
      runtimeAnalyticsScheduleMinutes: 45,
      logsScheduleEnabled: false,
      logsScheduleMinutes: 20,
      logsAutoOnError: true,
      analyticsPromptSystem: 'Watch for meaningful analytics drift and summarize key changes.',
      runtimeAnalyticsPromptSystem:
        'Highlight runtime parity regressions and queue reliability risk.',
      logsPromptSystem: 'Summarize the highest-confidence log incidents first.',
      runtimeAnalyticsLiveEnabled: true,
      liveOllamaModels: ['llama3.3:70b', 'qwen2.5-coder:32b'],
      modelQuickPickCount: 4,
      agentQuickPickCount: 2,
      overridesEnabled: {
        analytics: true,
        runtime_analytics: false,
      } as never,
      featureOverrides: {
        analytics: {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1-mini',
          agentId: '',
          temperature: 0.3,
          maxTokens: 1800,
          notes: null,
        },
      } as never,
      capabilityOverrides: {
        'insights.analytics': {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1',
          agentId: '',
          temperature: 0.2,
          maxTokens: 2200,
          notes: 'Prefer concise warnings.',
        },
      } as never,
      effectiveAssignments: {
        analytics: {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1-mini',
          agentId: '',
          temperature: 0.3,
          maxTokens: 1800,
          notes: null,
        },
        runtime_analytics: {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1-mini',
          agentId: '',
          temperature: 0.2,
          maxTokens: 1800,
          notes: null,
        },
      } as never,
      effectiveCapabilityAssignments: {
        'insights.analytics': {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1',
          agentId: '',
          temperature: 0.2,
          maxTokens: 2200,
          notes: 'Prefer concise warnings.',
        },
        'insights.runtime_analytics': {
          enabled: true,
          provider: 'model',
          modelId: 'gpt-4.1-mini',
          agentId: '',
          temperature: 0.2,
          maxTokens: 1800,
          notes: null,
        },
      } as never,
      analyticsSummary: {
        from: '2026-03-08T00:00:00.000Z',
        to: '2026-03-09T00:00:00.000Z',
        scope: 'all',
        totals: {
          events: 1200,
          pageviews: 750,
        },
        visitors: 280,
        sessions: 410,
        topPages: [{ path: '/admin/brain', count: 120 }],
        topReferrers: [],
        topEventNames: [],
        topLanguages: [],
        topCountries: [],
        topRegions: [],
        topCities: [],
        topBrowsers: [],
        topOs: [],
        topDevices: [],
        topUtmSources: [],
        topUtmMediums: [],
        topUtmCampaigns: [],
        recent: [],
      } as never,
      logMetrics: {
        total: 88,
        levels: { info: 20, warn: 18, error: 50 },
        last24Hours: 24,
        last7Days: 70,
        topSources: [{ source: 'brain', count: 14 }],
        topServices: [],
        topPaths: [],
        generatedAt: '2026-03-09T09:00:00.000Z',
      },
      insights: {
        analytics: [
          {
            id: 'analytics-1',
            status: 'new',
            source: 'manual',
            summary: 'Analytics traffic is rising in the admin dashboard.',
            createdAt: '2026-03-09T08:00:00.000Z',
          },
        ],
        runtimeAnalytics: [
          {
            id: 'runtime-1',
            status: 'warning',
            source: 'manual',
            summary: 'Runtime queue failure rate increased.',
            createdAt: '2026-03-09T08:30:00.000Z',
          },
        ],
        logs: [
          {
            id: 'logs-1',
            status: 'error',
            source: 'manual',
            summary: 'System logs show repeated chatbot worker failures.',
            createdAt: '2026-03-09T08:45:00.000Z',
          },
        ],
      },
      runtimeAnalytics: {
        from: '2026-03-08T00:00:00.000Z',
        to: '2026-03-09T00:00:00.000Z',
        range: '24h',
        storage: 'redis',
        runs: {
          total: 80,
          queued: 4,
          started: 72,
          completed: 64,
          failed: 8,
          canceled: 0,
          successRate: 80,
          failureRate: 10,
          avgDurationMs: 4200,
          p95DurationMs: 9100,
        },
        nodes: {
          started: 280,
          completed: 250,
          failed: 12,
          queued: 8,
          running: 5,
          polling: 3,
          cached: 30,
          waitingCallback: 2,
        },
        brain: {
          analyticsReports: 4,
          logReports: 5,
          totalReports: 9,
          warningReports: 2,
          errorReports: 1,
        },
        traces: {
          total: 0,
          withProfile: 0,
          profileCoverage: 0,
          eventsSampled: 0,
          topRunTypes: [],
          topNodeTypes: [],
          kernelParity: {
            sampledRuns: 0,
            runsWithKernelParity: 0,
            sampledHistoryEntries: 0,
            strategyCounts: {
              compatibility: 0,
              code_object_v3: 0,
            },
            resolutionSourceCounts: {
              override: 0,
              registry: 0,
              missing: 0,
            },
          },
        },
        generatedAt: '2026-03-09T09:05:00.000Z',
      } as never,
      operationsOverview: {
        generatedAt: '2026-03-09T09:05:00.000Z',
        range: '6h',
        domains: {
          ai_paths: {
            key: 'ai_paths',
            label: 'AI Paths',
            state: 'warning',
            sampleSize: 14,
            updatedAt: '2026-03-09T09:05:00.000Z',
            metrics: [{ key: 'queued_runs', label: 'Queued Runs', value: 4 }],
            trend: {
              direction: 'up',
              delta: 2,
              label: 'Failed vs previous 6h',
              current: 3,
              previous: 1,
            },
            recentEvents: [{ status: 'failed', timestamp: '2026-03-09T08:55:00.000Z' }],
            links: [],
          },
          chatbot: {
            key: 'chatbot',
            label: 'Chatbot',
            state: 'healthy',
            sampleSize: 20,
            updatedAt: '2026-03-09T09:05:00.000Z',
            metrics: [],
            trend: {
              direction: 'flat',
              delta: 0,
              label: 'Failed vs previous 6h',
              current: 0,
              previous: 0,
            },
            recentEvents: [],
            links: [],
          },
          agent_runtime: {
            key: 'agent_runtime',
            label: 'Agent Runtime',
            state: 'healthy',
            sampleSize: 10,
            updatedAt: '2026-03-09T09:05:00.000Z',
            metrics: [],
            trend: {
              direction: 'down',
              delta: -1,
              label: 'Failed vs previous 6h',
              current: 1,
              previous: 2,
            },
            recentEvents: [],
            links: [],
          },
          image_studio: {
            key: 'image_studio',
            label: 'Image Studio',
            state: 'healthy',
            sampleSize: 9,
            updatedAt: '2026-03-09T09:05:00.000Z',
            metrics: [],
            trend: {
              direction: 'flat',
              delta: 0,
              label: 'Failed vs previous 6h',
              current: 0,
              previous: 0,
            },
            recentEvents: [],
            links: [],
          },
        },
      },
    });

    expect(bundle.refs).toEqual([
      expect.objectContaining({
        id: 'runtime:brain:workspace',
        kind: 'runtime_document',
        providerId: 'brain-page-local',
        entityType: 'ai_brain_workspace_state',
      }),
    ]);
    expect(bundle.documents).toHaveLength(1);
    expect(bundle.documents[0]).toMatchObject({
      entityType: 'ai_brain_workspace_state',
      title: 'AI Brain workspace state',
      status: 'saving',
      facts: expect.objectContaining({
        activeTab: 'operations',
        operationsRange: '6h',
        featureOverrideCount: 1,
        capabilityOverrideCount: 1,
        enabledFeatureCount: 2,
        enabledCapabilityCount: 2,
        liveOllamaModelCount: 2,
      }),
    });
    expect(bundle.documents[0].sections.map((section) => section.title)).toEqual(
      expect.arrayContaining([
        'Workspace snapshot',
        'Report automation and prompts',
        'Effective feature routing',
        'Capability overrides',
        'Live model catalog',
        'Latest visible insights',
        'Operations overview',
        'Telemetry snapshot',
      ])
    );
  });
});
