import 'server-only';

export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_KIND =
  'ai-paths.portable-envelope-verification-audit.v1' as const;
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_DEFAULT_CATEGORY =
  'ai_path_portable_envelope_verification_audit';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_DEFAULT_SOURCE =
  'ai-paths.portable-engine.envelope-verification';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_DEFAULT_SERVICE = 'ai-paths.portable-engine';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_DEFAULT_MONGO_COLLECTION =
  'ai_path_portable_envelope_verification_audit';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_HEALTH_KIND =
  'ai-paths.portable-envelope-verification-audit-sink-health.v1' as const;
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_HEALTH_CATEGORY =
  'ai_path_portable_envelope_verification_audit_sink_health';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_BOOTSTRAP_SOURCE =
  'ai-paths.portable-engine.envelope-verification.sink-bootstrap';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_PROFILES = [
  'dev',
  'staging',
  'prod',
] as const;
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_HEALTH_POLICIES = [
  'off',
  'warn',
  'error',
] as const;

export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_BOOTSTRAP_ENABLED_ENV =
  'PORTABLE_PATH_AUDIT_SINK_BOOTSTRAP_ENABLED';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_PROFILE_ENV =
  'PORTABLE_PATH_AUDIT_SINK_PROFILE';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_HEALTH_POLICY_ENV =
  'PORTABLE_PATH_AUDIT_SINK_HEALTH_POLICY';
export const PORTABLE_PATH_ENVELOPE_VERIFICATION_AUDIT_SINK_HEALTH_TIMEOUT_MS_ENV =
  'PORTABLE_PATH_AUDIT_SINK_HEALTH_TIMEOUT_MS';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_REPORTER_ENABLED_ENV =
  'PORTABLE_PATH_SIGNING_POLICY_TREND_REPORTER_ENABLED';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_REPORT_EVERY_USES_ENV =
  'PORTABLE_PATH_SIGNING_POLICY_TREND_REPORT_EVERY_USES';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_PERSISTENCE_ENABLED_ENV =
  'PORTABLE_PATH_SIGNING_POLICY_TREND_PERSISTENCE_ENABLED';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_PERSISTENCE_MAX_SNAPSHOTS_ENV =
  'PORTABLE_PATH_SIGNING_POLICY_TREND_PERSISTENCE_MAX_SNAPSHOTS';
export const PORTABLE_PATH_SIGNING_POLICY_DRIFT_ALERT_LEVEL_ENV =
  'PORTABLE_PATH_SIGNING_POLICY_DRIFT_ALERT_LEVEL';
export const PORTABLE_PATH_AUDIT_SINK_FAILURE_ALERT_LEVEL_ENV =
  'PORTABLE_PATH_AUDIT_SINK_FAILURE_ALERT_LEVEL';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_KIND =
  'ai-paths.portable-signing-policy-trend.v1' as const;
export const PORTABLE_PATH_SIGNING_POLICY_TREND_CATEGORY = 'ai_path_portable_signing_policy_trend';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_SOURCE =
  'ai-paths.portable-engine.signing-policy-trend';
export const PORTABLE_PATH_SIGNING_POLICY_TREND_SETTINGS_KEY =
  'ai_paths_portable_signing_policy_trend_history_v1';
export const PORTABLE_PATH_SIGNING_POLICY_ALERT_LEVELS = ['off', 'warn', 'error'] as const;
