import type { KangurGameDefinition } from '@/shared/contracts/kangur-games';
import { createSharedLibraryGame, createVariant } from '../factories';

export const TEN_YEAR_OLD_ENGLISH_GAMES: readonly KangurGameDefinition[] = [
  createSharedLibraryGame({
    id: 'english_subject_verb_agreement',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_subject_verb_agreement'],
    label: 'English subject-verb agreement',
    title: 'English Subject-Verb Agreement',
    description:
      'Shared grammar agreement engine for lessons, library previews, and fullscreen English practice.',
    emoji: '⚖️',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'agreement'],
    sortOrder: 1210,
    launchableRuntimeId: 'english_subject_verb_agreement_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_adjectives_scene',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_adjectives'],
    label: 'English adjectives scene',
    title: 'English Adjectives Scene',
    description:
      'Shared adjectives practice engine for describing people, places, and objects across lesson and fullscreen flows.',
    emoji: '🎨',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'adjectives'],
    sortOrder: 1220,
    launchableRuntimeId: 'english_adjectives_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_compare_and_crown',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_comparatives_superlatives'],
    label: 'English compare and crown',
    title: 'English Compare & Crown',
    description:
      'Shared comparatives-and-superlatives engine for comparing animated scenes and crowning the winner across lesson and fullscreen flows.',
    emoji: '👑',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'comparatives', 'superlatives'],
    sortOrder: 1225,
    launchableRuntimeId: 'english_compare_and_crown_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_adverbs_action_studio',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_adverbs'],
    label: 'English adverbs action studio',
    title: 'English Adverbs Action Studio',
    description:
      'Shared adverbs practice engine for directing action style across lesson and fullscreen flows.',
    emoji: '🎭',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'adverbs'],
    sortOrder: 1230,
    launchableRuntimeId: 'english_adverbs_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_adverbs_frequency_routine',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_adverbs_frequency'],
    label: 'English adverbs frequency routine',
    title: 'English Adverbs Frequency Routine',
    description:
      'Shared adverbs-of-frequency engine for routine building in lessons, previews, and fullscreen practice.',
    emoji: '🔁',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'adverbs'],
    sortOrder: 1240,
    launchableRuntimeId: 'english_adverbs_frequency_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_articles_drag_drop',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_articles'],
    label: 'English articles drag drop',
    title: 'English Articles Drag Drop',
    description:
      'Shared article-building engine for choosing a, an, and the across lesson and fullscreen surfaces.',
    emoji: '🧲',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'articles'],
    sortOrder: 1250,
    launchableRuntimeId: 'english_articles_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_prepositions_time_place',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_prepositions_time_place'],
    label: 'English prepositions time and place',
    title: 'English Prepositions Time and Place',
    description:
      'Shared prepositions quiz engine for time and place grammar across lessons, previews, and fullscreen practice.',
    emoji: '🧭',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'prepositions'],
    sortOrder: 1260,
    launchableRuntimeId: 'english_prepositions_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_prepositions_sort',
    engineId: 'classification-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_prepositions_time_place'],
    label: 'English prepositions sort',
    title: 'English Prepositions Sort',
    description:
      'Shared sorting engine for grouping prepositions by time, place, and relation patterns.',
    emoji: '🧲',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'prepositions', 'sorting'],
    sortOrder: 1260,
    launchableRuntimeId: 'english_prepositions_sort_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_prepositions_order',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_prepositions_time_place'],
    label: 'English prepositions order',
    title: 'English Prepositions Order',
    description:
      'Shared sentence-order engine for rebuilding preposition phrases in lessons, previews, and fullscreen practice.',
    emoji: '🧩',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'prepositions', 'word-order'],
    sortOrder: 1270,
    launchableRuntimeId: 'english_prepositions_order_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  createSharedLibraryGame({
    id: 'english_pronouns_warmup',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_parts_of_speech'],
    label: 'English pronouns warmup',
    title: 'English Pronouns Warm-up',
    description:
      'Shared pronoun warm-up engine for quick grammar rounds in lessons, previews, and fullscreen practice.',
    emoji: '⚡',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    tags: ['english', 'grammar', 'pronouns'],
    sortOrder: 1280,
    launchableRuntimeId: 'english_pronouns_warmup_quiz',
    lessonVariantSurface: 'lesson_stage',
  }),
  {
    id: 'english_sentence_builder',
    engineId: 'sentence-builder-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_sentence_structure'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'English sentence builder',
    title: 'English Sentence Builder',
    description:
      'Sentence-building engine scaffolded as a shared asset for English lessons, previews, and fullscreen practice.',
    emoji: '🧩',
    mechanic: 'sentence_building',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['english', 'sentence', 'grammar'],
    variants: [
      createVariant({
        id: 'english_sentence_builder.lesson-stage',
        label: 'Lesson variant',
        title: 'Sentence builder inside lessons',
        description: 'Lesson-facing variant for the shared sentence-builder engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'english_sentence_builder.library-preview',
        label: 'Library preview',
        title: 'Sentence builder preview',
        description: 'Catalog preview for the shared English sentence engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'english_sentence_builder.game-screen',
        label: 'Game screen',
        title: 'Sentence builder fullscreen',
        description: 'Fullscreen entry for the shared sentence-building engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'english_sentence_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1300,
  },
  {
    id: 'english_parts_of_speech_sort',
    engineId: 'classification-engine',
    subject: 'english',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['english_parts_of_speech'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'English parts of speech sort',
    title: 'English Parts of Speech Sort',
    description:
      'Classification-engine reuse for English grammar, showing how one engine family can power multiple subjects.',
    emoji: '🔤',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['english', 'grammar', 'classification'],
    variants: [
      createVariant({
        id: 'english_parts_of_speech_sort.lesson-stage',
        label: 'Lesson variant',
        title: 'Parts of speech inside lessons',
        description: 'Lesson-facing variant backed by the shared classification engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'english_parts_of_speech_sort.library-preview',
        label: 'Library preview',
        title: 'Parts of speech preview',
        description: 'Catalog preview for the shared grammar classification engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'english_parts_of_speech_sort.game-screen',
        label: 'Game screen',
        title: 'Parts of speech fullscreen',
        description: 'Fullscreen entry for the shared grammar classification engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'english_parts_of_speech_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1400,
  },
];
