import type { KangurGameDefinition } from '@/shared/contracts/kangur-games';
import { createVariant } from '../factories';

export const TEN_YEAR_OLD_MATH_GAMES: readonly KangurGameDefinition[] = [
  {
    id: 'clock_training',
    engineId: 'clock-dial-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['clock'],
    activityIds: ['clock-training'],
    legacyScreenIds: [],
    label: 'Clock training',
    title: 'Clock Training',
    description:
      'Shared clock engine for analogue reading drills in lessons, the games library, and fullscreen practice.',
    emoji: '🕐',
    mechanic: 'clock_training',
    interactionMode: 'mixed',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['time', 'clock', 'analogue'],
    variants: [
      createVariant({
        id: 'clock_training.lesson-inline',
        label: 'Lesson inline',
        title: 'Clock training in lessons',
        description: 'Embeds the shared clock engine inside modular lesson documents.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'clock-training',
      }),
      createVariant({
        id: 'clock_training.library-preview',
        label: 'Library preview',
        title: 'Clock training preview',
        description: 'Shows the shared clock engine as a reusable catalog entry.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'clock_training.game-screen',
        label: 'Game screen',
        title: 'Clock training fullscreen',
        description: 'Launches the shared clock engine from the standalone game runtime.',
        surface: 'game_screen',
        launchableRuntimeId: 'clock_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 100,
  },
  {
    id: 'calendar_interactive',
    engineId: 'calendar-grid-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['calendar'],
    activityIds: ['calendar-interactive'],
    legacyScreenIds: [],
    label: 'Calendar interactive',
    title: 'Calendar Interactive',
    description:
      'Interactive calendar engine for dates, weekdays, and time shifts reused across lesson and game surfaces.',
    emoji: '📅',
    mechanic: 'calendar_interactive',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['calendar', 'dates', 'time'],
    variants: [
      createVariant({
        id: 'calendar_interactive.lesson-inline',
        label: 'Lesson inline',
        title: 'Calendar practice in lessons',
        description: 'Embeds the shared calendar engine inside lesson activity blocks.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'calendar-interactive',
      }),
      createVariant({
        id: 'calendar_interactive.library-preview',
        label: 'Library preview',
        title: 'Calendar preview',
        description: 'Catalog preview of the reusable calendar engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'calendar_interactive.game-screen',
        label: 'Game screen',
        title: 'Calendar fullscreen practice',
        description: 'Standalone game runtime entry backed by the shared calendar engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'calendar_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 200,
  },
  {
    id: 'adding_ball',
    engineId: 'quantity-drag-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['adding'],
    activityIds: ['adding-ball'],
    legacyScreenIds: [],
    label: 'Adding ball',
    title: 'Adding Ball',
    description:
      'Drag-and-drop quantity engine for early addition practice. Intended as a shared lesson and library asset before fullscreen rollout.',
    emoji: '➕',
    mechanic: 'drag_drop',
    interactionMode: 'drag',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['addition', 'drag', 'quantity'],
    variants: [
      createVariant({
        id: 'adding_ball.lesson-inline',
        label: 'Lesson inline',
        title: 'Adding ball in lessons',
        description: 'Current lesson activity backed by the shared quantity-drag engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'adding-ball',
      }),
      createVariant({
        id: 'adding_ball.lesson-stage',
        label: 'Lesson variant',
        title: 'Adding ball as a lesson variant',
        description:
          'Lesson-facing variant for the adding lesson game shell, backed by the same shared quantity-drag engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'adding_ball.library-preview',
        label: 'Library preview',
        title: 'Adding ball preview',
        description: 'Preview variant used by the shared games library.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'adding_ball.game-screen',
        label: 'Game screen',
        title: 'Adding ball fullscreen',
        description: 'Fullscreen entry wired to the shared addition drag-and-drop engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'addition_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 300,
  },
  {
    id: 'adding_synthesis',
    engineId: 'rhythm-answer-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['adding'],
    activityIds: ['adding-synthesis'],
    legacyScreenIds: [],
    label: 'Adding synthesis',
    title: 'Adding Synthesis',
    description:
      'Rhythm-based answer engine for addition fluency. Shared catalog entry for future standalone practice modes.',
    emoji: '🎵',
    mechanic: 'rhythm',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['addition', 'rhythm', 'fluency'],
    variants: [
      createVariant({
        id: 'adding_synthesis.lesson-inline',
        label: 'Lesson inline',
        title: 'Adding synthesis in lessons',
        description: 'Current lesson activity variant powered by the rhythm-answer engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'adding-synthesis',
      }),
      createVariant({
        id: 'adding_synthesis.lesson-stage',
        label: 'Lesson variant',
        title: 'Adding synthesis as a lesson variant',
        description:
          'Lesson-facing variant for the addition synthesis lesson shell, using the shared rhythm-answer engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'adding_synthesis.library-preview',
        label: 'Library preview',
        title: 'Adding synthesis preview',
        description: 'Library preview of the shared rhythm engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'adding_synthesis.game-screen',
        label: 'Game screen',
        title: 'Adding synthesis fullscreen',
        description: 'Launches the shared rhythm-answer engine from the standalone game runtime.',
        surface: 'game_screen',
        launchableRuntimeId: 'adding_synthesis_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 400,
  },
  {
    id: 'subtracting_garden',
    engineId: 'quantity-drag-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['subtracting'],
    activityIds: ['subtracting-game'],
    legacyScreenIds: [],
    label: 'Subtracting garden',
    title: 'Subtracting Garden',
    description:
      'Shared quantity-drag engine variant for subtraction, grouped with adding ball under the same mechanic family.',
    emoji: '➖',
    mechanic: 'drag_drop',
    interactionMode: 'drag',
    surfaces: ['lesson', 'library'],
    tags: ['subtraction', 'drag', 'quantity'],
    variants: [
      createVariant({
        id: 'subtracting_garden.lesson-inline',
        label: 'Lesson inline',
        title: 'Subtracting garden in lessons',
        description: 'Lesson activity variant powered by the shared quantity-drag engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'subtracting-game',
      }),
      createVariant({
        id: 'subtracting_garden.lesson-stage',
        label: 'Lesson variant',
        title: 'Subtracting garden as a lesson variant',
        description:
          'Lesson-facing variant for the subtraction lesson game shell, still powered by the shared quantity-drag engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'subtracting_garden.library-preview',
        label: 'Library preview',
        title: 'Subtracting garden preview',
        description: 'Library preview of the subtraction drag-and-drop variant.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'subtracting_garden.game-screen',
        label: 'Game screen',
        title: 'Subtracting garden fullscreen',
        description: 'Fullscreen entry wired to the shared subtraction drag-and-drop engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'subtraction_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 500,
  },
  {
    id: 'multiplication_array',
    engineId: 'array-builder-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['multiplication'],
    activityIds: ['multiplication-array'],
    legacyScreenIds: [],
    label: 'Multiplication array',
    title: 'Multiplication Array',
    description:
      'Array-building engine for repeated groups and visual multiplication practice, scaffolded for shared library reuse.',
    emoji: '✖️',
    mechanic: 'tap_select',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library'],
    tags: ['multiplication', 'arrays', 'visual'],
    variants: [
      createVariant({
        id: 'multiplication_array.lesson-inline',
        label: 'Lesson inline',
        title: 'Multiplication array in lessons',
        description: 'Lesson activity variant for the shared array-builder engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'multiplication-array',
      }),
      createVariant({
        id: 'multiplication_array.lesson-stage',
        label: 'Lesson variant',
        title: 'Multiplication array as a lesson variant',
        description:
          'Lesson-facing variant for the multiplication lesson shell, backed by the shared array-builder engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'multiplication_array.library-preview',
        label: 'Library preview',
        title: 'Multiplication array preview',
        description: 'Library preview for the shared multiplication array engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
    ],
    status: 'active',
    sortOrder: 600,
  },
  {
    id: 'multiplication_quiz',
    engineId: 'choice-quiz-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['multiplication'],
    activityIds: ['multiplication-quiz'],
    legacyScreenIds: [],
    label: 'Multiplication quiz',
    title: 'Multiplication Quiz',
    description:
      'Choice-based quiz engine shared between multiplication lesson activity blocks and fullscreen game practice.',
    emoji: '🧮',
    mechanic: 'multiple_choice',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['multiplication', 'quiz', 'choice'],
    variants: [
      createVariant({
        id: 'multiplication_quiz.lesson-inline',
        label: 'Lesson inline',
        title: 'Multiplication quiz in lessons',
        description: 'Lesson activity variant using the shared choice-quiz engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'multiplication-quiz',
      }),
      createVariant({
        id: 'multiplication_quiz.library-preview',
        label: 'Library preview',
        title: 'Multiplication quiz preview',
        description: 'Catalog preview for the shared multiplication quiz engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'multiplication_quiz.game-screen',
        label: 'Game screen',
        title: 'Multiplication quiz fullscreen',
        description: 'Legacy fullscreen entry wired to the same shared quiz engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'multiplication_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 700,
  },
  {
    id: 'division_groups',
    engineId: 'choice-quiz-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['division'],
    activityIds: ['division-game'],
    legacyScreenIds: [],
    label: 'Division groups',
    title: 'Division Groups',
    description:
      'Division variant of the shared choice-quiz engine, prepared for lesson embedding and standalone fullscreen practice.',
    emoji: '➗',
    mechanic: 'multiple_choice',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['division', 'quiz', 'choice'],
    variants: [
      createVariant({
        id: 'division_groups.lesson-inline',
        label: 'Lesson inline',
        title: 'Division groups in lessons',
        description: 'Lesson activity variant using the shared choice-quiz engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'division-game',
      }),
      createVariant({
        id: 'division_groups.lesson-stage',
        label: 'Lesson variant',
        title: 'Division groups as a lesson variant',
        description:
          'Lesson-facing variant for the division lesson shell, using the extracted shared division-group practice engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'division_groups.library-preview',
        label: 'Library preview',
        title: 'Division groups preview',
        description: 'Library preview of the shared division quiz engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'division_groups.game-screen',
        label: 'Game screen',
        title: 'Division groups fullscreen',
        description: 'Legacy fullscreen entry wired to the shared division quiz engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'division_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 800,
  },
  {
    id: 'geometry_shape_workshop',
    engineId: 'shape-drawing-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['geometry_basics', 'geometry_shapes'],
    activityIds: ['geometry-drawing'],
    legacyScreenIds: [],
    label: 'Geometry shape workshop',
    title: 'Geometry Shape Workshop',
    description:
      'Shared shape-sketching engine for geometry basics and named figures, reused in lessons, the games library, and the fullscreen geometry quiz.',
    emoji: '📐',
    mechanic: 'drawing',
    interactionMode: 'draw',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'shapes', 'basics'],
    variants: [
      createVariant({
        id: 'geometry_shape_workshop.lesson-inline',
        label: 'Lesson inline',
        title: 'Geometry shape workshop in lessons',
        description: 'Lesson activity variant backed by the shared shape drawing engine.',
        surface: 'lesson_inline',
        lessonActivityRuntimeId: 'geometry-drawing',
      }),
      createVariant({
        id: 'geometry_shape_workshop.lesson-stage',
        label: 'Lesson variant',
        title: 'Geometry shape workshop as a lesson variant',
        description:
          'Lesson-facing variant for the geometry shapes lesson shell, backed by the shared shape drawing engine.',
        surface: 'lesson_stage',
        sortOrder: 50,
      }),
      createVariant({
        id: 'geometry_shape_workshop.library-preview',
        label: 'Library preview',
        title: 'Geometry shape workshop preview',
        description: 'Preview variant for the shared shape drawing engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'geometry_shape_workshop.game-screen',
        label: 'Game screen',
        title: 'Geometry shape workshop fullscreen',
        description: 'Fullscreen entry for the shared shape drawing engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'geometry_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 900,
  },
  {
    id: 'geometry_symmetry_studio',
    engineId: 'symmetry-drawing-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['geometry_symmetry'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Geometry symmetry studio',
    title: 'Geometry Symmetry Studio',
    description:
      'Dedicated symmetry drawing engine for axes, reflections, and mirrored shapes, cataloged separately from general shape sketching.',
    emoji: '🪞',
    mechanic: 'drawing',
    interactionMode: 'draw',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'symmetry'],
    variants: [
      createVariant({
        id: 'geometry_symmetry_studio.lesson-stage',
        label: 'Lesson variant',
        title: 'Geometry symmetry studio in lessons',
        description: 'Lesson-facing variant for the shared symmetry drawing engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'geometry_symmetry_studio.library-preview',
        label: 'Library preview',
        title: 'Geometry symmetry studio preview',
        description: 'Preview variant for the shared symmetry drawing engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'geometry_symmetry_studio.game-screen',
        label: 'Game screen',
        title: 'Geometry symmetry studio fullscreen',
        description: 'Fullscreen entry for the shared symmetry drawing engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'geometry_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 910,
  },
  {
    id: 'geometry_perimeter_trainer',
    engineId: 'perimeter-drawing-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['geometry_perimeter'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Geometry perimeter trainer',
    title: 'Geometry Perimeter Trainer',
    description:
      'Dedicated perimeter drawing engine for tracing side lengths on the grid and choosing the correct outline totals.',
    emoji: '📏',
    mechanic: 'drawing',
    interactionMode: 'draw',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'perimeter'],
    variants: [
      createVariant({
        id: 'geometry_perimeter_trainer.lesson-stage',
        label: 'Lesson variant',
        title: 'Geometry perimeter trainer in lessons',
        description: 'Lesson-facing variant for the shared perimeter drawing engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'geometry_perimeter_trainer.library-preview',
        label: 'Library preview',
        title: 'Geometry perimeter trainer preview',
        description: 'Preview variant for the shared perimeter drawing engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'geometry_perimeter_trainer.game-screen',
        label: 'Game screen',
        title: 'Geometry perimeter trainer fullscreen',
        description: 'Fullscreen entry for the shared perimeter drawing engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'geometry_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 920,
  },
  {
    id: 'logical_patterns_workshop',
    engineId: 'pattern-sequence-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_patterns'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Logical patterns workshop',
    title: 'Logical Patterns Workshop',
    description:
      'Pattern-sequence engine shared between lesson variants, previews, and standalone logical patterns practice.',
    emoji: '🔢',
    mechanic: 'logic_pattern',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'patterns', 'sequence'],
    variants: [
      createVariant({
        id: 'logical_patterns_workshop.lesson-stage',
        label: 'Lesson variant',
        title: 'Logical patterns inside lessons',
        description: 'Lesson-facing variant intended for unified lesson flows.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_patterns_workshop.library-preview',
        label: 'Library preview',
        title: 'Logical patterns preview',
        description: 'Preview variant for the shared logical pattern engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_patterns_workshop.game-screen',
        label: 'Game screen',
        title: 'Logical patterns fullscreen',
        description: 'Fullscreen entry for the shared logical pattern engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'logical_patterns_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1000,
  },
  {
    id: 'logical_classification_lab',
    engineId: 'classification-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_classification'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Logical classification lab',
    title: 'Logical Classification Lab',
    description:
      'Shared classification engine for grouping and odd-one-out mechanics used in lesson variants and game screens.',
    emoji: '📦',
    mechanic: 'logic_classification',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'classification', 'sorting'],
    variants: [
      createVariant({
        id: 'logical_classification_lab.lesson-stage',
        label: 'Lesson variant',
        title: 'Logical classification inside lessons',
        description: 'Lesson-facing variant for the shared classification engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_classification_lab.library-preview',
        label: 'Library preview',
        title: 'Logical classification preview',
        description: 'Library preview of the shared classification engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_classification_lab.game-screen',
        label: 'Game screen',
        title: 'Logical classification fullscreen',
        description: 'Fullscreen entry for the shared classification engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'logical_classification_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1100,
  },
  {
    id: 'logical_analogies_relations',
    engineId: 'relation-match-engine',
    subject: 'maths',
    ageGroup: 'ten_year_old',
    lessonComponentIds: ['logical_analogies'],
    activityIds: [],
    legacyScreenIds: [],
    label: 'Logical analogies relations',
    title: 'Logical Analogies Relations',
    description:
      'Relation-matching engine shared across lesson variants and fullscreen logical analogies practice.',
    emoji: '🔗',
    mechanic: 'logic_relation',
    interactionMode: 'tap',
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'analogies', 'relations'],
    variants: [
      createVariant({
        id: 'logical_analogies_relations.lesson-stage',
        label: 'Lesson variant',
        title: 'Logical analogies inside lessons',
        description: 'Lesson-facing variant for the shared relation-match engine.',
        surface: 'lesson_stage',
      }),
      createVariant({
        id: 'logical_analogies_relations.library-preview',
        label: 'Library preview',
        title: 'Logical analogies preview',
        description: 'Catalog preview of the shared logical analogies engine.',
        surface: 'library_preview',
        sortOrder: 100,
      }),
      createVariant({
        id: 'logical_analogies_relations.game-screen',
        label: 'Game screen',
        title: 'Logical analogies fullscreen',
        description: 'Fullscreen entry for the shared logical analogies engine.',
        surface: 'game_screen',
        launchableRuntimeId: 'logical_analogies_quiz',
        sortOrder: 200,
      }),
    ],
    status: 'active',
    sortOrder: 1200,
  },
];
