export const CHATBOT_SETTINGS_KEY = "default";
export const CHATBOT_SETTINGS_STORAGE_KEY = "chatbot.settings.v1";

export const DEFAULT_CHATBOT_SETTINGS: any = {
  model: "",
  webSearchEnabled: false,
  useGlobalContext: false,
  useLocalContext: false,
  localContextMode: "override",
  searchProvider: "serpapi",
  agentModeEnabled: false,
  agentBrowser: "chromium",
  runHeadless: true,
  ignoreRobotsTxt: false,
  requireHumanApproval: false,
  memoryValidationModel: "",
  plannerModel: "",
  selfCheckModel: "",
  extractionValidationModel: "",
  loopGuardModel: "",
  approvalGateModel: "",
  memorySummarizationModel: "",
  selectorInferenceModel: "",
  outputNormalizationModel: "",
  maxSteps: 12,
  maxStepAttempts: 2,
  maxReplanCalls: 2,
  replanEverySteps: 2,
  maxSelfChecks: 4,
  loopGuardThreshold: 2,
  loopBackoffBaseMs: 2000,
  loopBackoffMaxMs: 12000,
};

export const MODEL_TASK_RULES: Record<string, any> = {
  main: { preferLarge: true, minSize: 7, preferReasoning: true },
  planner: { preferLarge: true, minSize: 7, preferReasoning: true },
  selfCheck: { preferLarge: true, minSize: 7 },
  extractionValidation: { preferLarge: true, minSize: 7 },
  approvalGate: { preferLarge: true, minSize: 7, preferReasoning: true },
  memoryValidation: { preferSmall: true, targetSize: 7, maxSize: 13 },
  memorySummarization: { preferLarge: true, minSize: 7, preferReasoning: true },
  loopGuard: { preferSmall: true, targetSize: 7, maxSize: 13 },
  selectorInference: { preferSmall: true, targetSize: 7, maxSize: 13 },
  outputNormalization: { preferSmall: true, targetSize: 3, maxSize: 7 },
};

export const DEFAULT_AGENT_SETTINGS: any = {
  agentBrowser: "chromium",
  runHeadless: true,
  ignoreRobotsTxt: false,
  requireHumanApproval: false,
  memoryValidationModel: "",
  plannerModel: "",
  selfCheckModel: "",
  extractionValidationModel: "",
  loopGuardModel: "",
  approvalGateModel: "",
  memorySummarizationModel: "",
  selectorInferenceModel: "",
  outputNormalizationModel: "",
  maxSteps: 12,
  maxStepAttempts: 2,
  maxReplanCalls: 2,
  replanEverySteps: 2,
  maxSelfChecks: 4,
  loopGuardThreshold: 2,
  loopBackoffBaseMs: 2000,
  loopBackoffMaxMs: 12000,
};
