export const createRouteHealth = (
  source: string,
  overrides?: {
    metrics?: {
      total: number;
      levels: { info: number; warn: number; error: number };
      last24Hours: number;
      last7Days: number;
      topSources: Array<{ source: string; count: number }>;
      topServices: Array<{ service: string; count: number }>;
      topPaths: Array<{ path: string; count: number }>;
      generatedAt: string;
    } | null;
    latency?: {
      sampleSize: number;
      avgDurationMs: number | null;
      p95DurationMs: number | null;
      maxDurationMs: number | null;
      slowRequestCount: number;
      slowRequestRatePercent: number | null;
      slowThresholdMs: number;
    } | null;
  }
) => ({
  metrics: overrides?.metrics ?? null,
  latency: overrides?.latency ?? null,
  investigation: {
    label: 'Inspect route logs',
    href: `/admin/system/logs?source=${encodeURIComponent(source)}&from=2026-03-06T12%3A00%3A00.000Z&to=2026-03-07T12%3A00%3A00.000Z`,
  },
});

export const createSummary = (range: '24h' | '7d' | '30d' = '24h') => ({
  generatedAt: '2026-03-07T12:00:00.000Z',
  range,
  overallStatus: 'warning' as const,
  window: {
    from: '2026-03-06T12:00:00.000Z',
    to: '2026-03-07T12:00:00.000Z',
  },
  keyMetrics: {
    serverErrorRatePercent: 2.4,
    learnerSignInAttempts: 12,
    learnerSignInFailureRatePercent: 8.3,
    progressSyncFailures: 4,
    ttsRequests: 11,
    ttsGenerationFailures: 2,
    ttsFallbackRatePercent: 18.2,
  },
  alerts: [
    {
      id: 'kangur-knowledge-graph-readiness',
      title: 'Knowledge Graph Readiness',
      status: 'ok' as const,
      value: null,
      unit: 'status',
      warningThreshold: null,
      criticalThreshold: null,
      summary:
        'Neo4j graph kangur-website-help-v1 is vector-ready with 87 nodes, 108 edges, and an online vector index.',
      investigation: {
        label: 'Open graph status',
        href: `/admin/kangur/observability?range=${range}#knowledge-graph-status`,
      },
    },
    {
      id: 'kangur-knowledge-graph-freshness',
      title: 'Knowledge Graph Freshness',
      status: 'warning' as const,
      value: 2,
      unit: 'hours',
      warningThreshold: 0,
      criticalThreshold: 24,
      summary:
        'Page content was updated after the latest Neo4j sync by about 2 hours. Last graph sync: 2026-03-07T12:00:00.000Z. Latest canonical update: 2026-03-07T14:00:00.000Z.',
      investigation: {
        label: 'Open graph status',
        href: `/admin/kangur/observability?range=${range}#knowledge-graph-status`,
      },
    },
    {
      id: 'kangur-server-error-rate',
      title: 'Server error rate',
      status: 'ok' as const,
      value: 2.4,
      unit: '%',
      warningThreshold: 3,
      criticalThreshold: 5,
      summary: 'Healthy.',
      investigation: {
        label: 'View error logs',
        href: '/admin/system/logs?query=kangur.&level=error&from=2026-03-06T12:00:00.000Z&to=2026-03-07T12:00:00.000Z',
      },
    },
    {
      id: 'kangur-learner-signin-failure-rate',
      title: 'Learner sign-in failure rate',
      status: 'warning' as const,
      value: 8.3,
      unit: '%',
      warningThreshold: 5,
      criticalThreshold: 10,
      summary: 'Watch learner sign-in failures.',
      investigation: {
        label: 'Review sign-in analytics',
        href: `/admin/kangur/observability?range=${range}#recent-analytics-events`,
      },
    },
    {
      id: 'kangur-progress-sync-failures',
      title: 'Progress sync failures',
      status: 'warning' as const,
      value: 4,
      unit: 'count',
      warningThreshold: 3,
      criticalThreshold: 10,
      summary: 'Progress sync failures detected.',
      investigation: {
        label: 'Review sync analytics',
        href: `/admin/kangur/observability?range=${range}#recent-analytics-events`,
      },
    },
    {
      id: 'kangur-tts-generation-failures',
      title: 'TTS generation failures',
      status: 'warning' as const,
      value: 2,
      unit: 'count',
      warningThreshold: 1,
      criticalThreshold: 3,
      summary: 'Neural narration generation is failing before fallback.',
      investigation: {
        label: 'View generation failure logs',
        href: '/admin/system/logs?source=kangur.tts.generationFailed&from=2026-03-06T12:00:00.000Z&to=2026-03-07T12:00:00.000Z',
      },
    },
    {
      id: 'kangur-tts-fallback-rate',
      title: 'TTS fallback rate',
      status: 'ok' as const,
      value: 18.2,
      unit: '%',
      warningThreshold: 20,
      criticalThreshold: 35,
      summary: 'Fallback rate within threshold.',
      investigation: {
        label: 'View fallback logs',
        href: '/admin/system/logs?source=kangur.tts.fallback&from=2026-03-06T12:00:00.000Z&to=2026-03-07T12:00:00.000Z',
      },
    },
    {
      id: 'kangur-ai-tutor-bridge-completion-rate',
      title: 'AI Tutor Bridge Completion Rate',
      status: 'warning' as const,
      value: 33.3,
      unit: '%',
      warningThreshold: 40,
      criticalThreshold: 20,
      summary:
        'Bridge suggestions are not converting into completed cross-surface follow-ups fast enough.',
      investigation: {
        label: 'Review tutor bridge analytics',
        href: `/admin/kangur/observability?range=${range}#recent-analytics-events`,
      },
    },
    {
      id: 'kangur-ai-tutor-direct-answer-rate',
      title: 'AI Tutor Direct Answer Rate',
      status: 'warning' as const,
      value: 50,
      unit: '%',
      warningThreshold: 60,
      criticalThreshold: 30,
      summary: 'Deterministic Tutor answers are below the preferred rollout target.',
      investigation: {
        label: 'Open AI Tutor graph metrics',
        href: `/admin/kangur/observability?range=${range}#ai-tutor-bridge`,
      },
    },
    {
      id: 'kangur-ai-tutor-graph-coverage-rate',
      title: 'AI Tutor Graph Coverage Rate',
      status: 'warning' as const,
      value: 66.7,
      unit: '%',
      warningThreshold: 60,
      criticalThreshold: 30,
      summary: 'Neo4j graph coverage is below the preferred Tutor reply share.',
      investigation: {
        label: 'Open AI Tutor graph metrics',
        href: `/admin/kangur/observability?range=${range}#ai-tutor-bridge`,
      },
    },
    {
      id: 'kangur-ai-tutor-vector-assist-rate',
      title: 'AI Tutor Vector Assist Rate',
      status: 'critical' as const,
      value: 12.5,
      unit: '%',
      warningThreshold: 40,
      criticalThreshold: 15,
      summary: 'Vector-assisted recall is contributing to too few semantic Tutor replies.',
      investigation: {
        label: 'Open AI Tutor graph metrics',
        href: `/admin/kangur/observability?range=${range}#ai-tutor-bridge`,
      },
    },
    {
      id: 'kangur-performance-baseline',
      title: 'Performance baseline',
      status: 'warning' as const,
      value: 1,
      unit: 'count',
      warningThreshold: 1,
      criticalThreshold: 2,
      summary: 'Latest baseline is degraded.',
      investigation: {
        label: 'Open baseline details',
        href: `/admin/kangur/observability?range=${range}#performance-baseline`,
      },
    },
  ],
  serverLogs: {
    metrics: {
      total: 14,
      levels: { info: 10, warn: 2, error: 2 },
      last24Hours: 14,
      last7Days: 20,
      topSources: [{ source: 'kangur.tts', count: 5 }],
      topServices: [{ service: 'app', count: 14 }],
      topPaths: [{ path: '/api/kangur/tts', count: 5 }],
      generatedAt: '2026-03-07T12:00:00.000Z',
    },
    recent: [
      {
        id: 'log-1',
        createdAt: '2026-03-07T11:45:00.000Z',
        level: 'error' as const,
        message: 'Kangur TTS fallback used.',
        source: 'kangur.tts.fallback',
        path: '/api/kangur/tts',
        requestId: 'req-1',
        traceId: 'trace-1',
      },
    ],
  },
  routes: {
    authMeGet: createRouteHealth('kangur.auth.me.GET'),
    learnerSignInPost: createRouteHealth('kangur.auth.learnerSignIn.POST'),
    progressPatch: createRouteHealth('kangur.progress.PATCH'),
    scoresPost: createRouteHealth('kangur.scores.POST'),
    assignmentsPost: createRouteHealth('kangur.assignments.POST'),
    learnersPost: createRouteHealth('kangur.learners.POST'),
    ttsPost: createRouteHealth('kangur.tts.POST', {
      metrics: {
        total: 5,
        levels: { info: 4, warn: 0, error: 1 },
        last24Hours: 5,
        last7Days: 5,
        topSources: [{ source: 'kangur.tts', count: 5 }],
        topServices: [{ service: 'app', count: 5 }],
        topPaths: [{ path: '/api/kangur/tts', count: 5 }],
        generatedAt: '2026-03-07T12:00:00.000Z',
      },
      latency: {
        sampleSize: 5,
        avgDurationMs: 540,
        p95DurationMs: 820,
        maxDurationMs: 910,
        slowRequestCount: 2,
        slowRequestRatePercent: 40,
        slowThresholdMs: 750,
      },
    }),
  },
  analytics: {
    totals: { events: 10, pageviews: 4 },
    visitors: 3,
    sessions: 5,
    topPaths: [{ path: '/kangur', count: 4 }],
    topEventNames: [{ name: 'kangur_game_completed', count: 3 }],
    importantEvents: [
      { name: 'kangur_progress_sync_failed', count: 4 },
      { name: 'kangur_duels_lobby_viewed', count: 12 },
      { name: 'kangur_duels_lobby_refresh_clicked', count: 5 },
      { name: 'kangur_duels_lobby_filter_changed', count: 4 },
      { name: 'kangur_duels_lobby_sort_changed', count: 3 },
      { name: 'kangur_duels_lobby_join_clicked', count: 2 },
      { name: 'kangur_duels_lobby_create_clicked', count: 1 },
      { name: 'kangur_duels_lobby_login_clicked', count: 6 },
    ],
    aiTutor: {
      messageSucceededCount: 6,
      pageContentAnswerCount: 2,
      nativeGuideAnswerCount: 1,
      brainAnswerCount: 3,
      knowledgeGraphAppliedCount: 4,
      knowledgeGraphSemanticCount: 3,
      knowledgeGraphWebsiteHelpCount: 1,
      knowledgeGraphMetadataOnlyRecallCount: 1,
      knowledgeGraphHybridRecallCount: 2,
      knowledgeGraphVectorOnlyRecallCount: 1,
      knowledgeGraphVectorRecallAttemptedCount: 3,
      bridgeSuggestionCount: 3,
      lessonToGameBridgeSuggestionCount: 2,
      gameToLessonBridgeSuggestionCount: 1,
      bridgeQuickActionClickCount: 2,
      bridgeFollowUpClickCount: 2,
      bridgeFollowUpCompletionCount: 1,
      directAnswerRatePercent: 50,
      brainFallbackRatePercent: 50,
      bridgeCompletionRatePercent: 33.3,
      knowledgeGraphCoverageRatePercent: 66.7,
      knowledgeGraphVectorAssistRatePercent: 100,
    },
    duelsLobby: {
      totals: {
        viewed: 12,
        refreshClicked: 5,
        filterChanged: 4,
        sortChanged: 3,
        joinClicked: 2,
        createClicked: 1,
        loginClicked: 6,
      },
      byUser: {
        guest: {
          viewed: 7,
          refreshClicked: 3,
          filterChanged: 2,
          sortChanged: 1,
          joinClicked: 0,
          createClicked: 0,
          loginClicked: 6,
        },
        authenticated: {
          viewed: 5,
          refreshClicked: 2,
          filterChanged: 2,
          sortChanged: 2,
          joinClicked: 2,
          createClicked: 1,
          loginClicked: 0,
        },
      },
      byFilterMode: {
        all: 2,
        challenge: 2,
        quick_match: 0,
      },
      bySort: {
        recent: 2,
        time_fast: 1,
        time_slow: 0,
        questions_low: 0,
        questions_high: 0,
      },
      loginBySource: {
        banner: 2,
        join: 3,
        invite_join: 1,
      },
    },
    recent: [
      {
        id: 'event-1',
        ts: '2026-03-07T11:40:00.000Z',
        type: 'event' as const,
        name: 'kangur_progress_sync_failed',
        path: '/kangur/play',
        visitorId: 'visitor-1',
        sessionId: 'session-1',
        meta: null,
      },
      {
        id: 'event-tutor-1',
        ts: '2026-03-07T11:42:00.000Z',
        type: 'event' as const,
        name: 'kangur_ai_tutor_message_sent',
        path: '/kangur',
        visitorId: 'visitor-1',
        sessionId: 'session-1',
        meta: {
          latestUserMessage: 'Wyjaśnij ranking wyników',
          surface: 'game',
          promptMode: 'explain',
          interactionIntent: 'explain',
          focusKind: 'leaderboard',
          focusId: 'kangur-game-home-leaderboard',
          focusLabel: 'Ranking na stronie głównej',
          contentId: 'game:home',
          questionId: 'question-7',
          assignmentId: 'assignment-42',
          answerRevealed: false,
          selectedText: 'Ranking wyników',
          title: 'Ranking na stronie głównej',
          description: 'Aktualna tabela wyników.',
        },
      },
    ],
  },
  knowledgeGraphStatus: {
    mode: 'status' as const,
    graphKey: 'kangur-website-help-v1',
    present: true,
    locale: 'pl',
    syncedAt: '2026-03-07T12:00:00.000Z',
    syncedNodeCount: 87,
    syncedEdgeCount: 108,
    liveNodeCount: 87,
    liveEdgeCount: 108,
    canonicalNodeCount: 80,
    validCanonicalNodeCount: 80,
    invalidCanonicalNodeCount: 0,
    semanticNodeCount: 87,
    embeddingNodeCount: 87,
    embeddingDimensions: 1536,
    embeddingModels: ['text-embedding-3-small'],
    vectorIndexPresent: true,
    vectorIndexState: 'ONLINE',
    vectorIndexType: 'VECTOR',
    vectorIndexDimensions: 1536,
    semanticCoverageRatePercent: 100,
    embeddingCoverageRatePercent: 100,
    semanticReadiness: 'vector_ready' as const,
  },
  performanceBaseline: {
    generatedAt: '2026-03-07T08:00:00.000Z',
    unitStatus: 'pass',
    unitDurationMs: 1000,
    e2eStatus: 'infra_fail',
    e2eDurationMs: 2000,
    infraFailures: 1,
    failedRuns: 0,
    bundleRiskTotalBytes: 100,
    bundleRiskTotalLines: 10,
  },
  errors: {
    analytics: 'Analytics aggregation is partially degraded.',
  },
});

export const createKnowledgeGraphPreviewResponse = () => ({
  learnerId: 'learner-1',
  locale: 'pl',
  runtimeResolution: 'live' as const,
  requestedRefIds: [
    'runtime:kangur:learner:learner-1',
    'runtime:kangur:login-activity:learner-1',
  ],
  runtimeDocumentIds: ['runtime:kangur:learner:learner-1'],
  summary: {
    requestedRefCount: 2,
    runtimeDocumentCount: 1,
    retrievalStatus: 'hit' as const,
    queryMode: 'semantic' as const,
    recallStrategy: 'hybrid_vector' as const,
    nodeCount: 2,
    sourceCount: 1,
    lexicalHitCount: 1,
    vectorHitCount: 1,
    vectorRecallAttempted: true,
    tokenCount: 3,
    normalizedQuerySeed: 'wyjaśnij ranking wyników',
    websiteHelpTargetNodeId: 'guide:native:game-leaderboard',
  },
  retrieval: {
    status: 'hit' as const,
    queryMode: 'semantic' as const,
    recallStrategy: 'hybrid_vector' as const,
    lexicalHitCount: 1,
    vectorHitCount: 1,
    vectorRecallAttempted: true,
    querySeed: 'Wyjaśnij ranking wyników',
    normalizedQuerySeed: 'wyjaśnij ranking wyników',
    tokens: ['wyjasnij', 'ranking', 'wynikow'],
    instructions: 'Kangur semantic graph context:\n- Ranking wyników',
    sources: [
      {
        documentId: 'guide:native:game-leaderboard',
        collectionId: 'kangur_ai_tutor_native_guides',
        text: 'Sekcja rankingu pokazuje wyniki.',
        score: 0.97,
        metadata: {
          source: 'manual-text',
          sourceId: 'guide:native:game-leaderboard',
          title: 'Ranking wyników',
          tags: ['kangur-knowledge-graph', 'guide', 'game'],
        },
      },
    ],
    nodeIds: ['guide:native:game-leaderboard', 'page:kangur-game'],
    websiteHelpTarget: {
      nodeId: 'guide:native:game-leaderboard',
      label: 'Ranking wyników',
      route: '/game',
      anchorId: 'kangur-game-result-leaderboard',
    },
    graphFollowUpActions: [],
    hits: [
      {
        id: 'guide:native:game-leaderboard',
        kind: 'guide',
        title: 'Ranking wyników',
        summary: 'Sekcja rankingu pokazuje wyniki.',
        surface: 'game',
        focusKind: 'leaderboard',
        route: '/game',
        anchorId: 'kangur-game-result-leaderboard',
        sourceCollection: 'kangur_ai_tutor_native_guides',
        sourceRecordId: 'game-leaderboard',
        sourcePath: 'entry:game-leaderboard',
        semanticScore: 214,
        tokenHits: 2,
        relatedTargetIds: ['page:kangur-game'],
        canonicalTitle: 'Ranking wyników',
        canonicalSummary: 'Sekcja rankingu pokazuje wyniki.',
        canonicalSourceCollection: 'kangur_ai_tutor_native_guides',
        hydrationSource: 'kangur_ai_tutor_native_guides' as const,
      },
    ],
    sourceCollections: ['kangur_ai_tutor_native_guides'],
    hydrationSources: ['kangur_ai_tutor_native_guides' as const],
  },
});
