import { DEFAULT_THEME, normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';

export const KANGUR_DAILY_CRYSTAL_THEME: ThemeSettings = normalizeThemeSettings({
  ...DEFAULT_THEME,
  themePreset: 'kangur-daily-crystal',
  darkMode: false,

  // ── Core Palette ──────────────────────────────────────────
  primaryColor: '#2563eb',
  secondaryColor: '#7c3aed',
  accentColor: '#f59e0b',
  backgroundColor: '#eef3fa',
  surfaceColor: '#f7f9ff',
  textColor: '#1e293b',
  mutedTextColor: '#64748b',
  pageTextColor: '#1e293b',
  pageMutedTextColor: '#64748b',
  cardTextColor: '#1e293b',
  navTextColor: '#475569',
  navActiveTextColor: '#2563eb',
  navHoverTextColor: '#1d4ed8',
  borderColor: '#dde4f0',
  errorColor: '#ef4444',
  successColor: '#10b981',

  // ── Accent Gradients (all 8) ──────────────────────────────
  gradientIndigoStart: '#2563eb',
  gradientIndigoEnd: '#4f46e5',
  gradientVioletStart: '#7c3aed',
  gradientVioletEnd: '#a855f7',
  gradientEmeraldStart: '#10b981',
  gradientEmeraldEnd: '#34d399',
  gradientSkyStart: '#0ea5e9',
  gradientSkyEnd: '#38bdf8',
  gradientAmberStart: '#f59e0b',
  gradientAmberEnd: '#fbbf24',
  gradientRoseStart: '#f43f5e',
  gradientRoseEnd: '#fb7185',
  gradientTealStart: '#14b8a6',
  gradientTealEnd: '#2dd4bf',
  gradientSlateStart: '#94a3b8',
  gradientSlateEnd: '#64748b',

  // ── Logo ──────────────────────────────────────────────────
  logoWordStart: '#2563eb',
  logoWordMid: '#4f46e5',
  logoWordEnd: '#7c3aed',
  logoRingStart: '#3b82f6',
  logoRingEnd: '#7c3aed',
  logoAccentStart: '#f59e0b',
  logoAccentEnd: '#f97316',
  logoInnerStart: '#ffffff',
  logoInnerEnd: '#e0e7ff',
  logoShadow: '#a8b5d6',
  logoGlint: '#fffbe6',

  // ── Home Actions — Lessons (sapphire-to-indigo) ───────────
  homeActionLessonsTextColor: '#1e3a6e',
  homeActionLessonsTextActiveColor: '#f8fafc',
  homeActionLessonsLabelStart: '#2563eb',
  homeActionLessonsLabelMid: '#3b82f6',
  homeActionLessonsLabelEnd: '#4f46e5',
  homeActionLessonsLabelStartActive: '#ffffff',
  homeActionLessonsLabelMidActive: '#eaf2ff',
  homeActionLessonsLabelEndActive: '#dbe7ff',
  homeActionLessonsAccentStart: '#2563eb',
  homeActionLessonsAccentMid: '#3b82f6',
  homeActionLessonsAccentEnd: '#4f46e5',
  homeActionLessonsUnderlayStart: 'rgba(37, 99, 235, 0.18)',
  homeActionLessonsUnderlayMid: 'rgba(59, 130, 246, 0.14)',
  homeActionLessonsUnderlayEnd: 'rgba(79, 70, 229, 0.20)',
  homeActionLessonsUnderlayTintStart: 'rgba(37, 99, 235, 0.24)',
  homeActionLessonsUnderlayTintMid: 'rgba(59, 130, 246, 0.46)',
  homeActionLessonsUnderlayTintEnd: 'rgba(79, 70, 229, 0.68)',
  homeActionLessonsAccentShadowColor: '#3b82f6',
  homeActionLessonsUnderlayShadowColor: '#4f46e5',
  homeActionLessonsSurfaceShadowColor: '#2563eb',

  // ── Home Actions — Play (violet-to-purple) ────────────────
  homeActionPlayTextColor: '#3b1f7a',
  homeActionPlayTextActiveColor: '#f5f3ff',
  homeActionPlayLabelStart: '#7c3aed',
  homeActionPlayLabelMid: '#8b5cf6',
  homeActionPlayLabelEnd: '#a855f7',
  homeActionPlayLabelStartActive: '#ffffff',
  homeActionPlayLabelMidActive: '#f3e8ff',
  homeActionPlayLabelEndActive: '#e9d5ff',
  homeActionPlayAccentStart: '#7c3aed',
  homeActionPlayAccentMid: '#8b5cf6',
  homeActionPlayAccentEnd: '#a855f7',
  homeActionPlayUnderlayStart: 'rgba(124, 58, 237, 0.18)',
  homeActionPlayUnderlayMid: 'rgba(139, 92, 246, 0.14)',
  homeActionPlayUnderlayEnd: 'rgba(168, 85, 247, 0.20)',
  homeActionPlayUnderlayTintStart: 'rgba(124, 58, 237, 0.24)',
  homeActionPlayUnderlayTintMid: 'rgba(139, 92, 246, 0.46)',
  homeActionPlayUnderlayTintEnd: 'rgba(168, 85, 247, 0.68)',
  homeActionPlayAccentShadowColor: '#8b5cf6',
  homeActionPlayUnderlayShadowColor: '#a855f7',
  homeActionPlaySurfaceShadowColor: '#7c3aed',

  // ── Home Actions — Training (sky-to-cyan) ─────────────────
  homeActionTrainingTextColor: '#0c4a6e',
  homeActionTrainingTextActiveColor: '#f0f9ff',
  homeActionTrainingLabelStart: '#0ea5e9',
  homeActionTrainingLabelMid: '#22d3ee',
  homeActionTrainingLabelEnd: '#38bdf8',
  homeActionTrainingLabelStartActive: '#ffffff',
  homeActionTrainingLabelMidActive: '#e0f2fe',
  homeActionTrainingLabelEndActive: '#bae6fd',
  homeActionTrainingAccentStart: '#0ea5e9',
  homeActionTrainingAccentMid: '#22d3ee',
  homeActionTrainingAccentEnd: '#38bdf8',
  homeActionTrainingUnderlayStart: 'rgba(14, 165, 233, 0.18)',
  homeActionTrainingUnderlayMid: 'rgba(34, 211, 238, 0.14)',
  homeActionTrainingUnderlayEnd: 'rgba(56, 189, 248, 0.20)',
  homeActionTrainingUnderlayTintStart: 'rgba(14, 165, 233, 0.24)',
  homeActionTrainingUnderlayTintMid: 'rgba(34, 211, 238, 0.44)',
  homeActionTrainingUnderlayTintEnd: 'rgba(56, 189, 248, 0.66)',
  homeActionTrainingAccentShadowColor: '#22d3ee',
  homeActionTrainingUnderlayShadowColor: '#0ea5e9',
  homeActionTrainingSurfaceShadowColor: '#0284c7',

  // ── Home Actions — Kangur (amber-to-orange) ───────────────
  homeActionKangurTextColor: '#78350f',
  homeActionKangurTextActiveColor: '#fff7ed',
  homeActionKangurLabelStart: '#f59e0b',
  homeActionKangurLabelMid: '#f97316',
  homeActionKangurLabelEnd: '#fb923c',
  homeActionKangurLabelStartActive: '#fff7ed',
  homeActionKangurLabelMidActive: '#ffedd5',
  homeActionKangurLabelEndActive: '#fed7aa',
  homeActionKangurAccentStart: '#f59e0b',
  homeActionKangurAccentMid: '#f97316',
  homeActionKangurAccentEnd: '#fb923c',
  homeActionKangurUnderlayStart: 'rgba(245, 158, 11, 0.20)',
  homeActionKangurUnderlayMid: 'rgba(249, 115, 22, 0.14)',
  homeActionKangurUnderlayEnd: 'rgba(251, 146, 60, 0.22)',
  homeActionKangurUnderlayTintStart: 'rgba(245, 158, 11, 0.24)',
  homeActionKangurUnderlayTintMid: 'rgba(249, 115, 22, 0.44)',
  homeActionKangurUnderlayTintEnd: 'rgba(251, 146, 60, 0.64)',
  homeActionKangurAccentShadowColor: '#f97316',
  homeActionKangurUnderlayShadowColor: '#f59e0b',
  homeActionKangurSurfaceShadowColor: '#d97706',

  // ── Color Schemes ─────────────────────────────────────────
  colorSchemes: [
    {
      id: 'kangur-crystal-sapphire',
      name: 'Crystal Sapphire',
      colors: {
        background: '#eef3fa',
        surface: '#f7f9ff',
        text: '#1e293b',
        accent: '#2563eb',
        border: '#dde4f0',
      },
    },
    {
      id: 'kangur-crystal-amethyst',
      name: 'Crystal Amethyst',
      colors: {
        background: '#f3effe',
        surface: '#f9f7ff',
        text: '#1e293b',
        accent: '#7c3aed',
        border: '#e4daf8',
      },
    },
    {
      id: 'kangur-crystal-aqua',
      name: 'Crystal Aqua',
      colors: {
        background: '#ecf8ff',
        surface: '#f5fbff',
        text: '#1e293b',
        accent: '#0ea5e9',
        border: '#d4edf8',
      },
    },
    {
      id: 'kangur-crystal-amber',
      name: 'Crystal Amber',
      colors: {
        background: '#fef7ec',
        surface: '#fffbf5',
        text: '#1e293b',
        accent: '#f59e0b',
        border: '#f3e4c8',
      },
    },
  ],
  activeColorSchemeId: 'kangur-crystal-sapphire',

  // ── Typography ────────────────────────────────────────────
  headingFont: '\'Space Grotesk\', sans-serif',
  bodyFont: '\'DM Sans\', sans-serif',
  baseSize: 16,
  headingWeight: '700',
  bodyWeight: '400',
  headingSizeScale: 1.08,
  bodySizeScale: 1,
  lineHeight: 1.62,
  headingLineHeight: 1.16,

  // ── Layout ────────────────────────────────────────────────
  maxContentWidth: 1240,
  gridGutter: 28,
  sectionSpacing: 72,
  containerPadding: 28,
  borderRadius: 24,
  pagePaddingTop: 36,
  pagePaddingRight: 32,
  pagePaddingBottom: 84,
  pagePaddingLeft: 32,
  pagePadding: 32,
  pageMargin: 0,
  fullWidth: false,

  // ── Animations ────────────────────────────────────────────
  enableAnimations: true,
  animationDuration: 260,
  animationEasing: 'ease-out',
  scrollReveal: true,
  hoverEffect: 'vertical-lift',
  hoverScale: 1.015,

  // ── Buttons (full gel showcase) ───────────────────────────
  btnPaddingX: 24,
  btnPaddingY: 12,
  btnFontSize: 14,
  btnFontWeight: '600',
  btnRadius: 999,
  btnPrimaryBg: 'linear-gradient(180deg, #e0e7ff 0%, #c7d2fe 46%, #818cf8 100%)',
  btnPrimaryText: '#1e3a6e',
  btnSecondaryBg: 'linear-gradient(180deg, rgba(255, 255, 255, 0.96) 0%, rgba(226, 238, 255, 0.92) 100%)',
  btnSecondaryText: '#1e3a6e',
  btnOutlineBorder: '#c7d6ef',
  btnBorderWidth: 1,
  btnBorderOpacity: 55,
  btnBorderRadius: 999,
  btnShadowOpacity: 0.22,
  btnShadowX: 0,
  btnShadowY: 8,
  btnShadowBlur: 24,

  // ── Button Gel Effects (all 12, full showcase) ────────────
  btnGlossOpacity: 0.38,
  btnGlossHeight: 52,
  btnGlossAngle: 178,
  btnInsetHighlightOpacity: 0.45,
  btnInsetShadowOpacity: 0.3,
  btnInsetShadowBlur: 5,
  btnInsetShadowY: 3,
  btnTextShadowOpacity: 0,
  btnTextShadowY: 1,
  btnTextShadowBlur: 0,
  btnGlowOpacity: 0.18,
  btnGlowSpread: 10,

  // ── Variant Pills ─────────────────────────────────────────
  pillRadius: 999,
  pillPaddingX: 14,
  pillPaddingY: 6,
  pillFontSize: 12,
  pillBg: 'rgba(255, 255, 255, 0.82)',
  pillText: '#475569',
  pillActiveBg: '#dbeafe',
  pillActiveText: '#1d4ed8',
  pillBorderColor: '#dde4f0',
  pillBorderWidth: 1,
  pillBorderOpacity: 65,
  pillShadowOpacity: 0.14,
  pillShadowX: 0,
  pillShadowY: 8,
  pillShadowBlur: 22,

  // ── Inputs ────────────────────────────────────────────────
  inputHeight: 50,
  inputRadius: 22,
  inputBorderColor: '#d4dbed',
  inputBorderWidth: 1,
  inputBorderOpacity: 80,
  inputBg: '#ffffff',
  inputText: '#1e293b',
  inputFocusBorder: '#93b4f6',
  inputPlaceholder: '#94a3b8',
  inputFontSize: 14,
  inputShadowOpacity: 0.1,
  inputShadowX: 0,
  inputShadowY: 10,
  inputShadowBlur: 28,

  // ── Product Cards ─────────────────────────────────────────
  cardStyle: 'standard',
  cardImageRatio: '3:4',
  cardTextAlignment: 'left',
  cardColorScheme: 'kangur-crystal-sapphire',
  cardRadius: 22,
  cardShadow: 'large',
  cardBg: '#ffffff',
  cardHoverShadow: 'large',
  showBadge: true,
  showQuickAdd: false,
  cardBorderWidth: 1,
  cardBorderOpacity: 60,
  cardBorderRadius: 22,
  cardShadowOpacity: 0.14,
  cardShadowX: 0,
  cardShadowY: 16,
  cardShadowBlur: 36,

  // ── Collections ───────────────────────────────────────────
  collectionRatio: '16:9',
  collectionRadius: 22,
  collectionStyle: 'overlay',
  collectionImagePadding: 8,
  collectionOverlay: true,
  collectionOverlayColor: 'rgba(255, 255, 255, 0.68)',
  collectionTextAlign: 'left',
  collectionColorScheme: 'kangur-crystal-sapphire',
  collectionBorderWidth: 1,
  collectionBorderOpacity: 60,
  collectionShadowOpacity: 0.14,
  collectionShadowX: 0,
  collectionShadowY: 16,
  collectionShadowBlur: 36,

  // ── Blog ──────────────────────────────────────────────────
  blogStyle: 'standard',
  blogRatio: '16:9',
  blogImagePadding: 8,
  blogTextAlignment: 'left',
  blogColorScheme: 'kangur-crystal-sapphire',
  blogRadius: 22,
  blogShowDate: true,
  blogShowExcerpt: true,
  blogExcerptLines: 3,
  blogBorderWidth: 1,
  blogBorderOpacity: 60,
  blogBorderRadius: 22,
  blogShadowOpacity: 0.14,
  blogShadowX: 0,
  blogShadowY: 16,
  blogShadowBlur: 36,

  // ── Content Containers ────────────────────────────────────
  containerBg: '#f7f9ff',
  containerBorderColor: '#e2e8f4',
  containerRadius: 26,
  containerPaddingInner: 24,
  containerShadow: 'large',
  containerBorderWidth: 1,
  containerBorderOpacity: 65,
  containerBorderRadius: 26,
  containerShadowOpacity: 0.16,
  containerShadowX: 0,
  containerShadowY: 18,
  containerShadowBlur: 44,

  // ── Panel & Nav Gradients ─────────────────────────────────
  panelGradientStart: 'rgba(255, 255, 255, 0.98)',
  panelGradientEnd: 'rgba(238, 243, 250, 0.94)',
  panelTransparency: 0.96,
  navGradientStart: 'rgba(255, 255, 255, 0.97)',
  navGradientEnd: 'rgba(240, 245, 255, 0.92)',
  navTransparency: 0.95,

  // ── Media ─────────────────────────────────────────────────
  imageRadius: 16,
  imageBorderColor: '#dde4f0',
  imageBorderWidth: 1,
  imageBorderOpacity: 55,
  imageShadowOpacity: 0.1,
  imageShadowX: 0,
  imageShadowY: 10,
  imageShadowBlur: 28,
  imagePlaceholderBg: '#f0f4ff',

  // ── Dropdowns ─────────────────────────────────────────────
  dropdownBg: '#ffffff',
  dropdownBorder: '#dde4f0',
  dropdownBorderWidth: 1,
  dropdownBorderOpacity: 70,
  dropdownRadius: 18,
  dropdownShadow: 'large',
  dropdownShadowOpacity: 0.18,
  dropdownShadowX: 0,
  dropdownShadowY: 14,
  dropdownShadowBlur: 36,
  popupOverlayColor: 'rgba(30, 41, 59, 0.16)',
  popupRadius: 24,

  // ── Drawers ───────────────────────────────────────────────
  drawerWidth: 400,
  drawerBg: '#f7f9ff',
  drawerOverlayColor: 'rgba(30, 41, 59, 0.18)',
  drawerPosition: 'right',
  drawerBorderColor: '#e0e7f2',
  drawerBorderWidth: 1,
  drawerBorderOpacity: 70,
  drawerRadius: 24,
  drawerShadowOpacity: 0.2,
  drawerShadowX: 0,
  drawerShadowY: 16,
  drawerShadowBlur: 44,

  // ── Badges ────────────────────────────────────────────────
  badgePosition: 'top-right',
  badgeFontSize: 11,
  badgeRadius: 999,
  badgePaddingX: 10,
  badgePaddingY: 4,
  badgeDefaultBg: '#e0e7ff',
  badgeDefaultText: '#3730a3',
  badgeSaleColorScheme: 'kangur-crystal-amber',
  badgeSaleBg: '#fef3c7',
  badgeSaleText: '#92400e',
  badgeSoldOutColorScheme: 'kangur-crystal-sapphire',
  badgeSoldOutBg: '#f0f4ff',
  badgeSoldOutText: '#64748b',
});

/** Kangur Nightly Crystal theme — deep sapphire night with high-gloss gel buttons (2026-03-14). */
