import { normalizeThemeSettings, type ThemeSettings } from '@/shared/contracts/cms-theme';
import { KANGUR_NIGHTLY_AURORA_THEME } from './nightly';

export const KANGUR_SUNSET_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_NIGHTLY_AURORA_THEME,
  themePreset: 'kangur-sunset',
  primaryColor: '#f97316',
  secondaryColor: '#fb7185',
  accentColor: '#fbbf24',
  backgroundColor: '#140b14',
  surfaceColor: '#1d131f',
  textColor: '#fff4e6',
  mutedTextColor: '#e2bfa8',
  borderColor: '#2a1b2f',
  errorColor: '#fb7185',
  successColor: '#34d399',
  colorSchemes: [
    {
      id: 'kangur-sunset-ember',
      name: 'Sunset Ember',
      colors: {
        background: '#140b14',
        surface: '#1d131f',
        text: '#fff4e6',
        accent: '#f97316',
        border: '#2a1b2f',
      },
    },
    {
      id: 'kangur-sunset-rose',
      name: 'Sunset Rose',
      colors: {
        background: '#180d1a',
        surface: '#241322',
        text: '#fff4e6',
        accent: '#fb7185',
        border: '#332035',
      },
    },
    {
      id: 'kangur-sunset-amber',
      name: 'Sunset Amber',
      colors: {
        background: '#16100f',
        surface: '#231816',
        text: '#fff4e6',
        accent: '#fbbf24',
        border: '#332620',
      },
    },
    {
      id: 'kangur-sunset-coral',
      name: 'Sunset Coral',
      colors: {
        background: '#140e13',
        surface: '#20141a',
        text: '#fff4e6',
        accent: '#fb923c',
        border: '#2f2027',
      },
    },
  ],
  activeColorSchemeId: 'kangur-sunset-ember',
  btnPrimaryBg: 'linear-gradient(135deg, #f97316 0%, #fb923c 52%, #fbbf24 100%)',
  btnPrimaryText: '#1f130a',
  btnSecondaryBg: 'rgba(24, 16, 24, 0.9)',
  btnSecondaryText: '#fff3e0',
  btnOutlineBorder: '#3a2a2f',
  pillBg: 'rgba(24, 16, 24, 0.82)',
  pillText: '#e8c8b4',
  pillActiveBg: 'rgba(45, 28, 36, 0.9)',
  pillActiveText: '#fbbf24',
  pillBorderColor: '#3a2a2f',
  inputBorderColor: '#3a2a2f',
  inputBg: '#160f16',
  inputText: '#fff3e0',
  inputFocusBorder: '#fbbf24',
  inputPlaceholder: '#c9a88e',
  cardColorScheme: 'kangur-sunset-ember',
  cardBg: '#1a121c',
  collectionColorScheme: 'kangur-sunset-ember',
  collectionOverlayColor: 'rgba(10, 6, 12, 0.6)',
  blogColorScheme: 'kangur-sunset-ember',
  containerBg: '#171019',
  containerBorderColor: '#2a1b2f',
  panelGradientStart: '#221423',
  panelGradientEnd: '#120a14',
  navGradientStart: '#1e111f',
  navGradientEnd: '#0f0811',
  imageBorderColor: '#2d1d2e',
  imagePlaceholderBg: '#120a14',
  dropdownBg: '#1e111f',
  dropdownBorder: '#3a2a2f',
  popupOverlayColor: 'rgba(10, 6, 12, 0.6)',
  drawerBg: '#171019',
  drawerOverlayColor: 'rgba(10, 6, 12, 0.6)',
  drawerBorderColor: '#2a1b2f',
  badgeDefaultBg: '#241824',
  badgeDefaultText: '#f1d2bd',
  badgeSaleColorScheme: 'kangur-sunset-rose',
  badgeSaleBg: '#fcd7c2',
  badgeSaleText: '#7a3b21',
  badgeSoldOutColorScheme: 'kangur-sunset-ember',
  badgeSoldOutBg: '#1d121c',
  badgeSoldOutText: '#c7a390',
});

/** Kangur Sunset Horizon theme — twilight indigo with amber glow (2026-03-13). */
export const KANGUR_SUNSET_HORIZON_THEME: ThemeSettings = normalizeThemeSettings({
  ...KANGUR_SUNSET_THEME,
  themePreset: 'kangur-sunset-horizon',
  primaryColor: '#5f54d8',
  secondaryColor: '#8a5dff',
  accentColor: '#ffb35c',
  backgroundColor: '#0d0f1f',
  surfaceColor: '#151a33',
  textColor: '#f6f4ff',
  mutedTextColor: '#c3bddc',
  borderColor: '#262b46',
  errorColor: '#ff7d8a',
  successColor: '#45d3a4',
  gradientIndigoStart: '#4f62db',
  gradientIndigoEnd: '#7c52ff',
  gradientVioletStart: '#5f54d8',
  gradientVioletEnd: '#9a5be2',
  gradientEmeraldStart: '#2dd4bf',
  gradientEmeraldEnd: '#5eead4',
  gradientSkyStart: '#2f88d8',
  gradientSkyEnd: '#58b8df',
  gradientAmberStart: '#ff9a35',
  gradientAmberEnd: '#ffd560',
  gradientRoseStart: '#fb7185',
  gradientRoseEnd: '#f9a8d4',
  gradientTealStart: '#4aa7ff',
  gradientTealEnd: '#60d9ff',
  gradientSlateStart: '#9aa5c3',
  gradientSlateEnd: '#4b5568',
  colorSchemes: [
    {
      id: 'kangur-horizon-indigo',
      name: 'Horizon Indigo',
      colors: {
        background: '#0d0f1f',
        surface: '#151a33',
        text: '#f6f4ff',
        accent: '#5f54d8',
        border: '#262b46',
      },
    },
    {
      id: 'kangur-horizon-violet',
      name: 'Horizon Violet',
      colors: {
        background: '#130f26',
        surface: '#1c1636',
        text: '#f6f4ff',
        accent: '#9a5be2',
        border: '#31244a',
      },
    },
    {
      id: 'kangur-horizon-amber',
      name: 'Horizon Amber',
      colors: {
        background: '#151018',
        surface: '#1f1824',
        text: '#f9f0e6',
        accent: '#ffb35c',
        border: '#35263a',
      },
    },
    {
      id: 'kangur-horizon-sky',
      name: 'Horizon Sky',
      colors: {
        background: '#0d1527',
        surface: '#15203a',
        text: '#f1f7ff',
        accent: '#4aa7ff',
        border: '#26314f',
      },
    },
  ],
  activeColorSchemeId: 'kangur-horizon-indigo',
  btnPrimaryBg: 'linear-gradient(135deg, #5f54d8 0%, #7c52ff 52%, #d17b49 100%)',
  btnPrimaryText: '#fdf7ff',
  btnSecondaryBg: 'rgba(16, 18, 35, 0.92)',
  btnSecondaryText: '#f6f4ff',
  btnOutlineBorder: '#2d314c',
  pillBg: 'rgba(19, 20, 39, 0.82)',
  pillText: '#d5cee8',
  pillActiveBg: 'rgba(41, 36, 76, 0.92)',
  pillActiveText: '#ffd27d',
  pillBorderColor: '#2d314c',
  inputBorderColor: '#2d314c',
  inputBg: '#121629',
  inputText: '#f6f4ff',
  inputFocusBorder: '#ffd27d',
  inputPlaceholder: '#9d96b7',
  cardColorScheme: 'kangur-horizon-indigo',
  cardBg: '#121626',
  collectionColorScheme: 'kangur-horizon-indigo',
  collectionOverlayColor: 'rgba(10, 12, 22, 0.62)',
  blogColorScheme: 'kangur-horizon-indigo',
  containerBg: '#121626',
  containerBorderColor: '#262b46',
  panelGradientStart: '#1b2039',
  panelGradientEnd: '#0d1022',
  navGradientStart: '#191d34',
  navGradientEnd: '#0b0f21',
  imageBorderColor: '#2b2f4b',
  imagePlaceholderBg: '#11162a',
  dropdownBg: '#161b32',
  dropdownBorder: '#2f3350',
  popupOverlayColor: 'rgba(8, 10, 20, 0.62)',
  drawerBg: '#14182d',
  drawerOverlayColor: 'rgba(8, 10, 20, 0.62)',
  drawerBorderColor: '#262b46',
  badgeDefaultBg: '#1b2036',
  badgeDefaultText: '#d6d0ee',
  badgeSaleColorScheme: 'kangur-horizon-amber',
  badgeSaleBg: '#ffd7b3',
  badgeSaleText: '#7a3b21',
  badgeSoldOutColorScheme: 'kangur-horizon-indigo',
  badgeSoldOutBg: '#131828',
  badgeSoldOutText: '#a6a1c2',
});

export const KANGUR_DEFAULT_SUNSET_THEME: ThemeSettings = KANGUR_SUNSET_THEME;
