import { PromptValidationRule } from '@/shared/contracts/prompt-engine';

import { createRegexRule, CASE_RESOLVER_PROMPT_EXPLODER_SCOPE } from './base';
import {
  CASE_RESOLVER_ADDRESSER_LABEL_PATTERN,
  CASE_RESOLVER_ADDRESSEE_LABEL_PATTERN,
  CASE_RESOLVER_PERSON_NAME_LINE_PATTERN,
  CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
  CASE_RESOLVER_ORGANIZATION_LINE_PATTERN,
  CASE_RESOLVER_ORGANIZATION_LINE_CAPTURE_PATTERN,
  CASE_RESOLVER_INLINE_ADDRESSER_LABEL_PATTERN,
  CASE_RESOLVER_INLINE_ADDRESSEE_LABEL_PATTERN,
} from './case-resolver-patterns';

export const CASE_RESOLVER_RULES: PromptValidationRule[] = [
  createRegexRule({
    id: 'segment.case_resolver.heading.place_date',
    title: 'Case Resolver Heading: Place + Date',
    description:
      'Detects a location-and-date heading line used in legal letters (for example: "Szczecin 25.01.2026").',
    pattern:
      '^\\\\s*[\\\\p{L}][\\\\p{L}\\\\s\\\\-.\x27\u2019]{1,60}?(?:,)?(?:\\\\s+dnia)?\\\\s+(?:\\\\d{1,2}[./-]\\\\d{1,2}[./-]\\\\d{2,4}|\\\\[(?:\\\\d{1,2}|DD)[./-](?:\\\\d{1,2}|MM)[./-](?:\\\\d{2,4}|YYYY|RRRR)\\\\])(?:\\\\s*r\\\\.?\\\\s*)?$',
    flags: 'imu',
    message: 'Place and date heading detected.',
    sequence: 35,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 42,
    promptExploderConfidenceBoost: 0.2,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.addresser_label',
    title: 'Case Resolver Heading: Addresser Label',
    description:
      'Detects labeled sender headings such as "From:" or "Nadawca:" and treats them as correspondence block boundaries.',
    pattern: `^\\\\s*${CASE_RESOLVER_ADDRESSER_LABEL_PATTERN}\\\\s*:\\\\s*(?:.+)?$`,
    flags: 'imu',
    message: 'Addresser label heading detected.',
    sequence: 36,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 47,
    promptExploderConfidenceBoost: 0.24,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.addresser_person',
    title: 'Case Resolver Heading: Addresser Person',
    description:
      'Detects sender person-name heading lines to split addresser blocks into a dedicated segment.',
    pattern: CASE_RESOLVER_PERSON_NAME_LINE_PATTERN,
    flags: 'imu',
    message: 'Addresser person heading detected.',
    sequence: 36,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 43,
    promptExploderConfidenceBoost: 0.2,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.addressee_label',
    title: 'Case Resolver Heading: Addressee Label',
    description:
      'Detects labeled recipient headings such as "To:" or "Adresat:" and treats them as correspondence block boundaries.',
    pattern: `^\\\\s*${CASE_RESOLVER_ADDRESSEE_LABEL_PATTERN}\\\\s*:\\\\s*(?:.+)?$`,
    flags: 'imu',
    message: 'Addressee label heading detected.',
    sequence: 36,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 48,
    promptExploderConfidenceBoost: 0.24,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.addressee_organization',
    title: 'Case Resolver Heading: Addressee Organization',
    description: 'Detects organization addressee heading lines in correspondence blocks.',
    pattern: CASE_RESOLVER_ORGANIZATION_LINE_PATTERN,
    flags: 'imu',
    message: 'Addressee organization heading detected.',
    sequence: 36,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 45,
    promptExploderConfidenceBoost: 0.22,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.not_heading.case_resolver.body_sentence',
    title: 'Not Heading: Case Resolver Body Sentence',
    description:
      'Prevents body/request sentence starters from being misclassified as heading boundaries.',
    pattern:
      '^\\\\s*(w\\\\s+związku\\\\s+z\\\\b|w\\\\s+zwiazku\\\\s+z\\\\b|biorąc\\\\s+pod\\\\s+uwagę\\\\b|biorac\\\\s+pod\\\\s+uwage\\\\b|ponadto\\\\b|jednocześnie\\\\b|jednoczesnie\\\\b).*$',
    flags: 'imu',
    message: 'Case Resolver body sentence detected (not a heading).',
    sequence: 37,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 48,
    promptExploderConfidenceBoost: 0.05,
    promptExploderTreatAsHeading: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.subject_or_section',
    title: 'Case Resolver Heading: Subject/Section',
    description: 'Detects common subject and section headings in legal document bodies.',
    pattern:
      '^\\\\s*(wniosek\\\\b|rezygnacja\\\\b|dotyczy\\\\b|uzasadnienie\\\\b|na\\\\s+zakończenie\\\\b|z\\\\s+poważaniem\\\\b|subject\\\\b|re:\\\\b|sincerely\\\\b|regards\\\\b).*$',
    flags: 'imu',
    message: 'Case Resolver subject/section heading detected.',
    sequence: 38,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 34,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.dotyczy',
    title: 'Case Resolver Heading: Dotyczy Subheading',
    description: 'Detects Dotyczy subheadings so they can be isolated as standalone segments.',
    pattern: '^\\\\s*dotyczy\\\\b.*$',
    flags: 'imu',
    message: 'Case Resolver Dotyczy subheading detected.',
    sequence: 38,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.body_statement',
    title: 'Case Resolver Heading: Body Statement Start',
    description:
      'Detects the opening body statement line (for example: "Niniejszym...") to keep subject/subheading lines separated as standalone segments.',
    pattern:
      '^\\\\s*(niniejszym\\\\b|działając\\\\b|dzialajac\\\\b|wnoszę\\\\b|wnosze\\\\b|zwracam\\\\s+się\\\\b|zwracam\\\\s+sie\\\\b|na\\\\s+podstawie\\\\s+art\\\\.?)',
    flags: 'imu',
    message: 'Case Resolver body statement start detected.',
    sequence: 39,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 33,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.heading.closing_statement',
    title: 'Case Resolver Heading: Closing Statement',
    description:
      'Detects closing/request headings such as "Na zakończenie..." or "Z poważaniem," so they can keep empty titles.',
    pattern:
      '^\\\\s*(na\\\\s+zakończenie\\\\b|na\\\\s+zakonczenie\\\\b|z\\\\s+poważaniem\\\\b|z\\\\s+powazaniem\\\\b|z\\\\s+wyrazami\\\\s+szacunku\\\\b|pozdrawiam\\\\b).*$',
    flags: 'imu',
    message: 'Case Resolver closing statement heading detected.',
    sequence: 40,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 39,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.place_date.city',
    title: 'Case Resolver Extract: Place Date City',
    description: 'Extracts city/place from a place+date line (for example: "Szczecin 25.01.2026").',
    pattern:
      '^\\\\s*([\\\\p{L}][\\\\p{L}\\\\s\\\\-.\x27\u2019]{1,60}?)(?:,)?\\\\s+(\\\\d{1,2})[./-](\\\\d{1,2})[./-](\\\\d{2,4})(?:\\\\s*r\\\\.?\\\\s*)?$',
    flags: 'imu',
    message: 'Case Resolver place/date city captured.',
    sequence: 38,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.18,
    promptExploderCaptureTarget: 'case_resolver.place_date.city',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.place_date.day',
    title: 'Case Resolver Extract: Place Date Day',
    description: 'Extracts day value from a place+date line.',
    pattern:
      '^\\\\s*([\\\\p{L}][\\\\p{L}\\\\s\\\\-.\x27\u2019]{1,60}?)(?:,)?\\\\s+(\\\\d{1,2})[./-](\\\\d{1,2})[./-](\\\\d{2,4})(?:\\\\s*r\\\\.?\\\\s*)?$',
    flags: 'imu',
    message: 'Case Resolver place/date day captured.',
    sequence: 39,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.18,
    promptExploderCaptureTarget: 'case_resolver.place_date.day',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'day',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.place_date.month',
    title: 'Case Resolver Extract: Place Date Month',
    description: 'Extracts month value from a place+date line.',
    pattern:
      '^\\\\s*([\\\\p{L}][\\\\p{L}\\\\s\\\\-.\x27\u2019]{1,60}?)(?:,)?\\\\s+(\\\\d{1,2})[./-](\\\\d{1,2})[./-](\\\\d{2,4})(?:\\\\s*r\\\\.?\\\\s*)?$',
    flags: 'imu',
    message: 'Case Resolver place/date month captured.',
    sequence: 40,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.18,
    promptExploderCaptureTarget: 'case_resolver.place_date.month',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'month',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.place_date.year',
    title: 'Case Resolver Extract: Place Date Year',
    description: 'Extracts year value from a place+date line.',
    pattern:
      '^\\\\s*([\\\\p{L}][\\\\p{L}\\\\s\\\\-.\x27\u2019]{1,60}?)(?:,)?\\\\s+(\\\\d{1,2})[./-](\\\\d{1,2})[./-](\\\\d{2,4})(?:\\\\s*r\\\\.?\\\\s*)?$',
    flags: 'imu',
    message: 'Case Resolver place/date year captured.',
    sequence: 41,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.18,
    promptExploderCaptureTarget: 'case_resolver.place_date.year',
    promptExploderCaptureGroup: 4,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'year',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.inline_first_name',
    title: 'Case Resolver Extract: Addresser Inline First Name',
    description:
      'Extracts sender first name from inline labeled lines such as "From: Michał Matynia".',
    pattern: CASE_RESOLVER_INLINE_ADDRESSER_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addresser first name captured.',
    sequence: 42,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.firstName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.inline_middle_name',
    title: 'Case Resolver Extract: Addresser Inline Middle Name',
    description: 'Extracts sender middle name from inline labeled lines when present.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSER_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addresser middle name captured.',
    sequence: 43,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.middleName',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.inline_last_name',
    title: 'Case Resolver Extract: Addresser Inline Last Name',
    description: 'Extracts sender last name from inline labeled lines.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSER_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addresser last name captured.',
    sequence: 44,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.lastName',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.first_name',
    title: 'Case Resolver Extract: Addresser First Name',
    description: 'Extracts addresser first name from a capitalized person name line.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addresser first name captured.',
    sequence: 42,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 26,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.firstName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.middle_name',
    title: 'Case Resolver Extract: Addresser Middle Name',
    description: 'Extracts addresser middle name from a capitalized person name line when present.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addresser middle name captured.',
    sequence: 43,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 26,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.middleName',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.last_name',
    title: 'Case Resolver Extract: Addresser Last Name',
    description: 'Extracts addresser last name from a capitalized person name line.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addresser last name captured.',
    sequence: 44,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 26,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addresser.lastName',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.inline_organization_name',
    title: 'Case Resolver Extract: Addresser Inline Display Name',
    description: 'Extracts sender display name from inline labeled lines.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSER_LABEL_PATTERN,
    flags: 'imu',
    message: 'Case Resolver inline addresser display name captured.',
    sequence: 45,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 26,
    promptExploderConfidenceBoost: 0.1,
    promptExploderCaptureTarget: 'case_resolver.addresser.displayName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addresser.organization_name',
    title: 'Case Resolver Extract: Addresser Organization Name',
    description: 'Extracts addresser organization/company name when sender is an institution.',
    pattern: CASE_RESOLVER_ORGANIZATION_LINE_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addresser organization captured.',
    sequence: 45,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 24,
    promptExploderConfidenceBoost: 0.1,
    promptExploderCaptureTarget: 'case_resolver.addresser.organizationName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.street',
    title: 'Case Resolver Extract: Address Street',
    description: 'Extracts street, street number, and house number from address lines.',
    pattern:
      '^\\\\s*(?:(?:ul\\\\.?|al\\\\.?|os\\\\.?|pl\\\\.?|aleja)\\\\s+)?([\\\\p{L}][\\\\p{L}\\\\s\x27\u2019.-]+?)\\\\s+(\\\\d+[A-Za-z]?)(?:\\\\s*\\\\/\\\\s*([0-9A-Za-z-]+))?\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address street captured.',
    sequence: 45,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.party.street',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.street_number',
    title: 'Case Resolver Extract: Address Street Number',
    description: 'Extracts street number from address lines.',
    pattern:
      '^\\\\s*(?:(?:ul\\\\.?|al\\\\.?|os\\\\.?|pl\\\\.?|aleja)\\\\s+)?([\\\\p{L}][\\\\p{L}\\\\s\x27\u2019.-]+?)\\\\s+(\\\\d+[A-Za-z]?)(?:\\\\s*\\\\/\\\\s*([0-9A-Za-z-]+))?\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address street number captured.',
    sequence: 46,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.party.streetNumber',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.house_number',
    title: 'Case Resolver Extract: Address House Number',
    description: 'Extracts house/unit number from address lines.',
    pattern:
      '^\\\\s*(?:(?:ul\\\\.?|al\\\\.?|os\\\\.?|pl\\\\.?|aleja)\\\\s+)?([\\\\p{L}][\\\\p{L}\\\\s\x27\u2019.-]+?)\\\\s+(\\\\d+[A-Za-z]?)(?:\\\\s*\\\\/\\\\s*([0-9A-Za-z-]+))?\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address house number captured.',
    sequence: 47,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.party.houseNumber',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.postal_code',
    title: 'Case Resolver Extract: Address Postal Code',
    description: 'Extracts postal code from postal-code and city lines.',
    pattern:
      '^\\\\s*(?:PL-)?(\\\\d{2}-\\\\d{3})\\\\s+([\\\\p{L}][\\\\p{L}\\\\s\x27\u2019.-]+)\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address postal code captured.',
    sequence: 48,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.party.postalCode',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.city',
    title: 'Case Resolver Extract: Address City',
    description: 'Extracts city from postal-code and city lines.',
    pattern:
      '^\\\\s*(?:PL-)?(\\\\d{2}-\\\\d{3})\\\\s+([\\\\p{L}][\\\\p{L}\\\\s\x27\u2019.-]+)\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address city captured.',
    sequence: 49,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.party.city',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.address.country',
    title: 'Case Resolver Extract: Address Country',
    description: 'Extracts country from standalone country lines (Polish and English names).',
    pattern:
      '^\\\\s*(polska|poland|niemcy|germany|deutschland|francja|france|hiszpania|spain|włochy|wlochy|italy|uk|united\\\\s+kingdom|wielka\\\\s+brytania|usa|u\\\\.s\\\\.a\\\\.|stany\\\\s+zjednoczone)\\\\s*$',
    flags: 'imu',
    message: 'Case Resolver address country captured.',
    sequence: 51,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 24,
    promptExploderConfidenceBoost: 0.08,
    promptExploderCaptureTarget: 'case_resolver.party.country',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'country',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.inline_first_name',
    title: 'Case Resolver Extract: Addressee Inline First Name',
    description:
      'Extracts recipient first name from inline labeled lines such as "To: Jan Kowalski".',
    pattern: CASE_RESOLVER_INLINE_ADDRESSEE_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addressee first name captured.',
    sequence: 52,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.firstName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.inline_middle_name',
    title: 'Case Resolver Extract: Addressee Inline Middle Name',
    description: 'Extracts recipient middle name from inline labeled lines when present.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSEE_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addressee middle name captured.',
    sequence: 53,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.middleName',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.inline_last_name',
    title: 'Case Resolver Extract: Addressee Inline Last Name',
    description: 'Extracts recipient last name from inline labeled lines.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSEE_LABEL_PATTERN.replace(
      '(.+?)',
      '([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)(?:\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+(?:\\\\s+[\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+){0,2}))?\\\\s+([\\\\p{Lu}][\\\\p{L}\x27\u2019.-]+)'
    ),
    flags: 'imu',
    message: 'Case Resolver inline addressee last name captured.',
    sequence: 54,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.lastName',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.first_name',
    title: 'Case Resolver Extract: Addressee First Name',
    description: 'Extracts addressee first name from a capitalized person name line.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addressee first name captured.',
    sequence: 55,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.firstName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.middle_name',
    title: 'Case Resolver Extract: Addressee Middle Name',
    description: 'Extracts addressee middle name from a capitalized person name line when present.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addressee middle name captured.',
    sequence: 56,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.middleName',
    promptExploderCaptureGroup: 2,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.last_name',
    title: 'Case Resolver Extract: Addressee Last Name',
    description: 'Extracts addressee last name from a capitalized person name line.',
    pattern: CASE_RESOLVER_PERSON_NAME_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addressee last name captured.',
    sequence: 57,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.12,
    promptExploderCaptureTarget: 'case_resolver.addressee.lastName',
    promptExploderCaptureGroup: 3,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.inline_organization_name',
    title: 'Case Resolver Extract: Addressee Inline Display Name',
    description: 'Extracts recipient display name from inline labeled lines.',
    pattern: CASE_RESOLVER_INLINE_ADDRESSEE_LABEL_PATTERN,
    flags: 'imu',
    message: 'Case Resolver inline addressee display name captured.',
    sequence: 58,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 36,
    promptExploderConfidenceBoost: 0.14,
    promptExploderCaptureTarget: 'case_resolver.addressee.displayName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
  createRegexRule({
    id: 'segment.case_resolver.extract.addressee.organization_name',
    title: 'Case Resolver Extract: Addressee Organization Name',
    description: 'Extracts addressee organization/company name.',
    pattern: CASE_RESOLVER_ORGANIZATION_LINE_CAPTURE_PATTERN,
    flags: 'imu',
    message: 'Case Resolver addressee organization captured.',
    sequence: 52,
    sequenceGroupId: 'case_resolver_structure',
    sequenceGroupLabel: 'Case Resolver Structure',
    promptExploderPriority: 34,
    promptExploderConfidenceBoost: 0.14,
    promptExploderCaptureTarget: 'case_resolver.addressee.organizationName',
    promptExploderCaptureGroup: 1,
    promptExploderCaptureApplyTo: 'line',
    promptExploderCaptureNormalize: 'trim',
    promptExploderCaptureOverwrite: false,
    appliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
    launchAppliesToScopes: [...CASE_RESOLVER_PROMPT_EXPLODER_SCOPE],
  }),
];
