import { type PromptValidationRule } from '@/shared/contracts/prompt-engine';

import { createRegexRule } from './base';

export const EXPLODER_RULES: PromptValidationRule[] = [
  createRegexRule({
    id: 'segment.metadata.banner',
    title: 'Metadata Banner',
    description: 'Recognizes versioned metadata banners framed by ===.',
    pattern: '^\\\\s*={3,}.+={3,}\\\\s*$',
    flags: 'm',
    message: 'Metadata banner section detected.',
    sequence: 10,
    sequenceGroupId: 'exploder_metadata',
    sequenceGroupLabel: 'Exploder Metadata',
    promptExploderSegmentType: 'metadata',
    promptExploderPriority: 40,
    promptExploderConfidenceBoost: 0.2,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.metadata.pipe_header',
    title: 'Metadata Pipe Header',
    description: 'Detects first-line pipe-delimited product metadata.',
    pattern: '^\\\\s*[^|\\\\n]+(?:\\\\s*\\\\|\\\\s*[^|\\\\n]+){2,}\\\\s*$',
    flags: 'm',
    message: 'Pipe metadata header detected.',
    sequence: 15,
    sequenceGroupId: 'exploder_metadata',
    sequenceGroupLabel: 'Exploder Metadata',
    promptExploderSegmentType: 'metadata',
    promptExploderPriority: 30,
    promptExploderConfidenceBoost: 0.18,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.heading.block',
    title: 'Section Heading',
    description: 'Detects uppercase section headings.',
    pattern: '^\\\\s*[A-Z][A-Z0-9 _()\\\\-/:&+.,]{3,}\\\\s*$',
    flags: 'm',
    message: 'Section heading detected.',
    sequence: 20,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.heading.markdown',
    title: 'Markdown Heading',
    description: 'Detects markdown section headings (## ROLE, ### ProductRecord).',
    pattern: '^\\\\s*#{1,6}\\\\s+\\\\S+',
    flags: 'm',
    message: 'Markdown heading detected.',
    sequence: 22,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.heading.bracket',
    title: 'Bracket Heading',
    description: 'Detects bracketed module headings ([PURPOSE], [MODULES], [VALIDATION_MODULE]).',
    pattern: '^\\\\s*\\\\[[A-Z0-9 _()\\\\-/:&+.,]{2,}]\\\\s*$',
    flags: 'm',
    message: 'Bracket heading detected.',
    sequence: 24,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.heading.numeric_section',
    title: 'Numeric Section Heading',
    description: 'Detects numbered section headings like "1. Preserve the Product Exactly".',
    pattern: '^\\\\s*\\\\d+\\\\.\\\\s+[A-Z][^\\\\n.:]{4,}$',
    flags: 'm',
    message: 'Numeric section heading detected.',
    sequence: 26,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 18,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.not_heading.rule_line',
    title: 'Not Heading: Rule Continuation',
    description:
      'Prevents indented/list continuation lines that begin with "Rule:" from being interpreted as headings.',
    pattern: '^\\\\s*Rule\\\\s*:\\\\s+.+$',
    flags: 'mi',
    message: 'Rule continuation line detected (not a heading).',
    sequence: 26,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderPriority: 35,
    promptExploderConfidenceBoost: 0.05,
    promptExploderTreatAsHeading: false,
  }),
  createRegexRule({
    id: 'segment.subsection.alpha_heading',
    title: 'Subsection: Alpha Heading',
    description: 'Detects A) / B) style subsection headings inside sequence segments.',
    pattern: '^\\\\s*([A-Z])\\\\)\\\\s+(.+)$',
    flags: 'm',
    message: 'Alpha subsection heading detected.',
    sequence: 27,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 16,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.reference_named',
    title: 'Subsection: Named Reference Header',
    description:
      'Detects RL/P/QA subsection headers with named bracket labels (e.g. RL0 (Mandatory): ...).',
    pattern: '^\\\\s*(RL\\\\d+|P\\\\d+|QA(?:_R)?\\\\d+)\\\\s+\\\\(([^)]+)\\\\)\\\\s*:\\\\s*(.*)$',
    flags: 'mi',
    message: 'Named reference subsection heading detected.',
    sequence: 31,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 20,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.reference_plain',
    title: 'Subsection: Plain Reference Header',
    description: 'Detects RL/P/QA subsection headers without bracket labels.',
    pattern: '^\\\\s*(RL\\\\d+|P\\\\d+|QA(?:_R)?\\\\d+)\\\\b\\\\s*[—:-]?\\\\s*(.*)$',
    flags: 'mi',
    message: 'Plain reference subsection heading detected.',
    sequence: 32,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'referential_list',
    promptExploderPriority: 18,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.qa_code',
    title: 'Subsection: QA Code Header',
    description: 'Detects QA/QA_R subsection rows for QA matrix parsing.',
    pattern: '^\\\\s*(QA(?:_R)?\\\\d+)\\\\b\\\\s*[—:-]?\\\\s*(.*)$',
    flags: 'mi',
    message: 'QA subsection heading detected.',
    sequence: 33,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'qa_matrix',
    promptExploderPriority: 19,
    promptExploderConfidenceBoost: 0.11,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.numeric_bracket_heading',
    title: 'Subsection: Numeric Bracket Heading',
    description: 'Detects numeric-bracket subsection headings like `1. [PURPOSE]`.',
    pattern: '^\\\\s*\\\\d+\\\\.\\\\s+\\\\[([A-Z0-9 _()\\\\-/:&+.,]{2,})]$',
    flags: 'm',
    message: 'Numeric bracket subsection heading detected.',
    sequence: 34,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 17,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.bracket_heading',
    title: 'Subsection: Bracket Heading',
    description: 'Detects bracket subsection headings like `[PURPOSE]`.',
    pattern: '^\\\\s*\\\\[([A-Z0-9 _()\\\\-/:&+.,]{2,})]$',
    flags: 'm',
    message: 'Bracket subsection heading detected.',
    sequence: 35,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 17,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.subsection.markdown_heading',
    title: 'Subsection: Markdown Heading',
    description: 'Detects markdown subsection headings like `### Details`.',
    pattern: '^\\\\s*#{1,6}\\\\s+(.+)$',
    flags: 'm',
    message: 'Markdown subsection heading detected.',
    sequence: 36,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 17,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.boundary.requirements',
    title: 'Boundary: Requirements',
    description:
      'Defines section headings treated as requirements sequences (default: REQUIREMENTS / COMPOSITING REQUIREMENTS).',
    pattern: '^\\\\s*(REQUIREMENTS|COMPOSITING\\\\s+REQUIREMENTS)\\\\b',
    flags: 'mi',
    message: 'Requirements boundary heading detected.',
    sequence: 28,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 24,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.boundary.studio_relighting',
    title: 'Boundary: Studio Relighting',
    description: 'Defines headings that start the studio relighting extension section.',
    pattern: '^(\\\\s*===\\\\s*STUDIO\\\\s+RELIGHTING|\\\\s*STUDIO\\\\s+RELIGHTING\\\\b)',
    flags: 'mi',
    message: 'Studio relighting boundary heading detected.',
    sequence: 29,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 24,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.boundary.pipeline',
    title: 'Boundary: Pipeline',
    description: 'Defines headings that should be parsed as hierarchical process lists.',
    pattern: '^\\\\s*(PIPELINE|WORKFLOW|PROCESS|EXECUTION\\\\s+TEMPLATE)\\\\b',
    flags: 'mi',
    message: 'Pipeline boundary heading detected.',
    sequence: 30,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'hierarchical_list',
    promptExploderPriority: 25,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.boundary.final_qa',
    title: 'Boundary: Final QA',
    description: 'Defines headings that should open QA matrix parsing.',
    pattern: '^\\\\s*FINAL\\\\s+QA\\\\b',
    flags: 'mi',
    message: 'Final QA boundary heading detected.',
    sequence: 34,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'qa_matrix',
    promptExploderPriority: 25,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
];
