import { PromptValidationRule } from '@/shared/contracts/prompt-engine';

import { createRegexRule } from './base';

export const OTHER_RULES: PromptValidationRule[] = [
  createRegexRule({
    id: 'segment.params.block',
    title: 'Parameters Block',
    description: 'Detects params assignment block.',
    pattern: '\\\\bparams\\\\s*=\\\\s*\\\\{',
    flags: 'mi',
    message: 'Parameters block detected.',
    sequence: 30,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'parameter_block',
    promptExploderPriority: 35,
    promptExploderConfidenceBoost: 0.2,
  }),
  createRegexRule({
    id: 'segment.params.global_settings',
    title: 'Global Settings Block',
    description: 'Detects GLOBAL_SETTINGS blocks and key-value setting lists.',
    pattern:
      '(\\\\[GLOBAL_SETTINGS\\\\]|GLOBAL[_\\\\s]SETTINGS)\\\\b[\\\\s\\\\S]{0,220}(\\\\[[A-Z_]+\\\\]\\\\s*=\\\\s*`?|\\\\[DRY_RUN\\\\]\\\\s*=)',
    flags: 'mi',
    message: 'Global settings block detected.',
    sequence: 34,
    sequenceGroupId: 'exploder_structure',
    sequenceGroupLabel: 'Exploder Structure',
    promptExploderSegmentType: 'parameter_block',
    promptExploderPriority: 28,
    promptExploderConfidenceBoost: 0.16,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.list.numeric',
    title: 'Numeric List',
    description: 'Detects numeric lists with 1) or 1. prefixes.',
    pattern: '^\\\\s*\\\\d+[.)]\\\\s+',
    flags: 'm',
    message: 'Numeric list detected.',
    sequence: 40,
    sequenceGroupId: 'exploder_lists',
    sequenceGroupLabel: 'Exploder Lists',
    promptExploderSegmentType: 'list',
    promptExploderPriority: 4,
  }),
  createRegexRule({
    id: 'segment.list.bullet',
    title: 'Bullet List',
    description: 'Detects bullet lists with * or - markers.',
    pattern: '^\\\\s*[*-]\\\\s+',
    flags: 'm',
    message: 'Bullet list detected.',
    sequence: 50,
    sequenceGroupId: 'exploder_lists',
    sequenceGroupLabel: 'Exploder Lists',
    promptExploderSegmentType: 'list',
    promptExploderPriority: 4,
  }),
  createRegexRule({
    id: 'segment.list.alpha_sequence',
    title: 'Alpha Sequence',
    description: 'Detects A) B) C) sequence headers.',
    pattern: '^\\\\s*[A-Z]\\\\)\\\\s+.+$',
    flags: 'm',
    message: 'Alpha sequence section detected.',
    sequence: 60,
    sequenceGroupId: 'exploder_lists',
    sequenceGroupLabel: 'Exploder Lists',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 10,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.reference.code',
    title: 'Reference Code',
    description: 'Detects referential section codes like P0, RL2, QA_R1.',
    pattern: '^\\\\s*(P\\\\d+|RL\\\\d+|QA(?:_R)?\\\\d+)\\\\b',
    flags: 'i',
    message: 'Reference code section detected.',
    sequence: 70,
    sequenceGroupId: 'exploder_references',
    sequenceGroupLabel: 'Exploder References',
    promptExploderSegmentType: 'referential_list',
    promptExploderPriority: 8,
    promptExploderConfidenceBoost: 0.04,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.conditional.only_if',
    title: 'Conditional: only if',
    description: 'Detects conditional blocks using “only if”.',
    pattern: '\\\\bonly if\\\\b',
    flags: 'mi',
    message: 'Conditional (only if) detected.',
    sequence: 80,
    sequenceGroupId: 'exploder_conditionals',
    sequenceGroupLabel: 'Exploder Conditionals',
    promptExploderSegmentType: 'conditional_list',
    promptExploderPriority: 12,
    promptExploderConfidenceBoost: 0.08,
  }),
  createRegexRule({
    id: 'segment.conditional.fix_until',
    title: 'Conditional: fix until',
    description: 'Detects iterative pass/fail constraints.',
    pattern: '\\\\bfix\\\\s+until\\\\b',
    flags: 'mi',
    message: 'Fix-until conditional detected.',
    sequence: 90,
    sequenceGroupId: 'exploder_conditionals',
    sequenceGroupLabel: 'Exploder Conditionals',
    promptExploderSegmentType: 'conditional_list',
    promptExploderPriority: 12,
    promptExploderConfidenceBoost: 0.08,
  }),
  createRegexRule({
    id: 'segment.pipeline.step',
    title: 'Pipeline Steps',
    description: 'Detects pipeline steps by ordered numbers.',
    pattern: '^\\\\s*\\\\d+\\\\.\\\\s+',
    flags: 'm',
    message: 'Pipeline step detected.',
    sequence: 100,
    sequenceGroupId: 'exploder_pipeline',
    sequenceGroupLabel: 'Exploder Pipeline',
    promptExploderSegmentType: 'hierarchical_list',
    promptExploderPriority: 14,
    promptExploderConfidenceBoost: 0.08,
  }),
  createRegexRule({
    id: 'segment.comment.patch',
    title: 'Patch Comment',
    description: 'Detects in-prompt patch comments.',
    pattern: '^\\\\s*//\\\\s*PATCH\\\\b',
    flags: 'mi',
    message: 'Patch comment detected.',
    sequence: 110,
    sequenceGroupId: 'exploder_metadata',
    sequenceGroupLabel: 'Exploder Metadata',
    promptExploderSegmentType: 'metadata',
    promptExploderPriority: 6,
    promptExploderConfidenceBoost: 0.04,
  }),
  createRegexRule({
    id: 'segment.infer.list.non_negotiable',
    title: 'Infer List: Non-negotiable',
    description: 'Recognizes non-negotiable requirement list headings.',
    pattern: '^\\\\s*NON[-\\\\s]?NEGOTIABLE\\\\s+GOAL\\\\b',
    flags: 'mi',
    message: 'Likely non-negotiable list segment.',
    sequence: 120,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'list',
    promptExploderPriority: 20,
    promptExploderConfidenceBoost: 0.12,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.parameter_block.params_heading',
    title: 'Infer Parameter Block',
    description: 'Recognizes parameter heading variants tied to params object.',
    pattern:
      '^\\\\s*(PARAMS|PARAMETERS|CONFIG)\\\\b[\\\\s\\\\S]{0,220}\\\\bparams\\\\s*=\\\\s*\\\\{',
    flags: 'mi',
    message: 'Likely parameter block segment.',
    sequence: 130,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'parameter_block',
    promptExploderPriority: 24,
    promptExploderConfidenceBoost: 0.14,
    promptExploderTreatAsHeading: true,
  }),
  createRegexRule({
    id: 'segment.infer.sequence.requirements',
    title: 'Infer Sequence: Requirements',
    description: 'Recognizes requirements-like sequence blocks.',
    pattern: '^\\\\s*(REQUIREMENTS|GUIDELINES|CONSTRAINTS|RULESET)\\\\b',
    flags: 'mi',
    message: 'Likely sequence segment.',
    sequence: 140,
    sequenceGroupId: 'exploder_infer',
    sequenceGroupLabel: 'Exploder Inference',
    promptExploderSegmentType: 'sequence',
    promptExploderPriority: 16,
    promptExploderConfidenceBoost: 0.1,
    promptExploderTreatAsHeading: true,
  }),
];
