import type { LabeledOptionDto } from '@/shared/contracts/base';
import type { KangurStorefrontAppearanceMode } from '@/features/kangur/storefront-appearance-settings';
import type { KangurAdminLocaleDto as AppearanceAdminLocale } from '../kangur-admin-locale';

type AppearanceCatalogSortOption =
  | 'created-desc'
  | 'created-asc'
  | 'updated-desc'
  | 'name-asc'
  | 'name-desc';

export const PAGE_COPY = {
  en: {
    breadcrumbs: ['Admin', 'Kangur', 'Settings', 'Appearance'],
    shellTitle: 'Kangur Appearance',
    shellDescription: 'Focused editing shell for lessons, tests, and content operations.',
    backToSettings: 'Back to Settings',
    saveTheme: 'Save theme',
    saving: 'Saving...',
    selectedTheme: 'Selected theme',
    selectedThemeAria: 'Selected theme',
    unsavedChanges: 'Unsaved changes',
    assignThemeToSlot: (themeName: string) => `Assign theme "${themeName}" to a slot`,
    presetReadOnly:
      'This Crystal preset is read-only, but you can still assign it to a slot above.',
    factoryReadOnly: 'This is a factory Kangur theme. It is read-only.',
    restoreDefaults: 'Restore defaults',
    statusTitle: 'Status',
    statusBadges: {
      readOnly: 'Read only',
      unsaved: 'Unsaved changes',
      saved: 'Saved',
    },
    statusItems: {
      theme: 'Theme',
      type: 'Type',
      assignedSlots: 'Assigned slots',
    },
    themeTypes: {
      factory: 'Factory',
      preset: 'Preset',
      builtin: 'Built-in',
      custom: 'Custom',
    },
    notAssigned: 'Not assigned',
  },
  pl: {
    breadcrumbs: ['Admin', 'Kangur', 'Ustawienia', 'Wygląd'],
    shellTitle: 'Wygląd Kangur',
    shellDescription: 'Skupiony panel edycji dla lekcji, testów i operacji na treści.',
    backToSettings: 'Wróć do ustawień',
    saveTheme: 'Zapisz motyw',
    saving: 'Zapisuje...',
    selectedTheme: 'Wybrany motyw',
    selectedThemeAria: 'Wybrany motyw',
    unsavedChanges: 'Niezapisane zmiany',
    assignThemeToSlot: (themeName: string) => `Przypisz motyw "${themeName}" do slotu`,
    presetReadOnly:
      'To preset Crystal. Jest tylko do odczytu, ale nadal możesz przypisać go do slotu powyżej.',
    factoryReadOnly: 'To fabryczny motyw Kangura. Jest tylko do odczytu.',
    restoreDefaults: 'Przywróć domyślne',
    statusTitle: 'Status',
    statusBadges: {
      readOnly: 'Tylko odczyt',
      unsaved: 'Niezapisane zmiany',
      saved: 'Zapisano',
    },
    statusItems: {
      theme: 'Motyw',
      type: 'Typ',
      assignedSlots: 'Przypisane sloty',
    },
    themeTypes: {
      factory: 'Fabryczny',
      preset: 'Preset',
      builtin: 'Wbudowany',
      custom: 'Wlasny',
    },
    notAssigned: 'Nieprzypisany',
  },
  uk: {
    breadcrumbs: ['Admin', 'Kangur', 'Налаштування', 'Вигляд'],
    shellTitle: 'Вигляд Kangur',
    shellDescription: 'Зосереджена панель редагування для уроків, тестів і операцій із вмістом.',
    backToSettings: 'Повернутися до налаштувань',
    saveTheme: 'Зберегти тему',
    saving: 'Зберігаю...',
    selectedTheme: 'Вибрана тема',
    selectedThemeAria: 'Вибрана тема',
    unsavedChanges: 'Незбережені зміни',
    assignThemeToSlot: (themeName: string) => `Призначити тему "${themeName}" до слоту`,
    presetReadOnly:
      'Цей пресет Crystal доступний лише для читання, але ви все одно можете призначити його до слоту вище.',
    factoryReadOnly: 'Це фабрична тема Kangur. Вона доступна лише для читання.',
    restoreDefaults: 'Відновити типові',
    statusTitle: 'Статус',
    statusBadges: {
      readOnly: 'Лише читання',
      unsaved: 'Незбережені зміни',
      saved: 'Збережено',
    },
    statusItems: {
      theme: 'Тема',
      type: 'Тип',
      assignedSlots: 'Призначені слоти',
    },
    themeTypes: {
      factory: 'Фабрична',
      preset: 'Пресет',
      builtin: 'Вбудована',
      custom: 'Власна',
    },
    notAssigned: 'Не призначено',
  },
} as const;

export const MODE_SELECTOR_COPY = {
  en: {
    title: 'Startup system',
    description:
      'Choose which visual system (light or dark) should load by default when the app starts.',
    selectAriaLabel: 'Select startup appearance mode',
  },
  pl: {
    title: 'System startowy',
    description:
      'Wybierz, który system wizualny (jasny lub ciemny) ma być ładowany domyślnie przy starcie aplikacji.',
    selectAriaLabel: 'Wybierz startowy tryb wyglądu',
  },
  uk: {
    title: 'Стартова система',
    description:
      'Виберіть, яку візуальну систему (світлу чи темну) потрібно завантажувати за замовчуванням під час запуску застосунку.',
    selectAriaLabel: 'Виберіть стартовий режим вигляду',
  },
} as const;

export const MODE_OPTION_LABELS: Record<
  AppearanceAdminLocale,
  Record<KangurStorefrontAppearanceMode, string>
> = {
  en: {
    default: 'Daily theme',
    dawn: 'Dawn theme',
    sunset: 'Sunset theme',
    dark: 'Night theme',
  },
  pl: {
    default: 'Motyw dzienny',
    dawn: 'Motyw świtowy',
    sunset: 'Motyw zachodu',
    dark: 'Motyw nocny',
  },
  uk: {
    default: 'Денна тема',
    dawn: 'Світанкова тема',
    sunset: 'Тема заходу',
    dark: 'Нічна тема',
  },
};

export const IMPORT_EXPORT_COPY = {
  en: {
    title: 'Import / Export',
    description: 'Move theme configuration between environments with the clipboard.',
    exportButton: 'Export to clipboard',
    importButton: 'Import from clipboard',
    exportError: 'Failed to copy the configuration.',
    exportSuccess: 'Theme configuration copied to the clipboard.',
    importError: 'Invalid clipboard data format.',
    importSuccess: 'Theme loaded from the clipboard. Remember to save your changes.',
  },
  pl: {
    title: 'Import / Eksport',
    description: 'Przenoś konfiguracje motywu między środowiskami za pomocą schowka.',
    exportButton: 'Eksportuj do schowka',
    importButton: 'Importuj ze schowka',
    exportError: 'Nie udało się skopiować konfiguracji.',
    exportSuccess: 'Konfiguracja motywu skopiowana do schowka.',
    importError: 'Nieprawidłowy format danych w schowku.',
    importSuccess: 'Motyw wczytany ze schowka. Pamiętaj o zapisaniu zmian.',
  },
  uk: {
    title: 'Імпорт / Експорт',
    description: 'Переносьте конфігурації тем між середовищами за допомогою буфера обміну.',
    exportButton: 'Експортувати в буфер обміну',
    importButton: 'Імпортувати з буфера обміну',
    exportError: 'Не вдалося скопіювати конфігурацію.',
    exportSuccess: 'Конфігурацію теми скопійовано в буфер обміну.',
    importError: 'Неправильний формат даних у буфері обміну.',
    importSuccess: 'Тему завантажено з буфера обміну. Не забудьте зберегти зміни.',
  },
} as const;

export const THEME_CATALOG_COPY = {
  en: {
    openButton: (count: number) => `Theme catalog (${count})`,
    modalTitle: 'Saved theme catalog',
    saveCurrentAsNew: 'Save current theme as new',
    themeNamePlaceholder: 'Theme name...',
    themeNameAria: 'Theme name',
    save: 'Save',
    filterCatalog: 'Filter catalog',
    searchPlaceholder: 'Search themes by name...',
    searchAria: 'Filter themes in the catalog',
    sortLabel: 'Sorting',
    sortAria: 'Theme catalog sorting',
    countSummary: (visible: number, total: number) => `Showing ${visible} of ${total} themes`,
    defaultSortHint: 'Default: newest themes first',
    savedBadge: 'Saved',
    createdLabel: 'Created',
    updatedLabel: 'Updated',
    selected: 'Selected',
    load: 'Load',
    duplicating: 'Duplicating...',
    duplicate: 'Duplicate',
    deleteAria: 'Delete theme from catalog',
    emptyCatalog: 'No saved themes in the catalog.',
    emptyFilters: 'No themes match the current filters.',
    noDate: 'no date',
    createDefaultName: 'New theme',
    duplicateSuffix: 'copy',
    createError: 'Theme save failed.',
    createSuccess: 'New theme was added to the catalog.',
    duplicateError: 'Failed to duplicate the theme.',
    duplicateSuccess: 'Theme duplicated.',
    deleteError: 'Theme deletion failed.',
    deleteSuccess: 'Theme removed.',
    confirmDelete: 'Are you sure you want to remove this theme from the catalog?',
    sortOptions: [
      { value: 'created-desc', label: 'Newest' },
      { value: 'created-asc', label: 'Oldest' },
      { value: 'updated-desc', label: 'Recently updated' },
      { value: 'name-asc', label: 'Name A-Z' },
      { value: 'name-desc', label: 'Name Z-A' },
    ] as const satisfies ReadonlyArray<LabeledOptionDto<AppearanceCatalogSortOption>>,
    dateLocale: 'en-US',
    compareLocale: 'en',
  },
  pl: {
    openButton: (count: number) => `Katalog motywów (${count})`,
    modalTitle: 'Katalog zapisanych motywów',
    saveCurrentAsNew: 'Zapisz aktualny motyw jako nowy',
    themeNamePlaceholder: 'Nazwa motywu...',
    themeNameAria: 'Nazwa motywu',
    save: 'Zapisz',
    filterCatalog: 'Filtruj katalog',
    searchPlaceholder: 'Szukaj motywu po nazwie...',
    searchAria: 'Filtruj motywy w katalogu',
    sortLabel: 'Sortowanie',
    sortAria: 'Sortowanie katalogu motywów',
    countSummary: (visible: number, total: number) => `Pokazano ${visible} z ${total} motywów`,
    defaultSortHint: 'Domyślnie: najnowsze motywy na górze',
    savedBadge: 'Zapisany',
    createdLabel: 'Utworzono',
    updatedLabel: 'Zaktualizowano',
    selected: 'Wybrany',
    load: 'Wczytaj',
    duplicating: 'Duplikuję...',
    duplicate: 'Duplikuj',
    deleteAria: 'Usuń motyw z katalogu',
    emptyCatalog: 'Brak zapisanych motywów w katalogu.',
    emptyFilters: 'Brak motywów pasujących do bieżących filtrów.',
    noDate: 'brak daty',
    createDefaultName: 'Nowy motyw',
    duplicateSuffix: 'kopia',
    createError: 'Błąd zapisu motywu.',
    createSuccess: 'Nowy motyw został dodany do katalogu.',
    duplicateError: 'Nie udało się zduplikować motywu.',
    duplicateSuccess: 'Motyw został zduplikowany.',
    deleteError: 'Błąd usuwania motywu.',
    deleteSuccess: 'Motyw został usunięty.',
    confirmDelete: 'Czy na pewno chcesz usunąć ten motyw z katalogu?',
    sortOptions: [
      { value: 'created-desc', label: 'Najnowsze' },
      { value: 'created-asc', label: 'Najstarsze' },
      { value: 'updated-desc', label: 'Ostatnio zaktualizowane' },
      { value: 'name-asc', label: 'Nazwa A-Z' },
      { value: 'name-desc', label: 'Nazwa Z-A' },
    ] as const satisfies ReadonlyArray<LabeledOptionDto<AppearanceCatalogSortOption>>,
    dateLocale: 'pl-PL',
    compareLocale: 'pl',
  },
  uk: {
    openButton: (count: number) => `Каталог тем (${count})`,
    modalTitle: 'Каталог збережених тем',
    saveCurrentAsNew: 'Зберегти поточну тему як нову',
    themeNamePlaceholder: 'Назва теми...',
    themeNameAria: 'Назва теми',
    save: 'Зберегти',
    filterCatalog: 'Фільтрувати каталог',
    searchPlaceholder: 'Шукати тему за назвою...',
    searchAria: 'Фільтрувати теми в каталозі',
    sortLabel: 'Сортування',
    sortAria: 'Сортування каталогу тем',
    countSummary: (visible: number, total: number) => `Показано ${visible} з ${total} тем`,
    defaultSortHint: 'За замовчуванням: новіші теми зверху',
    savedBadge: 'Збережена',
    createdLabel: 'Створено',
    updatedLabel: 'Оновлено',
    selected: 'Вибрана',
    load: 'Завантажити',
    duplicating: 'Дублюю...',
    duplicate: 'Дублювати',
    deleteAria: 'Видалити тему з каталогу',
    emptyCatalog: 'У каталозі немає збережених тем.',
    emptyFilters: 'Немає тем, що відповідають поточним фільтрам.',
    noDate: 'немає дати',
    createDefaultName: 'Нова тема',
    duplicateSuffix: 'копія',
    createError: 'Не вдалося зберегти тему.',
    createSuccess: 'Нову тему додано до каталогу.',
    duplicateError: 'Не вдалося дублювати тему.',
    duplicateSuccess: 'Тему дубльовано.',
    deleteError: 'Не вдалося видалити тему.',
    deleteSuccess: 'Тему видалено.',
    confirmDelete: 'Ви впевнені, що хочете видалити цю тему з каталогу?',
    sortOptions: [
      { value: 'created-desc', label: 'Найновіші' },
      { value: 'created-asc', label: 'Найстаріші' },
      { value: 'updated-desc', label: 'Нещодавно оновлені' },
      { value: 'name-asc', label: 'Назва A-Z' },
      { value: 'name-desc', label: 'Назва Z-A' },
    ] as const satisfies ReadonlyArray<LabeledOptionDto<AppearanceCatalogSortOption>>,
    dateLocale: 'uk-UA',
    compareLocale: 'uk',
  },
} as const;

export const PREVIEW_COPY = {
  en: {
    targetLabels: {
      current: 'Preview',
      daily: 'Day',
      dawn: 'Dawn',
      sunset: 'Sunset',
      nightly: 'Night',
    },
    groupAriaLabel: 'Theme preview',
    sectionLabels: {
      page: 'Page and Navigation',
      buttons: 'Buttons',
      cards: 'Cards and Inputs',
      colors: 'Colors and Gradients',
      chat: 'Chat',
      components: 'Components',
    },
    navItems: ['Courses', 'Results', 'Profile'],
    homeActions: [
      { id: 'lessons', label: 'Lessons', emoji: '\ud83d\udcda' },
      { id: 'play', label: 'Play', emoji: '\ud83c\udfae' },
      { id: 'training', label: 'Training', emoji: '\ud83c\udfc6' },
      { id: 'kangur', label: 'Kangur', emoji: '\ud83e\udd98' },
    ],
    pageHeading: 'Alphabet - age 6',
    pageSubtext: 'Letters, syllables, and first words.',
    buttonLabels: {
      primary: 'Primary',
      hover: 'Hover',
      secondary: 'Secondary',
      surface: 'Surface',
      warning: 'Warning',
      success: 'Success',
    },
    lessonTitle: 'Lesson 3 - Fractions',
    lessonMeta: '12 exercises · 45 min',
    continueLabel: 'Continue',
    resultsLabel: 'Results',
    searchPlaceholder: 'Search exercise...',
    studentOneName: 'Anna Kowalska',
    studentOneMeta: 'Progress: 74% · #12 in class',
    studentTwoName: 'Jan Nowak',
    studentTwoMeta: '1,240 pts',
    profileLabel: 'Profile',
    dropdownItems: ['Common fractions', 'Decimal fractions', 'Percentages'],
    accentGradientsLabel: 'Accent Gradients',
    accentGradientNames: ['Indigo', 'Violet', 'Emerald', 'Sky', 'Amber', 'Rose', 'Teal', 'Slate'],
    logoPaletteLabel: 'Logo Palette',
    logoPaletteNames: ['Word Start', 'Word Mid', 'Word End', 'Ring Start', 'Ring End', 'Accent Start', 'Accent End'],
    badgesLabel: 'Badges',
    badges: ['New', '-20%', 'Done', 'Important', 'Info', 'VIP'],
    assistantName: 'AI Assistant',
    assistantStatus: 'online',
    assistantGreeting: 'Hi! How can I help you today?',
    assistantHint: 'Tip: ask about fractions',
    userPrompt: 'Explain decimal fractions to me',
    successMessage: 'Reply generated successfully',
    chatChips: ['More', 'Quiz'],
    composerPlaceholder: 'Write a message...',
    elevatedLabel: 'Elevated',
    subtleLabel: 'Subtle',
    segmentedLabels: ['Day', 'Week', 'Month'],
    disabledFieldLabel: 'Disabled field',
    controlLabel: 'Control',
    previewInputAria: 'preview input',
  },
  pl: {
    targetLabels: {
      current: 'Podgląd',
      daily: 'Dzień',
      dawn: 'Świt',
      sunset: 'Zmierzch',
      nightly: 'Noc',
    },
    groupAriaLabel: 'Podgląd motywu',
    sectionLabels: {
      page: 'Strona i nawigacja',
      buttons: 'Przyciski',
      cards: 'Karty i pola',
      colors: 'Kolory i gradienty',
      chat: 'Czat',
      components: 'Komponenty',
    },
    navItems: ['Kursy', 'Wyniki', 'Profil'],
    homeActions: [
      { id: 'lessons', label: 'Lekcje', emoji: '\ud83d\udcda' },
      { id: 'play', label: 'Graj', emoji: '\ud83c\udfae' },
      { id: 'training', label: 'Trening', emoji: '\ud83c\udfc6' },
      { id: 'kangur', label: 'Kangur', emoji: '\ud83e\udd98' },
    ],
    pageHeading: 'Alfabet - 6 lat',
    pageSubtext: 'Litery, sylaby i pierwsze słowa.',
    buttonLabels: {
      primary: 'Główny',
      hover: 'Hover',
      secondary: 'Drugorzędny',
      surface: 'Powierzchnia',
      warning: 'Ostrzeżenie',
      success: 'Sukces',
    },
    lessonTitle: 'Lekcja 3 - Ułamki',
    lessonMeta: '12 ćwiczeń · 45 min',
    continueLabel: 'Kontynuuj',
    resultsLabel: 'Wyniki',
    searchPlaceholder: 'Wyszukaj ćwiczenie...',
    studentOneName: 'Anna Kowalska',
    studentOneMeta: 'Postęp: 74% · #12 w klasie',
    studentTwoName: 'Jan Nowak',
    studentTwoMeta: '1 240 pkt',
    profileLabel: 'Profil',
    dropdownItems: ['Ułamki zwykłe', 'Ułamki dziesiętne', 'Procenty'],
    accentGradientsLabel: 'Gradienty akcentów',
    accentGradientNames: ['Indygo', 'Fiolet', 'Szmaragd', 'Błękit', 'Bursztyn', 'Róż', 'Turkus', 'Łupkowy'],
    logoPaletteLabel: 'Paleta logo',
    logoPaletteNames: ['Napis start', 'Napis środek', 'Napis koniec', 'Obwódka start', 'Obwódka koniec', 'Akcent start', 'Akcent koniec'],
    badgesLabel: 'Znaczniki',
    badges: ['Nowe', '-20%', 'Gotowe', 'Ważne', 'Info', 'VIP'],
    assistantName: 'Asystent AI',
    assistantStatus: 'online',
    assistantGreeting: 'Cześć! W czym mogę Ci dzisiaj pomóc?',
    assistantHint: 'Podpowiedź: zapytaj o ułamki',
    userPrompt: 'Wyjaśnij mi ułamki dziesiętne',
    successMessage: 'Odpowiedź wygenerowana pomyślnie',
    chatChips: ['Więcej', 'Quiz'],
    composerPlaceholder: 'Napisz wiadomość...',
    elevatedLabel: 'Wyniesiony',
    subtleLabel: 'Subtelny',
    segmentedLabels: ['Dzień', 'Tydzień', 'Miesiąc'],
    disabledFieldLabel: 'Pole wyłączone',
    controlLabel: 'Kontrolka',
    previewInputAria: 'pole podglądu',
  },
  uk: {
    targetLabels: {
      current: 'Перегляд',
      daily: 'День',
      dawn: 'Світанок',
      sunset: 'Захід',
      nightly: 'Ніч',
    },
    groupAriaLabel: 'Перегляд теми',
    sectionLabels: {
      page: 'Сторінка і навігація',
      buttons: 'Кнопки',
      cards: 'Картки і поля',
      colors: 'Кольори і градієнти',
      chat: 'Чат',
      components: 'Компоненти',
    },
    navItems: ['Курси', 'Результати', 'Профіль'],
    homeActions: [
      { id: 'lessons', label: 'Уроки', emoji: '\ud83d\udcda' },
      { id: 'play', label: 'Грай', emoji: '\ud83c\udfae' },
      { id: 'training', label: 'Тренування', emoji: '\ud83c\udfc6' },
      { id: 'kangur', label: 'Kangur', emoji: '\ud83e\udd98' },
    ],
    pageHeading: 'Абетка - 6 років',
    pageSubtext: 'Літери, склади й перші слова.',
    buttonLabels: {
      primary: 'Основна',
      hover: 'Hover',
      secondary: 'Другорядна',
      surface: 'Поверхня',
      warning: 'Попередження',
      success: 'Успіх',
    },
    lessonTitle: 'Урок 3 - Дроби',
    lessonMeta: '12 вправ · 45 хв',
    continueLabel: 'Продовжити',
    resultsLabel: 'Результати',
    searchPlaceholder: 'Шукати вправу...',
    studentOneName: 'Anna Kowalska',
    studentOneMeta: 'Прогрес: 74% · №12 у класі',
    studentTwoName: 'Jan Nowak',
    studentTwoMeta: '1 240 балів',
    profileLabel: 'Профіль',
    dropdownItems: ['Звичайні дроби', 'Десяткові дроби', 'Відсотки'],
    accentGradientsLabel: 'Градієнти акцентів',
    accentGradientNames: ['Індиго', 'Фіолетовий', 'Смарагдовий', 'Небесний', 'Бурштиновий', 'Рожевий', 'Бірюзовий', 'Сланцевий'],
    logoPaletteLabel: 'Палітра лого',
    logoPaletteNames: ['Початок напису', 'Середина напису', 'Кінець напису', 'Початок обвідки', 'Кінець обвідки', 'Початок акценту', 'Кінець акценту'],
    badgesLabel: 'Позначки',
    badges: ['Нове', '-20%', 'Готово', 'Важливо', 'Інфо', 'VIP'],
    assistantName: 'AI-помічник',
    assistantStatus: 'online',
    assistantGreeting: 'Привіт! Чим я можу допомогти сьогодні?',
    assistantHint: 'Підказка: запитайте про дроби',
    userPrompt: 'Поясни мені десяткові дроби',
    successMessage: 'Відповідь успішно згенеровано',
    chatChips: ['Більше', 'Квіз'],
    composerPlaceholder: 'Напишіть повідомлення...',
    elevatedLabel: 'Піднятий',
    subtleLabel: 'Делікатний',
    segmentedLabels: ['День', 'Тиждень', 'Місяць'],
    disabledFieldLabel: 'Вимкнене поле',
    controlLabel: 'Елемент керування',
    previewInputAria: 'поле перегляду',
  },
} as const;

export const CONTEXT_COPY = {
  en: {
    defaultModeSaveError: 'Failed to save the default startup theme.',
    defaultModeSaveSuccess: 'Default startup theme updated.',
    unsavedSwitchConfirm:
      'You have unsaved changes in the current theme. Do you want to switch anyway?',
    assignError: 'Failed to assign the theme.',
    assignSuccess: (slotLabel: string) => `Theme assigned to slot "${slotLabel}".`,
    unassignError: 'Failed to unassign the theme.',
    unassignSuccess: (slotLabel: string) => `Slot "${slotLabel}" restored to factory settings.`,
    saveFactoryError: 'Cannot save changes to a factory theme.',
    saveError: 'Theme save failed.',
    saveSuccess: 'Theme saved.',
  },
  pl: {
    defaultModeSaveError: 'Nie udało się zapisać domyślnego motywu startowego.',
    defaultModeSaveSuccess: 'Domyślny motyw startowy zaktualizowany.',
    unsavedSwitchConfirm:
      'Masz niezapisane zmiany w aktualnym motywie. Czy na pewno chcesz przełączyć?',
    assignError: 'Nie udało się przypisać motywu.',
    assignSuccess: (slotLabel: string) => `Motyw przypisany do slotu "${slotLabel}".`,
    unassignError: 'Nie udało się odpiąć motywu.',
    unassignSuccess: (slotLabel: string) => `Slot "${slotLabel}" przywrócony do fabrycznego.`,
    saveFactoryError: 'Nie można zapisać zmian w motywie fabrycznym.',
    saveError: 'Błąd zapisu motywu.',
    saveSuccess: 'Motyw został zapisany.',
  },
  uk: {
    defaultModeSaveError: 'Не вдалося зберегти стартову тему за замовчуванням.',
    defaultModeSaveSuccess: 'Стартову тему за замовчуванням оновлено.',
    unsavedSwitchConfirm:
      'У поточній темі є незбережені зміни. Ви впевнені, що хочете переключитися?',
    assignError: 'Не вдалося призначити тему.',
    assignSuccess: (slotLabel: string) => `Тему призначено до слоту "${slotLabel}".`,
    unassignError: 'Не вдалося відвʼязати тему.',
    unassignSuccess: (slotLabel: string) => `Слот "${slotLabel}" відновлено до фабричних налаштувань.`,
    saveFactoryError: 'Не можна зберігати зміни у фабричній темі.',
    saveError: 'Не вдалося зберегти тему.',
    saveSuccess: 'Тему збережено.',
  },
} as const;
