import type { NodeDefinition } from '@/shared/types/domain/ai-paths';

import {
  AGENT_INPUT_PORTS,
  AGENT_OUTPUT_PORTS,
  AUDIO_OSCILLATOR_INPUT_PORTS,
  AUDIO_OSCILLATOR_OUTPUT_PORTS,
  AUDIO_SPEAKER_INPUT_PORTS,
  AUDIO_SPEAKER_OUTPUT_PORTS,
  LEARNER_AGENT_INPUT_PORTS,
  LEARNER_AGENT_OUTPUT_PORTS,
  BUNDLE_INPUT_PORTS,
  CONTEXT_INPUT_PORTS,
  DATABASE_INPUT_PORTS,
  DELAY_INPUT_PORTS,
  DELAY_OUTPUT_PORTS,
  DESCRIPTION_OUTPUT_PORTS,
  HTTP_INPUT_PORTS,
  MODEL_OUTPUT_PORTS,
  NOTIFICATION_INPUT_PORTS,
  POLL_INPUT_PORTS,
  POLL_OUTPUT_PORTS,
  PROMPT_INPUT_PORTS,
  PROMPT_OUTPUT_PORTS,
  REGEX_INPUT_PORTS,
  REGEX_OUTPUT_PORTS,
  STRING_MUTATOR_INPUT_PORTS,
  STRING_MUTATOR_OUTPUT_PORTS,
  ITERATOR_INPUT_PORTS,
  ITERATOR_OUTPUT_PORTS,
  ROUTER_INPUT_PORTS,
  ROUTER_OUTPUT_PORTS,
  SIMULATION_INPUT_PORTS,
  SIMULATION_OUTPUT_PORTS,
  TEMPLATE_INPUT_PORTS,
  TRIGGER_INPUT_PORTS,
  TRIGGER_OUTPUT_PORTS,
  VIEWER_INPUT_PORTS,
} from '../constants';

export const palette: NodeDefinition[] = [
  {
    type: 'trigger',
    title: 'Trigger: Product Modal',
    description: 'Runs when Context Filter is clicked inside Product modal.',
    inputs: TRIGGER_INPUT_PORTS,
    outputs: TRIGGER_OUTPUT_PORTS,
  },
  {
    type: 'trigger',
    title: 'Trigger: Bulk Generate',
    description: 'Runs from bulk action in Product list.',
    inputs: TRIGGER_INPUT_PORTS,
    outputs: TRIGGER_OUTPUT_PORTS,
  },
  {
    type: 'trigger',
    title: 'Trigger: On Product Save',
    description: 'Runs automatically after a product is saved.',
    inputs: TRIGGER_INPUT_PORTS,
    outputs: TRIGGER_OUTPUT_PORTS,
  },
  {
    type: 'trigger',
    title: 'Trigger: Scheduled Run',
    description: 'Runs on a server schedule or cron.',
    inputs: TRIGGER_INPUT_PORTS,
    outputs: TRIGGER_OUTPUT_PORTS,
    config: { trigger: { event: 'scheduled_run' } },
  },
  {
    type: 'simulation',
    title: 'Simulation: Entity Modal',
    description: 'Simulate a modal action by Entity ID.',
    inputs: SIMULATION_INPUT_PORTS,
    outputs: SIMULATION_OUTPUT_PORTS,
  },
  {
    type: 'audio_oscillator',
    title: 'Audio Oscillator',
    description: 'Generate a waveform signal (sine/square/triangle/sawtooth).',
    inputs: AUDIO_OSCILLATOR_INPUT_PORTS,
    outputs: AUDIO_OSCILLATOR_OUTPUT_PORTS,
    config: {
      audioOscillator: {
        waveform: 'sine',
        frequencyHz: 440,
        gain: 0.25,
        durationMs: 400,
      },
    },
  },
  {
    type: 'audio_speaker',
    title: 'Audio Speaker (Mono)',
    description: 'Play incoming audio signals in local runtime.',
    inputs: AUDIO_SPEAKER_INPUT_PORTS,
    outputs: AUDIO_SPEAKER_OUTPUT_PORTS,
    config: {
      audioSpeaker: {
        enabled: true,
        autoPlay: true,
        gain: 1,
        stopPrevious: true,
      },
    },
  },
  {
    type: 'viewer',
    title: 'Result Viewer',
    description: 'Preview outputs connected from other nodes.',
    inputs: VIEWER_INPUT_PORTS,
    outputs: [],
  },
  {
    type: 'notification',
    title: 'Toast Notification',
    description: 'Display an instant toast from incoming results.',
    inputs: NOTIFICATION_INPUT_PORTS,
    outputs: [],
  },
  {
    type: 'ai_description',
    title: 'AI Description Generator',
    description: 'Runs the AI Description pipeline to produce description_en.',
    inputs: ['entityJson', 'images', 'title'],
    outputs: DESCRIPTION_OUTPUT_PORTS,
  },
  {
    type: 'context',
    title: 'Context Filter',
    description: 'Filter incoming context payloads into scoped entity data.',
    inputs: CONTEXT_INPUT_PORTS,
    outputs: ['context', 'entityId', 'entityType', 'entityJson'],
  },
  {
    type: 'parser',
    title: 'JSON Parser',
    description: 'Extract fields into outputs or a single bundle.',
    inputs: ['entityJson', 'context'],
    outputs: ['productId', 'title', 'images', 'content_en'],
  },
  {
    type: 'regex',
    title: 'Regex Grouper',
    description: 'Group strings with regex or extract matched fragments.',
    inputs: REGEX_INPUT_PORTS,
    outputs: REGEX_OUTPUT_PORTS,
    config: {
      regex: {
        pattern: '',
        flags: 'g',
        mode: 'group',
        matchMode: 'first',
        groupBy: 'match',
        outputMode: 'object',
        includeUnmatched: true,
        unmatchedKey: '__unmatched__',
        splitLines: true,
        sampleText: '',
        aiPrompt:
          'You are a regex expert. Propose a JavaScript RegExp to group items in the input.\n\nReturn ONLY JSON:\n{"pattern":"...","flags":"...","groupBy":"match|1|<namedGroup>"}\n\nInput:\n{{text}}',
        aiAutoRun: false,
      },
    },
  },
  {
    type: 'iterator',
    title: 'Iterator',
    description: 'Iterate over an array and emit one item at a time (advance on callback).',
    inputs: ITERATOR_INPUT_PORTS,
    outputs: ITERATOR_OUTPUT_PORTS,
    config: {
      iterator: {
        autoContinue: true,
        maxSteps: 50,
      },
    },
  },
  {
    type: 'mapper',
    title: 'JSON Mapper',
    description: 'Map context to custom outputs.',
    inputs: ['context', 'result', 'bundle', 'value'],
    outputs: ['value', 'result'],
  },
  {
    type: 'mutator',
    title: 'Mutator',
    description: 'Mutate context values with templates.',
    inputs: ['context'],
    outputs: ['context'],
  },
  {
    type: 'string_mutator',
    title: 'String Mutator',
    description: 'Transform text with chained string operations.',
    inputs: STRING_MUTATOR_INPUT_PORTS,
    outputs: STRING_MUTATOR_OUTPUT_PORTS,
  },
  {
    type: 'validator',
    title: 'Validator',
    description: 'Validate required fields.',
    inputs: ['context'],
    outputs: ['context', 'valid', 'errors'],
  },
  {
    type: 'compare',
    title: 'Compare',
    description: 'Compare a value and emit valid/errors.',
    inputs: ['value'],
    outputs: ['value', 'valid', 'errors'],
  },
  {
    type: 'router',
    title: 'Router',
    description: 'Route payloads based on a condition.',
    inputs: ROUTER_INPUT_PORTS,
    outputs: ROUTER_OUTPUT_PORTS,
  },
  {
    type: 'delay',
    title: 'Delay',
    description: 'Delay signals to sequence flows.',
    inputs: DELAY_INPUT_PORTS,
    outputs: DELAY_OUTPUT_PORTS,
  },
  {
    type: 'poll',
    title: 'Poll Job',
    description: 'Poll an AI job or database query until it completes.',
    inputs: POLL_INPUT_PORTS,
    outputs: POLL_OUTPUT_PORTS,
  },
  {
    type: 'http',
    title: 'HTTP Fetch',
    description: 'Call external APIs with templated inputs.',
    inputs: HTTP_INPUT_PORTS,
    outputs: ['value', 'bundle'],
  },
  {
    type: 'database',
    title: 'Database Query',
    description: 'Query, update, insert, or delete records.',
    inputs: DATABASE_INPUT_PORTS,
    outputs: ['result', 'bundle', 'content_en', 'aiPrompt'],
  },
  {
    type: 'db_schema',
    title: 'Database Schema',
    description: 'Provides live database structure as context for AI.',
    inputs: [],
    outputs: ['schema', 'context'],
  },
  {
    type: 'constant',
    title: 'Constant',
    description: 'Emit a constant value as a signal.',
    inputs: [],
    outputs: ['value'],
  },
  {
    type: 'math',
    title: 'Math',
    description: 'Apply numeric transformation to a value.',
    inputs: ['value'],
    outputs: ['value'],
  },
  {
    type: 'gate',
    title: 'Gate',
    description: 'Allow context through when valid is true.',
    inputs: ['context', 'valid', 'errors'],
    outputs: ['context', 'valid', 'errors'],
  },
  {
    type: 'bundle',
    title: 'Bundle',
    description: 'Cluster inputs into a single bundle output.',
    inputs: BUNDLE_INPUT_PORTS,
    outputs: ['bundle'],
  },
  {
    type: 'template',
    title: 'Template',
    description: 'Create prompts from template strings.',
    inputs: TEMPLATE_INPUT_PORTS,
    outputs: ['prompt'],
  },
  {
    type: 'prompt',
    title: 'Prompt',
    description: 'Formats text with placeholders.',
    inputs: PROMPT_INPUT_PORTS,
    outputs: PROMPT_OUTPUT_PORTS,
  },
  {
    type: 'model',
    title: 'Model',
    description: 'Runs a selected model.',
    inputs: ['prompt', 'images'],
    outputs: MODEL_OUTPUT_PORTS,
  },
  {
    type: 'learner_agent',
    title: 'Learner Agent',
    description: 'Answer using connected embedding collections (RAG).',
    inputs: LEARNER_AGENT_INPUT_PORTS,
    outputs: LEARNER_AGENT_OUTPUT_PORTS,
    config: {
      learnerAgent: {
        agentId: '',
        promptTemplate: '',
        includeSources: true,
      },
    },
  },
  {
    type: 'agent',
    title: 'Reasoning Agent',
    description: 'Run a multi-step agent persona over the prompt.',
    inputs: AGENT_INPUT_PORTS,
    outputs: AGENT_OUTPUT_PORTS,
  },
];
