import type { KangurGameEngineDefinition } from '@/shared/contracts/kangur-games';

export const KANGUR_FOUNDATIONAL_GAME_ENGINES: readonly KangurGameEngineDefinition[] = [
  {
    id: 'clock-dial-engine',
    category: 'foundational',
    label: 'Clock dial engine',
    title: 'Clock Dial Engine',
    description:
      'Shared analogue clock engine for reading hours, minutes, and time relationships across lesson and fullscreen surfaces.',
    mechanics: ['clock_training'],
    interactionModes: ['mixed'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['time', 'clock', 'analogue'],
    status: 'active',
    sortOrder: 100,
  },
  {
    id: 'calendar-grid-engine',
    category: 'foundational',
    label: 'Calendar grid engine',
    title: 'Calendar Grid Engine',
    description:
      'Reusable calendar engine for dates, weekdays, and month navigation in lessons, previews, and standalone play.',
    mechanics: ['calendar_interactive'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['calendar', 'dates', 'time'],
    status: 'active',
    sortOrder: 200,
  },
  {
    id: 'quantity-drag-engine',
    category: 'foundational',
    label: 'Quantity drag engine',
    title: 'Quantity Drag Engine',
    description:
      'Drag-and-drop quantity engine for early arithmetic variants such as adding ball and subtracting garden.',
    mechanics: ['drag_drop'],
    interactionModes: ['drag'],
    surfaces: ['lesson', 'library'],
    tags: ['quantity', 'drag', 'arithmetic'],
    status: 'active',
    sortOrder: 300,
  },
  {
    id: 'rhythm-answer-engine',
    category: 'foundational',
    label: 'Rhythm answer engine',
    title: 'Rhythm Answer Engine',
    description:
      'Tap-driven fluency engine for rhythm-based answer rounds and future music-like arithmetic practice variants.',
    mechanics: ['rhythm'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library'],
    tags: ['rhythm', 'fluency', 'answers'],
    status: 'active',
    sortOrder: 400,
  },
  {
    id: 'array-builder-engine',
    category: 'foundational',
    label: 'Array builder engine',
    title: 'Array Builder Engine',
    description:
      'Visual array engine for repeated groups and multiplication structure, designed for lesson embedding and catalog reuse.',
    mechanics: ['tap_select'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library'],
    tags: ['arrays', 'multiplication', 'visual'],
    status: 'active',
    sortOrder: 500,
  },
  {
    id: 'choice-quiz-engine',
    category: 'foundational',
    label: 'Choice quiz engine',
    title: 'Choice Quiz Engine',
    description:
      'Reusable multiple-choice quiz engine for arithmetic recall, with fullscreen runtime support already wired.',
    mechanics: ['multiple_choice'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['quiz', 'choice', 'arithmetic'],
    status: 'active',
    sortOrder: 600,
  },
  {
    id: 'shape-drawing-engine',
    category: 'foundational',
    label: 'Shape drawing engine',
    title: 'Shape Drawing Engine',
    description:
      'Shared drawing engine for geometry activities focused on sketching shapes, tracing edges, and building figure fluency.',
    mechanics: ['drawing'],
    interactionModes: ['draw'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'shapes'],
    status: 'active',
    sortOrder: 700,
  },
  {
    id: 'symmetry-drawing-engine',
    category: 'foundational',
    label: 'Symmetry drawing engine',
    title: 'Symmetry Drawing Engine',
    description:
      'Shared drawing engine for symmetry axes, mirror reflections, and geometry tasks centered on balanced shapes.',
    mechanics: ['drawing'],
    interactionModes: ['draw'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'symmetry'],
    status: 'active',
    sortOrder: 710,
  },
  {
    id: 'perimeter-drawing-engine',
    category: 'foundational',
    label: 'Perimeter drawing engine',
    title: 'Perimeter Drawing Engine',
    description:
      'Shared grid-based drawing engine for tracing side lengths, outlining figures, and perimeter practice across lessons and the catalog.',
    mechanics: ['drawing'],
    interactionModes: ['draw'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['geometry', 'drawing', 'perimeter'],
    status: 'active',
    sortOrder: 720,
  },
  {
    id: 'pattern-sequence-engine',
    category: 'foundational',
    label: 'Pattern sequence engine',
    title: 'Pattern Sequence Engine',
    description:
      'Sequence-focused engine for ordering, progression, and rule detection across logic, alphabet, and adult workflow games.',
    mechanics: ['logic_pattern'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['logic', 'patterns', 'sequence'],
    status: 'active',
    sortOrder: 800,
  },
  {
    id: 'classification-engine',
    category: 'foundational',
    label: 'Classification engine',
    title: 'Classification Engine',
    description:
      'Cross-subject grouping and routing engine shared by logical classification, grammar sorting, agentic triage, and early matching games.',
    mechanics: ['logic_classification'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['classification', 'sorting', 'cross-subject'],
    status: 'active',
    sortOrder: 900,
  },
  {
    id: 'relation-match-engine',
    category: 'foundational',
    label: 'Relation match engine',
    title: 'Relation Match Engine',
    description:
      'Shared engine for analogy matching and relationship reasoning across lesson variants and fullscreen surfaces.',
    mechanics: ['logic_relation'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['relations', 'analogies', 'logic'],
    status: 'active',
    sortOrder: 1000,
  },
  {
    id: 'sentence-builder-engine',
    category: 'foundational',
    label: 'Sentence builder engine',
    title: 'Sentence Builder Engine',
    description:
      'English sentence construction engine prepared for lesson staging, previews, and standalone grammar rounds.',
    mechanics: ['sentence_building'],
    interactionModes: ['tap'],
    surfaces: ['lesson', 'library', 'game'],
    tags: ['english', 'grammar', 'sentences'],
    status: 'active',
    sortOrder: 1100,
  },
];
