import { colorSchemeField, paddingFields } from './shared-field-helpers';

import type { BlockDefinition } from '../../../types/page-builder';

export const mediaBlockDefinitions: Record<string, BlockDefinition> = {
  ImageElement: {
    type: 'ImageElement',
    label: 'Image element',
    icon: 'ImageIcon',
    defaultSettings: {
      src: '',
      alt: '',
      width: 100,
      height: 0,
      aspectRatio: 'auto',
      objectFit: 'cover',
      objectPosition: 'center',
      opacity: 100,
      blur: 0,
      grayscale: 0,
      brightness: 100,
      contrast: 100,
      scale: 100,
      rotate: 0,
      shape: 'none',
      borderRadius: 0,
      borderWidth: 0,
      borderStyle: 'solid',
      borderColor: '#ffffff',
      clipOverflow: 'false',
      overlayType: 'none',
      overlayColor: '#000000',
      overlayOpacity: 0,
      overlayGradientFrom: '#000000',
      overlayGradientTo: '#ffffff',
      overlayGradientDirection: 'to-bottom',
      transparencyMode: 'none',
      transparencyDirection: 'bottom',
      transparencyStrength: 0,
      imageShadow: { x: 0, y: 0, blur: 0, spread: 0, color: '#00000000' },
    },
    settingsSchema: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text', defaultValue: '' },
      { key: 'width', label: 'Width (%)', type: 'range', defaultValue: 100, min: 10, max: 100 },
      {
        key: 'height',
        label: 'Fixed height (px)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 800,
      },
      {
        key: 'aspectRatio',
        label: 'Aspect ratio',
        type: 'select',
        options: [
          { label: 'Auto', value: 'auto' },
          { label: '1 / 1', value: '1 / 1' },
          { label: '4 / 3', value: '4 / 3' },
          { label: '3 / 4', value: '3 / 4' },
          { label: '16 / 9', value: '16 / 9' },
          { label: '9 / 16', value: '9 / 16' },
        ],
        defaultValue: 'auto',
      },
      {
        key: 'objectFit',
        label: 'Crop mode',
        type: 'select',
        options: [
          { label: 'Cover (crop)', value: 'cover' },
          { label: 'Contain (fit)', value: 'contain' },
          { label: 'Fill', value: 'fill' },
          { label: 'None', value: 'none' },
          { label: 'Scale down', value: 'scale-down' },
        ],
        defaultValue: 'cover',
      },
      {
        key: 'objectPosition',
        label: 'Position',
        type: 'select',
        options: [
          { label: 'Center', value: 'center' },
          { label: 'Top', value: 'top' },
          { label: 'Bottom', value: 'bottom' },
          { label: 'Left', value: 'left' },
          { label: 'Right', value: 'right' },
          { label: 'Top left', value: 'top-left' },
          { label: 'Top right', value: 'top-right' },
          { label: 'Bottom left', value: 'bottom-left' },
          { label: 'Bottom right', value: 'bottom-right' },
        ],
        defaultValue: 'center',
      },
      { key: 'opacity', label: 'Opacity', type: 'range', defaultValue: 100, min: 0, max: 100 },
      { key: 'blur', label: 'Blur (px)', type: 'range', defaultValue: 0, min: 0, max: 20 },
      {
        key: 'grayscale',
        label: 'Grayscale (%)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 100,
      },
      {
        key: 'brightness',
        label: 'Brightness (%)',
        type: 'range',
        defaultValue: 100,
        min: 0,
        max: 200,
      },
      {
        key: 'contrast',
        label: 'Contrast (%)',
        type: 'range',
        defaultValue: 100,
        min: 0,
        max: 200,
      },
      { key: 'scale', label: 'Scale (%)', type: 'range', defaultValue: 100, min: 50, max: 200 },
      { key: 'rotate', label: 'Rotate (deg)', type: 'range', defaultValue: 0, min: -180, max: 180 },
      {
        key: 'shape',
        label: 'Shape',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Rounded', value: 'rounded' },
          { label: 'Circle', value: 'circle' },
        ],
        defaultValue: 'none',
      },
      {
        key: 'clipOverflow',
        label: 'Contain image',
        type: 'select',
        options: [
          { label: 'Allow overflow', value: 'false' },
          { label: 'Clip to block', value: 'true' },
        ],
        defaultValue: 'false',
      },
      {
        key: 'borderRadius',
        label: 'Corner radius (px)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 40,
      },
      {
        key: 'borderWidth',
        label: 'Border width (px)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 12,
      },
      {
        key: 'borderStyle',
        label: 'Border style',
        type: 'select',
        options: [
          { label: 'Solid', value: 'solid' },
          { label: 'Dashed', value: 'dashed' },
          { label: 'Dotted', value: 'dotted' },
          { label: 'None', value: 'none' },
        ],
        defaultValue: 'solid',
      },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '#ffffff' },
      {
        key: 'imageShadow',
        label: 'Shadow',
        type: 'shadow',
        defaultValue: { x: 0, y: 0, blur: 0, spread: 0, color: '#00000000' },
      },
      {
        key: 'overlayType',
        label: 'Overlay',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Solid', value: 'solid' },
          { label: 'Gradient', value: 'gradient' },
        ],
        defaultValue: 'none',
      },
      { key: 'overlayColor', label: 'Overlay color', type: 'color', defaultValue: '#000000' },
      {
        key: 'overlayOpacity',
        label: 'Overlay opacity (%)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 100,
      },
      {
        key: 'overlayGradientFrom',
        label: 'Gradient from',
        type: 'color',
        defaultValue: '#000000',
      },
      { key: 'overlayGradientTo', label: 'Gradient to', type: 'color', defaultValue: '#ffffff' },
      {
        key: 'overlayGradientDirection',
        label: 'Gradient direction',
        type: 'select',
        options: [
          { label: 'Top', value: 'to-top' },
          { label: 'Bottom', value: 'to-bottom' },
          { label: 'Left', value: 'to-left' },
          { label: 'Right', value: 'to-right' },
          { label: 'Top left', value: 'to-top-left' },
          { label: 'Top right', value: 'to-top-right' },
          { label: 'Bottom left', value: 'to-bottom-left' },
          { label: 'Bottom right', value: 'to-bottom-right' },
        ],
        defaultValue: 'to-bottom',
      },
      {
        key: 'transparencyMode',
        label: 'Transparency',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Gradient', value: 'gradient' },
        ],
        defaultValue: 'none',
      },
      {
        key: 'transparencyDirection',
        label: 'Transparency direction',
        type: 'select',
        options: [
          { label: 'Top', value: 'top' },
          { label: 'Bottom', value: 'bottom' },
          { label: 'Left', value: 'left' },
          { label: 'Right', value: 'right' },
          { label: 'Top left', value: 'top-left' },
          { label: 'Top right', value: 'top-right' },
          { label: 'Bottom left', value: 'bottom-left' },
          { label: 'Bottom right', value: 'bottom-right' },
        ],
        defaultValue: 'bottom',
      },
      {
        key: 'transparencyStrength',
        label: 'Transparency strength (%)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 100,
      },
    ],
  },
  Image: {
    type: 'Image',
    label: 'Image',
    icon: 'ImageIcon',
    defaultSettings: { src: '', alt: '', width: 100, borderRadius: 0, clipOverflow: 'false' },
    settingsSchema: [
      { key: 'src', label: 'Image', type: 'image' },
      { key: 'alt', label: 'Alt text', type: 'text', defaultValue: '' },
      { key: 'width', label: 'Width (%)', type: 'range', defaultValue: 100, min: 10, max: 100 },
      { key: 'borderRadius', label: 'Border radius', type: 'number', defaultValue: 0 },
      {
        key: 'clipOverflow',
        label: 'Contain image',
        type: 'select',
        options: [
          { label: 'Allow overflow', value: 'false' },
          { label: 'Clip to block', value: 'true' },
        ],
        defaultValue: 'false',
      },
    ],
  },
  Model3D: {
    type: 'Model3D',
    label: '3D model',
    icon: 'Cube',
    defaultSettings: {
      assetId: '',
      height: 360,
      backgroundColor: '#111827',
      autoRotate: 'true',
      autoRotateSpeed: 2,
      environment: 'studio',
      lighting: 'studio',
      lightIntensity: 1,
      enableShadows: 'true',
      enableBloom: 'false',
      bloomIntensity: 0.5,
      exposure: 1,
      showGround: 'false',
      enableContactShadows: 'true',
      enableVignette: 'false',
      autoFit: 'true',
      presentationMode: 'false',
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scale: 1,
    },
    settingsSchema: [
      { key: 'assetId', label: '3D asset', type: 'asset3d' },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 360 },
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '#111827' },
      {
        key: 'autoRotate',
        label: 'Auto-rotate',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      { key: 'autoRotateSpeed', label: 'Rotate speed', type: 'number', defaultValue: 2 },
      {
        key: 'environment',
        label: 'Environment',
        type: 'select',
        options: [
          { label: 'Studio', value: 'studio' },
          { label: 'Sunset', value: 'sunset' },
          { label: 'Dawn', value: 'dawn' },
          { label: 'Night', value: 'night' },
          { label: 'Warehouse', value: 'warehouse' },
          { label: 'Forest', value: 'forest' },
          { label: 'Apartment', value: 'apartment' },
          { label: 'City', value: 'city' },
          { label: 'Park', value: 'park' },
          { label: 'Lobby', value: 'lobby' },
        ],
        defaultValue: 'studio',
      },
      {
        key: 'lighting',
        label: 'Lighting',
        type: 'select',
        options: [
          { label: 'Studio', value: 'studio' },
          { label: 'Outdoor', value: 'outdoor' },
          { label: 'Dramatic', value: 'dramatic' },
          { label: 'Soft', value: 'soft' },
        ],
        defaultValue: 'studio',
      },
      { key: 'lightIntensity', label: 'Light intensity', type: 'number', defaultValue: 1 },
      {
        key: 'enableShadows',
        label: 'Shadows',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'enableBloom',
        label: 'Bloom',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      { key: 'bloomIntensity', label: 'Bloom intensity', type: 'number', defaultValue: 0.5 },
      { key: 'exposure', label: 'Exposure', type: 'number', defaultValue: 1 },
      {
        key: 'showGround',
        label: 'Ground plane',
        type: 'select',
        options: [
          { label: 'Show', value: 'true' },
          { label: 'Hide', value: 'false' },
        ],
        defaultValue: 'false',
      },
      {
        key: 'enableContactShadows',
        label: 'Contact shadows',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'enableVignette',
        label: 'Vignette',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      {
        key: 'autoFit',
        label: 'Auto-fit camera',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'presentationMode',
        label: 'Presentation mode',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      { key: 'positionX', label: 'Position X', type: 'number', defaultValue: 0 },
      { key: 'positionY', label: 'Position Y', type: 'number', defaultValue: 0 },
      { key: 'positionZ', label: 'Position Z', type: 'number', defaultValue: 0 },
      { key: 'rotationX', label: 'Rotation X (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationY', label: 'Rotation Y (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationZ', label: 'Rotation Z (deg)', type: 'number', defaultValue: 0 },
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1 },
    ],
  },
  Model3DElement: {
    type: 'Model3DElement',
    label: '3D element',
    icon: 'Cube',
    defaultSettings: {
      assetId: '',
      height: 360,
      backgroundColor: '#111827',
      autoRotate: 'true',
      autoRotateSpeed: 2,
      environment: 'studio',
      lighting: 'studio',
      lightIntensity: 1,
      enableShadows: 'true',
      enableBloom: 'false',
      bloomIntensity: 0.5,
      exposure: 1,
      showGround: 'false',
      enableContactShadows: 'true',
      enableVignette: 'false',
      autoFit: 'true',
      presentationMode: 'false',
      positionX: 0,
      positionY: 0,
      positionZ: 0,
      rotationX: 0,
      rotationY: 0,
      rotationZ: 0,
      scale: 1,
    },
    settingsSchema: [
      { key: 'assetId', label: '3D asset', type: 'asset3d' },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 360 },
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '#111827' },
      {
        key: 'autoRotate',
        label: 'Auto-rotate',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      { key: 'autoRotateSpeed', label: 'Rotate speed', type: 'number', defaultValue: 2 },
      {
        key: 'environment',
        label: 'Environment',
        type: 'select',
        options: [
          { label: 'Studio', value: 'studio' },
          { label: 'Sunset', value: 'sunset' },
          { label: 'Dawn', value: 'dawn' },
          { label: 'Night', value: 'night' },
          { label: 'Warehouse', value: 'warehouse' },
          { label: 'Forest', value: 'forest' },
          { label: 'Apartment', value: 'apartment' },
          { label: 'City', value: 'city' },
          { label: 'Park', value: 'park' },
          { label: 'Lobby', value: 'lobby' },
        ],
        defaultValue: 'studio',
      },
      {
        key: 'lighting',
        label: 'Lighting',
        type: 'select',
        options: [
          { label: 'Studio', value: 'studio' },
          { label: 'Outdoor', value: 'outdoor' },
          { label: 'Dramatic', value: 'dramatic' },
          { label: 'Soft', value: 'soft' },
        ],
        defaultValue: 'studio',
      },
      { key: 'lightIntensity', label: 'Light intensity', type: 'number', defaultValue: 1 },
      {
        key: 'enableShadows',
        label: 'Shadows',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'enableBloom',
        label: 'Bloom',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      { key: 'bloomIntensity', label: 'Bloom intensity', type: 'number', defaultValue: 0.5 },
      { key: 'exposure', label: 'Exposure', type: 'number', defaultValue: 1 },
      {
        key: 'showGround',
        label: 'Ground plane',
        type: 'select',
        options: [
          { label: 'Show', value: 'true' },
          { label: 'Hide', value: 'false' },
        ],
        defaultValue: 'false',
      },
      {
        key: 'enableContactShadows',
        label: 'Contact shadows',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'enableVignette',
        label: 'Vignette',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      {
        key: 'autoFit',
        label: 'Auto-fit camera',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'true',
      },
      {
        key: 'presentationMode',
        label: 'Presentation mode',
        type: 'select',
        options: [
          { label: 'On', value: 'true' },
          { label: 'Off', value: 'false' },
        ],
        defaultValue: 'false',
      },
      { key: 'positionX', label: 'Position X', type: 'number', defaultValue: 0 },
      { key: 'positionY', label: 'Position Y', type: 'number', defaultValue: 0 },
      { key: 'positionZ', label: 'Position Z', type: 'number', defaultValue: 0 },
      { key: 'rotationX', label: 'Rotation X (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationY', label: 'Rotation Y (deg)', type: 'number', defaultValue: 0 },
      { key: 'rotationZ', label: 'Rotation Z (deg)', type: 'number', defaultValue: 0 },
      { key: 'scale', label: 'Scale', type: 'number', defaultValue: 1 },
    ],
  },
  VideoEmbed: {
    type: 'VideoEmbed',
    label: 'Video embed',
    icon: 'Video',
    defaultSettings: { url: '', aspectRatio: '16:9', autoplay: 'no' },
    settingsSchema: [
      { key: 'url', label: 'Video URL', type: 'text', defaultValue: '' },
      {
        key: 'aspectRatio',
        label: 'Aspect ratio',
        type: 'select',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '4:3', value: '4:3' },
          { label: '1:1', value: '1:1' },
        ],
        defaultValue: '16:9',
      },
      {
        key: 'autoplay',
        label: 'Autoplay',
        type: 'select',
        options: [
          { label: 'No', value: 'no' },
          { label: 'Yes', value: 'yes' },
        ],
        defaultValue: 'no',
      },
    ],
  },
  Divider: {
    type: 'Divider',
    label: 'Divider',
    icon: 'Minus',
    defaultSettings: { dividerStyle: 'solid', thickness: 1, dividerColor: '#4b5563' },
    settingsSchema: [
      {
        key: 'dividerStyle',
        label: 'Style',
        type: 'select',
        options: [
          { label: 'Solid', value: 'solid' },
          { label: 'Dashed', value: 'dashed' },
          { label: 'Dotted', value: 'dotted' },
        ],
        defaultValue: 'solid',
      },
      { key: 'thickness', label: 'Thickness (px)', type: 'number', defaultValue: 1 },
      { key: 'dividerColor', label: 'Color', type: 'color', defaultValue: '#4b5563' },
    ],
  },
  SocialLinks: {
    type: 'SocialLinks',
    label: 'Social links',
    icon: 'Share2',
    defaultSettings: { platforms: '' },
    settingsSchema: [
      {
        key: 'platforms',
        label: 'Platform URLs (comma-separated)',
        type: 'text',
        defaultValue: '',
      },
    ],
  },
  Icon: {
    type: 'Icon',
    label: 'Icon',
    icon: 'Smile',
    defaultSettings: { iconName: 'Star', iconSize: 24, iconColor: '#ffffff' },
    settingsSchema: [
      { key: 'iconName', label: 'Icon name', type: 'text', defaultValue: 'Star' },
      { key: 'iconSize', label: 'Size (px)', type: 'number', defaultValue: 24 },
      { key: 'iconColor', label: 'Color', type: 'color', defaultValue: '#ffffff' },
    ],
  },
  AppEmbed: {
    type: 'AppEmbed',
    label: 'App embed',
    icon: 'AppWindow',
    defaultSettings: {
      appId: 'chatbot',
      title: '',
      embedUrl: '',
      height: 420,
    },
    settingsSchema: [
      { key: 'appId', label: 'App', type: 'select', options: [], defaultValue: 'chatbot' },
      { key: 'title', label: 'Title', type: 'text', defaultValue: '' },
      { key: 'embedUrl', label: 'Embed URL (iframe)', type: 'text', defaultValue: '' },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 420 },
    ],
  },
  Slideshow: {
    type: 'Slideshow',
    label: 'Slideshow',
    icon: 'GalleryHorizontal',
    allowedBlockTypes: [
      'SlideshowFrame',
      'Block',
      'Image',
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'AppEmbed',
    ],
    defaultSettings: {
      transition: 'fade',
      transitionDuration: 700,
      autoplay: 'yes',
      autoplaySpeed: 5000,
      pauseOnHover: 'yes',
      loop: 'yes',
      showArrows: 'yes',
      showDots: 'yes',
      heightMode: 'auto',
      height: 360,
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
      // Default element reveal settings
      elementAnimationType: 'fade-in',
      elementAnimationDuration: 400,
      elementAnimationDelay: 0,
      elementAnimationEasing: 'ease-out',
      elementAnimationStagger: 100,
    },
    settingsSchema: [
      {
        key: 'transition',
        label: 'Transition',
        type: 'select',
        options: [
          { label: 'Fade', value: 'fade' },
          { label: 'Slide', value: 'slide' },
        ],
        defaultValue: 'fade',
      },
      {
        key: 'transitionDuration',
        label: 'Transition duration (ms)',
        type: 'number',
        defaultValue: 700,
      },
      {
        key: 'autoplay',
        label: 'Autoplay',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        defaultValue: 'yes',
      },
      { key: 'autoplaySpeed', label: 'Autoplay speed (ms)', type: 'number', defaultValue: 5000 },
      {
        key: 'pauseOnHover',
        label: 'Pause on hover',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        defaultValue: 'yes',
      },
      {
        key: 'loop',
        label: 'Loop',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        defaultValue: 'yes',
      },
      {
        key: 'showArrows',
        label: 'Show arrows',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        defaultValue: 'yes',
      },
      {
        key: 'showDots',
        label: 'Show dots',
        type: 'select',
        options: [
          { label: 'Yes', value: 'yes' },
          { label: 'No', value: 'no' },
        ],
        defaultValue: 'yes',
      },
      {
        key: 'heightMode',
        label: 'Height mode',
        type: 'select',
        options: [
          { label: 'Auto (fit content)', value: 'auto' },
          { label: 'Fixed', value: 'fixed' },
        ],
        defaultValue: 'auto',
      },
      { key: 'height', label: 'Fixed height (px)', type: 'number', defaultValue: 360 },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      {
        key: 'elementAnimationType',
        label: 'Element animation',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Fade in', value: 'fade-in' },
          { label: 'Slide up', value: 'slide-up' },
          { label: 'Slide down', value: 'slide-down' },
          { label: 'Slide left', value: 'slide-left' },
          { label: 'Slide right', value: 'slide-right' },
          { label: 'Zoom in', value: 'zoom-in' },
          { label: 'Zoom out', value: 'zoom-out' },
        ],
        defaultValue: 'fade-in',
      },
      {
        key: 'elementAnimationDuration',
        label: 'Element duration (ms)',
        type: 'range',
        defaultValue: 400,
        min: 100,
        max: 2000,
      },
      {
        key: 'elementAnimationDelay',
        label: 'Element delay (ms)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 2000,
      },
      {
        key: 'elementAnimationEasing',
        label: 'Element easing',
        type: 'select',
        options: [
          { label: 'Linear', value: 'linear' },
          { label: 'Ease', value: 'ease' },
          { label: 'Ease in', value: 'ease-in' },
          { label: 'Ease out', value: 'ease-out' },
          { label: 'Ease in-out', value: 'ease-in-out' },
        ],
        defaultValue: 'ease-out',
      },
      {
        key: 'elementAnimationStagger',
        label: 'Stagger delay (ms)',
        type: 'range',
        defaultValue: 100,
        min: 0,
        max: 500,
      },
    ],
  },
};
