import type { BlockDefinition } from '@/features/cms/types/page-builder';

import { WRAP_OPTIONS, colorSchemeField, paddingFields } from './shared-field-helpers';
import {
  FONT_STYLE_OPTIONS,
  HEADING_SIZE_OPTIONS,
  TEXT_DECORATION_OPTIONS,
  TEXT_TRANSFORM_OPTIONS,
} from './block-definitions-content.constants';

export const contentTextBlockDefinitions: Record<string, BlockDefinition> = {
  Heading: {
    type: 'Heading',
    label: 'Heading',
    icon: 'Heading',
    defaultSettings: {
      headingText: 'Heading',
      headingSize: 'medium',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'headingText', label: 'Heading text', type: 'text', defaultValue: 'Heading' },
      {
        key: 'headingSize',
        label: 'Heading size',
        type: 'select',
        options: HEADING_SIZE_OPTIONS,
        defaultValue: 'medium',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  Text: {
    type: 'Text',
    label: 'Text',
    icon: 'AlignLeft',
    defaultSettings: {
      textContent: '',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      wordSpacing: 0,
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'textContent', label: 'Text', type: 'text', defaultValue: '' },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'wordSpacing', label: 'Word spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  TextElement: {
    type: 'TextElement',
    label: 'Text element',
    icon: 'FileText',
    defaultSettings: {
      textContent: 'Text element',
      fontFamily: 'Inter, sans-serif',
      fontSize: 0,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 0,
      letterSpacing: 0,
      textColor: '',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      wordSpacing: 0,
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'textContent', label: 'Text', type: 'text', defaultValue: 'Text element' },
      {
        key: 'fontFamily',
        label: 'Font family',
        type: 'font-family',
        defaultValue: 'Inter, sans-serif',
      },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '400' },
      {
        key: 'fontStyle',
        label: 'Font style',
        type: 'select',
        options: FONT_STYLE_OPTIONS,
        defaultValue: 'normal',
      },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'wordSpacing', label: 'Word spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  TextAtom: {
    type: 'TextAtom',
    label: 'Text atoms',
    icon: 'Folder',
    defaultSettings: {
      text: 'Text',
      alignment: 'left',
      letterGap: 0,
      lineGap: 0,
      wrap: 'wrap',
    },
    settingsSchema: [
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'Text' },
      {
        key: 'alignment',
        label: 'Alignment',
        type: 'alignment',
        defaultValue: 'left',
      },
      { key: 'letterGap', label: 'Letter gap (px)', type: 'number', defaultValue: 0 },
      { key: 'lineGap', label: 'Line gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'wrap',
        label: 'Wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
    ],
  },
  TextAtomLetter: {
    type: 'TextAtomLetter',
    label: 'Text atom',
    icon: 'FileText',
    defaultSettings: {
      textContent: '',
      fontFamily: 'Inter, sans-serif',
      fontSize: 0,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 0,
      letterSpacing: 0,
      textColor: '',
    },
    settingsSchema: [
      {
        key: 'fontFamily',
        label: 'Font family',
        type: 'font-family',
        defaultValue: 'Inter, sans-serif',
      },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '400' },
      {
        key: 'fontStyle',
        label: 'Font style',
        type: 'select',
        options: FONT_STYLE_OPTIONS,
        defaultValue: 'normal',
      },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
    ],
  },
  RichText: {
    type: 'RichText',
    label: 'Rich text',
    icon: 'FileText',
    defaultSettings: {
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [colorSchemeField('colorScheme', 'Color scheme'), ...paddingFields()],
  },
};
