import type { BlockDefinition } from '@/features/cms/types/page-builder';

import { BLOCK_SECTION_ALLOWED_BLOCK_TYPES } from './block-definitions-layout';
import {
  ALIGN_OPTIONS,
  JUSTIFY_OPTIONS,
  WRAP_OPTIONS,
  colorSchemeFieldWithNone,
  layoutFields,
  marginFields,
  paddingFields,
  sectionStyleFields,
} from './shared-field-helpers';
import {
  ANIMATION_EASING_OPTIONS,
  CAROUSEL_FRAME_ALLOWED_BLOCK_TYPES,
  CAROUSEL_TRANSITION_OPTIONS,
  COLUMN_ROW_OPTIONS,
  FRAME_ANIMATION_OPTIONS,
  FRAME_ANIMATION_WITH_INHERIT_OPTIONS,
  HEIGHT_MODE_OPTIONS,
  INHERIT_JUSTIFY_OPTIONS,
  LEFT_CENTER_RIGHT_OPTIONS,
  LINK_TARGET_OPTIONS,
  ROW_COLUMN_OPTIONS,
  SLIDESHOW_FRAME_ALLOWED_BLOCK_TYPES,
  TRUE_FALSE_OPTIONS,
  VERTICAL_ALIGNMENT_OPTIONS,
  YES_NO_OPTIONS,
} from './block-definitions-content.constants';

export const contentLayoutBlockDefinitions: Record<string, BlockDefinition> = {
  Block: {
    type: 'Block',
    label: 'Block',
    icon: 'Box',
    allowedBlockTypes: BLOCK_SECTION_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      colorScheme: 'none',
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 24,
      paddingRight: 24,
      blockGap: 0,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      contentAlignment: 'left',
      linkUrl: '',
      linkTarget: '_self',
      layoutDirection: 'row',
      wrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'inherit',
      minHeight: 0,
      maxWidth: 0,
      overflow: 'visible',
      opacity: 100,
      zIndex: 0,
      background: { type: 'none' },
      customCss: '',
    },
    settingsSchema: [
      colorSchemeFieldWithNone('colorScheme', 'Color scheme', 'none'),
      { key: 'blockGap', label: 'Content gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'layoutDirection',
        label: 'Layout direction',
        type: 'select',
        options: ROW_COLUMN_OPTIONS,
        defaultValue: 'row',
      },
      {
        key: 'wrap',
        label: 'Wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'left',
      },
      { key: 'linkUrl', label: 'Block link', type: 'link', defaultValue: '' },
      {
        key: 'linkTarget',
        label: 'Link target',
        type: 'select',
        options: LINK_TARGET_OPTIONS,
        defaultValue: '_self',
      },
      {
        key: 'justifyContent',
        label: 'Justify content',
        type: 'select',
        options: INHERIT_JUSTIFY_OPTIONS,
        defaultValue: 'inherit',
      },
      {
        key: 'alignItems',
        label: 'Align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'center',
      },
      ...paddingFields(),
      ...marginFields(),
      ...sectionStyleFields(),
      ...layoutFields(),
    ],
  },
  Carousel: {
    type: 'Carousel',
    label: 'Carousel',
    icon: 'GalleryHorizontal',
    allowedBlockTypes: ['CarouselFrame'],
    defaultSettings: {
      frameCount: 3,
      autoPlay: true,
      autoPlaySpeed: 5000,
      loop: true,
      showNavigation: true,
      showIndicators: true,
      transitionType: 'slide',
      transitionDuration: 500,
      pauseOnHover: true,
      heightMode: 'auto',
      height: 400,
    },
    settingsSchema: [
      {
        key: 'frameCount',
        label: 'Number of frames',
        type: 'range',
        defaultValue: 3,
        min: 1,
        max: 10,
      },
      {
        key: 'autoPlay',
        label: 'Auto play',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'autoPlaySpeed',
        label: 'Auto play speed (ms)',
        type: 'range',
        defaultValue: 5000,
        min: 1000,
        max: 15000,
      },
      {
        key: 'loop',
        label: 'Loop',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'showNavigation',
        label: 'Show arrows',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'showIndicators',
        label: 'Show indicators',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'transitionType',
        label: 'Transition type',
        type: 'select',
        options: CAROUSEL_TRANSITION_OPTIONS,
        defaultValue: 'slide',
      },
      {
        key: 'transitionDuration',
        label: 'Transition duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'pauseOnHover',
        label: 'Pause on hover',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'heightMode',
        label: 'Height mode',
        type: 'select',
        options: HEIGHT_MODE_OPTIONS,
        defaultValue: 'auto',
      },
      {
        key: 'height',
        label: 'Fixed height (px)',
        type: 'range',
        defaultValue: 400,
        min: 100,
        max: 800,
      },
    ],
  },
  CarouselFrame: {
    type: 'CarouselFrame',
    label: 'Carousel Frame',
    icon: 'Frame',
    allowedBlockTypes: CAROUSEL_FRAME_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      backgroundColor: '',
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      contentAlignment: 'center',
      verticalAlignment: 'center',
      // Animation settings for this frame
      animationType: 'fade-in',
      animationDuration: 500,
      animationDelay: 0,
      animationEasing: 'ease-out',
    },
    settingsSchema: [
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '' },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'verticalAlignment',
        label: 'Vertical alignment',
        type: 'select',
        options: VERTICAL_ALIGNMENT_OPTIONS,
        defaultValue: 'center',
      },
      ...paddingFields(),
      {
        key: 'animationType',
        label: 'Content animation',
        type: 'select',
        options: FRAME_ANIMATION_OPTIONS,
        defaultValue: 'fade-in',
      },
      {
        key: 'animationDuration',
        label: 'Animation duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'animationDelay',
        label: 'Animation delay (ms)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 2000,
      },
      {
        key: 'animationEasing',
        label: 'Animation easing',
        type: 'select',
        options: ANIMATION_EASING_OPTIONS,
        defaultValue: 'ease-out',
      },
    ],
  },
  SlideshowFrame: {
    type: 'SlideshowFrame',
    label: 'Slideshow Frame',
    icon: 'Frame',
    allowedBlockTypes: SLIDESHOW_FRAME_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      backgroundColor: '',
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      contentAlignment: 'center',
      verticalAlignment: 'center',
      fillContent: 'no',
      // Animation settings for this frame
      animationType: 'inherit',
      animationDuration: 500,
      animationDelay: 0,
      animationEasing: 'ease-out',
    },
    settingsSchema: [
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '' },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'verticalAlignment',
        label: 'Vertical alignment',
        type: 'select',
        options: VERTICAL_ALIGNMENT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'fillContent',
        label: 'Fill frame with image',
        type: 'select',
        options: YES_NO_OPTIONS,
        defaultValue: 'no',
      },
      { key: 'paddingTop', label: 'Top padding', type: 'number', defaultValue: 0 },
      { key: 'paddingRight', label: 'Right padding', type: 'number', defaultValue: 0 },
      { key: 'paddingBottom', label: 'Bottom padding', type: 'number', defaultValue: 0 },
      { key: 'paddingLeft', label: 'Left padding', type: 'number', defaultValue: 0 },
      {
        key: 'animationType',
        label: 'Content animation',
        type: 'select',
        options: FRAME_ANIMATION_WITH_INHERIT_OPTIONS,
        defaultValue: 'inherit',
      },
      {
        key: 'animationDuration',
        label: 'Animation duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'animationDelay',
        label: 'Animation delay (ms)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 2000,
      },
      {
        key: 'animationEasing',
        label: 'Animation easing',
        type: 'select',
        options: ANIMATION_EASING_OPTIONS,
        defaultValue: 'ease-out',
      },
    ],
  },
  Repeater: {
    type: 'Repeater',
    label: 'Repeater',
    icon: 'ListCollapse',
    allowedBlockTypes: BLOCK_SECTION_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      collectionSource: '',
      collectionPath: '',
      emptyMessage: 'No items to show yet.',
      itemLimit: 0,
      itemsGap: 16,
      listLayoutDirection: 'column',
      listWrap: 'wrap',
      listAlignItems: 'stretch',
      listJustifyContent: 'start',
      itemGap: 12,
      itemLayoutDirection: 'column',
      itemWrap: 'wrap',
      itemAlignItems: 'stretch',
      itemJustifyContent: 'start',
    },
    settingsSchema: [
      { key: 'collectionSource', label: 'Collection source', type: 'text', defaultValue: '' },
      { key: 'collectionPath', label: 'Collection path', type: 'text', defaultValue: '' },
      {
        key: 'emptyMessage',
        label: 'Empty message',
        type: 'text',
        defaultValue: 'No items to show yet.',
      },
      { key: 'itemLimit', label: 'Limit items', type: 'number', defaultValue: 0 },
      { key: 'itemsGap', label: 'Gap between items (px)', type: 'number', defaultValue: 16 },
      {
        key: 'listLayoutDirection',
        label: 'List layout',
        type: 'select',
        options: COLUMN_ROW_OPTIONS,
        defaultValue: 'column',
      },
      {
        key: 'listWrap',
        label: 'List wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'listAlignItems',
        label: 'List align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'stretch',
      },
      {
        key: 'listJustifyContent',
        label: 'List justify content',
        type: 'select',
        options: JUSTIFY_OPTIONS,
        defaultValue: 'start',
      },
      { key: 'itemGap', label: 'Gap inside item (px)', type: 'number', defaultValue: 12 },
      {
        key: 'itemLayoutDirection',
        label: 'Item layout',
        type: 'select',
        options: COLUMN_ROW_OPTIONS,
        defaultValue: 'column',
      },
      {
        key: 'itemWrap',
        label: 'Item wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'itemAlignItems',
        label: 'Item align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'stretch',
      },
      {
        key: 'itemJustifyContent',
        label: 'Item justify content',
        type: 'select',
        options: JUSTIFY_OPTIONS,
        defaultValue: 'start',
      },
    ],
  },
};
