import type { BlockDefinition } from '@/features/cms/types/page-builder';

import { BLOCK_SECTION_ALLOWED_BLOCK_TYPES } from './block-definitions-layout';
import {
  WRAP_OPTIONS,
  JUSTIFY_OPTIONS,
  ALIGN_OPTIONS,
  colorSchemeField,
  colorSchemeFieldWithNone,
  paddingFields,
  marginFields,
  layoutFields,
  sectionStyleFields,
} from './shared-field-helpers';

const ROW_COLUMN_OPTIONS = [
  { label: 'Row', value: 'row' },
  { label: 'Column', value: 'column' },
];

const COLUMN_ROW_OPTIONS = [
  { label: 'Column', value: 'column' },
  { label: 'Row', value: 'row' },
];

const LEFT_CENTER_RIGHT_OPTIONS = [
  { label: 'Left', value: 'left' },
  { label: 'Center', value: 'center' },
  { label: 'Right', value: 'right' },
];

const LINK_TARGET_OPTIONS = [
  { label: 'Same tab', value: '_self' },
  { label: 'New tab', value: '_blank' },
];

const INHERIT_JUSTIFY_OPTIONS = [{ label: 'Inherit alignment', value: 'inherit' }, ...JUSTIFY_OPTIONS];

const TRUE_FALSE_OPTIONS = [
  { label: 'Yes', value: 'true' },
  { label: 'No', value: 'false' },
];

const FALSE_TRUE_OPTIONS = [
  { label: 'No', value: 'false' },
  { label: 'Yes', value: 'true' },
];

const YES_NO_OPTIONS = [
  { label: 'No', value: 'no' },
  { label: 'Yes', value: 'yes' },
];

const CAROUSEL_TRANSITION_OPTIONS = [
  { label: 'Slide', value: 'slide' },
  { label: 'Fade', value: 'fade' },
  { label: 'None', value: 'none' },
];

const HEIGHT_MODE_OPTIONS = [
  { label: 'Auto (fit content)', value: 'auto' },
  { label: 'Fixed', value: 'fixed' },
];

const VERTICAL_ALIGNMENT_OPTIONS = [
  { label: 'Top', value: 'top' },
  { label: 'Center', value: 'center' },
  { label: 'Bottom', value: 'bottom' },
];

const FRAME_ANIMATION_OPTIONS = [
  { label: 'None', value: 'none' },
  { label: 'Fade in', value: 'fade-in' },
  { label: 'Slide up', value: 'slide-up' },
  { label: 'Slide down', value: 'slide-down' },
  { label: 'Slide left', value: 'slide-left' },
  { label: 'Slide right', value: 'slide-right' },
  { label: 'Zoom in', value: 'zoom-in' },
  { label: 'Zoom out', value: 'zoom-out' },
];

const FRAME_ANIMATION_WITH_INHERIT_OPTIONS = [
  { label: 'Inherit from Slideshow', value: 'inherit' },
  ...FRAME_ANIMATION_OPTIONS,
];

const ANIMATION_EASING_OPTIONS = [
  { label: 'Linear', value: 'linear' },
  { label: 'Ease', value: 'ease' },
  { label: 'Ease in', value: 'ease-in' },
  { label: 'Ease out', value: 'ease-out' },
  { label: 'Ease in-out', value: 'ease-in-out' },
];

const HEADING_SIZE_OPTIONS = [
  { label: 'Small', value: 'small' },
  { label: 'Medium', value: 'medium' },
  { label: 'Large', value: 'large' },
];

const TEXT_DECORATION_OPTIONS = [
  { label: 'None', value: 'none' },
  { label: 'Underline', value: 'underline' },
  { label: 'Line-through', value: 'line-through' },
];

const TEXT_TRANSFORM_OPTIONS = [
  { label: 'None', value: 'none' },
  { label: 'Uppercase', value: 'uppercase' },
  { label: 'Lowercase', value: 'lowercase' },
  { label: 'Capitalize', value: 'capitalize' },
];

const FONT_STYLE_OPTIONS = [
  { label: 'Normal', value: 'normal' },
  { label: 'Italic', value: 'italic' },
];

const INPUT_TYPE_OPTIONS = [
  { label: 'Text', value: 'text' },
  { label: 'Email', value: 'email' },
  { label: 'Password', value: 'password' },
  { label: 'Number', value: 'number' },
];

const BUTTON_STYLE_OPTIONS = [
  { label: 'Solid', value: 'solid' },
  { label: 'Outline', value: 'outline' },
];

const DISABLE_WHEN_OPTIONS = [
  { label: 'Value is truthy', value: 'truthy' },
  { label: 'Value is falsy', value: 'falsy' },
];

const IMAGE_HEIGHT_OPTIONS = [
  { label: 'Small', value: 'small' },
  { label: 'Medium', value: 'medium' },
  { label: 'Large', value: 'large' },
  { label: 'Adapt to image', value: 'adapt' },
];

const IMAGE_PLACEMENT_OPTIONS = [
  { label: 'Image first', value: 'image-first' },
  { label: 'Image second', value: 'image-second' },
];


// Content blocks that can be placed inside a CarouselFrame
export const CAROUSEL_FRAME_ALLOWED_BLOCK_TYPES = [
  'ImageElement',
  'TextElement',
  'TextAtom',
  'Block',
  'Button',
  'Input',
  'Progress',
  'Repeater',
  'Heading',
  'Text',
  'VideoEmbed',
  'Divider',
  'SocialLinks',
  'Icon',
];

// Content blocks that can be placed inside a SlideshowFrame
export const SLIDESHOW_FRAME_ALLOWED_BLOCK_TYPES = [
  'ImageElement',
  'Image',
  'Heading',
  'Text',
  'TextElement',
  'TextAtom',
  'Block',
  'Button',
  'Input',
  'Progress',
  'Repeater',
  'AppEmbed',
];

export const contentBlockDefinitions: Record<string, BlockDefinition> = {
  Block: {
    type: 'Block',
    label: 'Block',
    icon: 'Box',
    allowedBlockTypes: BLOCK_SECTION_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      colorScheme: 'none',
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 24,
      paddingRight: 24,
      blockGap: 0,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      contentAlignment: 'left',
      linkUrl: '',
      linkTarget: '_self',
      layoutDirection: 'row',
      wrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'inherit',
      minHeight: 0,
      maxWidth: 0,
      overflow: 'visible',
      opacity: 100,
      zIndex: 0,
      background: { type: 'none' },
      customCss: '',
    },
    settingsSchema: [
      colorSchemeFieldWithNone('colorScheme', 'Color scheme', 'none'),
      { key: 'blockGap', label: 'Content gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'layoutDirection',
        label: 'Layout direction',
        type: 'select',
        options: ROW_COLUMN_OPTIONS,
        defaultValue: 'row',
      },
      {
        key: 'wrap',
        label: 'Wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'left',
      },
      { key: 'linkUrl', label: 'Block link', type: 'link', defaultValue: '' },
      {
        key: 'linkTarget',
        label: 'Link target',
        type: 'select',
        options: LINK_TARGET_OPTIONS,
        defaultValue: '_self',
      },
      {
        key: 'justifyContent',
        label: 'Justify content',
        type: 'select',
        options: INHERIT_JUSTIFY_OPTIONS,
        defaultValue: 'inherit',
      },
      {
        key: 'alignItems',
        label: 'Align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'center',
      },
      ...paddingFields(),
      ...marginFields(),
      ...sectionStyleFields(),
      ...layoutFields(),
    ],
  },
  Carousel: {
    type: 'Carousel',
    label: 'Carousel',
    icon: 'GalleryHorizontal',
    allowedBlockTypes: ['CarouselFrame'],
    defaultSettings: {
      frameCount: 3,
      autoPlay: true,
      autoPlaySpeed: 5000,
      loop: true,
      showNavigation: true,
      showIndicators: true,
      transitionType: 'slide',
      transitionDuration: 500,
      pauseOnHover: true,
      heightMode: 'auto',
      height: 400,
    },
    settingsSchema: [
      {
        key: 'frameCount',
        label: 'Number of frames',
        type: 'range',
        defaultValue: 3,
        min: 1,
        max: 10,
      },
      {
        key: 'autoPlay',
        label: 'Auto play',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'autoPlaySpeed',
        label: 'Auto play speed (ms)',
        type: 'range',
        defaultValue: 5000,
        min: 1000,
        max: 15000,
      },
      {
        key: 'loop',
        label: 'Loop',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'showNavigation',
        label: 'Show arrows',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'showIndicators',
        label: 'Show indicators',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'transitionType',
        label: 'Transition type',
        type: 'select',
        options: CAROUSEL_TRANSITION_OPTIONS,
        defaultValue: 'slide',
      },
      {
        key: 'transitionDuration',
        label: 'Transition duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'pauseOnHover',
        label: 'Pause on hover',
        type: 'select',
        options: TRUE_FALSE_OPTIONS,
        defaultValue: 'true',
      },
      {
        key: 'heightMode',
        label: 'Height mode',
        type: 'select',
        options: HEIGHT_MODE_OPTIONS,
        defaultValue: 'auto',
      },
      {
        key: 'height',
        label: 'Fixed height (px)',
        type: 'range',
        defaultValue: 400,
        min: 100,
        max: 800,
      },
    ],
  },
  CarouselFrame: {
    type: 'CarouselFrame',
    label: 'Carousel Frame',
    icon: 'Frame',
    allowedBlockTypes: CAROUSEL_FRAME_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      backgroundColor: '',
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      contentAlignment: 'center',
      verticalAlignment: 'center',
      // Animation settings for this frame
      animationType: 'fade-in',
      animationDuration: 500,
      animationDelay: 0,
      animationEasing: 'ease-out',
    },
    settingsSchema: [
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '' },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'verticalAlignment',
        label: 'Vertical alignment',
        type: 'select',
        options: VERTICAL_ALIGNMENT_OPTIONS,
        defaultValue: 'center',
      },
      ...paddingFields(),
      {
        key: 'animationType',
        label: 'Content animation',
        type: 'select',
        options: FRAME_ANIMATION_OPTIONS,
        defaultValue: 'fade-in',
      },
      {
        key: 'animationDuration',
        label: 'Animation duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'animationDelay',
        label: 'Animation delay (ms)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 2000,
      },
      {
        key: 'animationEasing',
        label: 'Animation easing',
        type: 'select',
        options: ANIMATION_EASING_OPTIONS,
        defaultValue: 'ease-out',
      },
    ],
  },
  SlideshowFrame: {
    type: 'SlideshowFrame',
    label: 'Slideshow Frame',
    icon: 'Frame',
    allowedBlockTypes: SLIDESHOW_FRAME_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      backgroundColor: '',
      paddingTop: 0,
      paddingBottom: 0,
      paddingLeft: 0,
      paddingRight: 0,
      contentAlignment: 'center',
      verticalAlignment: 'center',
      fillContent: 'no',
      // Animation settings for this frame
      animationType: 'inherit',
      animationDuration: 500,
      animationDelay: 0,
      animationEasing: 'ease-out',
    },
    settingsSchema: [
      { key: 'backgroundColor', label: 'Background color', type: 'color', defaultValue: '' },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: LEFT_CENTER_RIGHT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'verticalAlignment',
        label: 'Vertical alignment',
        type: 'select',
        options: VERTICAL_ALIGNMENT_OPTIONS,
        defaultValue: 'center',
      },
      {
        key: 'fillContent',
        label: 'Fill frame with image',
        type: 'select',
        options: YES_NO_OPTIONS,
        defaultValue: 'no',
      },
      { key: 'paddingTop', label: 'Top padding', type: 'number', defaultValue: 0 },
      { key: 'paddingRight', label: 'Right padding', type: 'number', defaultValue: 0 },
      { key: 'paddingBottom', label: 'Bottom padding', type: 'number', defaultValue: 0 },
      { key: 'paddingLeft', label: 'Left padding', type: 'number', defaultValue: 0 },
      {
        key: 'animationType',
        label: 'Content animation',
        type: 'select',
        options: FRAME_ANIMATION_WITH_INHERIT_OPTIONS,
        defaultValue: 'inherit',
      },
      {
        key: 'animationDuration',
        label: 'Animation duration (ms)',
        type: 'range',
        defaultValue: 500,
        min: 100,
        max: 2000,
      },
      {
        key: 'animationDelay',
        label: 'Animation delay (ms)',
        type: 'range',
        defaultValue: 0,
        min: 0,
        max: 2000,
      },
      {
        key: 'animationEasing',
        label: 'Animation easing',
        type: 'select',
        options: ANIMATION_EASING_OPTIONS,
        defaultValue: 'ease-out',
      },
    ],
  },
  Heading: {
    type: 'Heading',
    label: 'Heading',
    icon: 'Heading',
    defaultSettings: {
      headingText: 'Heading',
      headingSize: 'medium',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'headingText', label: 'Heading text', type: 'text', defaultValue: 'Heading' },
      {
        key: 'headingSize',
        label: 'Heading size',
        type: 'select',
        options: HEADING_SIZE_OPTIONS,
        defaultValue: 'medium',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  Text: {
    type: 'Text',
    label: 'Text',
    icon: 'AlignLeft',
    defaultSettings: {
      textContent: '',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      wordSpacing: 0,
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'textContent', label: 'Text', type: 'text', defaultValue: '' },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'wordSpacing', label: 'Word spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  TextElement: {
    type: 'TextElement',
    label: 'Text element',
    icon: 'FileText',
    defaultSettings: {
      textContent: 'Text element',
      fontFamily: 'Inter, sans-serif',
      fontSize: 0,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 0,
      letterSpacing: 0,
      textColor: '',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      wordSpacing: 0,
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'textContent', label: 'Text', type: 'text', defaultValue: 'Text element' },
      {
        key: 'fontFamily',
        label: 'Font family',
        type: 'font-family',
        defaultValue: 'Inter, sans-serif',
      },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '400' },
      {
        key: 'fontStyle',
        label: 'Font style',
        type: 'select',
        options: FONT_STYLE_OPTIONS,
        defaultValue: 'normal',
      },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: TEXT_DECORATION_OPTIONS,
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: TEXT_TRANSFORM_OPTIONS,
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'wordSpacing', label: 'Word spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  TextAtom: {
    type: 'TextAtom',
    label: 'Text atoms',
    icon: 'Folder',
    defaultSettings: {
      text: 'Text',
      alignment: 'left',
      letterGap: 0,
      lineGap: 0,
      wrap: 'wrap',
    },
    settingsSchema: [
      { key: 'text', label: 'Text', type: 'text', defaultValue: 'Text' },
      {
        key: 'alignment',
        label: 'Alignment',
        type: 'alignment',
        defaultValue: 'left',
      },
      { key: 'letterGap', label: 'Letter gap (px)', type: 'number', defaultValue: 0 },
      { key: 'lineGap', label: 'Line gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'wrap',
        label: 'Wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
    ],
  },
  TextAtomLetter: {
    type: 'TextAtomLetter',
    label: 'Text atom',
    icon: 'FileText',
    defaultSettings: {
      textContent: '',
      fontFamily: 'Inter, sans-serif',
      fontSize: 0,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 0,
      letterSpacing: 0,
      textColor: '',
    },
    settingsSchema: [
      {
        key: 'fontFamily',
        label: 'Font family',
        type: 'font-family',
        defaultValue: 'Inter, sans-serif',
      },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '400' },
      {
        key: 'fontStyle',
        label: 'Font style',
        type: 'select',
        options: FONT_STYLE_OPTIONS,
        defaultValue: 'normal',
      },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
    ],
  },
  Button: {
    type: 'Button',
    label: 'Button',
    icon: 'MousePointerClick',
    defaultSettings: {
      buttonLabel: 'Button',
      buttonLink: '',
      buttonStyle: 'solid',
      runtimeActionSource: '',
      runtimeActionPath: '',
      runtimeActionArgs: '',
      buttonDisabled: 'false',
      buttonDisabledSource: '',
      buttonDisabledPath: '',
      buttonDisabledWhen: 'truthy',
    },
    settingsSchema: [
      { key: 'buttonLabel', label: 'Button label', type: 'text', defaultValue: 'Button' },
      { key: 'buttonLink', label: 'Button link', type: 'text', defaultValue: '' },
      {
        key: 'runtimeActionSource',
        label: 'Runtime action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'runtimeActionPath',
        label: 'Runtime action path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'runtimeActionArgs',
        label: 'Runtime action args',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonStyle',
        label: 'Button style',
        type: 'select',
        options: BUTTON_STYLE_OPTIONS,
        defaultValue: 'solid',
      },
      {
        key: 'buttonDisabled',
        label: 'Disabled',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
      {
        key: 'buttonDisabledSource',
        label: 'Disabled source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonDisabledPath',
        label: 'Disabled path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonDisabledWhen',
        label: 'Disable when',
        type: 'select',
        options: DISABLE_WHEN_OPTIONS,
        defaultValue: 'truthy',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      { key: 'bgColor', label: 'Background color', type: 'color', defaultValue: '' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '' },
      { key: 'borderRadius', label: 'Border radius (px)', type: 'number', defaultValue: 0 },
      { key: 'borderWidth', label: 'Border width (px)', type: 'number', defaultValue: 0 },
    ],
  },
  Input: {
    type: 'Input',
    label: 'Input',
    icon: 'TextCursorInput',
    defaultSettings: {
      inputValue: '',
      inputPlaceholder: 'Type here',
      inputAriaLabel: '',
      inputType: 'text',
      inputAutoComplete: '',
      inputMaxLength: 0,
      inputDisabled: 'false',
      inputChangeActionSource: '',
      inputChangeActionPath: '',
      inputSubmitActionSource: '',
      inputSubmitActionPath: '',
      fontFamily: '',
      fontSize: 0,
      fontWeight: '',
      textColor: '',
      bgColor: '',
      borderColor: '',
      borderRadius: 0,
      borderWidth: 0,
      height: 0,
    },
    settingsSchema: [
      { key: 'inputPlaceholder', label: 'Placeholder', type: 'text', defaultValue: 'Type here' },
      { key: 'inputAriaLabel', label: 'Accessible label', type: 'text', defaultValue: '' },
      {
        key: 'inputType',
        label: 'Input type',
        type: 'select',
        options: INPUT_TYPE_OPTIONS,
        defaultValue: 'text',
      },
      { key: 'inputValue', label: 'Default value', type: 'text', defaultValue: '' },
      { key: 'inputAutoComplete', label: 'Autocomplete', type: 'text', defaultValue: '' },
      { key: 'inputMaxLength', label: 'Max length', type: 'number', defaultValue: 0 },
      {
        key: 'inputDisabled',
        label: 'Disabled',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
      {
        key: 'inputChangeActionSource',
        label: 'Change action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputChangeActionPath',
        label: 'Change action path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputSubmitActionSource',
        label: 'Submit action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputSubmitActionPath',
        label: 'Submit action path',
        type: 'text',
        defaultValue: '',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      { key: 'bgColor', label: 'Background color', type: 'color', defaultValue: '' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '' },
      { key: 'borderRadius', label: 'Border radius (px)', type: 'number', defaultValue: 0 },
      { key: 'borderWidth', label: 'Border width (px)', type: 'number', defaultValue: 0 },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 0 },
    ],
  },
  Progress: {
    type: 'Progress',
    label: 'Progress',
    icon: 'Gauge',
    defaultSettings: {
      progressValue: 50,
      progressMax: 100,
      progressHeight: 12,
      borderRadius: 999,
      fillColor: '#6366f1',
      trackColor: '#e2e8f0',
      showPercentage: 'false',
    },
    settingsSchema: [
      { key: 'progressValue', label: 'Value', type: 'number', defaultValue: 50 },
      { key: 'progressMax', label: 'Max', type: 'number', defaultValue: 100 },
      { key: 'progressHeight', label: 'Height (px)', type: 'number', defaultValue: 12 },
      { key: 'borderRadius', label: 'Radius (px)', type: 'number', defaultValue: 999 },
      { key: 'fillColor', label: 'Fill color', type: 'color', defaultValue: '#6366f1' },
      {
        key: 'trackColor',
        label: 'Track color',
        type: 'color',
        defaultValue: '#e2e8f0',
      },
      {
        key: 'showPercentage',
        label: 'Show percentage',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
    ],
  },
  Repeater: {
    type: 'Repeater',
    label: 'Repeater',
    icon: 'ListCollapse',
    allowedBlockTypes: BLOCK_SECTION_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      collectionSource: '',
      collectionPath: '',
      emptyMessage: 'No items to show yet.',
      itemLimit: 0,
      itemsGap: 16,
      listLayoutDirection: 'column',
      listWrap: 'wrap',
      listAlignItems: 'stretch',
      listJustifyContent: 'start',
      itemGap: 12,
      itemLayoutDirection: 'column',
      itemWrap: 'wrap',
      itemAlignItems: 'stretch',
      itemJustifyContent: 'start',
    },
    settingsSchema: [
      { key: 'collectionSource', label: 'Collection source', type: 'text', defaultValue: '' },
      { key: 'collectionPath', label: 'Collection path', type: 'text', defaultValue: '' },
      {
        key: 'emptyMessage',
        label: 'Empty message',
        type: 'text',
        defaultValue: 'No items to show yet.',
      },
      { key: 'itemLimit', label: 'Limit items', type: 'number', defaultValue: 0 },
      { key: 'itemsGap', label: 'Gap between items (px)', type: 'number', defaultValue: 16 },
      {
        key: 'listLayoutDirection',
        label: 'List layout',
        type: 'select',
        options: COLUMN_ROW_OPTIONS,
        defaultValue: 'column',
      },
      {
        key: 'listWrap',
        label: 'List wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'listAlignItems',
        label: 'List align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'stretch',
      },
      {
        key: 'listJustifyContent',
        label: 'List justify content',
        type: 'select',
        options: JUSTIFY_OPTIONS,
        defaultValue: 'start',
      },
      { key: 'itemGap', label: 'Gap inside item (px)', type: 'number', defaultValue: 12 },
      {
        key: 'itemLayoutDirection',
        label: 'Item layout',
        type: 'select',
        options: COLUMN_ROW_OPTIONS,
        defaultValue: 'column',
      },
      {
        key: 'itemWrap',
        label: 'Item wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'itemAlignItems',
        label: 'Item align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'stretch',
      },
      {
        key: 'itemJustifyContent',
        label: 'Item justify content',
        type: 'select',
        options: JUSTIFY_OPTIONS,
        defaultValue: 'start',
      },
    ],
  },
  ImageWithText: {
    type: 'ImageWithText',
    label: 'Image with text',
    icon: 'Layers',
    defaultSettings: {
      imageHeight: 'medium',
      desktopImageWidth: 'medium',
      desktopImagePlacement: 'image-first',
      desktopContentPosition: 'middle',
      desktopContentAlignment: 'left',
      contentLayout: 'no-overlap',
      colorScheme: 'scheme-3',
      containerColorScheme: 'scheme-1',
      imageBehavior: 'none',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'imageHeight',
        label: 'Image height',
        type: 'select',
        options: IMAGE_HEIGHT_OPTIONS,
        defaultValue: 'medium',
      },
      {
        key: 'desktopImagePlacement',
        label: 'Desktop image placement',
        type: 'radio',
        options: IMAGE_PLACEMENT_OPTIONS,
        defaultValue: 'image-first',
      },
      colorSchemeField('colorScheme', 'Color scheme', 'scheme-3'),
      ...paddingFields(),
    ],
  },
  RichText: {
    type: 'RichText',
    label: 'Rich text',
    icon: 'FileText',
    defaultSettings: {
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [colorSchemeField('colorScheme', 'Color scheme'), ...paddingFields()],
  },
  Hero: {
    type: 'Hero',
    label: 'Hero banner',
    icon: 'LayoutTemplate',
    defaultSettings: {
      imageHeight: 'large',
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'imageHeight',
        label: 'Image height',
        type: 'select',
        options: IMAGE_HEIGHT_OPTIONS,
        defaultValue: 'large',
      },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
    ],
  },
};
