import type { BlockDefinition } from '@/features/cms/types/page-builder';

import {
  BUTTON_STYLE_OPTIONS,
  DISABLE_WHEN_OPTIONS,
  FALSE_TRUE_OPTIONS,
  INPUT_TYPE_OPTIONS,
} from './block-definitions-content.constants';

export const contentControlBlockDefinitions: Record<string, BlockDefinition> = {
  Button: {
    type: 'Button',
    label: 'Button',
    icon: 'MousePointerClick',
    defaultSettings: {
      buttonLabel: 'Button',
      buttonLink: '',
      buttonStyle: 'solid',
      runtimeActionSource: '',
      runtimeActionPath: '',
      runtimeActionArgs: '',
      buttonDisabled: 'false',
      buttonDisabledSource: '',
      buttonDisabledPath: '',
      buttonDisabledWhen: 'truthy',
    },
    settingsSchema: [
      { key: 'buttonLabel', label: 'Button label', type: 'text', defaultValue: 'Button' },
      { key: 'buttonLink', label: 'Button link', type: 'text', defaultValue: '' },
      {
        key: 'runtimeActionSource',
        label: 'Runtime action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'runtimeActionPath',
        label: 'Runtime action path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'runtimeActionArgs',
        label: 'Runtime action args',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonStyle',
        label: 'Button style',
        type: 'select',
        options: BUTTON_STYLE_OPTIONS,
        defaultValue: 'solid',
      },
      {
        key: 'buttonDisabled',
        label: 'Disabled',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
      {
        key: 'buttonDisabledSource',
        label: 'Disabled source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonDisabledPath',
        label: 'Disabled path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'buttonDisabledWhen',
        label: 'Disable when',
        type: 'select',
        options: DISABLE_WHEN_OPTIONS,
        defaultValue: 'truthy',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      { key: 'bgColor', label: 'Background color', type: 'color', defaultValue: '' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '' },
      { key: 'borderRadius', label: 'Border radius (px)', type: 'number', defaultValue: 0 },
      { key: 'borderWidth', label: 'Border width (px)', type: 'number', defaultValue: 0 },
    ],
  },
  Input: {
    type: 'Input',
    label: 'Input',
    icon: 'TextCursorInput',
    defaultSettings: {
      inputValue: '',
      inputPlaceholder: 'Type here',
      inputAriaLabel: '',
      inputType: 'text',
      inputAutoComplete: '',
      inputMaxLength: 0,
      inputDisabled: 'false',
      inputChangeActionSource: '',
      inputChangeActionPath: '',
      inputSubmitActionSource: '',
      inputSubmitActionPath: '',
      fontFamily: '',
      fontSize: 0,
      fontWeight: '',
      textColor: '',
      bgColor: '',
      borderColor: '',
      borderRadius: 0,
      borderWidth: 0,
      height: 0,
    },
    settingsSchema: [
      { key: 'inputPlaceholder', label: 'Placeholder', type: 'text', defaultValue: 'Type here' },
      { key: 'inputAriaLabel', label: 'Accessible label', type: 'text', defaultValue: '' },
      {
        key: 'inputType',
        label: 'Input type',
        type: 'select',
        options: INPUT_TYPE_OPTIONS,
        defaultValue: 'text',
      },
      { key: 'inputValue', label: 'Default value', type: 'text', defaultValue: '' },
      { key: 'inputAutoComplete', label: 'Autocomplete', type: 'text', defaultValue: '' },
      { key: 'inputMaxLength', label: 'Max length', type: 'number', defaultValue: 0 },
      {
        key: 'inputDisabled',
        label: 'Disabled',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
      {
        key: 'inputChangeActionSource',
        label: 'Change action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputChangeActionPath',
        label: 'Change action path',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputSubmitActionSource',
        label: 'Submit action source',
        type: 'text',
        defaultValue: '',
      },
      {
        key: 'inputSubmitActionPath',
        label: 'Submit action path',
        type: 'text',
        defaultValue: '',
      },
      { key: 'fontFamily', label: 'Font family', type: 'font-family', defaultValue: '' },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '' },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      { key: 'bgColor', label: 'Background color', type: 'color', defaultValue: '' },
      { key: 'borderColor', label: 'Border color', type: 'color', defaultValue: '' },
      { key: 'borderRadius', label: 'Border radius (px)', type: 'number', defaultValue: 0 },
      { key: 'borderWidth', label: 'Border width (px)', type: 'number', defaultValue: 0 },
      { key: 'height', label: 'Height (px)', type: 'number', defaultValue: 0 },
    ],
  },
  Progress: {
    type: 'Progress',
    label: 'Progress',
    icon: 'Gauge',
    defaultSettings: {
      progressValue: 50,
      progressMax: 100,
      progressHeight: 12,
      borderRadius: 999,
      fillColor: '#6366f1',
      trackColor: '#e2e8f0',
      showPercentage: 'false',
    },
    settingsSchema: [
      { key: 'progressValue', label: 'Value', type: 'number', defaultValue: 50 },
      { key: 'progressMax', label: 'Max', type: 'number', defaultValue: 100 },
      { key: 'progressHeight', label: 'Height (px)', type: 'number', defaultValue: 12 },
      { key: 'borderRadius', label: 'Radius (px)', type: 'number', defaultValue: 999 },
      { key: 'fillColor', label: 'Fill color', type: 'color', defaultValue: '#6366f1' },
      {
        key: 'trackColor',
        label: 'Track color',
        type: 'color',
        defaultValue: '#e2e8f0',
      },
      {
        key: 'showPercentage',
        label: 'Show percentage',
        type: 'select',
        options: FALSE_TRUE_OPTIONS,
        defaultValue: 'false',
      },
    ],
  },
};
