import { BLOCK_DEFINITIONS, BLOCK_SECTION_ALLOWED_BLOCK_TYPES } from './block-definitions';
import {
  WRAP_OPTIONS,
  JUSTIFY_OPTIONS,
  ALIGN_OPTIONS,
  colorSchemeField,
  colorSchemeFieldWithNone,
  paddingFields,
  marginFields,
  layoutFields,
  sectionStyleFields,
} from './shared-field-helpers';

import type { SectionDefinition } from '../../../types/page-builder';

// ---------------------------------------------------------------------------
// Section definitions
// ---------------------------------------------------------------------------

export const SECTION_DEFINITIONS: Record<string, SectionDefinition> = {
  AnnouncementBar: {
    type: 'AnnouncementBar',
    label: 'Announcement bar',
    icon: 'Megaphone',
    allowedBlockTypes: [
      'Announcement',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'Icon',
      'AppEmbed',
    ],
    defaultSettings: {
      colorScheme: 'scheme-2',
      paddingTop: 12,
      paddingBottom: 12,
      paddingLeft: 0,
      paddingRight: 0,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      contentAlignment: 'center',
    },
    settingsSchema: [
      colorSchemeField('colorScheme', 'Color scheme', 'scheme-2'),
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'alignment',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
        defaultValue: 'center',
      },
      ...paddingFields(),
      ...marginFields(),
      ...sectionStyleFields(),
    ],
  },
  Block: {
    type: 'Block',
    label: 'Block',
    icon: 'Box',
    allowedBlockTypes: BLOCK_SECTION_ALLOWED_BLOCK_TYPES,
    defaultSettings: {
      colorScheme: 'none',
      paddingTop: 24,
      paddingBottom: 24,
      paddingLeft: 24,
      paddingRight: 24,
      blockGap: 0,
      marginTop: 0,
      marginBottom: 0,
      marginLeft: 0,
      marginRight: 0,
      contentAlignment: 'left',
      linkUrl: '',
      linkTarget: '_self',
      layoutDirection: 'row',
      wrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'inherit',
      minHeight: 0,
      maxWidth: 0,
      overflow: 'visible',
      opacity: 100,
      zIndex: 0,
      customCss: '',
    },
    settingsSchema: [
      colorSchemeFieldWithNone('colorScheme', 'Color scheme', 'none'),
      { key: 'blockGap', label: 'Content gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'layoutDirection',
        label: 'Layout direction',
        type: 'select',
        options: [
          { label: 'Row', value: 'row' },
          { label: 'Column', value: 'column' },
        ],
        defaultValue: 'row',
      },
      {
        key: 'wrap',
        label: 'Wrap',
        type: 'select',
        options: WRAP_OPTIONS,
        defaultValue: 'wrap',
      },
      {
        key: 'contentAlignment',
        label: 'Content alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
        defaultValue: 'left',
      },
      { key: 'linkUrl', label: 'Block link', type: 'link', defaultValue: '' },
      {
        key: 'linkTarget',
        label: 'Link target',
        type: 'select',
        options: [
          { label: 'Same tab', value: '_self' },
          { label: 'New tab', value: '_blank' },
        ],
        defaultValue: '_self',
      },
      {
        key: 'justifyContent',
        label: 'Justify content',
        type: 'select',
        options: [{ label: 'Inherit alignment', value: 'inherit' }, ...JUSTIFY_OPTIONS],
        defaultValue: 'inherit',
      },
      {
        key: 'alignItems',
        label: 'Align items',
        type: 'select',
        options: ALIGN_OPTIONS,
        defaultValue: 'center',
      },
      ...paddingFields(),
      ...marginFields(),
      ...sectionStyleFields(),
      ...layoutFields(),
    ],
  },
  TextElement: {
    type: 'TextElement',
    label: 'Text element',
    icon: 'FileText',
    allowedBlockTypes: [],
    defaultSettings: {
      textContent: 'Text element',
      fontFamily: 'Inter, sans-serif',
      fontSize: 0,
      fontWeight: '400',
      fontStyle: 'normal',
      lineHeight: 0,
      letterSpacing: 0,
      textColor: '',
      textDecoration: 'none',
      textTransform: 'none',
      textAlign: 'left',
      wordSpacing: 0,
      textShadowX: 0,
      textShadowY: 0,
      textShadowBlur: 0,
      textShadowColor: '#00000000',
    },
    settingsSchema: [
      { key: 'textContent', label: 'Text', type: 'text', defaultValue: 'Text element' },
      {
        key: 'fontFamily',
        label: 'Font family',
        type: 'font-family',
        defaultValue: 'Inter, sans-serif',
      },
      { key: 'fontSize', label: 'Font size (px)', type: 'number', defaultValue: 0 },
      { key: 'fontWeight', label: 'Font weight', type: 'font-weight', defaultValue: '400' },
      {
        key: 'fontStyle',
        label: 'Font style',
        type: 'select',
        options: [
          { label: 'Normal', value: 'normal' },
          { label: 'Italic', value: 'italic' },
        ],
        defaultValue: 'normal',
      },
      { key: 'lineHeight', label: 'Line height', type: 'number', defaultValue: 0 },
      { key: 'letterSpacing', label: 'Letter spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textColor', label: 'Text color', type: 'color', defaultValue: '' },
      {
        key: 'textDecoration',
        label: 'Text decoration',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Underline', value: 'underline' },
          { label: 'Line-through', value: 'line-through' },
        ],
        defaultValue: 'none',
      },
      {
        key: 'textTransform',
        label: 'Text transform',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Uppercase', value: 'uppercase' },
          { label: 'Lowercase', value: 'lowercase' },
          { label: 'Capitalize', value: 'capitalize' },
        ],
        defaultValue: 'none',
      },
      { key: 'textAlign', label: 'Text align', type: 'alignment', defaultValue: 'left' },
      { key: 'wordSpacing', label: 'Word spacing (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowX', label: 'Text shadow X (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowY', label: 'Text shadow Y (px)', type: 'number', defaultValue: 0 },
      { key: 'textShadowBlur', label: 'Text shadow blur (px)', type: 'number', defaultValue: 0 },
      {
        key: 'textShadowColor',
        label: 'Text shadow color',
        type: 'color',
        defaultValue: '#00000000',
      },
    ],
  },
  TextAtom: {
    type: 'TextAtom',
    label: 'Text atoms',
    icon: 'Folder',
    allowedBlockTypes: [],
    defaultSettings: { ...BLOCK_DEFINITIONS['TextAtom']!.defaultSettings },
    settingsSchema: [...BLOCK_DEFINITIONS['TextAtom']!.settingsSchema],
  },
  ImageElement: {
    type: 'ImageElement',
    label: 'Image element',
    icon: 'ImageIcon',
    allowedBlockTypes: [],
    defaultSettings: { ...BLOCK_DEFINITIONS['ImageElement']!.defaultSettings },
    settingsSchema: [...BLOCK_DEFINITIONS['ImageElement']!.settingsSchema],
  },
  Model3DElement: {
    type: 'Model3DElement',
    label: '3D element',
    icon: 'Cube',
    allowedBlockTypes: [],
    defaultSettings: { ...BLOCK_DEFINITIONS['Model3D']!.defaultSettings },
    settingsSchema: [...BLOCK_DEFINITIONS['Model3D']!.settingsSchema],
  },
  ButtonElement: {
    type: 'ButtonElement',
    label: 'Button element',
    icon: 'MousePointerClick',
    allowedBlockTypes: [],
    defaultSettings: { ...BLOCK_DEFINITIONS['Button']!.defaultSettings },
    settingsSchema: [...BLOCK_DEFINITIONS['Button']!.settingsSchema],
  },
  ImageWithText: {
    type: 'ImageWithText',
    label: 'Image with text',
    icon: 'ImageIcon',
    allowedBlockTypes: [
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'AppEmbed',
    ],
    defaultSettings: {
      imageHeight: 'medium',
      desktopImageWidth: 'medium',
      desktopImagePlacement: 'image-first',
      desktopContentPosition: 'middle',
      desktopContentAlignment: 'left',
      contentLayout: 'no-overlap',
      colorScheme: 'scheme-3',
      containerColorScheme: 'scheme-1',
      imageBehavior: 'none',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'imageHeight',
        label: 'Image height',
        type: 'select',
        options: [
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
          { label: 'Adapt to image', value: 'adapt' },
        ],
        defaultValue: 'medium',
      },
      {
        key: 'desktopImageWidth',
        label: 'Desktop image width',
        type: 'select',
        options: [
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
        ],
        defaultValue: 'medium',
      },
      {
        key: 'desktopImagePlacement',
        label: 'Desktop image placement',
        type: 'radio',
        options: [
          { label: 'Image first', value: 'image-first' },
          { label: 'Image second', value: 'image-second' },
        ],
        defaultValue: 'image-first',
      },
      {
        key: 'desktopContentPosition',
        label: 'Desktop content position',
        type: 'select',
        options: [
          { label: 'Top', value: 'top' },
          { label: 'Middle', value: 'middle' },
          { label: 'Bottom', value: 'bottom' },
        ],
        defaultValue: 'middle',
      },
      {
        key: 'desktopContentAlignment',
        label: 'Desktop content alignment',
        type: 'select',
        options: [
          { label: 'Left', value: 'left' },
          { label: 'Center', value: 'center' },
          { label: 'Right', value: 'right' },
        ],
        defaultValue: 'left',
      },
      {
        key: 'contentLayout',
        label: 'Content layout',
        type: 'radio',
        options: [
          { label: 'No overlap', value: 'no-overlap' },
          { label: 'Overlap', value: 'overlap' },
        ],
        defaultValue: 'no-overlap',
      },
      colorSchemeField('colorScheme', 'Color scheme', 'scheme-3'),
      colorSchemeField('containerColorScheme', 'Container color scheme', 'scheme-1'),
      {
        key: 'imageBehavior',
        label: 'Image behavior',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Ambient movement', value: 'ambient' },
          { label: 'Zoom in on scroll', value: 'zoom-scroll' },
        ],
        defaultValue: 'none',
      },
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  RichText: {
    type: 'RichText',
    label: 'Rich text',
    icon: 'FileText',
    allowedBlockTypes: [
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'AppEmbed',
    ],
    defaultSettings: {
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  Grid: {
    type: 'Grid',
    label: 'Grid',
    icon: 'LayoutGrid',
    allowedBlockTypes: ['Row', 'ImageElement'],
    defaultSettings: {
      rows: 1,
      columns: 2,
      gap: 'medium',
      rowGap: 'inherit',
      columnGap: 'inherit',
      rowGapPx: 0,
      columnGapPx: 0,
      paddingTop: 36,
      paddingBottom: 36,
      marginTop: 0,
      marginBottom: 0,
      colorScheme: 'scheme-1',
      minHeight: 0,
      maxWidth: 0,
      overflow: 'visible',
      opacity: 100,
      zIndex: 0,
      customCss: '',
    },
    settingsSchema: [
      { key: 'rows', label: 'Rows', type: 'range', defaultValue: 1, min: 1, max: 8 },
      { key: 'columns', label: 'Columns', type: 'range', defaultValue: 2, min: 1, max: 12 },
      {
        key: 'gap',
        label: 'Gap',
        type: 'select',
        options: [
          { label: 'None', value: 'none' },
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
        ],
        defaultValue: 'medium',
      },
      {
        key: 'rowGap',
        label: 'Row gap',
        type: 'select',
        options: [
          { label: 'Inherit grid gap', value: 'inherit' },
          { label: 'None', value: 'none' },
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
        ],
        defaultValue: 'inherit',
      },
      { key: 'rowGapPx', label: 'Row gap (px)', type: 'number', defaultValue: 0 },
      {
        key: 'columnGap',
        label: 'Column gap',
        type: 'select',
        options: [
          { label: 'Inherit grid gap', value: 'inherit' },
          { label: 'None', value: 'none' },
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
        ],
        defaultValue: 'inherit',
      },
      { key: 'columnGapPx', label: 'Column gap (px)', type: 'number', defaultValue: 0 },
      ...paddingFields(),
      ...marginFields(),
      colorSchemeField('colorScheme', 'Color scheme'),
      ...sectionStyleFields(),
      ...layoutFields(),
    ],
  },

  Hero: {
    type: 'Hero',
    label: 'Hero banner',
    icon: 'LayoutTemplate',
    allowedBlockTypes: [
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'AppEmbed',
    ],
    defaultSettings: {
      imageHeight: 'large',
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'image', label: 'Image', type: 'image' },
      {
        key: 'imageHeight',
        label: 'Image height',
        type: 'select',
        options: [
          { label: 'Small', value: 'small' },
          { label: 'Medium', value: 'medium' },
          { label: 'Large', value: 'large' },
          { label: 'Adapt to image', value: 'adapt' },
        ],
        defaultValue: 'large',
      },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  Accordion: {
    type: 'Accordion',
    label: 'Accordion',
    icon: 'ListCollapse',
    allowedBlockTypes: ['Heading', 'Text', 'TextElement', 'TextAtom', 'ImageElement', 'AppEmbed'],
    defaultSettings: {
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  Testimonials: {
    type: 'Testimonials',
    label: 'Testimonials',
    icon: 'Quote',
    allowedBlockTypes: [
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Image',
      'AppEmbed',
    ],
    defaultSettings: {
      layout: 'grid',
      columns: 3,
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      {
        key: 'layout',
        label: 'Layout',
        type: 'select',
        options: [
          { label: 'Grid', value: 'grid' },
          { label: 'Carousel', value: 'carousel' },
        ],
        defaultValue: 'grid',
      },
      { key: 'columns', label: 'Columns', type: 'range', defaultValue: 3, min: 1, max: 4 },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  Video: {
    type: 'Video',
    label: 'Video',
    icon: 'Video',
    allowedBlockTypes: [],
    defaultSettings: {
      videoUrl: '',
      aspectRatio: '16:9',
      autoplay: 'no',
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'videoUrl', label: 'Video URL', type: 'text', defaultValue: '' },
      {
        key: 'aspectRatio',
        label: 'Aspect ratio',
        type: 'select',
        options: [
          { label: '16:9', value: '16:9' },
          { label: '4:3', value: '4:3' },
          { label: '1:1', value: '1:1' },
        ],
        defaultValue: '16:9',
      },
      {
        key: 'autoplay',
        label: 'Autoplay',
        type: 'select',
        options: [
          { label: 'No', value: 'no' },
          { label: 'Yes', value: 'yes' },
        ],
        defaultValue: 'no',
      },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  Slideshow: {
    type: 'Slideshow',
    label: 'Slideshow',
    icon: 'GalleryHorizontal',
    allowedBlockTypes: [
      'SlideshowFrame',
      'Block',
      'Image',
      'Heading',
      'Text',
      'TextElement',
      'TextAtom',
      'ImageElement',
      'Button',
      'AppEmbed',
    ],
    defaultSettings: { ...BLOCK_DEFINITIONS['Slideshow']!.defaultSettings },
    settingsSchema: [...BLOCK_DEFINITIONS['Slideshow']!.settingsSchema, ...sectionStyleFields()],
  },

  Newsletter: {
    type: 'Newsletter',
    label: 'Newsletter',
    icon: 'Mail',
    allowedBlockTypes: ['Heading', 'Text', 'TextElement', 'TextAtom', 'ImageElement', 'AppEmbed'],
    defaultSettings: {
      buttonText: 'Subscribe',
      placeholder: 'Enter your email',
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      { key: 'buttonText', label: 'Button text', type: 'text', defaultValue: 'Subscribe' },
      { key: 'placeholder', label: 'Placeholder', type: 'text', defaultValue: 'Enter your email' },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },

  ContactForm: {
    type: 'ContactForm',
    label: 'Contact form',
    icon: 'Send',
    allowedBlockTypes: [],
    defaultSettings: {
      fields: 'name,email,message',
      submitText: 'Send message',
      successMessage: 'Thank you! We will be in touch.',
      colorScheme: 'scheme-1',
      paddingTop: 36,
      paddingBottom: 36,
    },
    settingsSchema: [
      {
        key: 'fields',
        label: 'Fields (comma-separated)',
        type: 'text',
        defaultValue: 'name,email,message',
      },
      {
        key: 'submitText',
        label: 'Submit button text',
        type: 'text',
        defaultValue: 'Send message',
      },
      {
        key: 'successMessage',
        label: 'Success message',
        type: 'text',
        defaultValue: 'Thank you! We will be in touch.',
      },
      colorSchemeField('colorScheme', 'Color scheme'),
      ...paddingFields(),
      ...sectionStyleFields(),
    ],
  },
};
