export const QUICK_START_OPERATIONS = new Set([
  'addition',
  'subtraction',
  'multiplication',
  'division',
  'decimals',
  'powers',
  'roots',
  'clock',
  'mixed',
]);

export const ACTIVITY_PRIMARY_TO_OPERATION: Record<string, string> = {
  adding: 'addition',
  addition: 'addition',
  subtracting: 'subtraction',
  subtraction: 'subtraction',
  multiplication: 'multiplication',
  division: 'division',
  decimals: 'decimals',
  powers: 'powers',
  roots: 'roots',
  mixed: 'mixed',
  clock: 'clock',
  calendar: 'calendar',
  geometry: 'geometry',
  geometry_shape_recognition: 'geometry',
  geometry_basics: 'geometry',
  geometry_shapes: 'geometry',
  geometry_symmetry: 'geometry',
  geometry_perimeter: 'geometry',
  art_colors_harmony: 'art_colors_harmony',
  art_shapes_basic: 'art_shapes_basic',
  music_diatonic_scale: 'music_diatonic_scale',
  logical_thinking: 'logical',
  logical_patterns: 'logical',
  logical_classification: 'logical',
  logical_reasoning: 'logical',
  logical_analogies: 'logical',
  english_pronoun_remix: 'english_basics',
  english_parts_of_speech_sort: 'english_parts_of_speech',
  english_pronouns_warmup: 'english_parts_of_speech',
  english_sentence_structure_quiz: 'english_sentence_structure',
  english_subject_verb_agreement_quiz: 'english_subject_verb_agreement',
  english_going_to_plan_parade: 'english_going_to',
  english_articles_drag_drop: 'english_articles',
  english_adjectives_scene_studio: 'english_adjectives',
  english_adverbs_action_studio: 'english_adverbs',
  english_adverbs_frequency_routine_studio: 'english_adverbs_frequency',
  english_prepositions_quiz: 'english_prepositions_time_place',
  english_prepositions_sort: 'english_prepositions_time_place',
  english_prepositions_order: 'english_prepositions_time_place',
};
