import type { AiNode, DbQueryConfig, Edge, NodeType } from "@/shared/types/ai-paths";

export const NODE_WIDTH = 280;
export const NODE_MIN_HEIGHT = 160;
export const CANVAS_WIDTH = 2200;
export const CANVAS_HEIGHT = 1400;
export const MIN_SCALE = 0.5;
export const MAX_SCALE = 1.6;
export const VIEW_MARGIN = 40;
export const PORT_GAP = 18;
export const PORT_SIZE = 10;
export const DEFAULT_CONTEXT_ROLE = "entity";
export const CACHEABLE_NODE_TYPES: NodeType[] = [
  "constant",
  "math",
  "compare",
  "router",
  "gate",
  "bundle",
  "template",
  "prompt",
  "regex",
  "mapper",
  "mutator",
  "validator",
  "viewer",
];
export const CACHEABLE_NODE_TYPE_SET = new Set<NodeType>(CACHEABLE_NODE_TYPES);
export const TRIGGER_INPUT_PORTS = ["context"];
export const TRIGGER_OUTPUT_PORTS = ["trigger", "triggerName", "context", "meta", "entityId", "entityType"];
export const CONTEXT_INPUT_PORTS = ["context"];
export const CONTEXT_OUTPUT_PORTS = ["context", "entityId", "entityType", "entityJson"];
export const SIMULATION_INPUT_PORTS = ["trigger"];
export const SIMULATION_OUTPUT_PORTS = ["context", "entityId", "entityType", "productId"];
export const DESCRIPTION_OUTPUT_PORTS = ["description_en"];
export const BUNDLE_INPUT_PORTS = [
  "context",
  "meta",
  "trigger",
  "triggerName",
  "result",
  "entityJson",
  "entityId",
  "entityType",
  "value",
  "errors",
  "valid",
  "description_en",
  "prompt",
];
export const TEMPLATE_INPUT_PORTS = [
  "context",
  "meta",
  "trigger",
  "triggerName",
  "result",
  "entityJson",
  "entityId",
  "entityType",
  "value",
  "bundle",
  "description_en",
  "prompt",
];
export const ROUTER_INPUT_PORTS = [
  "context",
  "bundle",
  "prompt",
  "result",
  "value",
  "valid",
  "errors",
];
export const ROUTER_OUTPUT_PORTS = [
  "context",
  "bundle",
  "prompt",
  "result",
  "value",
  "valid",
  "errors",
];
export const DELAY_INPUT_PORTS = ["context", "bundle", "prompt", "result", "value"];
export const DELAY_OUTPUT_PORTS = ["context", "bundle", "prompt", "result", "value"];
export const HTTP_INPUT_PORTS = [
  "context",
  "bundle",
  "prompt",
  "result",
  "value",
  "entityId",
  "entityType",
];
export const DATABASE_INPUT_PORTS = [
  "entityId",
  "entityType",
  "productId",
  "context",
  "query",
  "value",
  "bundle",
  "result",
  "content_en",
  "queryCallback",
  "schema",
  "aiQuery",
];
export const REGEX_INPUT_PORTS = ["value", "prompt", "regexCallback"];
export const REGEX_OUTPUT_PORTS = ["grouped", "matches", "value", "aiPrompt"];
export const ITERATOR_INPUT_PORTS = ["value", "callback"];
export const ITERATOR_OUTPUT_PORTS = ["value", "index", "total", "done", "status"];
export const DEFAULT_DB_QUERY: DbQueryConfig = {
  provider: "mongodb",
  collection: "products",
  mode: "preset",
  preset: "by_id",
  field: "_id",
  idType: "string",
  queryTemplate: "{\n  \"_id\": \"{{value}}\"\n}",
  limit: 20,
  sort: "",
  sortPresetId: "custom",
  projection: "",
  projectionPresetId: "custom",
  single: false,
};

export const DB_COLLECTION_OPTIONS = [
  { value: "products", label: "Products" },
  { value: "product_drafts", label: "Product Drafts" },
  { value: "product_categories", label: "Product Categories" },
  { value: "product_tags", label: "Product Tags" },
  { value: "catalogs", label: "Catalogs" },
  { value: "image_files", label: "Image Files" },
  { value: "product_listings", label: "Product Listings" },
  { value: "product_ai_jobs", label: "Product AI Jobs" },
  { value: "integrations", label: "Integrations" },
  { value: "integration_connections", label: "Integration Connections" },
  { value: "settings", label: "Settings" },
  { value: "users", label: "Users" },
  { value: "user_preferences", label: "User Preferences" },
  { value: "languages", label: "Languages" },
  { value: "system_logs", label: "System Logs" },
  { value: "notes", label: "Notes" },
  { value: "tags", label: "Note Tags" },
  { value: "categories", label: "Note Categories" },
  { value: "notebooks", label: "Note Notebooks" },
  { value: "noteFiles", label: "Note Files" },
  { value: "themes", label: "Note Themes" },
  { value: "chatbot_sessions", label: "Chatbot Sessions" },
  { value: "auth_security_attempts", label: "Auth Security Attempts" },
  { value: "auth_security_profiles", label: "Auth Security Profiles" },
  { value: "auth_login_challenges", label: "Auth Login Challenges" },
  { value: "custom", label: "Custom (allowlisted only)" },
];

export const CONTEXT_PRESET_FIELDS: Record<
  string,
  { light: string[]; medium: string[]; full: string[]; suggested: string[] }
> = {
  product: {
    light: ["id", "sku", "name_en", "name_pl", "name_de", "price", "stock", "imageLinks"],
    medium: [
      "id",
      "sku",
      "name_en",
      "name_pl",
      "name_de",
      "price",
      "stock",
      "imageLinks",
      "description_en",
      "description_pl",
      "description_de",
      "catalogs",
      "parameters",
      "supplierName",
      "supplierLink",
      "createdAt",
      "updatedAt",
    ],
    full: [],
    suggested: [
      "id",
      "sku",
      "name_en",
      "name_pl",
      "name_de",
      "description_en",
      "price",
      "stock",
      "imageLinks",
      "catalogs",
      "parameters",
      "supplierName",
      "supplierLink",
      "createdAt",
      "updatedAt",
    ],
  },
  note: {
    light: ["id", "title", "content", "notebookId", "isPinned", "isFavorite", "updatedAt"],
    medium: [
      "id",
      "title",
      "content",
      "notebookId",
      "isPinned",
      "isFavorite",
      "isArchived",
      "editorType",
      "color",
      "tags",
      "categories",
      "createdAt",
      "updatedAt",
    ],
    full: [],
    suggested: [
      "id",
      "title",
      "content",
      "notebookId",
      "tags",
      "categories",
      "relationsFrom",
      "relationsTo",
      "isPinned",
      "isFavorite",
      "isArchived",
      "editorType",
      "color",
      "createdAt",
      "updatedAt",
    ],
  },
  default: {
    light: ["id", "name", "title", "status", "updatedAt"],
    medium: ["id", "name", "title", "status", "createdAt", "updatedAt", "meta"],
    full: [],
    suggested: ["id", "name", "title", "status", "createdAt", "updatedAt", "meta"],
  },
};

export const PARSER_PRESETS = [
  {
    id: "product_core",
    label: "Product: Core",
    description: "id, title, images, content_en, sku, price, stock",
    mappings: {
      productId: "$.id",
      title: "$.title",
      images: "$.images",
      content_en: "$.content_en",
      sku: "$.sku",
      price: "$.price",
      stock: "$.stock",
    },
  },
  {
    id: "product_media",
    label: "Product: Media",
    description: "imageLinks, gallery, videos",
    mappings: {
      images: "$.imageLinks",
      gallery: "$.gallery",
      videos: "$.videos",
    },
  },
  {
    id: "note_core",
    label: "Note: Core",
    description: "id, title, content, tags, updatedAt",
    mappings: {
      noteId: "$.id",
      title: "$.title",
      content: "$.content",
      tags: "$.tags",
      updatedAt: "$.updatedAt",
    },
  },
  {
    id: "chat_message",
    label: "Chat: Message",
    description: "id, role, content, createdAt",
    mappings: {
      messageId: "$.id",
      role: "$.role",
      content: "$.content",
      createdAt: "$.createdAt",
    },
  },
  {
    id: "generic_audit",
    label: "Generic: Audit",
    description: "id, name, title, status, createdAt, updatedAt",
    mappings: {
      id: "$.id",
      name: "$.name",
      title: "$.title",
      status: "$.status",
      createdAt: "$.createdAt",
      updatedAt: "$.updatedAt",
    },
  },
];

export const PARSER_PATH_OPTIONS = [
  { label: "Common: id", value: "$.id" },
  { label: "Common: title", value: "$.title" },
  { label: "Common: name", value: "$.name" },
  { label: "Common: status", value: "$.status" },
  { label: "Common: createdAt", value: "$.createdAt" },
  { label: "Common: updatedAt", value: "$.updatedAt" },
  { label: "Product: sku", value: "$.sku" },
  { label: "Product: price", value: "$.price" },
  { label: "Product: stock", value: "$.stock" },
  { label: "Product: content_en", value: "$.content_en" },
  { label: "Product: name_en", value: "$.name_en" },
  { label: "Product: name_pl", value: "$.name_pl" },
  { label: "Product: imageLinks", value: "$.imageLinks" },
  { label: "Product: images", value: "$.images" },
  { label: "Product: media", value: "$.media" },
  { label: "Product: gallery", value: "$.gallery" },
  { label: "Product: supplierName", value: "$.supplierName" },
  { label: "Product: catalogs", value: "$.catalogs" },
  { label: "Note: content", value: "$.content" },
  { label: "Note: tags", value: "$.tags" },
  { label: "Note: notebookId", value: "$.notebookId" },
  { label: "Chat: role", value: "$.role" },
  { label: "Chat: messages[0].content", value: "$.messages[0].content" },
];

export const VIEWER_INPUT_PORTS = [
  "result",
  "sources",
  "grouped",
  "matches",
  "index",
  "total",
  "done",
  "analysis",
  "description",
  "description_en",
  "prompt",
  "images",
  "title",
  "productId",
  "content_en",
  "context",
  "meta",
  "trigger",
  "triggerName",
  "jobId",
  "status",
  "entityId",
  "entityType",
  "entityJson",
  "bundle",
  "valid",
  "errors",
  "value",
  "queryCallback",
  "aiPrompt",
];
export const PROMPT_INPUT_PORTS = ["bundle", "title", "images", "result"];
export const PROMPT_OUTPUT_PORTS = ["prompt", "images"];
export const POLL_INPUT_PORTS = ["jobId", "query", "value", "entityId", "productId", "bundle"];
export const POLL_OUTPUT_PORTS = ["result", "status", "jobId", "bundle"];
export const MODEL_OUTPUT_PORTS = ["result", "jobId"];
export const AGENT_INPUT_PORTS = [
  "prompt",
  "bundle",
  "context",
  "entityJson",
  "value",
  "result",
  "title",
  "images",
  "content_en",
  "entityId",
  "entityType",
  "productId",
];
export const AGENT_OUTPUT_PORTS = ["result", "jobId", "status", "bundle"];
export const LEARNER_AGENT_INPUT_PORTS = AGENT_INPUT_PORTS;
export const LEARNER_AGENT_OUTPUT_PORTS = ["result", "sources", "status", "bundle"];
export const NOTIFICATION_INPUT_PORTS = [
  "result",
  "prompt",
  "value",
  "bundle",
  "context",
  "meta",
  "trigger",
  "triggerName",
  "entityId",
];

export const PATH_INDEX_KEY = "ai_paths_index";
export const AI_PATHS_LAST_ERROR_KEY = "ai_paths_last_error";
export const PATH_CONFIG_PREFIX = "ai_paths_config_";
export const PATH_DEBUG_PREFIX = "ai_paths_debug_";
export const CLUSTER_PRESETS_KEY = "ai_paths_cluster_presets";
export const DB_QUERY_PRESETS_KEY = "ai_paths_db_query_presets";
export const DB_NODE_PRESETS_KEY = "ai_paths_db_node_presets";
export const AI_PATHS_UI_STATE_KEY = "ai_paths_ui_state";
export const AI_PATHS_LOCAL_RUNS_KEY = "ai_paths_local_runs";
export const STORAGE_VERSION = 1;
export const DEFAULT_MODELS = ["gpt-4o", "gpt-4-turbo", "gpt-3.5-turbo"];
export const TRIGGER_EVENTS = [
  // Default trigger for interactive / client-driven runs.
  { id: "manual", label: "Manual / UI Trigger" },
  { id: "scheduled_run", label: "Scheduled Run (Server)" },
];

export const PORT_COMPATIBILITY: Record<string, string[]> = {
  entityJson: ["entityJson", "context", "value", "result", "bundle"],
  productId: ["productId", "entityId", "value", "result"],
  entityId: ["entityId", "productId", "value", "result"],
  entityType: ["entityType", "value", "result"],
  trigger: ["trigger", "value", "result"],
  triggerName: ["triggerName", "value", "result"],
  prompt: ["prompt"],
  result: ["result", "value", "queryCallback", "aiQuery", "callback", "regexCallback"],
  sources: ["sources", "value", "result", "bundle"],
  images: ["images", "value", "result"],
  title: ["title", "value", "result", "prompt", "aiPrompt"],
  content_en: ["content_en", "value", "result", "description_en", "prompt", "aiPrompt"],
  context: ["context", "entityJson", "value", "result", "bundle"],
  simulation: ["context", "simulation"],
  meta: ["meta", "value", "result"],
  bundle: ["bundle", "context", "value", "result", "callback"],
  value: [
    "value",
    "result",
    "query",
    "jobId",
    "status",
    "prompt",
    "aiPrompt",
    "queryCallback",
    "callback",
    "regexCallback",
  ],
  query: ["query", "value", "result"],
  jobId: ["jobId", "value", "result", "callback"],
  status: ["status", "value", "result", "callback"],
  description_en: ["description_en", "content_en", "value", "result"],
  valid: ["valid", "value", "result"],
  errors: ["errors", "value", "result"],
  queryCallback: ["queryCallback", "aiPrompt", "value", "result", "callback"],
  aiPrompt: ["prompt"],
  schema: ["schema"],
  aiQuery: ["aiQuery", "query", "queryCallback", "value", "callback"],
  grouped: ["grouped", "result", "value", "bundle", "query", "aiQuery", "queryCallback"],
  matches: ["matches", "result", "value", "bundle"],
  callback: ["callback"],
  index: ["index", "value", "result"],
  total: ["total", "value", "result"],
  done: ["done", "valid", "value", "result"],
};

export const NODE_TYPE_COMPATIBILITY: Record<NodeType, NodeType[]> = {
  context: [
    "trigger",
    "parser",
    "iterator",
    "viewer",
    "notification",
    "ai_description",
    "mapper",
    "mutator",
    "validator",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "http",
    "database",
  ],
  trigger: [
    "context",
    "parser",
    "iterator",
    "viewer",
    "notification",
    "mapper",
    "mutator",
    "validator",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "database",
    "simulation",
  ],
  simulation: ["trigger", "notification"],
  parser: [
    "prompt",
    "iterator",
    "regex",
    "database",
    "viewer",
    "notification",
    "ai_description",
    "description_updater",
    "mapper",
    "mutator",
    "validator",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "database",
  ],
  mapper: [
    "prompt",
    "iterator",
    "regex",
    "mutator",
    "validator",
    "viewer",
    "ai_description",
    "description_updater",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "database",
    "trigger",
  ],
  mutator: [
    "validator",
    "viewer",
    "prompt",
    "iterator",
    "regex",
    "ai_description",
    "description_updater",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "database",
  ],
  validator: [
    "viewer",
    "prompt",
    "iterator",
    "regex",
    "ai_description",
    "description_updater",
    "gate",
    "bundle",
    "template",
    "router",
    "delay",
    "poll",
    "database",
  ],
  constant: ["math", "template", "viewer", "bundle", "compare", "router", "delay", "poll", "http", "database"],
  math: ["template", "viewer", "bundle", "compare", "router", "delay", "poll", "http", "database"],
  compare: ["gate", "router", "viewer", "bundle", "template", "poll", "database"],
  gate: ["validator", "viewer", "prompt", "ai_description", "description_updater", "bundle", "template", "router", "delay", "poll"],
  router: ["viewer", "bundle", "template", "prompt", "model", "agent", "learner_agent", "delay", "poll", "database"],
  regex: ["viewer", "bundle", "template", "prompt", "model", "agent", "learner_agent", "delay", "poll", "database"],
  iterator: ["viewer", "bundle", "template", "prompt", "model", "agent", "learner_agent", "delay", "poll", "database", "notification"],
  delay: ["viewer", "bundle", "template", "prompt", "model", "agent", "learner_agent", "validator", "gate", "poll", "database"],
  poll: ["viewer", "notification", "bundle", "template", "prompt", "model", "agent", "learner_agent", "delay", "database"],
  http: ["viewer", "bundle", "template", "prompt", "math", "compare", "poll", "database"],
  database: ["viewer", "bundle", "template", "prompt", "mapper", "validator", "iterator", "poll", "notification", "model", "agent", "learner_agent"],
  db_schema: ["prompt", "template", "model", "agent", "learner_agent", "bundle", "viewer", "database"],
  bundle: ["viewer", "template", "prompt", "poll", "database"],
  template: ["model", "agent", "learner_agent", "viewer", "bundle", "prompt", "poll", "database", "iterator"],
  prompt: ["model", "agent", "learner_agent", "viewer", "bundle", "template", "poll", "notification", "iterator"],
  model: ["prompt", "database", "viewer", "description_updater", "bundle", "poll", "notification", "agent", "learner_agent", "iterator"],
  agent: ["viewer", "bundle", "template", "prompt", "database", "description_updater", "notification", "delay", "learner_agent"],
  learner_agent: ["viewer", "bundle", "template", "prompt", "database", "notification", "delay"],
  viewer: [],
  ai_description: ["viewer", "description_updater", "bundle", "delay", "poll"],
  description_updater: ["viewer", "bundle", "delay", "poll"],
  notification: ["viewer", "bundle", "delay", "poll"],
};

export const typeStyles: Record<NodeType, { border: string; glow: string }> = {
  trigger: { border: "border-lime-500/40", glow: "shadow-lime-500/20" },
  simulation: { border: "border-cyan-500/40", glow: "shadow-cyan-500/20" },
  context: { border: "border-emerald-500/40", glow: "shadow-emerald-500/20" },
  parser: { border: "border-sky-500/40", glow: "shadow-sky-500/20" },
  regex: { border: "border-cyan-500/40", glow: "shadow-cyan-500/20" },
  iterator: { border: "border-amber-500/40", glow: "shadow-amber-500/20" },
  mapper: { border: "border-blue-500/40", glow: "shadow-blue-500/20" },
  mutator: { border: "border-teal-500/40", glow: "shadow-teal-500/20" },
  validator: { border: "border-orange-500/40", glow: "shadow-orange-500/20" },
  constant: { border: "border-slate-400/40", glow: "shadow-slate-500/20" },
  math: { border: "border-yellow-500/40", glow: "shadow-yellow-500/20" },
  gate: { border: "border-red-500/40", glow: "shadow-red-500/20" },
  bundle: { border: "border-cyan-400/40", glow: "shadow-cyan-500/20" },
  template: { border: "border-lime-500/40", glow: "shadow-lime-500/20" },
  compare: { border: "border-amber-300/40", glow: "shadow-amber-300/20" },
  router: { border: "border-pink-500/40", glow: "shadow-pink-500/20" },
  delay: { border: "border-indigo-400/40", glow: "shadow-indigo-400/20" },
  poll: { border: "border-cyan-300/40", glow: "shadow-cyan-300/20" },
  http: { border: "border-sky-400/40", glow: "shadow-sky-400/20" },
  database: { border: "border-emerald-500/40", glow: "shadow-emerald-500/20" },
  db_schema: { border: "border-purple-500/40", glow: "shadow-purple-500/20" },
  prompt: { border: "border-amber-500/40", glow: "shadow-amber-500/20" },
  model: { border: "border-fuchsia-500/40", glow: "shadow-fuchsia-500/20" },
  agent: { border: "border-emerald-400/40", glow: "shadow-emerald-400/20" },
  learner_agent: { border: "border-emerald-300/40", glow: "shadow-emerald-300/20" },
  viewer: { border: "border-violet-500/40", glow: "shadow-violet-500/20" },
  notification: { border: "border-amber-400/40", glow: "shadow-amber-500/20" },
  ai_description: { border: "border-indigo-500/40", glow: "shadow-indigo-500/20" },
  description_updater: { border: "border-rose-400/40", glow: "shadow-rose-400/20" },
};

export const triggers = [
  "Product Modal - Context Filter",
  "Bulk Action - Generate Descriptions",
  "On Product Save",
];

export const initialNodes: AiNode[] = [
  {
    id: "node-context",
    type: "context",
    title: "Context Filter",
    description: "Filter Product modal context into scoped fields.",
    inputs: CONTEXT_INPUT_PORTS,
    outputs: CONTEXT_OUTPUT_PORTS,
    position: { x: 520, y: 590 },
    config: {
      context: {
        role: DEFAULT_CONTEXT_ROLE,
      },
    },
  },
  {
    id: "node-parser",
    type: "parser",
    title: "JSON Parser",
    description: "Extract [images], [title], [productId], [content_en].",
    inputs: ["entityJson"],
    outputs: ["images", "title", "productId", "content_en"],
    position: { x: 820, y: 590 },
    config: {
      parser: {
        mappings: {
          images: "$.images",
          title: "$.title",
          productId: "$.id",
          content_en: "$.content_en",
        },
      },
    },
  },
  {
    id: "node-vision-prompt",
    type: "prompt",
    title: "Vision Prompt",
    description: "Prompt: Analyze [images] and [title].",
    inputs: ["images", "title"],
    outputs: PROMPT_OUTPUT_PORTS,
    position: { x: 1120, y: 510 },
  },
  {
    id: "node-vision-model",
    type: "model",
    title: "Gemma Vision",
    description: "Image analysis.",
    inputs: ["prompt", "images"],
    outputs: MODEL_OUTPUT_PORTS,
    position: { x: 1400, y: 510 },
    config: {
      model: {
        modelId: "gemma",
        temperature: 0.4,
        maxTokens: 512,
        vision: true,
      },
    },
  },
  {
    id: "node-desc-prompt",
    type: "prompt",
    title: "Description Prompt",
    description: "Prompt: Use [result] and [title].",
    inputs: ["result", "title"],
    outputs: PROMPT_OUTPUT_PORTS,
    position: { x: 1120, y: 690 },
  },
  {
    id: "node-desc-model",
    type: "model",
    title: "GPT-4o",
    description: "Generate description.",
    inputs: ["prompt"],
    outputs: MODEL_OUTPUT_PORTS,
    position: { x: 1400, y: 690 },
    config: {
      model: {
        modelId: "gpt-4o",
        temperature: 0.6,
        maxTokens: 900,
        vision: false,
      },
    },
  },
  {
    id: "node-updater",
    type: "database",
    title: "Database Update",
    description: "Update product fields from AI results.",
    inputs: DATABASE_INPUT_PORTS,
    outputs: ["result", "bundle", "content_en", "aiPrompt"],
    position: { x: 1680, y: 600 },
    config: {
      database: {
        operation: "update",
        entityType: "product",
        idField: "productId",
        mode: "replace",
        mappings: [
          {
            targetPath: "content_en",
            sourcePort: "result",
          },
        ],
        query: {
          provider: "mongodb",
          collection: "products",
          mode: "preset",
          preset: "by_id",
          field: "_id",
          idType: "string",
          queryTemplate: "{\n  \"_id\": \"{{value}}\"\n}",
          limit: 20,
          sort: "",
          projection: "",
          single: false,
          },
        writeSource: "bundle",
        aiPrompt: "",
      },
    },
  },
];

export const initialEdges: Edge[] = [
  { id: "edge-1", from: "node-context", to: "node-parser", fromPort: "entityJson", toPort: "entityJson" },
  { id: "edge-2", from: "node-parser", to: "node-vision-prompt", fromPort: "images", toPort: "images" },
  { id: "edge-3", from: "node-parser", to: "node-vision-prompt", fromPort: "title", toPort: "title" },
  { id: "edge-4", from: "node-vision-prompt", to: "node-vision-model", fromPort: "prompt", toPort: "prompt" },
  { id: "edge-5", from: "node-vision-model", to: "node-desc-prompt", fromPort: "result", toPort: "result" },
  { id: "edge-6", from: "node-desc-prompt", to: "node-desc-model", fromPort: "prompt", toPort: "prompt" },
  { id: "edge-7", from: "node-desc-model", to: "node-updater", fromPort: "result", toPort: "result" },
  { id: "edge-8", from: "node-parser", to: "node-updater", fromPort: "productId", toPort: "productId" },
  { id: "edge-9", from: "node-parser", to: "node-updater", fromPort: "content_en", toPort: "content_en" },
];
