export type PromptExploderTooltipDocEntry = {
  id: string;
  title: string;
  summary: string;
  section: string;
  aliases: string[];
  docPath: string;
};

export const PROMPT_EXPLODER_TOOLTIP_CATALOG: PromptExploderTooltipDocEntry[] = [
  {
    id: 'workflow_overview',
    title: 'Prompt Exploder Workflow',
    summary:
      'Load prompt text, explode into segments, refine structure, validate warnings and metrics, then reassemble and apply.',
    section: 'Overview',
    aliases: ['workflow', 'overview', 'prompt exploder'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'docs_tooltips_toggle',
    title: 'Docs Tooltips',
    summary:
      'Toggles docs-driven tooltips for all Prompt Exploder interactive controls in the current route.',
    section: 'Header Actions',
    aliases: ['docs tooltips', 'enable docs tooltips', 'prompt-exploder-docs-tooltips'],
    docPath: '/docs/PROMPT_EXPLODER_TOOLTIP_GUIDE.md',
  },
  {
    id: 'reload_incoming_draft',
    title: 'Reload Incoming Draft',
    summary: 'Re-reads the latest bridged prompt payload from Image Studio or Case Resolver.',
    section: 'Header Actions',
    aliases: ['reload incoming draft', 'reload draft'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'open_settings',
    title: 'Settings',
    summary: 'Opens Prompt Exploder settings for runtime, learning, and AI configuration.',
    section: 'Header Actions',
    aliases: ['settings', 'open settings'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'back_to_source',
    title: 'Back To Source',
    summary: 'Navigates back to the caller page (Image Studio or Case Resolver).',
    section: 'Header Actions',
    aliases: ['back to case resolver', 'back to image studio'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'source_prompt_text',
    title: 'Source Prompt Input',
    summary: 'Raw prompt text that is parsed into typed segments.',
    section: 'Source Prompt',
    aliases: ['paste prompt text', 'source prompt'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'explode_prompt',
    title: 'Explode Prompt',
    summary: 'Runs segmentation and refreshes segments, metrics, warnings, and bindings.',
    section: 'Source Prompt',
    aliases: ['explode prompt'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'apply_to_target',
    title: 'Apply To Target',
    summary: 'Sends the currently reassembled prompt back to Image Studio or Case Resolver.',
    section: 'Source Prompt/Reassembled Prompt',
    aliases: ['apply to image studio', 'apply to case resolver'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'segment_selector',
    title: 'Segment Selector',
    summary: 'Chooses the active segment for editing.',
    section: 'Segments',
    aliases: ['select a segment to edit'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'segment_drag',
    title: 'Segment Reorder Drag Handle',
    summary: 'Drag to reorder segments; reassembly follows this order.',
    section: 'Segments',
    aliases: ['drag to reorder segment'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'segment_type',
    title: 'Segment Type',
    summary: 'Sets semantic type used for rendering, editing behavior, and validation.',
    section: 'Segments',
    aliases: ['type'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'segment_include_output',
    title: 'Include In Output',
    summary: 'Toggles whether the segment is included when rebuilding the final prompt.',
    section: 'Segments',
    aliases: ['include in output', 'metadata mode'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'segment_title',
    title: 'Segment Title',
    summary: 'Human-readable segment title used across panels and references.',
    section: 'Segments',
    aliases: ['title'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parameter_selector',
    title: 'Parameter Selector',
    summary:
      'Controls how a parameter is rendered and edited (auto, slider, select, json, rgb, etc).',
    section: 'Parameter Block',
    aliases: ['selector'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parameter_comment',
    title: 'Parameter Comment',
    summary: 'Inline comment metadata stored with the parameter definition.',
    section: 'Parameter Block',
    aliases: ['inline comment', 'comment'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parameter_description',
    title: 'Parameter Description',
    summary: 'Long-form metadata shown above the parameter in generated parameter text.',
    section: 'Parameter Block',
    aliases: ['description above this parameter', 'description'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'add_list_item',
    title: 'Add List Item',
    summary: 'Adds a new list row in list-like segment types.',
    section: 'Segments',
    aliases: ['add item', 'add list item'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'list_item_drag',
    title: 'List Item Reorder Drag Handle',
    summary: 'Drag to reorder list items inside the selected segment.',
    section: 'Segments',
    aliases: ['drag to reorder list item'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'bindings_type',
    title: 'Binding Type',
    summary: 'Defines relation kind between two endpoints (depends_on, references, uses_param).',
    section: 'Bindings',
    aliases: ['depends on', 'references', 'uses param'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'bindings_add_manual',
    title: 'Add Manual Binding',
    summary: 'Creates a binding from the current draft endpoint selections.',
    section: 'Bindings',
    aliases: ['add manual binding'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'bindings_remove_manual',
    title: 'Remove Manual Binding',
    summary: 'Deletes a manually created binding entry.',
    section: 'Bindings',
    aliases: ['remove manual binding'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'projects_save',
    title: 'Save Project',
    summary: 'Stores prompt text and exploded document state to Prompt Exploder library.',
    section: 'Projects',
    aliases: ['save project'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'projects_new',
    title: 'New Project',
    summary: 'Creates a new project draft in the Prompt Exploder library.',
    section: 'Projects',
    aliases: ['new project'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'projects_delete',
    title: 'Delete Project',
    summary: 'Deletes the selected Prompt Exploder project entry.',
    section: 'Projects',
    aliases: ['delete project'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'projects_name',
    title: 'Project Name',
    summary: 'Project label used in library lists and tables.',
    section: 'Projects',
    aliases: ['project name'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'projects_open',
    title: 'Open Project In Prompt Exploder',
    summary: 'Opens selected project in the main Prompt Exploder workspace.',
    section: 'Projects',
    aliases: ['open project', 'open'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'runtime_validation_stack',
    title: 'Validation Stack',
    summary: 'Chooses which validator scope/stack provides runtime rules for explosion.',
    section: 'Pattern Runtime',
    aliases: ['validation stack'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_rule_profile',
    title: 'Runtime Rule Profile',
    summary: 'Filters runtime rules to all, pattern pack only, or learned only.',
    section: 'Pattern Runtime',
    aliases: ['runtime rule profile'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_learning_enabled',
    title: 'Learning Toggle',
    summary: 'Enables or disables template/rule learning workflows.',
    section: 'Pattern Runtime',
    aliases: ['learning'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_capture_snapshot',
    title: 'Capture Snapshot',
    summary: 'Saves a snapshot of runtime learning/pattern state for rollback and comparison.',
    section: 'Pattern Runtime',
    aliases: ['capture snapshot'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_restore_snapshot',
    title: 'Restore Snapshot',
    summary: 'Restores selected snapshot into current runtime validation settings.',
    section: 'Pattern Runtime',
    aliases: ['restore snapshot'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_delete_snapshot',
    title: 'Delete Snapshot',
    summary: 'Removes selected runtime snapshot.',
    section: 'Pattern Runtime',
    aliases: ['delete snapshot'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'runtime_save_learning_settings',
    title: 'Save Learning Settings',
    summary: 'Persists runtime/learning draft values to Prompt Exploder settings.',
    section: 'Pattern Runtime',
    aliases: ['save learning settings'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'parser_tuning_expand',
    title: 'Parser Tuning Expand/Collapse',
    summary: 'Opens or hides parser tuning controls for structure and subsection parsing.',
    section: 'Parser Tuning',
    aliases: ['expand', 'collapse'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parser_tuning_save',
    title: 'Save Parser Tuning',
    summary: 'Persists parser tuning rules to validation patterns.',
    section: 'Parser Tuning',
    aliases: ['save parser tuning'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parser_tuning_reset',
    title: 'Reset Parser Tuning',
    summary: 'Reverts parser tuning draft to defaults/current persisted state.',
    section: 'Parser Tuning',
    aliases: ['reset parser tuning'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'parser_tuning_open_patterns',
    title: 'Open Validation Patterns',
    summary: 'Navigates to global validator pattern list for advanced rule management.',
    section: 'Parser Tuning',
    aliases: ['open validation patterns'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'benchmark_run',
    title: 'Run Benchmark',
    summary: 'Runs suite-level benchmark and generates precision/recall/F1 plus suggestions.',
    section: 'Benchmark Report',
    aliases: ['run benchmark'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_suite',
    title: 'Benchmark Suite',
    summary: 'Switches between default, extended, and custom JSON benchmark case sets.',
    section: 'Benchmark Report',
    aliases: ['benchmark suite'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_add_current',
    title: 'Add Current Prompt',
    summary: 'Adds current prompt into custom benchmark cases.',
    section: 'Benchmark Report',
    aliases: ['add current prompt'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_use_default',
    title: 'Use Default Suite',
    summary: 'Replaces custom benchmark JSON with default template cases.',
    section: 'Benchmark Report',
    aliases: ['use default'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_use_extended',
    title: 'Use Extended Suite',
    summary: 'Replaces custom benchmark JSON with extended template cases.',
    section: 'Benchmark Report',
    aliases: ['use extended'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_append_extended',
    title: 'Append Extended Suite',
    summary: 'Appends extended template cases to existing custom benchmark JSON.',
    section: 'Benchmark Report',
    aliases: ['append extended'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_clear_custom',
    title: 'Clear Custom Suite',
    summary: 'Clears the custom benchmark JSON editor content.',
    section: 'Benchmark Report',
    aliases: ['clear'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_apply_suggestion',
    title: 'Apply Suggestion',
    summary: 'Applies a suggested low-confidence rule/template improvement to runtime settings.',
    section: 'Benchmark Report',
    aliases: ['apply suggestion', 'apply'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_dismiss_suggestion',
    title: 'Dismiss Suggestion',
    summary: 'Hides a suggestion from current benchmark suggestion view.',
    section: 'Benchmark Report',
    aliases: ['dismiss'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'benchmark_apply_visible_suggestions',
    title: 'Apply Visible Suggestions',
    summary: 'Applies all currently visible benchmark suggestions in one action.',
    section: 'Benchmark Report',
    aliases: ['apply visible', 'apply all'],
    docPath: '/docs/PROMPT_EXPLODER_OPERATIONS_RUNBOOK.md',
  },
  {
    id: 'settings_refresh',
    title: 'Refresh Settings Data',
    summary: 'Reloads Prompt Exploder settings and model discovery sources.',
    section: 'Settings Page',
    aliases: ['refresh'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'settings_save',
    title: 'Save Prompt Exploder Settings',
    summary: 'Persists AI/runtime/learning defaults under Prompt Exploder settings key.',
    section: 'Settings Page',
    aliases: ['save prompt exploder settings', 'save settings'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
  {
    id: 'settings_reset_unsaved',
    title: 'Reset Unsaved Changes',
    summary: 'Reverts the draft settings UI state back to persisted settings values.',
    section: 'Settings Page',
    aliases: ['reset unsaved changes'],
    docPath: '/docs/PROMPT_EXPLODER_FEATURE_DOCUMENTATION.md',
  },
];
