export type KangurDocumentationGuide = {
  id: string;
  title: string;
  summary: string;
  audience: 'learner' | 'parent' | 'admin' | 'shared';
  docPath: string;
  sectionsCovered: string[];
};

export type KangurTooltipDocEntry = {
  id: string;
  title: string;
  summary: string;
  section: string;
  aliases: string[];
  docPath: string;
  tags?: string[];
  uiTargets?: string[];
};

export const KANGUR_DOCUMENTATION_GUIDES: KangurDocumentationGuide[] = [
  {
    id: 'overview',
    title: 'Kangur Overview',
    summary: 'Explains the purpose of Kangur, the major routes, and the documentation-driven tooltip model.',
    audience: 'shared',
    docPath: '/docs/kangur/README.md',
    sectionsCovered: ['Overview', 'Architecture', 'Documentation'],
  },
  {
    id: 'learner-navigation',
    title: 'Learner Navigation',
    summary: 'Covers the top navigation model, home screen behavior, and route transitions for learners.',
    audience: 'learner',
    docPath: '/docs/kangur/learner-navigation.md',
    sectionsCovered: ['Top navigation', 'Home screen', 'Tooltips'],
  },
  {
    id: 'lessons-and-activities',
    title: 'Lessons And Activities',
    summary: 'Documents the lesson library, content modes, narration, and reusable lesson activities.',
    audience: 'shared',
    docPath: '/docs/kangur/lessons-and-activities.md',
    sectionsCovered: ['Lesson library', 'Document mode', 'Narration', 'Activities'],
  },
  {
    id: 'tests-and-exams',
    title: 'Tests And Exams',
    summary: 'Documents Kangur test suites, test playback, and the admin-to-learner publishing model.',
    audience: 'shared',
    docPath: '/docs/kangur/tests-and-exams.md',
    sectionsCovered: ['Test suites', 'Playback', 'Admin responsibilities'],
  },
  {
    id: 'profile-and-parent-dashboard',
    title: 'Profile And Parent Dashboard',
    summary: 'Documents learner profile metrics, recommendations, learner management, and parent review flows.',
    audience: 'parent',
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    sectionsCovered: ['Learner profile', 'Parent dashboard', 'Tabs'],
  },
  {
    id: 'admin-content-authoring',
    title: 'Admin Content Authoring',
    summary: 'Documents Kangur authoring responsibilities across lessons, documents, questions, and settings.',
    audience: 'admin',
    docPath: '/docs/kangur/admin-content-authoring.md',
    sectionsCovered: ['Admin surfaces', 'Authoring principles', 'Tooltip principle'],
  },
  {
    id: 'settings-and-narration',
    title: 'Settings And Narration',
    summary: 'Documents how Kangur settings persist, how narration works, and how tooltip toggles are applied.',
    audience: 'admin',
    docPath: '/docs/kangur/settings-and-narration.md',
    sectionsCovered: ['Settings ownership', 'Narrator settings', 'Docs tooltips'],
  },
  {
    id: 'svg-and-media-rules',
    title: 'SVG And Media Rules',
    summary: 'Documents the SVG-only media rules used by Kangur lesson and question content.',
    audience: 'admin',
    docPath: '/docs/kangur/svg-and-media-rules.md',
    sectionsCovered: ['SVG-only rule', 'Rationale', 'Authoring impact'],
  },
  {
    id: 'observability-and-operations',
    title: 'Observability And Operations',
    summary: 'Documents Kangur alert thresholds, summary surfaces, log presets, and incident triage steps.',
    audience: 'admin',
    docPath: '/docs/kangur/observability-and-operations.md',
    sectionsCovered: ['Primary surfaces', 'Alert thresholds', 'Triage', 'Mitigation'],
  },
];

export const KANGUR_TOOLTIP_CATALOG: KangurTooltipDocEntry[] = [
  {
    id: 'app_overview',
    title: 'Kangur Overview',
    summary: 'Introduces the main Kangur routes for practice, lessons, tests, and learner progress.',
    section: 'Overview',
    aliases: ['kangur', 'app overview', 'home overview'],
    docPath: '/docs/kangur/README.md',
    tags: ['kangur', 'overview'],
    uiTargets: ['app.overview'],
  },
  {
    id: 'top_nav_home',
    title: 'Home Navigation',
    summary: 'Returns to the main Kangur practice hub and quick-start home screen.',
    section: 'Top Navigation',
    aliases: ['strona glowna', 'home'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'navigation', 'home'],
    uiTargets: ['top-nav.home'],
  },
  {
    id: 'top_nav_lessons',
    title: 'Lessons Navigation',
    summary: 'Opens the Kangur lesson library and the current lesson progress overview.',
    section: 'Top Navigation',
    aliases: ['lekcje', 'lessons'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'navigation', 'lessons'],
    uiTargets: ['top-nav.lessons'],
  },
  {
    id: 'top_nav_tests',
    title: 'Tests Navigation',
    summary: 'Opens custom Kangur test suites built with the test engine.',
    section: 'Top Navigation',
    aliases: ['testy', 'tests', 'custom tests'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'navigation', 'tests'],
    uiTargets: ['top-nav.tests'],
  },
  {
    id: 'top_nav_competition',
    title: 'Kangur Competition Navigation',
    summary: 'Opens the Kangur competition exam flow and setup.',
    section: 'Top Navigation',
    aliases: ['kangur', 'konkurs', 'competition'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'navigation', 'exam'],
    uiTargets: ['top-nav.competition'],
  },
  {
    id: 'top_nav_profile',
    title: 'Profile Navigation',
    summary: 'Opens learner profile actions and status links for the current Kangur account.',
    section: 'Top Navigation',
    aliases: ['profil', 'profile'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'navigation', 'profile'],
    uiTargets: ['top-nav.profile'],
  },
  {
    id: 'top_nav_parent_dashboard',
    title: 'Parent Dashboard Navigation',
    summary: 'Opens the parent dashboard when the current account can manage learner profiles.',
    section: 'Top Navigation',
    aliases: ['rodzic', 'parent dashboard', 'dashboard'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'navigation', 'parent'],
    uiTargets: ['top-nav.parent-dashboard'],
  },
  {
    id: 'profile_status_link',
    title: 'Profile Status',
    summary: 'Opens the learner profile page with progress, badges, and recent results.',
    section: 'Profile Menu',
    aliases: ['status', 'profile status'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'profile', 'status'],
    uiTargets: ['profile-menu.status'],
  },
  {
    id: 'profile_login',
    title: 'Login Action',
    summary: 'Starts the login flow so progress, assignments, and learner data can sync with Kangur.',
    section: 'Profile Menu',
    aliases: ['zaloguj sie', 'login'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'auth', 'profile'],
    uiTargets: ['profile-menu.login'],
  },
  {
    id: 'profile_logout',
    title: 'Logout Action',
    summary: 'Signs out of the current Kangur session and returns the user to local-mode behavior.',
    section: 'Profile Menu',
    aliases: ['wyloguj', 'logout'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'auth', 'profile'],
    uiTargets: ['profile-menu.logout'],
  },
  {
    id: 'home_player_name_input',
    title: 'Player Name',
    summary: 'Sets the learner name used during guest play on the Kangur home screen.',
    section: 'Home',
    aliases: ['imie gracza', 'player name'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'home', 'guest'],
    uiTargets: ['home.player-name'],
  },
  {
    id: 'home_quick_practice_action',
    title: 'Quick Practice Action',
    summary: 'Starts a direct practice flow from the Kangur home surface.',
    section: 'Home',
    aliases: ['practice action', 'quick start'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'home', 'practice'],
    uiTargets: ['home.quick-practice'],
  },
  {
    id: 'home_duels_action',
    title: 'Duels Action',
    summary: 'Opens the multiplayer duels lobby from the Kangur home surface.',
    section: 'Home',
    aliases: ['pojedynki', 'duels', 'lobby'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'home', 'multiplayer'],
    uiTargets: ['home.duels'],
  },
  {
    id: 'home_lessons_action',
    title: 'Lessons Action',
    summary: 'Jumps from the home surface into the Kangur lesson library.',
    section: 'Home',
    aliases: ['lessons action', 'open lessons'],
    docPath: '/docs/kangur/learner-navigation.md',
    tags: ['kangur', 'home', 'lessons'],
    uiTargets: ['home.open-lessons'],
  },
  {
    id: 'home_kangur_exam_action',
    title: 'Kangur Exam Action',
    summary: 'Opens the Kangur exam-style practice flow from the home surface.',
    section: 'Home',
    aliases: ['kangur matematyczny', 'exam action'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'home', 'exam'],
    uiTargets: ['home.kangur-exam'],
  },
  {
    id: 'home_admin_observability_action',
    title: 'Admin Observability Action',
    summary: 'Opens the Kangur observability dashboard with alerts, route health, analytics, and recent server logs.',
    section: 'Home',
    aliases: ['observability', 'diagnostics', 'admin observability'],
    docPath: '/docs/kangur/observability-and-operations.md',
    tags: ['kangur', 'home', 'admin', 'observability'],
    uiTargets: ['home.admin-observability'],
  },
  {
    id: 'home_priority_assignments',
    title: 'Priority Assignments',
    summary: 'Highlights active learner assignments that should be completed before free practice.',
    section: 'Home',
    aliases: ['priority assignments', 'priorytetowe zadania'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'home', 'assignments'],
    uiTargets: ['home.priority-assignments'],
  },
  {
    id: 'lessons_library_entry',
    title: 'Lesson Card',
    summary: 'Opens a lesson from the Kangur lesson library and shows its progress state.',
    section: 'Lessons',
    aliases: ['lesson card', 'lesson library'],
    docPath: '/docs/kangur/lessons-and-activities.md',
    tags: ['kangur', 'lessons', 'library'],
    uiTargets: ['lessons.library-entry'],
  },
  {
    id: 'lessons_back_button',
    title: 'Back To Lesson List',
    summary: 'Returns from an active lesson back to the Kangur lesson library.',
    section: 'Lessons',
    aliases: ['wroc do listy lekcji', 'back to lessons'],
    docPath: '/docs/kangur/lessons-and-activities.md',
    tags: ['kangur', 'lessons', 'navigation'],
    uiTargets: ['lessons.back'],
  },
  {
    id: 'lessons_document_mode',
    title: 'Lesson Document Mode',
    summary: 'Explains when a lesson is rendered from stored document blocks instead of a legacy component.',
    section: 'Lessons',
    aliases: ['lesson document', 'document mode'],
    docPath: '/docs/kangur/lessons-and-activities.md',
    tags: ['kangur', 'lessons', 'documents'],
    uiTargets: ['lessons.document-mode'],
  },
  {
    id: 'lessons_narrator',
    title: 'Lesson Narrator',
    summary: 'Controls lesson narration using the globally configured Kangur narrator settings.',
    section: 'Lessons',
    aliases: ['narrator', 'lesson narrator'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'lessons', 'narration'],
    uiTargets: ['lessons.narrator'],
  },
  {
    id: 'lessons_prev_next',
    title: 'Lesson Sequence Navigation',
    summary: 'Moves to the previous or next lesson while keeping the learner inside the lesson flow.',
    section: 'Lessons',
    aliases: ['previous lesson', 'next lesson'],
    docPath: '/docs/kangur/lessons-and-activities.md',
    tags: ['kangur', 'lessons', 'navigation'],
    uiTargets: ['lessons.prev-next'],
  },
  {
    id: 'tests_suite_card',
    title: 'Test Suite Card',
    summary: 'Opens a published Kangur test suite from the suite list.',
    section: 'Tests',
    aliases: ['test suite', 'suite card'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'tests', 'suite'],
    uiTargets: ['tests.suite-card'],
  },
  {
    id: 'tests_suite_player',
    title: 'Test Suite Player',
    summary: 'Runs the active test suite with its current question set and playback flow.',
    section: 'Tests',
    aliases: ['suite player', 'test player'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'tests', 'player'],
    uiTargets: ['tests.suite-player'],
  },
  {
    id: 'tests_back_button',
    title: 'Back To Test Suites',
    summary: 'Returns from an active suite back to the published Kangur test-suite list.',
    section: 'Tests',
    aliases: ['back to tests', 'wroc'],
    docPath: '/docs/kangur/tests-and-exams.md',
    tags: ['kangur', 'tests', 'navigation'],
    uiTargets: ['tests.back'],
  },
  {
    id: 'learner_daily_plan',
    title: 'Daily Plan',
    summary: 'Shows the learner’s short-term progress target and daily practice pacing.',
    section: 'Learner Profile',
    aliases: ['plan na dzis', 'daily plan'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'profile', 'progress'],
    uiTargets: ['profile.daily-plan'],
  },
  {
    id: 'learner_mastery_insights',
    title: 'Lesson Mastery Insights',
    summary: 'Summarizes lesson mastery so learners and parents can see what still needs practice.',
    section: 'Learner Profile',
    aliases: ['mastery insights', 'lesson mastery'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'profile', 'mastery'],
    uiTargets: ['profile.mastery-insights'],
  },
  {
    id: 'learner_recommendation_action',
    title: 'Recommended Action',
    summary: 'Starts the next recommended lesson or practice route for the learner.',
    section: 'Learner Profile',
    aliases: ['recommendation', 'zagraj teraz', 'otworz lekcje'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'profile', 'recommendation'],
    uiTargets: ['profile.recommendation'],
  },
  {
    id: 'parent_progress_tab',
    title: 'Parent Progress Tab',
    summary: 'Shows aggregated learner progress and instructional momentum for the selected profile.',
    section: 'Parent Dashboard',
    aliases: ['postep', 'progress tab'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'progress'],
    uiTargets: ['parent-dashboard.tab.progress'],
  },
  {
    id: 'parent_scores_tab',
    title: 'Parent Scores Tab',
    summary: 'Shows score history and recent game performance for the selected learner.',
    section: 'Parent Dashboard',
    aliases: ['wyniki', 'wyniki gier', 'scores tab'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'scores'],
    uiTargets: ['parent-dashboard.tab.scores'],
  },
  {
    id: 'parent_assignments_tab',
    title: 'Parent Assignments Tab',
    summary: 'Shows lesson and practice assignments that the parent can create or review.',
    section: 'Parent Dashboard',
    aliases: ['zadania', 'assignments tab'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'assignments'],
    uiTargets: ['parent-dashboard.tab.assignments'],
  },
  {
    id: 'parent_monitoring_tab',
    title: 'Parent Monitoring Tab',
    summary: 'Shows assignment progress and completion for parent-assigned and suggested tasks.',
    section: 'Parent Dashboard',
    aliases: ['monitoring', 'monitorowanie', 'postęp zadań', 'monitoring tab'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'assignments', 'monitoring'],
    uiTargets: ['parent-dashboard.tab.monitoring'],
  },
  {
    id: 'parent_ai_tutor_tab',
    title: 'Parent AI Tutor Tab',
    summary: 'Shows learner-specific AI tutor controls such as enablement, live daily usage, and learner guardrails. Global tutor persona, teaching-agent, device preset, and daily cap live in Kangur Settings.',
    section: 'Parent Dashboard',
    aliases: ['ai tutor', 'tutor tab', 'parent ai tutor'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'ai-tutor'],
    uiTargets: ['parent-dashboard.tab.ai-tutor'],
  },
  {
    id: 'parent_learner_profile_card',
    title: 'Learner Profile Card',
    summary: 'Selects the active learner profile inside the parent dashboard.',
    section: 'Parent Dashboard',
    aliases: ['learner profile', 'profile card'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'learner'],
    uiTargets: ['parent-dashboard.learner-card'],
  },
  {
    id: 'parent_create_learner',
    title: 'Create Learner',
    summary: 'Creates a new learner profile that the parent can manage in Kangur.',
    section: 'Parent Dashboard',
    aliases: ['create learner', 'dodaj profil'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'learner'],
    uiTargets: ['parent-dashboard.create-learner'],
  },
  {
    id: 'parent_save_learner',
    title: 'Save Learner Changes',
    summary: 'Saves changes to the selected learner profile such as name, login, password, or status.',
    section: 'Parent Dashboard',
    aliases: ['save learner', 'zapisz dane ucznia'],
    docPath: '/docs/kangur/profile-and-parent-dashboard.md',
    tags: ['kangur', 'parent', 'learner'],
    uiTargets: ['parent-dashboard.save-learner'],
  },
  {
    id: 'settings_narrator_engine',
    title: 'Narrator Engine',
    summary: 'Selects the global narration engine used by learner-facing Kangur lessons and exercises.',
    section: 'Admin Settings',
    aliases: ['narrator engine', 'server narrator', 'client narrator'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'narration'],
    uiTargets: ['admin-settings.narrator-engine'],
  },
  {
    id: 'settings_narrator_voice',
    title: 'Narrator Voice',
    summary: 'Selects the default cached server voice used when Kangur lessons play narration.',
    section: 'Admin Settings',
    aliases: ['narrator voice', 'voice'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'narration'],
    uiTargets: ['admin-settings.narrator-voice'],
  },
  {
    id: 'settings_narrator_sample_copy',
    title: 'Narrator Sample Text',
    summary: 'Copies the narrator sample text so the admin can test the current Kangur voice selection.',
    section: 'Admin Settings',
    aliases: ['copy text', 'sample text'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'narration'],
    uiTargets: ['admin-settings.narrator-sample-copy'],
  },
  {
    id: 'settings_docs_tooltips_master_toggle',
    title: 'Docs Tooltips Master Toggle',
    summary: 'Turns documentation-driven tooltips on or off across Kangur surfaces.',
    section: 'Admin Settings',
    aliases: ['docs tooltips', 'tooltips master'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.master'],
  },
  {
    id: 'settings_docs_tooltips_home_toggle',
    title: 'Home Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips on the Kangur home and practice shell.',
    section: 'Admin Settings',
    aliases: ['home tooltips', 'home docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.home'],
  },
  {
    id: 'settings_docs_tooltips_lessons_toggle',
    title: 'Lessons Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips inside the Kangur lesson library and lesson pages.',
    section: 'Admin Settings',
    aliases: ['lessons tooltips', 'lesson docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.lessons'],
  },
  {
    id: 'settings_docs_tooltips_tests_toggle',
    title: 'Tests Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips on Kangur test-suite routes.',
    section: 'Admin Settings',
    aliases: ['tests tooltips', 'test docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.tests'],
  },
  {
    id: 'settings_docs_tooltips_profile_toggle',
    title: 'Learner Profile Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips on the learner profile surface.',
    section: 'Admin Settings',
    aliases: ['profile tooltips', 'learner profile docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.profile'],
  },
  {
    id: 'settings_docs_tooltips_parent_dashboard_toggle',
    title: 'Parent Dashboard Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips on the parent dashboard surface.',
    section: 'Admin Settings',
    aliases: ['parent dashboard tooltips', 'parent docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.parent-dashboard'],
  },
  {
    id: 'settings_docs_tooltips_admin_toggle',
    title: 'Admin Tooltips Toggle',
    summary: 'Controls documentation-driven tooltips on Kangur admin routes.',
    section: 'Admin Settings',
    aliases: ['admin tooltips', 'admin docs'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'tooltips'],
    uiTargets: ['admin-settings.docs-tooltips.admin'],
  },
  {
    id: 'settings_documentation_library',
    title: 'Documentation Library',
    summary: 'Lists the central Kangur documentation guides and the tooltip catalog sections that feed the UI.',
    section: 'Admin Settings',
    aliases: ['documentation library', 'docs library'],
    docPath: '/docs/kangur/README.md',
    tags: ['kangur', 'settings', 'documentation'],
    uiTargets: ['admin-settings.documentation-library'],
  },
  {
    id: 'settings_save',
    title: 'Save Kangur Settings',
    summary: 'Persists narrator and documentation-tooltip settings to the shared Kangur settings store.',
    section: 'Admin Settings',
    aliases: ['save settings', 'save kangur settings'],
    docPath: '/docs/kangur/settings-and-narration.md',
    tags: ['kangur', 'settings', 'save'],
    uiTargets: ['admin-settings.save'],
  },
  {
    id: 'admin_observability_range',
    title: 'Observability Range Selector',
    summary: 'Changes the active Kangur observability window between 24 hours, 7 days, and 30 days.',
    section: 'Admin Observability',
    aliases: ['range selector', 'observability range', '24h 7d 30d'],
    docPath: '/docs/kangur/observability-and-operations.md',
    tags: ['kangur', 'admin', 'observability', 'range'],
    uiTargets: ['admin-observability.range'],
  },
  {
    id: 'admin_observability_alerts',
    title: 'Observability Alerts',
    summary: 'Summarizes the current Kangur alert thresholds for server errors, sign-in failures, progress sync, TTS fallback, and the performance baseline.',
    section: 'Admin Observability',
    aliases: ['alerts', 'thresholds', 'status cards'],
    docPath: '/docs/kangur/observability-and-operations.md',
    tags: ['kangur', 'admin', 'observability', 'alerts'],
    uiTargets: ['admin-observability.alerts'],
  },
  {
    id: 'admin_observability_quick_links',
    title: 'Observability Quick Links',
    summary: 'Opens Kangur-scoped log searches, analytics, and the raw summary payload for faster triage.',
    section: 'Admin Observability',
    aliases: ['quick links', 'log links', 'summary json'],
    docPath: '/docs/kangur/observability-and-operations.md',
    tags: ['kangur', 'admin', 'observability', 'links'],
    uiTargets: ['admin-observability.quick-links'],
  },
];
