import type { ContextNode } from '@/shared/contracts/ai-context-registry';

const SOURCE_REF = 'src/features/ai/ai-context-registry/registry/definitions/actions.ts';

export const actionNodesPart2: ContextNode[] = [
  {
    id: 'action:cms-css-ai-stream',
    kind: 'action',
    name: 'CMS CSS AI Stream',
    description:
      'Runs CMS page-builder AI turns for layout generation, inspector settings help, CSS authoring, ' +
      'and theme color generation using the current Context Registry page envelope.',
    tags: ['cms', 'page-builder', 'theme', 'css', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:cms-page-builder' },
      { type: 'reads', targetId: 'collection:cms-pages' },
      { type: 'reads', targetId: 'collection:cms-themes' },
      { type: 'uses', targetId: 'component:cms-page-builder-inspector' },
      { type: 'uses', targetId: 'component:cms-theme-settings-panel' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:agent-teaching-chat',
    kind: 'action',
    name: 'Agent Teaching Chat',
    description:
      'Runs a retrieval-augmented chat turn for a learner agent using embedding collections, ' +
      'Knowledge Base sources, and the current page context registry envelope.',
    tags: ['agent-creator', 'teaching', 'chat', 'rag'],
    relationships: [
      { type: 'uses', targetId: 'page:agent-teaching-chat' },
      { type: 'uses', targetId: 'component:agent-teaching-chat-panel' },
      { type: 'reads', targetId: 'collection:agent-teaching-agents' },
      { type: 'reads', targetId: 'collection:agent-teaching-embedding-collections' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:chatbot-chat',
    kind: 'action',
    name: 'Chatbot Chat',
    description:
      'Runs an admin chatbot turn using Brain model routing, persona memory, and the current page context registry envelope.',
    tags: ['chatbot', 'admin', 'chat', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-chatbot' },
      { type: 'uses', targetId: 'component:chatbot-chat-interface' },
      { type: 'uses', targetId: 'component:chatbot-settings-panel' },
      { type: 'uses', targetId: 'component:chatbot-debug-panel' },
      { type: 'reads', targetId: 'collection:chatbot-sessions' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:system-logs-generate-insight',
    kind: 'action',
    name: 'System Logs Generate Insight',
    description:
      'Generates an Observation Post log insight using the current page context registry envelope, visible workspace state, and recent warning or error logs.',
    tags: ['observability', 'logs', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:system-logs' },
      { type: 'uses', targetId: 'component:system-logs-ai-interpreter' },
      { type: 'reads', targetId: 'collection:system-logs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:system-logs-interpret',
    kind: 'action',
    name: 'System Logs Interpret',
    description:
      'Generates an AI interpretation for a specific system log entry by combining the selected log runtime context with the current Observation Post page context registry envelope.',
    tags: ['observability', 'logs', 'interpret', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:system-logs' },
      { type: 'uses', targetId: 'component:system-logs-event-stream' },
      { type: 'reads', targetId: 'collection:system-logs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:analytics-generate-insight',
    kind: 'action',
    name: 'Analytics Generate Insight',
    description:
      'Generates an analytics insight using the current dashboard or AI Insights page context registry envelope and the latest analytics summary snapshot.',
    tags: ['analytics', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:analytics' },
      { type: 'uses', targetId: 'page:ai-insights' },
      { type: 'uses', targetId: 'component:analytics-ai-insights' },
      { type: 'uses', targetId: 'component:ai-insights-analytics-panel' },
      { type: 'reads', targetId: 'collection:analytics-events' },
      { type: 'writes', targetId: 'collection:ai-insights-history' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:runtime-analytics-generate-insight',
    kind: 'action',
    name: 'Runtime Analytics Generate Insight',
    description:
      'Generates a runtime analytics insight using the current AI Insights page context registry envelope and AI Paths runtime telemetry.',
    tags: ['runtime-analytics', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:ai-insights' },
      { type: 'uses', targetId: 'component:ai-insights-runtime-panel' },
      { type: 'reads', targetId: 'collection:ai-path-runs' },
      { type: 'writes', targetId: 'collection:ai-insights-history' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-run',
    kind: 'action',
    name: 'Image Studio Run',
    description:
      'Queues an Image Studio generation or object-centering run using the current page context registry envelope, prompt, masks, and studio settings.',
    tags: ['image-studio', 'generation', 'run', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'component:image-studio-generation-toolbar' },
      { type: 'writes', targetId: 'collection:image-studio-runs' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-sequence-run',
    kind: 'action',
    name: 'Image Studio Sequence Run',
    description:
      'Starts a multi-step Image Studio sequencing workflow using the current page context registry envelope, prompt state, masks, and active slot selection.',
    tags: ['image-studio', 'sequence', 'workflow', 'generation', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
      { type: 'writes', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'reads', targetId: 'collection:image-studio-runs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
];
