import type { ContextNode } from '@/shared/contracts/ai-context-registry';

const SOURCE_REF = 'src/features/ai/ai-context-registry/registry/definitions/actions.ts';

export const actionNodes: ContextNode[] = [
  {
    id: 'action:export-products',
    kind: 'action',
    name: 'Export Products',
    description:
      'Triggers a bulk export of the product catalog to CSV or JSON. ' +
      'Supports field selection and filter scoping.',
    tags: ['products', 'export', 'bulk', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:products' },
      { type: 'reads', targetId: 'collection:products' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-01-01T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:product-studio-send',
    kind: 'action',
    name: 'Product Studio Send',
    description:
      'Launches a Product Studio generation or sequence run from the product editor, resolving ' +
      'the current page context registry envelope before dispatching Image Studio work.',
    tags: ['products', 'studio', 'image-studio', 'generation', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:product-editor' },
      { type: 'uses', targetId: 'component:product-form-studio' },
      { type: 'reads', targetId: 'collection:products' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
      { type: 'writes', targetId: 'collection:image-studio-runs' },
      { type: 'writes', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'depends_on', targetId: 'action:image-studio-run' },
      { type: 'depends_on', targetId: 'action:image-studio-sequence-run' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:product-validator-runtime-evaluate',
    kind: 'action',
    name: 'Product Validator Runtime Evaluate',
    description:
      'Runs AI-backed product validator runtime checks from the Product Editor using the current page context registry envelope and live validation workspace state.',
    tags: ['products', 'validation', 'runtime', 'editor', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:product-editor' },
      { type: 'uses', targetId: 'component:product-form' },
      { type: 'uses', targetId: 'component:product-form-validation-tab' },
      { type: 'reads', targetId: 'collection:products' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:run-ai-path',
    kind: 'action',
    name: 'Run AI Path',
    description:
      'Queues an AI path execution with optional runtime input overrides and the current page context registry envelope. ' +
      'Returns a run ID for polling status and streaming events.',
    tags: ['ai', 'automation', 'paths', 'execution'],
    relationships: [
      { type: 'uses', targetId: 'page:ai-paths' },
      { type: 'uses', targetId: 'component:ai-paths-canvas-board' },
      { type: 'writes', targetId: 'collection:ai-path-runs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      requiresApproval: true,
      riskTier: 'medium',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-01-01T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:ai-paths-preview-model',
    kind: 'action',
    name: 'AI Paths Preview Model',
    description:
      'Runs the node-config "Send to AI Model" preview flow using the current AI Paths page context registry envelope.',
    tags: ['ai-paths', 'preview', 'model', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:ai-paths' },
      { type: 'uses', targetId: 'component:ai-paths-node-config-dialog' },
      { type: 'uses', targetId: 'component:ai-paths-canvas-board' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:ai-paths-playwright-run',
    kind: 'action',
    name: 'AI Paths Playwright Run',
    description:
      'Queues an AI Paths Playwright browser-automation node using the current page context registry envelope and exposes the resolved workspace bundle to the Playwright runtime.',
    tags: ['ai-paths', 'playwright', 'automation', 'browser', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:ai-paths' },
      { type: 'uses', targetId: 'component:ai-paths-canvas-board' },
      { type: 'uses', targetId: 'component:ai-paths-node-config-dialog' },
      { type: 'writes', targetId: 'collection:ai-path-playwright-runs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'medium',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:run-db-query',
    kind: 'action',
    name: 'Run Database Query',
    description:
      'Executes a read-only query against a registered database provider. ' +
      'Supports MongoDB aggregations and SQL SELECT statements.',
    tags: ['database', 'query', 'admin', 'developer'],
    relationships: [{ type: 'uses', targetId: 'page:database-engine' }],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-01-01T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:kangur-ai-tutor-chat',
    kind: 'action',
    name: 'Kangur AI Tutor Chat',
    description:
      'Runs a Kangur AI tutor turn by resolving learner and page context through the Context Registry, ' +
      'then passing the resulting bundle to the tutor model.',
    tags: ['kangur', 'ai', 'tutor', 'education'],
    relationships: [
      { type: 'uses', targetId: 'page:kangur-lessons' },
      { type: 'uses', targetId: 'page:kangur-tests' },
      { type: 'uses', targetId: 'page:kangur-game' },
      { type: 'uses', targetId: 'page:kangur-learner-profile' },
      { type: 'uses', targetId: 'page:kangur-parent-dashboard' },
      { type: 'reads', targetId: 'collection:kangur-progress' },
      { type: 'reads', targetId: 'collection:kangur-scores' },
      { type: 'reads', targetId: 'collection:kangur-assignments' },
      { type: 'reads', targetId: 'collection:kangur-login-activity' },
      { type: 'reads', targetId: 'collection:kangur-lessons' },
      { type: 'reads', targetId: 'collection:kangur-test-suites' },
      { type: 'governed_by', targetId: 'policy:kangur-ai-tutor-socratic' },
      { type: 'governed_by', targetId: 'policy:kangur-ai-tutor-test-guardrails' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-08T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:kangur-lesson-tts',
    kind: 'action',
    name: 'Kangur Lesson TTS',
    description:
      'Generates or reuses Kangur lesson narration audio for learner playback and admin lesson-preview flows using the shared page context registry envelope.',
    tags: ['kangur', 'tts', 'narration', 'audio', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:kangur-lessons' },
      { type: 'uses', targetId: 'page:kangur-tests' },
      { type: 'uses', targetId: 'page:kangur-admin-lessons-manager' },
      { type: 'uses', targetId: 'component:kangur-lesson-narrator' },
      { type: 'uses', targetId: 'component:kangur-lesson-narration-panel' },
      { type: 'reads', targetId: 'collection:kangur-lessons' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:cms-css-ai-stream',
    kind: 'action',
    name: 'CMS CSS AI Stream',
    description:
      'Runs CMS page-builder AI turns for layout generation, inspector settings help, CSS authoring, ' +
      'and theme color generation using the current Context Registry page envelope.',
    tags: ['cms', 'page-builder', 'theme', 'css', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:cms-page-builder' },
      { type: 'reads', targetId: 'collection:cms-pages' },
      { type: 'reads', targetId: 'collection:cms-themes' },
      { type: 'uses', targetId: 'component:cms-page-builder-inspector' },
      { type: 'uses', targetId: 'component:cms-theme-settings-panel' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:agent-teaching-chat',
    kind: 'action',
    name: 'Agent Teaching Chat',
    description:
      'Runs a retrieval-augmented chat turn for a learner agent using embedding collections, ' +
      'Knowledge Base sources, and the current page context registry envelope.',
    tags: ['agent-creator', 'teaching', 'chat', 'rag'],
    relationships: [
      { type: 'uses', targetId: 'page:agent-teaching-chat' },
      { type: 'uses', targetId: 'component:agent-teaching-chat-panel' },
      { type: 'reads', targetId: 'collection:agent-teaching-agents' },
      { type: 'reads', targetId: 'collection:agent-teaching-embedding-collections' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:chatbot-chat',
    kind: 'action',
    name: 'Chatbot Chat',
    description:
      'Runs an admin chatbot turn using Brain model routing, persona memory, and the current page context registry envelope.',
    tags: ['chatbot', 'admin', 'chat', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-chatbot' },
      { type: 'uses', targetId: 'component:chatbot-chat-interface' },
      { type: 'uses', targetId: 'component:chatbot-settings-panel' },
      { type: 'uses', targetId: 'component:chatbot-debug-panel' },
      { type: 'reads', targetId: 'collection:chatbot-sessions' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:system-logs-generate-insight',
    kind: 'action',
    name: 'System Logs Generate Insight',
    description:
      'Generates an Observation Post log insight using the current page context registry envelope, visible workspace state, and recent warning or error logs.',
    tags: ['observability', 'logs', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:system-logs' },
      { type: 'uses', targetId: 'component:system-logs-ai-interpreter' },
      { type: 'reads', targetId: 'collection:system-logs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:system-logs-interpret',
    kind: 'action',
    name: 'System Logs Interpret',
    description:
      'Generates an AI interpretation for a specific system log entry by combining the selected log runtime context with the current Observation Post page context registry envelope.',
    tags: ['observability', 'logs', 'interpret', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:system-logs' },
      { type: 'uses', targetId: 'component:system-logs-event-stream' },
      { type: 'reads', targetId: 'collection:system-logs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:analytics-generate-insight',
    kind: 'action',
    name: 'Analytics Generate Insight',
    description:
      'Generates an analytics insight using the current dashboard or AI Insights page context registry envelope and the latest analytics summary snapshot.',
    tags: ['analytics', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:analytics' },
      { type: 'uses', targetId: 'page:ai-insights' },
      { type: 'uses', targetId: 'component:analytics-ai-insights' },
      { type: 'uses', targetId: 'component:ai-insights-analytics-panel' },
      { type: 'reads', targetId: 'collection:analytics-events' },
      { type: 'writes', targetId: 'collection:ai-insights-history' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:runtime-analytics-generate-insight',
    kind: 'action',
    name: 'Runtime Analytics Generate Insight',
    description:
      'Generates a runtime analytics insight using the current AI Insights page context registry envelope and AI Paths runtime telemetry.',
    tags: ['runtime-analytics', 'insights', 'ai', 'admin'],
    relationships: [
      { type: 'uses', targetId: 'page:ai-insights' },
      { type: 'uses', targetId: 'component:ai-insights-runtime-panel' },
      { type: 'reads', targetId: 'collection:ai-path-runs' },
      { type: 'writes', targetId: 'collection:ai-insights-history' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-run',
    kind: 'action',
    name: 'Image Studio Run',
    description:
      'Queues an Image Studio generation or object-centering run using the current page context registry envelope, prompt, masks, and studio settings.',
    tags: ['image-studio', 'generation', 'run', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'component:image-studio-generation-toolbar' },
      { type: 'writes', targetId: 'collection:image-studio-runs' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-sequence-run',
    kind: 'action',
    name: 'Image Studio Sequence Run',
    description:
      'Starts a multi-step Image Studio sequencing workflow using the current page context registry envelope, prompt state, masks, and active slot selection.',
    tags: ['image-studio', 'sequence', 'workflow', 'generation', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
      { type: 'writes', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'reads', targetId: 'collection:image-studio-runs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-ai-path-object-analysis',
    kind: 'action',
    name: 'Image Studio AI Paths Object Analysis',
    description:
      'Runs an AI Paths graph from Image Studio to detect object bounds, then applies the result back into the current page workspace using the shared context registry envelope.',
    tags: ['image-studio', 'ai-paths', 'analysis', 'object-detection', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'action:run-ai-path' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
      { type: 'writes', targetId: 'collection:ai-path-runs' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-prompt-extract',
    kind: 'action',
    name: 'Image Studio Prompt Extract',
    description:
      'Runs programmatic or model-assisted prompt parameter extraction using the current Image Studio page context registry envelope.',
    tags: ['image-studio', 'prompt', 'params', 'extraction', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-ui-extractor',
    kind: 'action',
    name: 'Image Studio UI Extractor',
    description:
      'Suggests prompt parameter UI controls for Image Studio using the current page context registry envelope and prompt workspace state.',
    tags: ['image-studio', 'prompt', 'ui', 'controls', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'action:image-studio-mask-ai',
    kind: 'action',
    name: 'Image Studio Mask AI',
    description:
      'Generates bounding-box or polygon masks for the active Image Studio slot using the current page context registry envelope.',
    tags: ['image-studio', 'mask', 'selection', 'vision', 'ai'],
    relationships: [
      { type: 'uses', targetId: 'page:admin-image-studio' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      proposeScopes: ['ctx:propose'],
      executeScopes: ['ctx:execute'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
];
