import type { ContextNode } from '@/shared/contracts/ai-context-registry';

const SOURCE_REF = 'src/features/ai/ai-context-registry/registry/definitions/collections.ts';

export const collectionNodesPart2: ContextNode[] = [
  {
    id: 'collection:system-logs',
    kind: 'collection',
    name: 'system_logs',
    description:
      'Stored platform telemetry and application log records, including request metadata, runtime context, stacks, and hydrated Context Registry envelopes.',
    tags: ['observability', 'logs', 'telemetry', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'page:system-logs' },
      { type: 'related_to', targetId: 'page:brain' },
      { type: 'related_to', targetId: 'action:system-logs-generate-insight' },
      { type: 'related_to', targetId: 'action:system-logs-interpret' },
    ],
    jsonSchema2020: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        _id: { type: 'string' },
        level: { type: 'string', enum: ['info', 'warn', 'error'] },
        message: { type: 'string' },
        category: { type: ['string', 'null'] },
        source: { type: ['string', 'null'] },
        service: { type: ['string', 'null'] },
        context: { type: ['object', 'null'] },
        stack: { type: ['string', 'null'] },
        path: { type: ['string', 'null'] },
        method: { type: ['string', 'null'] },
        statusCode: { type: ['number', 'null'] },
        requestId: { type: ['string', 'null'] },
        traceId: { type: ['string', 'null'] },
        correlationId: { type: ['string', 'null'] },
        userId: { type: ['string', 'null'] },
        createdAt: { type: 'string', format: 'date-time' },
      },
    },
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:analytics-events',
    kind: 'collection',
    name: 'analytics_events',
    description:
      'Stored analytics events used for summary dashboards, top-dimension breakdowns, and AI analytics insight generation.',
    tags: ['analytics', 'events', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'page:analytics' },
      { type: 'related_to', targetId: 'page:ai-insights' },
      { type: 'related_to', targetId: 'page:brain' },
      { type: 'related_to', targetId: 'action:analytics-generate-insight' },
    ],
    jsonSchema2020: {
      $schema: 'https://json-schema.org/draft/2020-12/schema',
      type: 'object',
      properties: {
        _id: { type: 'string' },
        type: { type: 'string', enum: ['pageview', 'event'] },
        scope: { type: 'string', enum: ['public', 'admin'] },
        path: { type: 'string' },
        visitorId: { type: 'string' },
        sessionId: { type: 'string' },
        name: { type: ['string', 'null'] },
        ts: { type: 'string', format: 'date-time' },
      },
    },
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:ai-insights-history',
    kind: 'collection',
    name: 'ai_insights_history',
    description:
      'Logical history store for analytics, runtime analytics, and system log insights persisted in settings-backed records.',
    tags: ['ai', 'insights', 'history', 'settings'],
    relationships: [
      { type: 'related_to', targetId: 'page:analytics' },
      { type: 'related_to', targetId: 'page:ai-insights' },
      { type: 'related_to', targetId: 'page:brain' },
      { type: 'related_to', targetId: 'action:analytics-generate-insight' },
      { type: 'related_to', targetId: 'action:runtime-analytics-generate-insight' },
      { type: 'related_to', targetId: 'action:system-logs-generate-insight' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:image-studio-projects',
    kind: 'collection',
    name: 'image_studio_projects',
    description:
      'Image Studio project records including canvas dimensions, project metadata, and workspace timestamps.',
    tags: ['image-studio', 'projects', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:image-studio-slots' },
      { type: 'related_to', targetId: 'collection:image-studio-runs' },
      { type: 'related_to', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'related_to', targetId: 'action:image-studio-run' },
      { type: 'related_to', targetId: 'action:image-studio-sequence-run' },
      { type: 'related_to', targetId: 'action:product-studio-send' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:image-studio-slots',
    kind: 'collection',
    name: 'image_studio_slots',
    description:
      'Image Studio slot records for imported assets, generated variants, composite layers, and per-slot metadata.',
    tags: ['image-studio', 'slots', 'assets', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:image-studio-projects' },
      { type: 'related_to', targetId: 'collection:image-studio-runs' },
      { type: 'related_to', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'related_to', targetId: 'action:image-studio-run' },
      { type: 'related_to', targetId: 'action:image-studio-sequence-run' },
      { type: 'related_to', targetId: 'action:product-studio-send' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:image-studio-runs',
    kind: 'collection',
    name: 'image_studio_runs',
    description:
      'Queued and completed Image Studio run records including request payloads, output images, history events, and dispatch state.',
    tags: ['image-studio', 'runs', 'generation', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:image-studio-projects' },
      { type: 'related_to', targetId: 'collection:image-studio-slots' },
      { type: 'related_to', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'related_to', targetId: 'action:image-studio-run' },
      { type: 'related_to', targetId: 'action:image-studio-sequence-run' },
      { type: 'related_to', targetId: 'action:product-studio-send' },
      { type: 'related_to', targetId: 'page:brain' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:image-studio-sequence-runs',
    kind: 'collection',
    name: 'image_studio_sequence_runs',
    description:
      'Image Studio sequence run records including step plans, current slot lineage, nested generation state, and streaming history events.',
    tags: ['image-studio', 'sequence', 'runs', 'workflow', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:image-studio-projects' },
      { type: 'related_to', targetId: 'collection:image-studio-slots' },
      { type: 'related_to', targetId: 'collection:image-studio-runs' },
      { type: 'related_to', targetId: 'action:image-studio-sequence-run' },
      { type: 'related_to', targetId: 'action:product-studio-send' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:kangur-progress',
    kind: 'collection',
    name: 'kangur_progress',
    description:
      'Learner progress state for Kangur including XP, badges, lesson mastery, and aggregated counters.',
    tags: ['kangur', 'progress', 'education', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:kangur-scores' },
      { type: 'related_to', targetId: 'collection:kangur-assignments' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-07T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'collection:kangur-scores',
    kind: 'collection',
    name: 'kangur_scores',
    description:
      'Historical practice and test results for Kangur learners including operation, accuracy, score, and timestamps.',
    tags: ['kangur', 'scores', 'education', 'database'],
    relationships: [
      { type: 'related_to', targetId: 'collection:kangur-progress' },
      { type: 'related_to', targetId: 'collection:kangur-assignments' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'low',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-07T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
];
