import type { ContextNode } from '@/shared/contracts/ai-context-registry';

const SOURCE_REF = 'src/features/ai/ai-context-registry/registry/definitions/pages.ts';

export const pageNodesPart1: ContextNode[] = [
  {
    id: 'page:context-registry',
    kind: 'page',
    name: 'AI Context Registry',
    description:
      'Central admin workspace for searching, resolving, previewing, and validating shared AI context ' +
      'across pages, components, collections, actions, policies, and runtime documents.',
    tags: ['ai', 'context', 'registry', 'admin', 'runtime'],
    relationships: [{ type: 'uses', targetId: 'component:context-registry-inspector' }],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:cms-page-builder',
    kind: 'page',
    name: 'CMS Page Builder',
    description:
      'Visual CMS editor for composing page sections, previewing responsive layouts, ' +
      'editing structure, and invoking page-scoped AI assistance.',
    tags: ['cms', 'page-builder', 'editor', 'ai', 'admin'],
    relationships: [
      { type: 'reads', targetId: 'collection:cms-pages' },
      { type: 'reads', targetId: 'collection:cms-themes' },
      { type: 'uses', targetId: 'component:cms-page-builder-preview' },
      { type: 'uses', targetId: 'component:cms-page-builder-inspector' },
      { type: 'uses', targetId: 'component:cms-theme-settings-panel' },
      { type: 'uses', targetId: 'action:cms-css-ai-stream' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:agent-teaching-chat',
    kind: 'page',
    name: 'Agent Creator Teaching Chat',
    description:
      'Admin chat surface for conversing with learner agents backed by embedding collections and ' +
      'retrieval-augmented generation.',
    tags: ['agent-creator', 'teaching', 'chat', 'ai', 'admin'],
    relationships: [
      { type: 'reads', targetId: 'collection:agent-teaching-agents' },
      { type: 'reads', targetId: 'collection:agent-teaching-embedding-collections' },
      { type: 'uses', targetId: 'component:agent-teaching-chat-panel' },
      { type: 'uses', targetId: 'action:agent-teaching-chat' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:admin-chatbot',
    kind: 'page',
    name: 'Admin Chatbot',
    description:
      'Admin chatbot workspace with session navigation, persona-aware chat, debug visibility, ' +
      'settings, and page-scoped context for AI turns.',
    tags: ['chatbot', 'admin', 'chat', 'ai'],
    relationships: [
      { type: 'reads', targetId: 'collection:chatbot-sessions' },
      { type: 'uses', targetId: 'component:chatbot-chat-interface' },
      { type: 'uses', targetId: 'component:chatbot-session-sidebar' },
      { type: 'uses', targetId: 'component:chatbot-settings-panel' },
      { type: 'uses', targetId: 'component:chatbot-debug-panel' },
      { type: 'uses', targetId: 'action:chatbot-chat' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:admin-image-studio',
    kind: 'page',
    name: 'Admin Image Studio',
    description:
      'Admin image generation workspace for managing projects, slot trees, masks, prompt parameters, ' +
      'generation settings, and output review.',
    tags: ['image-studio', 'admin', 'generation', 'editor', 'ai'],
    relationships: [
      { type: 'reads', targetId: 'collection:image-studio-projects' },
      { type: 'reads', targetId: 'collection:image-studio-slots' },
      { type: 'reads', targetId: 'collection:image-studio-runs' },
      { type: 'reads', targetId: 'collection:image-studio-sequence-runs' },
      { type: 'uses', targetId: 'component:image-studio-slot-tree' },
      { type: 'uses', targetId: 'component:image-studio-center-preview' },
      { type: 'uses', targetId: 'component:image-studio-right-sidebar' },
      { type: 'uses', targetId: 'component:image-studio-generation-toolbar' },
      { type: 'uses', targetId: 'action:image-studio-run' },
      { type: 'uses', targetId: 'action:image-studio-sequence-run' },
      { type: 'uses', targetId: 'action:image-studio-ai-path-object-analysis' },
      { type: 'uses', targetId: 'action:image-studio-prompt-extract' },
      { type: 'uses', targetId: 'action:image-studio-ui-extractor' },
      { type: 'uses', targetId: 'action:image-studio-mask-ai' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:system-logs',
    kind: 'page',
    name: 'Observation Post',
    description:
      'Admin system logs workspace for filtering telemetry, reviewing runtime context, generating AI insights, and interpreting individual log entries with shared page context.',
    tags: ['observability', 'logs', 'admin', 'ai', 'telemetry'],
    relationships: [
      { type: 'reads', targetId: 'collection:system-logs' },
      { type: 'uses', targetId: 'component:system-logs-filter-panel' },
      { type: 'uses', targetId: 'component:system-logs-metrics' },
      { type: 'uses', targetId: 'component:system-logs-ai-interpreter' },
      { type: 'uses', targetId: 'component:system-logs-event-stream' },
      { type: 'uses', targetId: 'action:system-logs-generate-insight' },
      { type: 'uses', targetId: 'action:system-logs-interpret' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:analytics',
    kind: 'page',
    name: 'Analytics Dashboard',
    description:
      'Admin analytics workspace for reviewing traffic summaries, recent events, top dimensions, and running analytics insight generation with the current dashboard state.',
    tags: ['analytics', 'admin', 'dashboard', 'ai'],
    relationships: [
      { type: 'reads', targetId: 'collection:analytics-events' },
      { type: 'reads', targetId: 'collection:ai-insights-history' },
      { type: 'uses', targetId: 'component:analytics-dashboard-header' },
      { type: 'uses', targetId: 'component:analytics-ai-insights' },
      { type: 'uses', targetId: 'component:analytics-metrics-grid' },
      { type: 'uses', targetId: 'component:analytics-top-stats' },
      { type: 'uses', targetId: 'component:analytics-recent-events-table' },
      { type: 'uses', targetId: 'action:analytics-generate-insight' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:ai-insights',
    kind: 'page',
    name: 'AI Insights Dashboard',
    description:
      'Admin dashboard aggregating analytics, runtime analytics, and system log insights with page-scoped runs for each insight bucket.',
    tags: ['ai', 'insights', 'admin', 'dashboard'],
    relationships: [
      { type: 'reads', targetId: 'collection:ai-insights-history' },
      { type: 'reads', targetId: 'collection:analytics-events' },
      { type: 'reads', targetId: 'collection:system-logs' },
      { type: 'reads', targetId: 'collection:ai-path-runs' },
      { type: 'uses', targetId: 'component:ai-insights-analytics-panel' },
      { type: 'uses', targetId: 'component:ai-insights-runtime-panel' },
      { type: 'uses', targetId: 'component:ai-insights-logs-panel' },
      { type: 'uses', targetId: 'action:analytics-generate-insight' },
      { type: 'uses', targetId: 'action:runtime-analytics-generate-insight' },
      { type: 'uses', targetId: 'action:system-logs-generate-insight' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
  {
    id: 'page:brain',
    kind: 'page',
    name: 'AI Brain',
    description:
      'Central AI control plane for routing, provider credentials, reporting schedules, prompt steering, and operational telemetry across AI-enabled product surfaces.',
    tags: ['ai', 'brain', 'admin', 'control-plane'],
    relationships: [
      { type: 'reads', targetId: 'collection:analytics-events' },
      { type: 'reads', targetId: 'collection:ai-insights-history' },
      { type: 'reads', targetId: 'collection:system-logs' },
      { type: 'reads', targetId: 'collection:ai-path-runs' },
      { type: 'reads', targetId: 'collection:chatbot-sessions' },
      { type: 'reads', targetId: 'collection:image-studio-runs' },
      { type: 'uses', targetId: 'component:brain-state-overview' },
      { type: 'uses', targetId: 'component:brain-operations-overview' },
      { type: 'uses', targetId: 'component:brain-routing-controls' },
      { type: 'uses', targetId: 'component:brain-provider-credentials' },
      { type: 'uses', targetId: 'component:brain-report-controls' },
      { type: 'uses', targetId: 'component:brain-metrics-dashboard' },
      { type: 'related_to', targetId: 'page:analytics' },
      { type: 'related_to', targetId: 'page:ai-insights' },
      { type: 'related_to', targetId: 'page:system-logs' },
      { type: 'related_to', targetId: 'page:ai-paths' },
      { type: 'related_to', targetId: 'page:admin-chatbot' },
      { type: 'related_to', targetId: 'page:admin-image-studio' },
      { type: 'related_to', targetId: 'page:agent-teaching-chat' },
      { type: 'related_to', targetId: 'action:analytics-generate-insight' },
      { type: 'related_to', targetId: 'action:runtime-analytics-generate-insight' },
      { type: 'related_to', targetId: 'action:system-logs-generate-insight' },
    ],
    permissions: {
      readScopes: ['ctx:read'],
      riskTier: 'none',
      classification: 'internal',
    },
    version: '1.0.0',
    updatedAtISO: '2026-03-09T00:00:00.000Z',
    source: { type: 'code', ref: SOURCE_REF },
  },
];
